= About network payload capture
:navtitle: About network payload capture

The Network Payload Capture enables users to intercept the network traffic and inspect data for every HTTP requests and responses in and out of devices in test sessions.

== Show the overview of network requests

In Session Details, users can see all network requests as (1) that follows the setting. To expand/collapse the overview, click on the icon (2) Expand/Collapse[^a].

== Show the network payload

In Session Details, users can observe the payloads in the tab Observe Request / Response Payloads.

== Setup Network Payload Capture

The setting steps on Kobiton Platform are described as follows:

1. Go to Settings, click Network Capture.
2. Input the base-domain that you want to capture the network transactions (i.e all transactions from sub-domains will be captured also).
3. Click Advanced and select the data type you want to capture. By default, Application/json will be captured. Supported MIME types are described below:

|===
|Data/ File | Types

|Application/json MIME type support | 'Application/json'

|Audio MIME type support | 'audio/aac', 'audio/mpeg', 'audio/webm', 'audio/wav'

|Font MIME type support | 'font/otf', 'font/ttf', 'font/woff', 'font/woff2'

|Image MIME type support | 'image/bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/svg+xml', 'image/webp', 'image/tiff'

|Text MIME type support | 'text/plain', 'text/xml', 'text/css', 'text/csv', 'text/html', 'text/javascript'

|Video MIME type support | 'video/mpeg', 'video/webm'

|Model MIME type support | 'model'

|===

To continue, follow guidelines to setup Network Payload Capture on iOS/ Android devices:

* Setup for iOS devices[^b] (follow all steps for Legacy Kobiton and steps 3, 4, 5, 6 for Latest Kobiton).
* Setup for Android devices[^c] (follow all steps for Legacy Kobiton and steps 3, 4, 5 for Latest Kobiton).

== Limitations

* Android support includes version 9-11.
* There is a 30-second to 1-minute delay for iOS devices as the proxy is being configured.
* Users can capture network transactions on Manual and Appium sessions only. Currently, Espresso and XCUITest are unable to generate network payload capture.
* We do not support certificate pinning for native apps due to instability. Make sure to disable certificate pinning on native apps if you want to capture payload.
* Please contact us for support if this feature is disabled on your system.
