= Prepare an Android device for hosting
:navtitle: Prepare an Android device

Learn how to prepare an Android device to be utilized with Kobiton 4.0 and later.

Different models of devices and versions of Android may have different layout for settings and options. Refer to the device's manual if you cannot find the options mentioned in this document.

== Download Google Chrome

Download and install Google Chrome from the Google Play Store onto the device.

== Enable USB debugging

From the Home screen, swipe up to show all apps. Open Settings.



Scroll down and select About phone. For some models, such as Google Pixel, this option is under System.



Select Software information.



Tap 7 times on Build number. A popup message will appear when you are close to enabling the mode. If you have a lock screen set, you’ll be asked to enter your security credentials.



The Developer mode is now activated.



Navigate back to the Settings main screen. Tap the newly available Developer options item. For some models such as Google Pixel, this option is under System.



Scroll down to the USB debugging option and turn it on. You can use the search function to quickly locate it.



Tap OK in the pop-up to confirm.



== Prevent screen from sleeping

In the Settings app, scroll down and select Developer options. For some models, such as Google Pixel, this option is under System.



Find the Stay awake option and turn it on.





== Turn off auto-update for system software

Many organizations want to test a variety of mobile operating systems. Turning off the auto-update for software updates allows organizations have control over the operating system upgrades. In the Settings app, tap Software update.



Turn off Auto download over Wi-Fi.



== Turn off auto-update for apps

Open the Play Store. Tap the 3-dot icon and select Settings.



Expand Network preferences, then tap Auto-update apps.



Select Don't auto-update apps in the pop-up. Tap DONE to save the changes.



== Disable lock screen

In the Settings app, select Lock screen.



Select Screen lock type.



Select None. Enter the device's passcode or lock pattern if required.



== Turn off adaptive brightness

In the Settings app, select Display.



Turn off Adaptive brightness.



== Disable text correction/prediction for keyboard

=== Samsung devices:

In the Settings app, select General management.



Tap Samsung Keyboard settings.



Turn off Predictive text.



=== Google Pixel devices:

In the Settings app, select System.



Select Languages & input.



Select On-screen keyboard.



Tap Gboard.



Tap Text correction.



Turn off Auto-correction.

