= Android biometrics authentication
:navtitle: Android biometrics authentication

Learn how to add our biometric authentication library to your Android xref:biometric-authentication/add-our-library-to-your-ios-app.adoc[or iOS] app, so you can test biometric authentication during your manual and automated test sessions. Our library lets you …, which we believe is xref:biometric-authentication/about-our-library.adoc[a better way to test biometrics].

After you add our library, rebuild your `.apk` and upload it to the xref:apps:manage-an-app.adoc[app repository].

== Before you start

Before you can add our library to your app, create a link:https://developer.android.com/build/build-variants#kts[test version] of your app and disable your `.CryptoObject` classes, _or_ ensure your app meets the following:

[cols="^1,8"]
|===
| &#10003;
| Only supports Android 9 or later.

| &#10003;
| Uses classes with lower-level security, like link:https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.AuthenticationCallback[`BiometricPrompt.AuthenticationCallback`] or link:https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo[`BiometricPrompt.PromptInfo`].

| &#10007;
| Does not use classes with higher-level security, like link:https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.CryptoObject[`BiometricPrompt.CryptoObject`].

| &#10007;
| Does not use deprecated classes, like link:https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager#public-methods_1[`FingerprintManager`].
|===

== Add `KobitonBiometric.aar`

First you’ll open your app’s Android Studio project and create a `libs` directory inside your project’s `app` directory if you don't already have one. Then download and move `KobitonBiometric.aar` into your new `libs` directory.

== Modify `build.gradle`

Next you’ll open the `build.gradle` in your app directory and add our library (or all your `.aar` libraries) to your list of `dependencies`:

[,groovy]
----
    implementation fileTree(dir: 'libs', include: ['<library>']) // Replace <library> with KobitonBiometric.aar or *.arr.
----

Here’s an example `build.gradle` file:

[,groovy]
----
dependencies {
    implementation fileTree(dir: 'libs', include: ['KobitonBiometric.aar']) // Alternatively, replace KobitonBiometric.aar with *.arr to include all libraries.
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version'
    implementation 'androidx.core:core-ktx1.3.0'
    implementation group: 'com.google.android.material', name: 'material', version: '1.3.0-alpha01'

    testImplementation 'junit:junit:4.13'

    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

}
----

When you’re finished, save your file.

== Modify AndroidManifest.xml

Next you’ll open the `AndroidManifest.xml` file in `/app/src/main` and add the following lines to your `<manifest>` element:

[,xml]
----
<uses-permission android:name="android.permission.USE_BIOMETRIC" android:requiredFeature="false"/>
<uses-permission android:name="android.permission.INTERNET"/>
----

Locate your `<application>` element and add the following line:

[,xml]
----
android:usesCleartextTraffic="true"
----

Inside `<application>`, replace:

* `*.BiometricManager` classes with `com.kobiton.biometric.BiometricManager`
* `*.BiometricPrompt` with `com.kobiton.biometric.BiometricPrompt`

Here’s an example `AndroidManifest.xml` file:

[,xml]
----
$EXAMPLE$
----

When you’re finished, save your file and xref:_verify_your_changes[verify your changes].

[#_verify_your_changes]
== Verify your changes

As with any code change, you’ll want to verify your new library works. First, rebuild your `.apk` and upload it to the app repository. Then, start a manual test session, launch your app, and try using biometric authentication to sign in. Select *Pass* and check the logs to verify your changes.

== Known issues

If you add our library to your app and send `BiometricPrompt.AuthenticationCallback` during authentication link:https://developer.android.com/guide/topics/ui/notifiers/toasts[using toasts], your app may crash during your test session. If this happens, you'll find the following error in your crash logs:

[source,java]
----
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
----

Here’s an example that could lead to a crash:

[source,java]
----
private BiometricPrompt.AuthenticationCallback getAuthenticationCallback() {
    return new BiometricPrompt.AuthenticationCallback() {
        @Override
        public void onAuthenticationError(int errorCode, @NonNull CharSequence errString) {
            Toast.makeText(MainActivity.this, "Authentication error", Toast.LENGTH_SHORT).show();
            super.onAuthenticationError(errorCode, errString);
        }

        @Override
        public void onAuthenticationSucceeded(@NonNull BiometricPrompt.AuthenticationResult result) {
            Toast.makeText(MainActivity.this, "Authentication successful", Toast.LENGTH_SHORT).show();
            super.onAuthenticationSucceeded(result);
        }

        @Override
        public void onAuthenticationFailed() {
            Toast.makeText(MainActivity.this, "Authentication failed", Toast.LENGTH_SHORT).show();
            super.onAuthenticationFailed();
        }
    };
}
----
