= Create biometric authentication scripts
:navtitle: Create biometric authentication scripts

Learn how to create biometric authentication scripts to run during your automation sessions.

== Before you start

You’ll need to add our biometric authentication library to your iOS and Android apps:

* xref:biometric-authentication/add-our-library-to-your-android-app.adoc[Add our library to your Android app]
* xref:biometric-authentication/add-our-library-to-your-ios-app.adoc[Add our library to your iOS app]

[NOTE]
Learn about xref:biometric-authentication/about-our-library.adoc[the benefits] of our biometrics authentication library.

== Script parameters

After you send a biometric authentication request, end-users can choose to authenticate themselves (`pass`) or reject your request (`fail`). Use these scripts to test how your app responds to each choice:

[cols="3,2"]
|===
| `driver.execute('mobile:biometrics-authenticate', {result: 'passed'})`
| Simulate the end-user authenticating themselves.

| `driver.execute('mobile:biometrics-authenticate', {result: 'failed'})`
| Simulate the end-user rejecting your request.
|===

[NOTE]
Learn more about Appium’s link:https://appium.io/docs/en/2.0/guides/execute-methods/[`driver.execute()`] method.

== Example script

Here’s an example script for testing biometric authentication:

[source,javascript]
----
// A test case for biometric authentication.
it('Run biometric auto', async () => {
   try {
        // Look for the XPath containing the words "Log In" and select the element.
        await driver.waitForElementByXPath('//XCUIElementTypeStaticText[@id="Log In"]').click()

        // Wait for 20 seconds for the biometric authentication screen to load.
        await driver.sleep(20000)

        // Simulate the end-user authenticating themselves.
        await driver.execute('mobile:biometrics-authenticate', {result: 'passed'})
    }
    // Catch any errors that occur.
    catch (err) {
        // Log the error in your console.
        console.error(err)

        // Throw the error to stop the test.
        throw err
    }
})
----
