= Create image injection script
:navtitle: Create an image injection script

Learn how to automate the process of image injection, so you can automate your test suite.

== Before you start

Take notes of the following prerequisites and limitations:

* Image injection requirements for iOS and Android apply.

* Only supported in Xium automation sessions.

* The image must be located on the runner machine and be passed with base64 encoding. Passing the image URL is not yet supported.

* Inject the image after launching the camera. Injecting the image before launching the camera might crash the app.

* Add a wait time for the image injection process to complete (up to 5 seconds) before performing the next command.

== Appium capability (instrumentation only)

Add the `'kobiton:instrumentenabled'` capability to your script’s capabilities list. The value of this capability must be `true` to instrument the app for image injection.


[IMPORTANT]
This Appium capability is only required for image injection via app instrumentation.

== Kobiton commands

To automate the process of image injection, use commands provided by the Kobiton SDK.

[options="header"]
|=======================
|Command | Description | Parameters
| `kobiton:setImage` | Starts the image injection process by injecting a specified image into the camera view. | `data`: A base64 encoded string of the image you want to inject.
| `kobiton:clearImage` |  This command stops the image injection process and reverts the camera view back to the live feed.
 |
|=======================

=== Handle image file and injection

Make sure the image file to inject is located locally and accessible by the test script.

Pass the image file to the test script using `base64` encoding and add the command to inject. See below for an example of a function to do such process.

.Example (javascript)
[source,javascript]

----

async function injectImage(driver, imagepath) {
  // assume the image is in the same folder as the test script so only need to provide a relative path to the image
  const imagePath = path.join(__dirname, imagepath);

  const base64Image = fs.readFileSync(imagePath, { encoding: 'base64' });

  // the command to set image on the device
  await driver.execute('kobiton:setImage', { data: base64Image });
}

----

=== Start Image Injection

Provided that the function `injectImage` has been declared in the previous section, use it to start image injection:

.Example (javascript)
[source,javascript]

    await injectImage(driver, 'path_to_image/image.jpg');

This will replace the camera view with the specified `image.png` file in `path_to_image`.

=== Stop image injection

To stop image injection use:

.Example (javascript)
[source,javascript]

    await driver.execute('kobiton:clearImage');

This will revert the camera view back to the live feed.

