= Obfuscate private data in Appium script
:navtitle: Obfuscate private data in Appium script

Learn how to obfuscate (hide) private data in an Appium test script in the *View HTTP Headers* and *Appium Inspector* section of Session Explorer.

=== Data obfuscation Appium setting

We introduced a new custom setting to start and stop obfuscation for private data in an Appium sesssion:

[options="header"]
|=======================
|Appium setting | Description | Default value
| `kobiton:privateMode` | Set to `true` to start obfuscating data, or to `false` to stop obfuscating | `false`
|=======================

=== Start data obfuscation

Before starting a test action that involves private data, such as passing account password, use the `Update Settings` Appium command to set `'kobiton:privateMode'` to `true`.

.Example (JavaScript)
[source,javascript]

await driver.updateSettings({'kobiton:privateMode': true})

As long as the setting is `true`, the data provided is marked for obfuscation.

=== Stop data obfuscation

When test steps no longer involve private data, use the `Update Settings` Appium command to set `'kobiton:privateMode'` back to `false`.

.Example (JavaScript)
[source,javascript]

await driver.updateSettings({'kobiton:privateMode': false})

When the setting is `false`, data is no longer obfuscated.

== Limitations/Notes

* Only supported in Xium and Appium 2 Basic automation sessions.

* Unlike Manual sessions with sensitive data, Automation sessions with obfuscated data are not marked as sensitive sessions and can be accessed by admins or other team members.

* Although the private data is obfuscated in _View HTTP Headers_ and _Appium Inspector_, it may not be obfuscated in session video, screenshots, and logs.