= Create a project
:navtitle: Create a project

Learn how to configure TestRail so you can xref:testrail/add-to-desired-capabilities.adoc[add TestRail to your test suite]. Once it's added, your future automation sessions will automatically update your TestRail project and link it to your session analytics.

[#_generate_an_api_key]
== Generate an API key

Ensure that your APIs are enabled in TestRail. Go to Site Settings/API and make sure the *Enable API* and *Enable session authentication for API* boxes are checked.

You will create your TestRail API key by logging into your TestRail account, clicking on your username in the top right-hand corner, and selecting *My Settings* from the dropdown menu.

Click on the API Keys tab, and then *Add key*. You can name your API key anything you would like, then click *+ Generate Key*.

Your API key will be generated and you can copy it from the API Key box.

[NOTE]
You can xref:profile:your-api-keys.adoc[add your TestRail API Key to Kobiton] for easy access.

[#_configure_project]
== Configure project

. On the TestRail website, click *+ Add Project*.

. Name your project, make sure
*Use a single repository for all cases* is selected, and then
click *Add Project* at the bottom.

. From the Dashboard, open your project, select the
*Test Runs & Results* tab, and then
*+Add Test Run*.

. Name your Test Run. Under "Assign To", select *Me* and click
*Add Test Run* at the bottom of the page.

. Next, click the *Test Cases* tab and click
*+ Add Test Case*.

. Name your Test Case and click *Add Test Case* at the bottom
of the page.
