= Katalon Studio Integration
:navtitle: Katalon

This guide explains how to create and execute a mobile test with Kobiton devices from Katalon Studio.

== Before you start

Make sure you have the following:

* A *Kobiton account*.
* A *Katalon account*. There are 2 options:
** *Enterprise account*: Supports the Kobiton plugin for performing Spy and Record actions, as well as running test cases on Kobiton devices through the Katalon UI.
** *Free account*: Does not support the Kobiton plugin, but you can still run tests on Kobiton devices by manually adding Appium capabilities to your test scripts to point to Kobiton devices.
* Access to *Katalon Studio*.
** For Cloud/Hybrid deployments, use Katalon Studio 9.7.5 or above.
** For Standalone/On-Prem deployments, use Katalon Studio 10.2.0 or above.

== Set up the Kobiton Integration plugin

[NOTE]
====
These features are only available for Katalon Enterprise accounts.
====

Open *Katalon Studio* and log into your Katalon Enterprise account.

Open an existing project or create a new one from the *Mobile* sample projects (see the sample project below).

Open the https://store.katalon.com/product/137/Kobiton-Integration[Kobiton Integration,window=read-later] web page in the Katalon Store. Make sure you are logged into the store using the same account in Katalon Studio.

Select *Install*.

Go back to Katalon Studio, select the account profile, then select *Reload Plugins*.

If the plugin is loaded successfully, the *Kobiton Integration* plugin displays with the *Success* status.

Close the pop-up, then open *Kobiton Integration* settings:

* Windows:
** From the menu bar, select *Window → Katalon Studio Preferences*.

* macOS:
** From the Katalon menu bar, select *Katalon Studio Enterprise* or *Katalon Studio → Settings*.

* Linux (Ubuntu):
** From the menu bar, select *Window → Katalon Studio Preferences*.

The next steps are the same for all operating systems:

* Expand *Katalon*, then select *Kobiton*.
* In the _Kobiton Integration_ options, check the *Enable Kobiton Integration* checkbox.

Enter the following information:

* Kobiton Server
* Username
* API Key

Select *Test Connection* to test the configuration. If successful, a message `Connection to Kobiton successful` will appear.
Select *Apply and Close*.

== Perform actions or tests with Kobiton Integration

[NOTE]
====
These features are only available for Katalon Enterprise accounts.
====

=== Mark devices as favorites in the Kobiton Portal

* Log in to your Kobiton Portal.
* Follow xref:devices:manage-devices.adoc#_favorite_the_device[this guide,window=read-later] to mark any Public or Private and Local devices as favorites.

[NOTE]
====
Only devices that are marked as favorites can be selected in the Spy and Record actions.
====

=== Upload application to the Kobiton App Repo (optional)

If you want to test an app not already installed on the device, follow xref:apps:upload-an-app/using-the-kobiton-portal.adoc[this guide,window=read-later] to upload the app to the App Repo.

== Perform Spy or Record actions

Make sure you have marked device(s) as favorites and uploaded application(s) to the App Repo.

Select the *Spy* or *Record* icon.

Select *Kobiton Devices*.

Wait for the device and application list to load.

Under *Configurations*, select a *Device Name*.

To install an app from the App Repo, select *Application File* under *Start With*, then choose an app from the dropdown.

To test an app already installed on the device, select *Application ID* under *Start With*, then input the package name or bundle ID.

Select *Refresh* to update the app list if needed.

Select *Start* to begin the Spy or Record action.

[NOTE]
====
* Local apps cannot be installed to Kobiton devices in Spy and Record actions. Upload the apps to the Kobiton App Repo or use a direct download URL.
* The _Kobiton Devices_ option only appears when the Kobiton Integration plugin is enabled.
* Learn more about the https://docs.katalon.com/katalon-studio/record-and-spy/mobile-record-and-spy-utilities/spy-mobile-utility[Spy,window=read-later] and https://docs.katalon.com/katalon-studio/record-and-spy/mobile-record-and-spy-utilities/mobile-recorder-utility[Record,window=read-later] mobile utilities in Katalon documentation.
====

== Run a test

Follow the Katalon official guide to https://docs.katalon.com/katalon-studio/create-test-cases/create-a-new-test-case-in-katalon-studio[create a test case,window=read-later]. You can use the sample https://docs.katalon.com/katalon-studio/get-started/sample-projects/mobile/mobile-create-and-run-android-test-case-in-katalon-studio[Android,window=read-later] or https://docs.katalon.com/katalon-studio/get-started/sample-projects/mobile/mobile-create-and-run-ios-test-case-in-katalon-studio[iOS,window=read-later] project.

Open the test case to test.

Make the following changes:

* Double-click the *input* column of the *Start Application* row.
* Double-click the *Value* column of the *appFile* row
* Replace it with `"<app-version-id>"` or `"<direct-download-url>. Example: `"kobiton-store:v1"` or `"https://drive.example.com/sample.apk"`
* Select *OK* to save the changes.

Select the *Run* or *Debug* dropdown icon.

Select *Kobiton Device*.

Wait for the device list to load and choose a device.

Select *OK* to start the test.

Wait for test execution and view the result.

[NOTE]
The _Kobiton Device_ option only appears when the Kobiton Integration plugin is enabled.

== Add Appium capabilities to run a Katalon script on Kobiton devices

[NOTE]
====
This process is available for both Free and Enterprise Katalon accounts.
====

== Create a test case in Katalon

* Follow the Katalon official guide to https://docs.katalon.com/katalon-studio/create-test-cases/create-a-new-test-case-in-katalon-studio[create a test case,window=read-later].
* You may also use the sample https://docs.katalon.com/katalon-studio/get-started/sample-projects/mobile/mobile-create-and-run-android-test-case-in-katalon-studio[Android,window=read-later] or https://docs.katalon.com/katalon-studio/get-started/sample-projects/mobile/mobile-create-and-run-ios-test-case-in-katalon-studio[iOS,window=read-later] project.

== Retrieve Appium capabilities for Kobiton devices

* Log in to the Kobiton Portal.
* Follow xref:automation-testing:capabilities/auto-generate-capabilities.adoc[this guide] to retrieve the Appium capabilities.
* Select *Java* as the language.
* To test an app that has been uploaded to the App Repo, select *Hybrid/Native* under *App Type*, then the app.
* Copy the capabilities.

== Modify the Katalon script to add Appium capabilities

Open *Katalon Studio* and the test case.

Switch to the *Script view*.

Add the following lines *before the import directives*:

* *Android*:
+
[source]
----
import org.openqa.selenium.remote.DesiredCapabilities
import com.kms.katalon.core.appium.driver.AppiumDriverManager
import com.kms.katalon.core.mobile.driver.MobileDriverType
import io.appium.java_client.android.AndroidDriver
----

* *iOS*:
+
[source]
----
import org.openqa.selenium.remote.DesiredCapabilities
import com.kms.katalon.core.appium.driver.AppiumDriverManager
import com.kms.katalon.core.mobile.driver.MobileDriverType
import io.appium.java_client.ios.IOSDriver
----

[NOTE]
====
Skip adding imports that are already in the test case.
====

Replace `Mobile.startApplication(...)` with the copied capabilities.
Add the following line after:

* *Android*:
+
[source]
----
AppiumDriverManager.createMobileDriver(MobileDriverType.ANDROID_DRIVER, capabilities, new URL(kobitonServerUrl))
----

* *iOS*:
+
[source]
----
AppiumDriverManager.createMobileDriver(MobileDriverType.IOS_DRIVER, capabilities, new URL(kobitonServerUrl))
----

Example added capabilities:

[source]
----
String kobitonServerUrl = "https://username:apiKey@api.kobiton.com/wd/hub";
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("kobiton:sessionName", "Automation test session");
capabilities.setCapability("appium:app", "kobiton-store:v722859");
capabilities.setCapability("kobiton:groupId", 13622);
capabilities.setCapability("kobiton:deviceGroup", "KOBITON");
capabilities.setCapability("appium:deviceName", "Galaxy Tab S7");
capabilities.setCapability("platformVersion", "12");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("kobiton:retainDurationInSeconds", 0);
----

== Complete example

The below sample code was taken from the test case _Verify Correct Alarm Message_ in Katalon’s Sample Android Project, then modified to include the Kobiton capabilities:

[source]
----

// Start of added import directives.
import org.openqa.selenium.remote.DesiredCapabilities
import com.kms.katalon.core.appium.driver.AppiumDriverManager
import com.kms.katalon.core.mobile.driver.MobileDriverType
import io.appium.java_client.android.AndroidDriver

// End of added import directives.

import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject

import com.kms.katalon.core.configuration.RunConfiguration
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.util.internal.PathUtil

import internal.GlobalVariable

Mobile.comment('Story: Verify correct alarm message')

Mobile.comment('Given that user has started an application')

'Get full directory\'s path of android application'
def appPath = PathUtil.relativeToAbsolutePath(GlobalVariable.G_AppPath, RunConfiguration.getProjectDir())

// The below line need to be removed, or commented out from the original script.
// Mobile.startApplication(appPath, false)

// Start of Appium capabilities copied from Kobiton'

String kobitonServerUrl = "https://johndoe:928c807c-6283-459a-9e45-0c13b0f972bf@api.kobiton.com/wd/hub";

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("kobiton:sessionName", "Automation test session");
capabilities.setCapability("kobiton:sessionDescription", "");
capabilities.setCapability("kobiton:deviceOrientation", "portrait");
capabilities.setCapability("kobiton:captureScreenshots", true);
// The maximum size of application is 4096MB
// By default, HTTP requests from testing library are expired
// in 2 minutes while the app copying and installation may
// take up-to 30 minutes. Therefore, you need to extend the HTTP
// request timeout duration in your testing library so that
// it doesn't interrupt while the device is being initialized.
capabilities.setCapability("appium:app", "kobiton-store:v722859");

// The given team is used for finding devices and the created session will be visible for all members within the team.
capabilities.setCapability("kobiton:groupId", 13622); // Group: Test
capabilities.setCapability("kobiton:deviceGroup", "KOBITON");
// For deviceName, platformVersion Kobiton supports wildcard
// character *, with 3 formats: *text, text* and *text*
// If there is no *, Kobiton will match the exact text provided
capabilities.setCapability("appium:deviceName", "Galaxy Tab S7");
capabilities.setCapability("platformVersion", "12");
capabilities.setCapability("platformName", "Android");
// Set between 30 and 86400 to retain the device after ending the session.
capabilities.setCapability("kobiton:retainDurationInSeconds", 0);

AppiumDriverManager.createMobileDriver(MobileDriverType.ANDROID_DRIVER, capabilities, new URL(kobitonServerUrl))

// End of Appium capabilities copied from Kobiton'

Mobile.comment('And he navigates the application to Activity form')

Mobile.tap(findTestObject('Application/android.widget.TextView - App'), 10)

Mobile.tap(findTestObject('Application/App/android.widget.TextView - Activity'), 10)

Mobile.comment('When he taps on the Custom Dialog button')

Mobile.tap(findTestObject('Application/App/Activity/android.widget.TextView - Custom Dialog'), 10)

'Get displayed message on the dialog'
def message = Mobile.getText(findTestObject('Application/App/Activity/Custom Dialog/android.widget.TextView - Message'),
    10)

Mobile.comment('Then the correct dialog message should be displayed')

Mobile.verifyEqual(message, 'Example of how you can use a custom Theme.Dialog theme to make an activity that looks like a customized dialog, here with an ugly frame.')

Mobile.closeApplication()

----


== Run the test

Select either the *Run* or *Debug* icon.

Do _not_ select the Kobiton Device from the dropdown — Appium capabilities handle everything.

Wait for test execution.
