= Katalon Studio Integration

This guide explains how to create and execute a mobile test with Kobiton devices from Katalon Studio.

== Before you start

Make sure you have the following:

* A Kobiton account.
* A Katalon account. There are 2 options:
** Enterprise account: Supports the Kobiton plugin for performing Spy and Record actions, as well as running test cases on Kobiton devices through the Katalon UI.
** Free account: Does not support the Kobiton plugin, but you can still run tests on Kobiton devices by manually adding Appium capabilities to your test scripts to point to Kobiton devices.
* Access to Katalon Studio.
** For Cloud/Hybrid deployments, use Katalon Studio 9.7.5 or above.
** For Standalone/On-Prem deployments, use Katalon Studio 10.2.0 or above.

== Set up the Kobiton Integration plugin

. Open Katalon Studio and log into your Katalon Enterprise account.
. Open an existing project or create a new one from the Mobile sample projects (see the sample project below). +
  This feature is only available for Katalon Enterprise accounts.

. Open the Kobiton Integration web page in the Katalon Store. Make sure you are logged into the store using the same account in Katalon Studio.
. Select _Install_.
. Go back to Katalon Studio, select the account profile, then select _Reload Plugins_.
. If the plugin is loaded successfully, the Kobiton Integration plugin displays with the *Success* status.
. Close the pop-up, then open Kobiton Integration settings:

* Windows:
** From the menu bar, select `Window → Katalon Studio Preferences`.

* macOS:
** From the Katalon menu bar, select `Katalon Studio Enterprise` or `Katalon Studio → Settings`.

* Linux Ubuntu:
** From the menu bar, select `Window → Katalon Studio Preferences`.

All platforms:
** Expand _Katalon_, then select _Kobiton_.
** In the Kobiton Integration options, check the `Enable Kobiton Integration` checkbox.

Enter the following information:

* Kobiton Server
* Username
* API Key

Select *Test Connection* to test the configuration. If successful, a message `Connection to Kobiton successful` will appear.  
Select *Apply and Close*.

== Perform actions or tests with Kobiton Integration

[NOTE]
====
These features are only available for Katalon Enterprise accounts.
====

=== Mark devices as favorites in the Kobiton Portal

* Log in to your Kobiton Portal.
* Follow this guide to mark any Public or Private and Local devices as favorites.

[NOTE]
====
Only devices that are marked as favorites can be selected in the Spy and Record actions.
====

=== Upload application to the Kobiton App Repo (optional)

If you want to test an app not already installed on the device, follow _this guide_ to upload the app to the App Repo.

== Perform Spy or Record actions

* Make sure you have marked device(s) as favorites and uploaded application(s) to the App Repo.
* Select the *Spy* or *Record* icon.
* Select *Kobiton Devices*.
* Wait for the device and application list to load.
* Under *Configurations*, select a *Device Name*.
* To test an app from the App Repo, select *Application File* under *Start With*, then choose an app from the dropdown.

[NOTE]
====
Only apps uploaded to the App Repo can be installed to the device in Spy and Record actions.  
This option only appears when the Kobiton Integration plugin is enabled.
====

* To test an app already installed on the device, select *Application ID* under *Start With*, then input the package name or bundle ID.
* Select *Refresh* to update the app list if needed.
* Select *Start* to begin the Spy or Record action.

== Run a test

. Follow the Katalon official guide to create a test case. Use a sample Android or iOS project.
. Open the test case to test.
. If the application path is local:
.. Double-click the *input* column of the *Start Application* row.
.. Double-click the *Value* column of the *appFile* row and replace it with `"<app-version-id>"`.  
   For example: `"kobiton-store:v1"`

. Select *OK* to save the changes.
. Select the *Run* or *Debug* dropdown icon.
. Select *Kobiton Device*.
. Wait for the device list to load and choose a device.
. Select *OK* to start the test.
. Wait for test execution and view the result.

== Add Appium capabilities to run a Katalon script on Kobiton devices

[NOTE]
====
This option only appears when the Kobiton Integration plugin is enabled.
====

== Create a test case in Katalon

* Follow the Katalon official guide to create a test case.
* You may also use the sample Android or iOS project.

== Retrieve Appium capabilities for Kobiton devices

* Log in to the Kobiton Portal.
* Follow _this guide_ to retrieve the Appium capabilities.
* Select _Java_ as the language.
* Select *Hybrid/Native* under *App Type*, then the app.
* Copy the capabilities.

== Modify the Katalon script to add Appium capabilities

. Open Katalon Studio and the test case.
. Switch to *Script view*.
. Add the following lines *before the import directives*:

=== For Android:
[source,java]
----
import org.openqa.selenium.remote.DesiredCapabilities
import com.kms.katalon.core.appium.driver.AppiumDriverManager
import com.kms.katalon.core.mobile.driver.MobileDriverType
import io.appium.java_client.android.AndroidDriver
----

=== For iOS:
[source,java]
----
import org.openqa.selenium.remote.DesiredCapabilities
import com.kms.katalon.core.appium.driver.AppiumDriverManager
import com.kms.katalon.core.mobile.driver.MobileDriverType
import io.appium.java_client.ios.IOSDriver
----

[NOTE]
====
Skip adding imports that are already in the test case.
====

. Replace `Mobile.startApplication(...)` with the copied capabilities.
. Add the following line after:

=== For Android:
[source,java]
----
AppiumDriverManager.createMobileDriver(MobileDriverType.ANDROID_DRIVER, capabilities, new URL(kobitonServerUrl))
----

=== For iOS:
[source,java]
----
AppiumDriverManager.createMobileDriver(MobileDriverType.IOS_DRIVER, capabilities, new URL(kobitonServerUrl))
----

. Example added capabilities:

[source,java]
----
String kobitonServerUrl = "https://username:apiKey@api.kobiton.com/wd/hub";
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("kobiton:sessionName", "Automation test session");
capabilities.setCapability("appium:app", "kobiton-store:v722859");
capabilities.setCapability("kobiton:groupId", 13622);
capabilities.setCapability("kobiton:deviceGroup", "KOBITON");
capabilities.setCapability("appium:deviceName", "Galaxy Tab S7");
capabilities.setCapability("platformVersion", "12");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("kobiton:retainDurationInSeconds", 0);
----

== Run the test

* Select either the *Run* or *Debug* icon.
* Wait for test execution.
* Do _not_ select the Kobiton Device from the dropdown — Appium capabilities handle everything.
