= Review network payload data
:navtitle: Review network payload data

Learn how to review network payload capture data after your test session so you can

== Before you start

You'll need to complete:

* xref:manual-testing:local-devices/capture-network-payload-data.adoc[A manual session with network payload capture enabled] +
_or_
* xref:automation-testing:local-devices/capture-network-payload-data.adoc[An automation session with network payload capture enabled]

== Observe Request / Response Payloads

First, search for a session and xref:session-explorer:launch-session-explorer.adoc[launch Session Explorer].

image:$NEW-IMAGE$[width=, alt=""]

In Session Explorer, select *Observe Request / Response Payloads*.

image:$NEW-IMAGE$[width=, alt=""]

== Analyze response times

First, search for a session and xref:session-explorer:launch-session-explorer.adoc[launch Session Explorer].

image:$NEW-IMAGE$[width=, alt=""]

In Session Explorer, select *Analyze response times*.

image:$NEW-IMAGE$[width=, alt=""]
