= Organization Setup
:navtitle: Organization Setup

An Organization on Kobiton is the central location where the organization’s settings are determined.

From the Org Management page, admins have the ability to access and make changes to Group, Member, Device, and Device Bundle details.

Note: Only admins have access to the Org Management section.

== Create an Organization

1. On the Kobiton portal, select *Org Management*.

2. Click *Create Organization*.

3. On the Create Organization modal, enter the organization’s *name* and *description* and click *Create your organization*.

== Edit an Organization

Specific changes and edits can be made to the details of the organization under each specific functionality, but the edit the Organization name or description

1. Click the pencil icon next to the Organization name.

2. In the Edit Organization modal, make the necessary changes to *Organization Name* and *Organization Description* and click *Update*.

== Invite Members to Organization

To add a member/s to the organization:

1. On the Org Management page, select the *Members* tab.

2. Click the *+Add* button.

3. Enter the email address for each member.

4. Assign a role: User or Admin.

5. Optional: Under Add To Group, select a group from the dropdown menu.

6. Click *Invite*.

Members will receive their Kobiton invitation via email.






