= v3.12 | May 31, 2021
:navtitle: v3.12 | May 31, 2021

== Updates to the Kobiton Platform

=== Organization Management

This release introduces Role-Based Access Control: a highly customizable role-based system giving org. owners and admins a variety of permissions to be added to new and existing roles that can further be assigned to users. This will not only assist with tailoring roles and user segmentation based on an organization's needs, but will also give Kobiton organizations added security measures throughout the platform. Additionally, Role-Based Access control provides support for SSO authentication.

Admins now have the ability to invite trial users/ end of subscription users to their organization by email invite.

=== Kobiton Intelligent Quality Suite and Scriptless Automation

==== Added Version Support

* Kobiton now supports iOS 14.5 and Xcode 12.5, along with supporting Chrome version 89.

==== Enhanced Session List

* Kobiton's session list has been enhanced with a fast and powerful searching capability that allows a user to search sessions by an array of attributes, including status, type of session, device type, OS version, and more, all with a new, nice look and feel that is easy to use.

==== New! Session Snapshots

* Kobiton is excited to introduce a new feature, Session Snapshots! When a user performs a manual session, the Kobiton Platform will render a snapshot of each interaction, ie tap, swipe, click, etc., to be displayed as a roll of test steps on the test execution page. Each snapshot will also highlight elements on the page that a user interacted with during the session, allowing more visibility into test case creation.

==== Enhanced Appium Export

* Kobiton now supports an additional testing framework, TestNG, when exporting Appium scripts from a manual or revisited session. Additionally, if the session has been executed more than once, a user also has the ability to chose which session run he or she would like to export the Appium script.

==== Manual Sessions

* Users now have the ability to increase a device's horizontal screen size when running a manual session.

== Device Lab Management

Kobiton's Soft Booking feature is now available through the user interface. A user may retain a private device for a certain amount of time, such as one hour, two hours, four hours, six hours, twelve hours, or twenty-four hours. The device is retained for the user, and admin user has the ability to terminate device retainment.

For more visibility across organizations, private devices can now be filtered by group by all users, including admin users.

== Bug Fixes and Database Optimization

* Some devices with special characters are now supported by Kobiton.

* Exporting Appium scripts from manual sessions has been improved by fixing known bugs.

* Kobiton's database has been optimized to deliver improved performance.
