= v3.17 | December 26, 2021
:navtitle: v3.17 | December 26, 2021

== What's New

=== Device Location

Device Location: Want to know where the device is physically located? We’ve added the location to the device modal. Look for the Location info on the modal.

=== ADB tunnel support for Linux

Access remote devices from Kobiton from your IDE using the ADB utility on Linux machines.

=== Service Level Availability Reports

We’ve added the ability to check on device status from the Kobiton portal with Service Level Availability (SLA) reports. SLA reports will display information for all the devices associated with the organization and display information such as minutes used, in service dates, dates online, and the average device availability. The reports can be set to display information for a determined amount of time or by default will be set for the past week.

== Portal procedure updates

=== Updates to how users are assigned / unassigned

We’ve made a few changes to how users and devices are assigned and unassigned.

When changing a user status, click Add new users to add a new user or to assign / unassign an existing user. The modal will now display all team members which will make it easier to make the change.

=== Team device information

Hovering over the Hosted by column on a team’s assigned devices page will display the user's email and name of host machine.

=== App Tagging

Identifying an app can get complicated when the repo may have more than one version of the same app.. to avoid having to search by the app ID or version number, set a tag on the app- it'll be much easier to find the app you are actually looking for.

=== App events to User History

To user history, we’ve added the Application Installed and Application Launched event.

== Scriptless Automation updates

=== New baseline for text and color assertions

The Set a new baseline functionality allows users to set a revisit as the baseline to test against for text and color assertions.

=== New device OS support

Support for iOS 15.2
