= v3.15 | October 9, 2021
:navtitle: v3.15 | October 9, 2021

== Org. Management

=== Enhancements to App Repository:

** the Kobiton App Repository’s UI has been modified to improve the user experience
** An app’s name can be changed by version number, which will then be reflected in the app repository, manual session (when selecting the app), device modal (when selecting the app for automated testing), and the session overview. This update will make it easier for users to find their chosen app and track historical installations in the session details

=== Improved UI on the Device List page:

Kobiton has made updates to the Device List UI and made improvements to the functionality of the device list filter.

== Kobiton Intelligent Quality Suite and Scriptless Automation

=== New! Saved Search:

Saved Search allows users to name and save search queries. This feature will be incredibly helpful to users who wish to save a commonly searched list of sessions.

=== Enhanced Figma Integration/Visual Validation:

We have made the Figma integration’s UI more user-friendly by separating this feature into two views (instead of combining Figma images and the comparison panel in one screen): at first, when opening the "Compare to UI design" tab, you will see the grid of Figma images. After selecting an image, you will then be navigated to the new page to perform the image comparison by overlaying your selected two images.

=== Additional functionality for UI design comparison:

Non-Figma users now have access to the same image validation functionality by uploading images directly from your computer.

=== Improved Stability for Revisit Sessions:

We’ve introduced a new model for element location to revisit sessions, addressing overlap element issues and to  improving accuracy and stability.

=== Refined Recommended Device Bundle:

We are replacing the current device bundle recommendations, with NOVA Recommended Devices. This device bundle will suggest devices that are online at the moment users attempt to configure revisit sessions, which will ensure a higher rate of successful device capture for revisit sessions.

=== Enhanced Main Flow for Text Assertions:

By changing our main flow for text assertions to utilize more of Google Vision’s capabilities alongside our AI’s analysis, we have reduced false positives and false negatives returned during tests using this assertion.

=== Enhanced screen capture:

Unique applications screens are now identifiable and objects within those screens will be captured. We plan on applying this same technology to several testing features in future releases- stay tuned!

== Device Lab Management

=== New! Login Message:

Private customers can add a customizable banner to the Kobiton portal that will be viewed by all the organization’s viewers upon login.

[NOTE]
At this time we only support customized login messages for paid organizations. As a result, trial or expired users are unable to use this feature.

=== Added Version Support:

** support for iOS 15 beta 7 and Xcode 13 beta 5

** support for Android 12 Beta 4.1

=== Enhancements to RBAC:

** Fixed incorrect behavior of the “-” button in Assigned Devices (Teams details)

** Made the following changes to the Cleanup Policy at Team Level, including:

** The ability to select a  cleanup policy and set it as the default policy.

** Kobiton has more detailed texts within the UI to assist users with the eCleanup Policy at Team level feature (such as notes and tip prompts)

** Enhanced search [is this for cleanup only?] (user can search by Name, Team)

** Better UI/ UX for the cleanup policy feature

=== Added information in manual test device view:

When launching devices in a manual session, users will be able to view a device’s information without navigating through the devices list page. Device information includes:

** Manufacturer

** UDID

** Serial Number

** IMEI Number

== Bug Fixes and Database Optimization

** We’ve corrected issues affecting some devices and the network checking feature, preventing them from being properly hosted in the Kobiton portal.
** We’ve corrected the issues caused by device manufacturer policy changes that prevented devices from retrieving phone numbers on the Kobiton platform.
