= v3.12.1 | June 21, 2021
:navtitle: v3.12.1 | June 21, 2021

== Kobiton Intelligent Quality Suite and Scriptless Automation

With this release, Kobiton has introduced a new, desired capability to feature 'Appium-based Visual Assertion' that allows users the ability to declare specific test step ID(s) they would like to execute visual assertion on. Instead of scanning all test steps, Visual Assertion will only perform a visual scanning on defined test steps.

== Test Case Management Integration

Kobiton users who leverage TestRail as his/her test case manager may now add TestRail test case IDs and run IDs to appium scripts to be executed. After execution, Kobiton will automatically map test case IDs from TestRail to created session and also populate data to TestRail. Now, users may connect and visualize his/her test case ID from TestRail to Kobiton and vice versa.

== Bug Fixes

To some users, 'Save Password' pop-up on Chrome (Android Devices) disrupts automation. Kobiton now handles this issue by turning off 'Save Password' pop-up on devices.
