= Hardware requirements for deviceConnect
:navtitle: Hardware requirements for deviceConnect

== Hardware requirements for deviceConnect
deviceConnect requires an Apple silicon Mac mini - the *Mac mini host* - with the following minimum specs:

* macOS Sonoma 14 or later (including Tahoe)
* At least 24GB RAM
* At least 512GB SSD (1TB optimal)

[IMPORTANT]
The Mac mini host must be dedicated to hosting Kobiton and devices. Do not install any additional software not mentioned in install documentation.

A Mac mini workstation can host up to 15 mobile devices. Use one of the following Cambrionix hub models to connect mobile devices to the workstation:

* link:https://www.cambrionix.com/products/powerpad15s-pp15s-industrial-usb-hub[PowerPad15S,window=read-later]
* link:https://www.cambrionix.com/products/supersync15/[SuperSync15,window=read-later]
* link:https://www.cambrionix.com/products/thundersync3-16[ThunderSync3-16,window=read-later]


PowerPad15S or SuperSync15 requires one USB 3.0 cable to connect a hub to the Mac mini or Dell server. We recommend shielded USB 3.0 cables. For Standard mode, 3ft or 6ft cables are usually sufficient.

ThunderSync3-16 requires one Thunderbolt™ cable to connect a hub to the Mac mini or Lenovo server. Thunderbolt 3 is the minimum requirement, but Thunderbolt 4 and Thunderbolt 5 cables also work. For Standard mode, 3ft or 6ft cables are usually sufficient.

[NOTE]
The Dell server does not support Thunderbolt. To connect a hub to a Dell server, use PowerPad15S or SuperSync15 with a USB 3.0 cable.
