#!/usr/bin/env node

const fs = require("fs");

const sourceFile = process.env.GAZETTE_SOURCES_FILE;
const releaseDate = process.env.RELEASE_DATE || "Target release date TBD";
const releaseLabel = process.env.RELEASE_LABEL || "Target release TBD";

function stripLeadingComments(content) {
  return content.replace(/^(\/\/.*\n|\s*\n)+/, "").trim();
}

if (!sourceFile) {
  console.error("Missing GAZETTE_SOURCES_FILE.");
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(sourceFile, "utf8"));

const lines = [];

lines.push("= Release Notes");
lines.push("");
lines.push(`_${releaseDate}_`);
lines.push("");
lines.push("// Generated by The Gazette.");
lines.push("// Review structure, release date, and entry placement before publishing.");
lines.push("");
lines.push(`== ${releaseLabel}`);
lines.push("");

if (data.sources.length === 0) {
  lines.push("// No release-note partials found for this run.");
  lines.push("");
} else {
  for (const source of data.sources) {
    lines.push(`// Source: ${source.ticket_key || "Unknown ticket"} from PR #${source.pr.number}`);
    lines.push(`// ${source.pr.url}`);
    lines.push("");
    lines.push(stripLeadingComments(source.content));
    lines.push("");
  }
}

if (data.needs_editor_review && data.needs_editor_review.length > 0) {
  lines.push("");
  lines.push("== Editor review candidates");
  lines.push("");
  lines.push("// These PRs may contain release-note-worthy changes.");
  lines.push("// They did not include release-note partial files.");
  lines.push("// Human review required before inclusion.");
  lines.push("");

  for (const candidate of data.needs_editor_review) {
    lines.push(`=== ${candidate.pr_title}`);
    lines.push("");
    lines.push(`// PR: ${candidate.pr_url}`);
    lines.push(`// Reason: ${candidate.reason}`);

    if (candidate.signal && candidate.signal.length > 0) {
      lines.push("// Signals:");
      for (const signal of candidate.signal) {
        lines.push(`// - ${signal}`);
      }
    }

    lines.push("");

    if (candidate.changed_files && candidate.changed_files.length > 0) {
      lines.push("// Changed files:");
      for (const file of candidate.changed_files) {
        lines.push(`// - ${file}`);
      }
    }

    lines.push("");
  }
}

process.stdout.write(lines.join("\n"));