#!/usr/bin/env node

const fs = require("fs");

const sourceFile = process.env.GAZETTE_SOURCES_FILE;
const releaseDate = process.env.RELEASE_DATE;
const releaseLabel = process.env.RELEASE_LABEL || "Target release TBD";

if (!sourceFile) {
  console.error("Missing GAZETTE_SOURCES_FILE.");
  process.exit(1);
}

if (!releaseDate) {
  console.error("Missing RELEASE_DATE.");
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(sourceFile, "utf8"));

const lines = [];

lines.push("= Release Notes");
lines.push("");
lines.push(`_${releaseDate}_`);
lines.push("");
lines.push("// Generated by The Gazette.");
lines.push("// Review structure, release date, and entry placement before publishing.");
lines.push("");
lines.push(`== ${releaseLabel}`);
lines.push("");

if (data.sources.length === 0) {
  lines.push("// No release-note partials found for this run.");
  lines.push("");
} else {
  for (const source of data.sources) {
    lines.push(`// Source: ${source.ticket_key || "Unknown ticket"} from PR #${source.pr.number}`);
    lines.push(`// ${source.pr.url}`);
    lines.push("");
    lines.push(source.content.trim());
    lines.push("");
  }
}

process.stdout.write(lines.join("\n"));