= Kobiton Docs contribution guide

Thanks for contributing to Kobiton Docs! This guide covers how content for link:https://docs.kobiton.com/[docs.kobiton.com] is created, organized, and published. Everyone here is expected to adhere to the xref:CODE_OF_CONDUCT.adoc[Code of Conduct], so be sure to review before continuing.

If you're new to docs-as-code, see xref:_get_started[], otherwise choose a topic from the xref:_table_of_contents[table of contents].

[#_table_of_contents]
== Table of contents

* xref:_get_started[]
* xref:_build_the_docs[]
* xref:_file_nameing[]
* xref:_directory_structure[]
* xref:_antora_playbooks[]
* xref:_navigation_bar[]
* xref:_partials[]
* xref:_page_templates[]
* xref:_style_and_voice[]
* xref:_publishing[]

[#_get_started]
== Get started

Our docs are managed as docs-as-code, meaning each document is a plain text file stored in a version-controlled repository. Select a topic to learn more:

* *Version control:* link:https://docs.github.com/get-started/quickstart/hello-world[GitHub]
* *Files:* `.adoc` files written in link:https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc] markup
* *Static site generator:* link:https://docs.antora.org/antora/latest/how-antora-works/[Antora]
* *Publish:* link:https://docs.docker.com/get-started/[Docker]

[#_build_the_docs]
== Build the docs

To build the docs locally, you'll need link:https://nodejs.org/[Node.js] and link:https://yarnpkg.com/[Yarn]. Run the following commands to check if they're installed:

[source,shell]
----
node --version
yarn --version
----

If Node.js and Yarn are installed, you can install our project dependencies and build the docs locally by running the following commands:

[source,shell]
----
yarn install
yarn build
----

[#_directory_structure]
== Directory structure

The Kobiton Docs repository uses one `modules` directory containing an `antora.yml` file, a `ROOT` directory, and directories for each Kobiton feature. Each directory within `modules` contains its own `images`, `pages`, and `partials` directories, along with a `nav.adoc` file.

For example:

[source,]
----
kobiton-docs
└── docs
    └── modules
        ├── ROOT
        │   ├── images
        │   ├── pages
        │   │   └── index.adoc
        │   ├── partials
        │   └── nav.adoc
        ├── automation-testing
        │   ├── images
        │   ├── pages
        │   │   └── index.adoc
        │   ├── partials
        │   └── nav.adoc
        ├── manual-testing
        │   ├── images
        │   ├── pages
        │   │   ├── index.adoc
        │   │   └── other-page.adoc
        │   ├── partials
        │   └── nav.adoc
        └── antora.yml
----

[#_antora_playbooks]
== Antora playbooks

Typically, Antora configurations use one `antora-playbook.yml` file, however in Kobiton Docs we use two:

* `antora-playbook-docs.yml`
* `antora-playbook-widget.yml`

The first playbook is used to configure link:https://docs.kobiton.com/[docs.kobiton.com], while the second is used to configure the help widget on link:https://portal.kobiton.com/[portal.kobiton.com]. Additionally, each playbook uses their own UI bundle:

* `ui-bundle-docs`
* `ui-bundle-widget`

In general, both playbooks should match each other, while each UI bundle should be unique.

[#_navigation_bar]
== Navigation bar

Each subdirectory in `modules` contains a dedicated `nav.adoc` file. When Antora builds the docs, `modules/antora.yml` will reference each `nav.adoc` and create the site's navigation bar.

For example, `antora.yml` will create the site's navigation bar by referencing `automation-testing/nav.adoc` and `manual-testing/nav.adoc`:

[source,]
----
kobiton-docs
└── docs
    └── modules
        ├── automation-testing
        │   └── nav.adoc
        ├── manual-testing
        │   └── nav.adoc
        └── antora.yml
----

To configure the navigation bar open a subdirectory in `modules` and edit the related `nav.adoc` file.

For example:

[source,asciidoc]
----
* xref:index.adoc[]
** desired-capabilities
*** xref:auto-generate-desired-capabilities.adoc[]
*** xref:list-of-desired-capabilities.adoc[]
** xref:download-appium-script.adoc[]
** xref:supported-client-libraries.adoc[]
----

[#_partials]
== Partials

You can use partials to reuse content accross the docs. _Global_ content (role requirements, pricing, etc.) is located within the `partials` directory in `ROOT`, while _feature-specific_ content (supported app filetypes, supported gestures, etc.) is located within the `partials` directory for that specific feature.

For example:

[source,]
----
kobiton-docs
└── docs
    └── modules
        ├── ROOT
        │   └── partials
        │       ├── pricing.adoc
        │       └── roles-page.adoc
        └── apps
            └── partials
                └── supported-filetypes.adoc
----

To reference a global partial, use the following `include` statement:

[source,asciidoc]
----
`include::ROOT:partial$<filename>.adoc`
----

To reference a feature-specific partial, use the following `include` statement:

[source,asciidoc]
----
`include::<feature>:partial$<filename>.adoc`
----

[#_file_nameing]
== File naming

Files in Kobiton Docs should follow these guidelines:

[cols="5,3,3"]
|===
|Guideline|Before|After

|Only lowercase letters
|`This Is My TITLE`
|`this is my title`

|Replace spaces with dashes
|`this is my title`
|`this-is-my-title`

|Replace important symbols
|`i love c++ & c#`
|`i love cpp and csharp`

|Remove unimportant symbols
|`this: is my title!`
|`this is my title`
|===

For example:

[source,]
----
automation-testing
└──pages
    ├── desired-capabilities.adoc
    ├── download-appium-script.adoc
    ├── index.adoc
    └── supported-client-libraries.adoc
----

[#_page_templates]
== Page templates

We use the link:https://diataxis.fr/#[Diátaxis] framework to structure our docs. Each Diátaxis category corresponds to one of these templates. Add a template to your `.adoc` file to get started.

=== Tutorial

Tutorial docs walk users through their first time attempting a task. Everything a user needs should be available in the tutorial.

For example, a tutorial titled "Your first manual session" would state a learning objective, show the user how to start a session, offer an app for them to install, and walk them through a variety of test steps.

==== Template

[source,asciidoc]
----
= Title
:navtitle: Title

In this tutorial we'll walk you through your first...

== Before you start

You'll need to download...

== Step 1

Content.

== Step 2

Content.

. Sub-step
. Sub-step

----

=== How-to

How-to docs outline the steps for solving a specific problem. Unlike tutorials, How-tos only focus on a specific problem--not an entire process.

For example, a how-to doc titled "Download an app during a manual test session" would state the goal, give a line of context, and start step one assuming the user has _already_ launched a manual test session.

==== Template

[source,asciidoc]
----
= Title
:navtitle: Title

Learn how to...

== Step 1

Explain and give steps.

== Step 2

Explain steps.

. Give step
. Give step

----

=== Reference

Reference docs describe a _product_, not a _process_. They're for users who know how to complete a proccess, but need more details about the _tools_ they use to complete a process.

For example, a reference doc titled "Desired capabilities" should list all desired capabilities along with their definition and a brief example. The reference doc shouldn't contain steps for modifying desired capabilities or walk users through their first automation session.

==== Template

[source,asciidoc]
----
= Title
:navtitle: Title

These are the ... for ...

== Category one

Item.

Definiton.

Example.

== Category two

=== Item one

Definiton.

Example.

=== Item two

Definiton.

Example.

----

=== Explanation

Explanation docs explore a topic, which could include its context within culture, its context within Kobiton, how it got here, and where it's headed.

For example, an explanation doc titled "About biometric authentication" should explore a few key milestones in its global development, why It's important to test, and how Kobiton can help.

==== Template

[source,asciidoc]
----
= Title
:navtitle: Title

<Topic does x...>

== First item

Content.

== Second item

Content.

----

[#_style_and_voice]
== Style and voice

One day we'll make our own, but for now we use the https://learn.microsoft.com/en-us/style-guide/welcome/[Microsoft Style Guide] as style and voice guideline.

[#_publishing]
== Publishing

We use link:https://www.docker.com/[Docker] to publish content to link:https://docs.kobiton.com/[docs.kobiton.com] and the help widget on link:https://portal.kobiton.com/[portal.kobiton.com]. Run the following commands to check if its installed:

[source,shell]
----
docker --version
----

To build an image for link:https://docs.kobiton.com/[docs.kobiton.com], run:

[source,shell]
----
docker build -t kobiton/docs:1.0 -f docker/docs/Dockerfile .
----

To build a docker image for the help widget on link:https://portal.kobiton.com/[portal.kobiton.com], run:

[source,shell]
----
docker build -t kobiton/widget:1.0 -f docker/widget/Dockerfile .
----
