= Install OpenSSL
:navtitle: Install OpenSSL

Learn how to install OpenSSL on your computer so you can use VirtualUSB to debug your devices from anywhere.

[NOTE]
VirtualUSB requires OpenSSL version *1.0.2t 10 Sep 2019* or later.

== Configure your environment

If you're using a Mac with Apple silicon, first you'll need to install Rosetta, enabling your machine to run apps built for Intel processors. Otherwise, you can continue.

[source,bash]
----
softwareupdate --install-rosetta
----

Install *Homebrew*, a package manager for MacOS:

[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
----

Verify your default shell and add *Homebrew* to your configuration file:

[source,bash]
----
echo $SHELL
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
----

Apply the changes to your configuration file:

[source,bash]
----
source ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
----

Finally, install *wget*, a command-line tool for retrieving web content:

[source,bash]
----
brew install wget
----

[#_install_and_configure_openssl]
== Install and configure OpenSSL

Install OpenSSL from the project's link:https://github.com/openssl/openssl[open-source repository]:

[source,bash]
----
wget https://raw.githubusercontent.com/rbenv/homebrew-tap/master/Formula/openssl%401.0.rb
----

Open `openssl@1.0.rb` in your text editor and remove `system "make", "test"` from line 42:

[source,ruby]
----
system "perl", "./Configure", *args
system "make", "depend"
system "make"
system "make", "test" # Remove this line
system "make", "install", "MANDIR=#{man}", "MANSUFFIX=ssl"
----

Now that `system "make", "test"` is removed, reinstall OpenSSL:

[source,bash]
----
brew reinstall openssl@1.0.rb
----

Create a symlink to your `/usr/local/lib/` directory:

[source,bash]
----
ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t/lib/libssl.dylib /usr/local/lib/libssl.dylib
----

Copy the contents from `openssl` to your `/usr/local/bin/` directory:

[source,bash]
----
sudo cp /usr/local/Cellar/openssl@1.0/1.0.2t/bin/openssl /usr/local/bin/
----

Add the following OpenSSL flags to your configuration file:

[source,bash]
----
echo 'export LDFLAGS=-L/usr/local/opt/openssl@1.0/lib' >> ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
echo 'export CPPFLAGS=-I/usr/local/opt/openssl@1.0/include' >> ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
----

Apply the changes to your configuration file:

[source,bash]
----
source ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
----

Finally, verify your OpenSSL installation and confirm the version is *1.0.2t 10 Sep 2019* or later:

[source,bash]
----
openssl version
----
