= Set up VirtualUSB
:navtitle: Set up VirtualUSB

Learn how to set up VirtualUSB on your personal computer, so you can debug public and private devices. If your local Kobiton server was configured for VirtualUSB, you can also debug local devices

== Before you start

This

[#_configure_openssl]
== Configure OpenSSL

If it's not installed already, install link:https://github.com/openssl/openssl[OpenSSL] using the following command:

[source,bash]
----
wget https://raw.githubusercontent.com/rbenv/homebrew-tap/master/Formula/openssl%401.0.rb
----

Open `openssl@1.0.rb` in a text editor and remove `system "make", "test"` from line 42:

[source,ruby]
----
system "perl", "./Configure", *args
system "make", "depend"
system "make"
system "make", "test" # Remove this line
system "make", "install", "MANDIR=#{man}", "MANSUFFIX=ssl"
----

Reinstall OpenSSL using the following command:

.MacOS
[source,bash]
----
brew reinstall openssl@1.0.rb
----

.Windows
[source,bash]
----
$UPDATE$
----

Create a symlink to your `/usr/local/lib/` directory:

.MacOS
[source,bash]
----
ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t/lib/libssl.dylib /usr/local/lib/libssl.dylib
----

.Windows
[source,bash]
----
$UPDATE$
----

Copy the contents from `openssl` to your `/usr/local/bin/` directory:

.MacOS
[source,bash]
----
sudo cp /usr/local/Cellar/openssl@1.0/1.0.2t/bin/openssl /usr/local/bin/
----

.Windows
[source,powershell]
----
$UPDATE$
----

Add the following OpenSSL flags to your shell's config file:

[source,bash]
----
echo 'export LDFLAGS=-L/usr/local/opt/openssl@1.0/lib' >> ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
echo 'export CPPFLAGS=-I/usr/local/opt/openssl@1.0/include' >> ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
----

Apply the changes to your configuration file:

[source,bash]
----
source ~/<config-file> # .zshrc for Z shell or .bashrc for Bash
----

Verify your OpenSSL version is *1.0.2t 10 Sep 2019* or later:

[source,bash]
----
openssl --version
----

== Add `adb` environment variables

To debug Android devices, install link:https://developer.android.com/tools/releases/platform-tools[Android Debug Bridge (adb)] and add the following `adb` environment variables to your path:

.MacOS
----
export ANDROID_HOME=path/to/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
----

.Windows
[source,powershell]
----
set ANDROID_HOME=C:\path\to\Android\Sdk
set PATH=%PATH%;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools
----

== Install iTunes and third-party libraries

To debug iOS devices on Windows, first link:https://support.apple.com/en-us/HT210384[install iTunes], then consider installing a third-party library that lets Windows communicate with iOS devices natively.

== Install virtualUSB

Download VirtualUSB from the link:https://portal.kobiton.com/[Kobiton portal].

image:$OLD-IMAGE$[width=, alt=""]

When your installation is finished, on Windows, run the following commands:

.Windows
[source,powershell]
----
cd C:\Program Files\virtualUSB
vusb setup-ios
----

Finally, launch VirtualUSB and sign in using your email address and password or xref:profile:server-url-and-api-keys.adoc[Kobiton API key].

image:$OLD-IMAGE$[width=, alt=""]

Now you can debug cloud devices using VirtualUSB. If you want to use virtualUSB on local devices, you'll also need to...
