= Using views
:navtitle: Using views

Use views like *card view* and *list view* to find a device and start testing!

== Types of views
[cols="1h,4",autowidth"]
|===
|Card view (default)
|A simplified view that displays essential information, like device name, operating system, and device status.

|List view
|A detailed view that displays information, like UDID, resolution, serial number, and more. You can also customize and sort these fields to build view that's right for you!
|===

== Using the card view

. Open the https://portal.kobiton.com/login[Kobiton portal].
. Select *Devices*.
. Choose *Public Devices* or *Local & Private Devices*.
. Select *Card View*.
. You can use the *Sort by:* drop-down to sort the list by *OS Version*, *Device Name*, *Friendly Name*, or *Device Health*.
[NOTE]
If you're not sure what the difference between *Device Name* and *Friendly Name*, you can read more here.

. You can select the *Apple logo* or *Android logo* to sort by operating system.
. You can use xref:launching-your-device/using-device-statuses.adoc[device statuses] to show or hide *Online*, *Busy*, or *Offline* devices.
. Once you've found the device you're looking for, select *Launch* to start testing!

== Using the list view

. Open the https://portal.kobiton.com/login[Kobiton portal].
. Select *Devices*.
. Choose *Public Devices* or *Local & Private Devices*.
. Select *List View*.
. You can select the *Apple logo* or *Android logo* to sort by operating system.
. You can use xref:launching-your-device/using-device-statuses.adoc[device statuses] to show or hide *Online*, *Busy*, or *Offline* devices.
. If you'd like to further customize your view, select *Edit Column*.
. You can display a maximum of nine columns, so select and deselect device details to build a view that's right for you.
. After you've built your new view, select *Edit Column* again to close the editing window.
. Now you can select a column header to sort the list by that specific device detail. You can also sort the list by ascending or descending order by using the *up* and *down arrows*, respectively.
. Once you've found the device you're looking for, select *Launch* to start testing!
