= Annotate a test step for scriptless automation
:navtitle: Annotate a test step

Learn how to annotate a test step from your xref:scriptless-automation:create-a-baseline-session.adoc[baseline session], so you can...

== Before you start

You'll need to xref:scriptless-automation:create-a-baseline-session.adoc[create a baseline session].

== Annotate a test step

In *Sessions*, xref:session-explorer:search-for-a-session.adoc[search for a session], then select the session.

image:$NEW$[width="",alt=""]

Select *Automation Test Case*.

image:$NEW$[width="",alt=""]

If one of your test steps were flagged, you'll see a warning similar to the following:

image:$NEW$[width="",alt=""]

Scroll through your test steps and look for any steps highlighted in red with the option to annotate.

image:$NEW$[width="",alt=""]

Select *Annotate*.

image:$NEW$[width="",alt=""]

== Annotation options

These are the different options for annotating a test step:

** xref:test-management:remediation/crash-remediation.adoc[]
** xref:test-management:remediation/element-selection-remediation.adoc[]
