= Create a test case
:navtitle: Create a test case

Learn how to create a test case so you can run xref:scriptless-automation:index.adoc[scriptless automation].

== Before you start

You'll need to complete the following:

* xref:scriptless-automation:create-a-baseline-session.adoc[Create a baseline session].
* If applicable, xref:remediation/annotate-a-test-step.adoc[annotate any flagged test steps].

== Create a test case

In *Sessions*, xref:session-explorer:search-for-a-session.adoc[search for a session], then select a session.

image:$NEW$[width="",alt=""]

Select *Automation Test Case*.

image:$NEW$[width="",alt=""]

If your test case has any issues, you'll need to xref:remediation/annotate-a-test-step.adoc[annotate your flagged test steps] first. When your test case is good to go, you'll see the following message:

image:$NEW$[width="",alt=""]

When you're ready, select *Convert to Test Case*.

image:$NEW$[width="",alt=""]

If you'd like to make changes to your test case before running scriptless automation, see xref:manage-test-steps.adoc[].
