= Data-driven testing for text
:navtitle: Data-driven testing for text

$DESCRIPTION$

== Access the Test Execution plan of a specific manual session

In the session list, click the Test Execution plan icon on a manual session

image:$OLD-IMAGE$[width="", alt=""]

== Access the Dynamic Data section

In the Dynamic Data section, you will see the “Manual” chipset, demonstrating the original values from your manual session and these values could not be modified.

NOTE: Currently Scriptless Automation only supports defining a new dataset for the test action “Set_Text" only. Stay tuned! Scriptless Automation will provide an ability to define more advanced assertions for the dynamic test case like Text Validations, Element Visible, etc. in our upcoming release.

image:$OLD-IMAGE$[width="", alt=""]

== Define a new dataset

Next to the “Manual” chipset, you will see the “+” icon for creating a new dataset for your revisit session.

image:$OLD-IMAGE$[width="", alt=""]

== Set new value

A created dataset will clone all values from a manual session as a default value, then you can modify these values again as your preferred set.

NOTE: For any values that are different from a manual, you will see the indicator “Edited” to demonstrate a new value.

image:$OLD-IMAGE$[width="", alt=""]

== Trigger revisit on new datasets

After defining all needed values, you can trigger Scriptless Automation by clicking on the button “Run Scriptless Sessions” or “Re-run Scriptless Automation”, the new dataset will be automatically applied for your revisit executions.
