= Manage scriptless sessions
:navtitle: Manage scriptless sessions

$DESCRIPTION$

== How to go to Test Case

. After you have triggered scriptless sessions rerun, the baseline session will convert itself to a Test Case within Test Management (this functionality is only available on Latest Kobiton, not Legacy Kobiton). You can navigate the Test Case in two ways:

* *Method 1:* Select *Session List* in the sidebar menu on the left,
right-click the original baseline session, and select
*View Test Case*.
+
image:./guide-media/01GWEJZ245RPCGGP65EWBCYSV7[width=, alt="Screen_Shot_2022-05-24_at_12.25.34_PM.png"]

* *Method 2:* Alternatively, select *Test Management* in the
sidebar menu on the left, and select the app-under-test on the list in the upper
right corner.
+
image:./guide-media/01GWE6K8MWC0ZJ8K408M0PSMC0[width=, alt="Screen_Shot_2022-05-24_at_12.26.48_PM.png"]

. Then, from the list of test cases, referencing the baseline session id to select
the generated test case.
+
image:./guide-media/01GWEBYE1TD8Q13YQXEV9GSVDB[width=, alt="Screen_Shot_2022-05-24_at_1.05.05_PM.png"]

== Navigate Test Case Details

=== Delete a test step

In the baseline manual session, you might make some redundant steps such as an accidental touch or swipe and you don't want that unnecessary step to be rerun. You can delete those redundant steps from the baseline manual session by checking at the upper right corner of the step, then select

image:./guide-media/01GWE6K9C28MM2FQYEZPZB1SCY[width=25, alt="Screen_Shot_2022-05-24_at_1.33.03_PM.png"]

image:./guide-media/01GWEQT8VF8KYJN0J6QA6PW8MQ[width=, alt="Jun-10-2022_14-33-20.gif"]

=== Modify value of a set-text step

For test steps that input string value to a field such as username, email, URLs, phone number, the value can be modified. Select

image:./guide-media/01GWE1D88XC65VYA26SMWE8H1S[width=, alt="Screen_Shot_2022-06-10_at_3.45.57_PM.png"]
underneath
the test step to modify its string value.

image:./guide-media/01GWEBYH5FX2AJ96QRFJNKR70F[width=, alt="Jun-10-2022_15-28-19.gif"]

=== Run Scriptless

After editing test steps with necessary deletion or modification, in the upper right corner, you can select *Run Scriptless* to start triggering
scripless rerun sessions.

image:./guide-media/01GWEMMMGMSS65AEFFQ882FXGG[width=, alt="Screen_Shot_2022-05-24_at_1.28.05_PM.png"]

=== Export Appium script

Alternatively, you can also export Appium automation script from the baseline session from here, simply choose among framwork TestNG or JUnit.

image:./guide-media/01GWEBYF144ZQ7DAR59C9GQCAJ[width=, alt="Screen_Shot_2022-05-24_at_1.33.17_PM.png"]
