= Manage automated test case
:navtitle: Manage automated test case

Learn how to manage the Automated Test Case before using it to run scriptless automation.

== Test case details

After converting a manual session into an Automated Test Case, you are taken to the test case details page. In this page, you can:

* Edit the test case name by selecting the edit button next to it.
* Remove test steps or update inputted data.
* Rerun the recorded test case on device bundles.
* Generate Appium script.

== Remove test steps

In a manual sessions, there may be undesired steps that was performed by mistake or redundant. To remove a step, select the checkbox next to it. You can select multiple test steps at the same time.

Select the Delete Test Step button to remove the selected steps.

Once deleted, the test steps are not recoverable.

== Edit inputted data

You can also change the text data inputted in the session. Select the gear icon on a step that has input data:

Select the edit icon next to the input text.

Change the text content to a new one. Select Save to make the change.

== Use predefined phone number

Todo