= Test cases
:navtitle: Test cases

$DESCRIPTION$

== Scriptless Automation's progress bar

After Scriptless Automation automated executions are completed, a validation
will be triggered to automatically identify visual difference across multiple
selected devices. When viewing the Test Case List, beside the Search bar, there
is a validation Progress that demonstrates the status of Scriptless Automation
executions at a single point of time.

image:./guide-media/01GWDZ1SJW0DRE50ZTFD9M7058[width=, alt="progress-bar.png"]

|===
|Action|Description

|Preparing
|This step will be checked as soon as you run an Scriptless Automation
session. During execution on each device that status is enqueued
or running, you can terminate any long-lasting executions that you
think may decelerate other executions. If your execution is stuck
with a blocker, let's resolve this by choosing the
link:/hc/en-us/articles/360055620472[ignore] option
to remove this blocking device out of the bundle.

|Analyzing
|Then do not lose track of this progress while we are using some AI
algorithms to instantly validate each page of your application sites
and highlight only some significant bugs related to color text, text
appearance, etc. We will send an email to you as soon as this step
completed

|Completed
|Well done! All have been finished and you can check your remediation
(if any) by jumping to the Validation List page.
|===

To navigate to the Validation List page, you can click on the icon shown in the
below image.

image:./guide-media/01GWEMM7EERNRMR70YBH8YWQY1[width=, alt="assertion-icon.png"]

*Note*: An icon is only available when the state of the progress
bar is Completed.

Then, you will be able to access validation List page

image:./guide-media/01GWECYVVZFG04V3VQFPQPZTFN[width=, alt="assertion-list.png"]
