= Manage users
:navtitle: Manage users

Learn how to manage your users, so you can ..., and more. In *Org Management*, select *Users*, then choose a user to get started.

image:<NEW-IMAGE>[width=,alt=""]

== Enable Single-Sign On (SSO) authentication

After you xref:sso-authentication/about-sso-authentication.adoc[configure SSO authentication for your organization], select *Details*, then *Enable SSO*.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Disable a user

In *Details*, select *Disable* to deactivate the user but keep them in your system.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove a user

In *Details*, select *Remove* to completely remove the user from your system.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Assign a role

In *Roles*, use the search bar to find a role you previously created.

image:<NEW-IMAGE>[width=,alt=""]

Select the *plus icon* next to the role.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove a role

In *Roles*, select the *minus icon* next to the role you want to remove.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Add to a team

In *Teams*, use the search bar to find a team you previously created.

image:<NEW-IMAGE>[width=,alt=""]

Select the *plus icon* next to the team.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove from a team

In *Teams*, select the *minus icon* next to the team you want to remove the user from.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== View user history

In *User History*, you can access a xref:users/user-history-report.adoc[user's history report].

image:<NEW-IMAGE>[width=,alt=""]
