= User history report
:navtitle: User history report

The user history report contains data about each user event.

== Open the report

In Kobiton, select *Org Management > Users*.

image:$NEW-IMAGE$[width=,alt=""]

xref:organization:users/search-for-a-user.adoc[Search for a user], then select their username.

image:$NEW-IMAGE$[width=,alt=""]

Select *User History* to open the report and view all user events.

image:$NEW-IMAGE$[width=,alt=""]

[#_filter_the_report]
== Filter the report

You can filter the report to review specific events. For more information, see xref:_event_types[].

=== By type

To filter the report by an event type, select the dropdown and choose an xref:_event_types[event type].

image:$NEW-IMAGE$[width=,alt=""]

=== By time

To filter the report by time, select *Time*, then choose a timeframe.

image:$NEW-IMAGE$[width=,alt=""]

If you select *Custom*, you can choose select two dates to create a custom date range.

image:$NEW-IMAGE$[width=,alt=""]

=== Using search

To filter the report using search, enter an application, session, or xref:_event_types[event type] into the search bar.

image:$NEW-IMAGE$[width=,alt=""]

[#_event_types]
== Event types

The following event types are included in the user history report:

[cols="1,1,2"]
|===
|Event Type |Event |Description

.5+|Activities
|User Login
|The user logged in to the portal.

|User Logout
|The user logged out of the portal.

|Removed User
|The user removed another user.

|Disabled User `<user_name>`
|The user disabled another user.

|User Created
|The user logged in to the portal for the first time.

.2+|Device Retainment
|Device Retained
|The user retained a device after their session.

|Device Released
|The user ended a session which released their device.

.3+|Device Enablement
|Device Registered
|The user's device connected to the portal.

|Device Unregistered
|The user's device disconnected from the portal.

|Device Restarted
|The user restarted their device.

|Application Installed
|Application Installed
|The user installed an application.

|Application Launched
|Application Launched
|The user launched an application they previously installed.
|===
