= User history report
:navtitle: User history report

The user history report contains data about each xref:_event_types[user event]. In *Org Management*, select *Users*, choose a user, then select *User History* to get started.

image:<NEW-IMAGE>[width=,alt=""]

== Type

Only display xref:_event_types[events] matching the selected type.

image:<NEW-IMAGE>[width=,alt=""]

== Time

Display the user history data within a preselected time range, or select *Custom* to xref:_date_range[choose your own].

image:<NEW-IMAGE>[width=,alt=""]

[#_date_range]
== Date range

Display the user history data within a custom date range.

== Search

Filter the report by a specific xref:_event_types[event], application, or session.

image:<NEW-IMAGE>[width=,alt=""]

== Columns

Each column contains details about the user history.

image:<NEW-IMAGE>[width=, alt=""]

=== Date

The date of the event.

=== Event

The type of event. xref:_event_types[See all event types].

=== Device

The device used in the event.

=== Application

The application used in the event.

=== Session

The session recording of the event.

[#_event_types]
== Event types

These are event types included in the user history report.

=== Activities

==== User Login

When the user logs in to the portal.

==== User Logout

When the user logs out of the portal.

==== Removed User

When the user removes another user.

==== Disabled User <user_name>

When the user disables another users.

==== User Created

When the user logs in to the portal for the first time.

=== Device Retainment

==== Device Retained

When the user retains a device.

==== Device Released

When the user ends a session.

=== Device Enablement

==== Device Registered

When the user's device was connected to the portal.

==== Device Unregistered

When the user's device was disconnected from the portal.

==== Device Restarted

When the user restarts a device.

=== Application Installed

When the user installs an application.

=== Application Launched

When the user launches an application they previously installed.
