= v3.5 | August 10, 2020
:navtitle: v3.5 | August 10, 2020

== New Device Lab Management features

* *Is your app ready for iOS 14?* Get ahead of the official release date and manually test your app with Kobiton’s support for iOS14 beta.

* *Get more done faster with our new Live View*: Now there’s no need to wait for your automation test session to finish before watching the video. With Live View, you can see your automation session executing in real-time!

* *Prefer Espresso to Appium?* Enhanced framework support with Espresso and UIAutomator is perfect for Android environments that prefer these frameworks over Appium.

* *Get deeper insights with System Metrics for Automation Sessions!* Easily review key system metrics and performance from your automated tests.

* *Other enhancements include*: Support for Android 11 beta on the OnePlus 8, improved SSO login flows, session exit flow and UI improvements.

== New Intelligent Test Automation features

* *Enhanced visual testing for even more flexibility!* Additional assertions have been added to allow additional visual testing, including the ability to test for text color differences, and the ability to support text equivalence assertions on dynamic controls such as in a list view.

* *Don’t let one-time-passwords stop you from automating your tests!* One-time-passwords (OTP) are increasingly common with today’s mobile apps, and can be a real pain for automation script developers. Kobiton will handle OTP verification seamlessly in the background so even the trickiest apps can be automated. This release supports the *_non short-code SMS verification_*, and additional verification methods will be supported in the September release.

* *Resume failed test executions*: When tests fail - because of a poor internet connection for example - Kobiton will classify the failure and allow automatic re-execution of that test on the specific device.

* *Rerun your tests on new versions of your app!* Want to rerun one of your existing ITA test sessions on a new version of your app? Easily invoke your previously recorded test sessions directly from within the portal, or via an API.

* *Bypass pesky pop-ups that break your scripts*: Pop-ups can wreak havoc with automation test scripts...especially unexpected system pop-ups. Now you have the option to bypass these pop-ups to allow your tests to continue uninterrupted!

* *Crash remediation on iOS means quickly finding problematic device/iOS combinations!* When a crash does occur, users will be presented with the specific crash remediation and the suggested course of action. This is our popular Android feature now available for iOS.

* *Forgot to request an automated test after a manual session?* We’ve got you covered! Now you can request to run an automated test from the Session Explorer page for any manual session.
