= v3.4 | June 29, 2020
:navtitle: v3.4 | June 29, 2020

== New Device Lab Management features

* *Is your App Android 11 ready? Announcing support for Android 11 Beta!* Get ahead of the biggest changes coming to Android and make sure your app is ready. Pinpoint the behavior changes that will affect your apps, and build with the latest platform capabilities provided in Android 11.

* *Simplify your development workflow! Access devices remotely from within your development environment* with our new ADB tunneling plugin (beta) for Android Studio/IntelliJ. Easily control devices remotely directly from within the IDE for the utmost in testing flexibility.

* *Find the devices you need, FAST!* The new search and filter logic gives you the ability to utilize more criteria in your searches (RAM, Carrier, Resolution etc.) and allow you to create compound searches, like looking for Samsung devices with a 1080x1920 resolution.

* *Same Day OS Support!* Although Kobiton aligns with testing framework’s official OS support, we have relaxed the restriction allowing you to test on the latest versions even when not officially supported by the framework.

* *Make sure your apps are well-behaved citizens with enhanced app monitoring!* Visually monitor CPU performance, Memory and Network Utilization to help with root cause analysis and finding those pesky performance and non-functional bottlenecks.

* *More scripting flexibility:* A new API/endpoint to allow installation of your app (and specific version) from the App Repository directly from within your automation scripts.

* *General system improvements* include improved cleanup policies on Android devices, Appium 1.17.1 support, Chrome v.83 support and iOS 13.5.1 support.

== New Intelligent Test Automation features

* *Elevate your functional test automation with Text Assertions!* Easily test expected vs actual results from your scriptless automation with text assertions. Choose how to handle each failed text assertion to accommodate different behavior across different devices.

* *Don’t let pop-ups break your automation scripts!* Improved Android and iOS pop-up handling means your automation scripts can run unhindered when unexpected pop-ups occur. Pop-up actions from your manual session are also captured for seamless replay in your automation session, even where text or visual differences are apparent across different operating systems.

* *Fly through resolving assertion failures with our one-of-a-kind Recommendation Engine!* Does your terms and conditions text always wrap differently on screens with a 4:3 aspect ratio? We’ll figure that out for you and recommend how to address the assertion failure permanently.

* *Additional gesture support* for scriptless automation including iOS Home button and Rotate, and improved touch and scroll gestures.

* *Improved scripless playbacks* thanks to a vastly increased AI dataset of over 1 million matches!
