= v3.8 | December 14, 2020
:navtitle: v3.8 | December 14, 2020

== Device Lab Management and Portal updates

* *Kobiton Payload information in the Session Explorer:* Kobiton will support Payload (request + response) capture for Android devices. For manual tests or automated tests built with Appium, we will capture this payload information during test execution. You will then be able to see these Performance Testing metrics in the Kobiton Session Explorer.

*_Known limitations:_*

* This will work best for Android devices running Android 9 or newer
* For the first version of this capability, this will only work for hybrid applications and mobile-browser

* *Performance improvements to your Kobiton Real Device Cloud with DirectTest:* We’ve made enhancements to our Real Device Cloud architecture that will improve your real device cloud performance across the board and drastically reduce input lag and latency.

[NOTE]
We will be rolling out these performance improvements on an On-Demand basis.

* *Better device identification with a new device tagging API:* We will offer a device tagging feature that allows you to easily identify devices and filter devices when users are running automated tests using the tag in their Appium desired capabilities.

* *Centralizing app versions in the Kobiton App Repository:* We've enhanced the Kobiton App Repository. With this new feature, teams will be able to better view apps as their own directories. These directories will house different versions of that particular app. This makes searching for and managing your apps much easier.

* *Customize your device display name:* Admins can now easily change the name of devices with the new custom naming capability. This custom name will then appear in the portal and you will be able to find that device by that custom name when running test automation.

* *Customize the window size of the Kobiton Desktop App:* In order to better fit more devices into one screen, you can now resize the window of the Kobiton desktop app. This removes the need to scroll or click through lists in order to see device status and troubleshoot if you have a large number of devices hosted by Kobiton.

* *Ability to resize the device log window:* In order to improve your overall user experience, we will allow you to resize the device log window.

* *App repository performance improvements with lazy-loading:* Your app repository performance has been improved with lazy-loading. This will help teams who have a lot of applications stored in the app repo, as you will no longer need to wait for all of your applications to load before interacting with the page.

* *ADB shell- more commands for public paid users:* Public Cloud users will be able to use just as many ADB shell commands as Private and Local Cloud users.

* *View remaining usage time of a softbooked device:* In our last release, you were able to softbook a device via an API. With this release, you can now see the remaining time left of that softbook via a count-down timer in the List View.

* *Automatic language switch back to English:* If you have changed the device language from English to one of 46 supported languages, the device will now automatically reset its language back to English upon cleanup. This will work for the following languages:

** English (US)
** English (Australia)
** Spanish (US)
** English (Canada)
** English (India)
** English (Ireland)
** English (New Zealand)
** English (Singapore)
** English (South Africa)
** English (UK)
** Chinese, Simplified
** Chinese, Traditional
** Chinese, Traditional (Hong Kong)
** Japanese
** Spanish
** Spanish (Latin America)
** French
** French (Canada)
** German
** Russian
** Portuguese (Brazil)
** Portuguese (Portugal)
** Italian
** Korean
** Turkish
** Dutch
** Arabic
** Thai
** Swedish
** Danish
** Vietnamese
** Norwegian Bokmål
** Polish
** Finnish
** Indonesian
** Hebrew
** Greek
** Romanian
** Hungarian
** Czech
** Catalan
** Slovak
** Ukrainian
** Croatian
** Malay
** Hindi

* *(Coming by end of 2020) Two new IDE plugins for ADB debugging:* You will have access to two new and improved IDE plugins for ADB debugging on IntelliJ and Android Studio by the end of 2020. The improvements to the plugins are as follows:
** Run your tests within your IDE’s without having to launch a separate manual session from the Kobiton portal
** The IntelliJ plugin is in the jet brains marketplace and is more accessible
** No need to restart the IDE after establishing a session

* *Device support updates:*
** Support for the iPhone 12 mini: We now offer enhanced support for the iPhone 12 mini.
** Support for the Huawei P20 Pro: Kobiton will support testing on the Huawei P20 Pro.

== Scriptless automation updates

[NOTE]
Moving forward, we are now referring to what was “ITA” as “Kobiton Scritptless automation.”

* *Data-Driven Testing (DDT) now supports an "element visible" validation:* You will be able to tell DDT to validate whether a certain element is present on your UI under test when executing scriptless test automation re-visits.

* *Drop-down menu support for DDT on Android Devices:* You will be able to use Kobiton's Data-driven testing capability to add parameters around data chosen from a drop-down menu on Android devices. This will tell our AI to run scriptless automated test executions according to the parameters chosen with DDT.

[NOTE]
Currently, this only works with Android.

* *Data-Driven-Testing for registration flow:* Now, you can parameterize the expected credential value for ITA's pre-processing (you can now edit the values on the “manual” card in DDT).

* *We’ll tell you what beautiful is—Scriptless Visual UX Testing:* Our AI has learned how to compare the visual design of your application to the world's best and most beautiful applications. Upon making the comparison, we will give recommendations for how to best optimize the UI and UX of your application. For this release, we’ll compare and offer recommendations around font size.

*_Known limitations:_* This new kind of Visual UX Testing will only work on native applications for both Android and iOS.

* *Live View for Kobiton scriptless test automation:* Users will now be able to watch live video footage of their scriptless automation revisit executions on their selected devices. This feature can be found in the Test Execution plan and will be displayed in a grid view.

[NOTE]
Live View will only be visible in the “Execution Plan” and not in the Session Details/Overview.

* *Enhanced support for scriptless automation of OTP (one-time password) for iOS:* We have improved our support for OTP on scriptless test automation revisits. For this release, we added support for apps that are using non-short code SMS to send out OTP code.

* *Scriptless test automation for mobile browser:* Customers will be able to use Kobiton’s scriptless test automation for exploratory tests done on mobile browser.

*_Known limitations:_*

* Manual tests on Chrome will revisit on Chrome on an Android devices
* Manual tests on Safari will revisit on Safari on iOS devices
