= v3.6 | September 21, 2020
:navtitle: v3.6 | September 21, 2020

== New Device Lab Management features

* *Android 11 is here!* Although it’s packed full of bells and whistles sure to delight users, it also comes with behavior changes that require careful testing of your app. Utilize Kobiton to ensure your app is a well-behaved Android 11 citizen across all device types.

* *Bullet-proof your app on iOS 14!* As iOS 14 is “hot off the press”, this capability is in beta pending completion of our tests.

* *Resolve test failures with pinpoint accuracy using the new Session Explorer!* Running test scripts is one thing, pinpointing the issue is another. Get unprecedented accuracy and efficiency and go straight to the problem, instead of reviewing hours of videos or pouring through gigabytes of log files.

* *Monitor app performance on iOS!* In addition to comprehensive log files and videos, you can now enjoy detailed session metrics including RAM usage, CPU performance and network activity.

* *Our powerful Organization Management feature just became even more powerful!* Our extended API provides for more fine-grained control including assignment/removal of a group for a user, user reactivation and user role assignment.

== New Intelligent Test Automation features

Intelligent Test Automation is the industry’s first and only scriptless mobile test automation platform, and continues to get exciting new features added with every update:

* *Parameterize the data for your scriptless tests!* Data-driven testing with scriptless automation is now a reality. Easily provide your own dataset to be used with every revisit session.

* *Use scriptless automation on your private devices!* Intelligent Test Automation isn’t just for running on our devices—you can now enjoy the benefits of rapid test automation and continuous testing on your private devices.

* *Configure your own device bundles!* Kobiton provides default test bundles out-of-the-box - like *_Top 20 Global_*, *_Top 5% United States_* etc. Now, you can define your own test bundles like _*“Smoke Test”*_, _*“Our Regional Devices”*_ … only limited by your imagination and the number of devices!

* *Let Intelligent Test Automation improve your Appium scripts!* Appium selector export lets you see and export the Appium selector used at any test step during your intelligent test automation session. Perfect for debugging and for including in your own Appium scripts.

* *Enhancements to our automatic One-Time-Password* supports mean your scriptless tests can automate OTPs for both SMS shortcode and non shortcode verification methods.
