= v3.1 | February 24, 2020
:navtitle: v3.1 | February 24, 2020

== Intelligent Test Automation (ITA)

Thanks for using ITA! We know our very first ITA’s version was not so perfect, but believe us, we are trying to make ITA better day by day for you. In this version:

* ITA won’t be stopped when you violate any currently unsupported actions (like Home, Recent App, etc.). ITA will only be executed on ‘qualified’ test steps from your manual session, therefore if you want ITA to execute full steps on your test case, make sure you won’t violate the ITA’s limitation. We knew it was quite inconvenient, but a team is working so hard to attack the ITA’s limitation to provide the most used of ITA. Stay tuned!
* Improved the success rate for the playback on other devices
* Supported the playback with the action Enter key & Delete key on iOS devices
* Supported the playback with the action Touch & Swipe on iOS devices

https://support.kobiton.com/hc/en-us/articles/360056068111[Explore ITA now]

== Kobiton

=== New Features

* *Jira integration with Kobiton*: Now you can directly file a bug while you are using Kobiton Portal without switching to another tab. Our integration automatically adds the metadata about the device you are testing on, which might help you easily troubleshoot an issue.

https://support.kobiton.com/hc/en-us/articles/360056066951[Explore the Jira integration now]

=== Enhancement

* A few of you had trouble logging into our Portal recently. Rest assured, we've resolved the issue.
* Supported the manual & automation test for iOS 13.3.1
* Fixed some bugs on iOS devices to provide the better testing experience
