= Launch a basic Appium 2 session on Kobiton (Beta)
:navtitle: Launch a basic Appium 2 session (Beta)

Kobiton includes two ways to run mobile automation: Xium, Kobiton's high-speed reimplementation of Appium Server, and basic Appium 2.

The default mobile automation method is Xium. Follow this guide to switch to basic Appium 2 for your automation session.

Note that basic Appium 2 support is a beta release, so it currently has several limitations that will be considered for future releases.

== Prerequisites

A basic Appium 2 session can only be launched on devices hosted by Kobiton v4.9 or above.

== Connecting to Appium Inspector

To run a basic Appium 2 session, you need to connect Kobiton to your Cloud Provider. When you start an intended session in Appium, you will be prompted for two pieces of information:

* **Your Kobiton Username**: You can find this in your profile
* **Your Kobiton Access Key**: You can generate this by following the guide at xref:profile:manage-your-api-credentials.adoc[Manage your API credentials]

=== Required Capabilities

The following table lists the capabilities required to run a basic Appium 2 session on Kobiton:

[cols="1,1,1,1"]
|===
|Capability |Type |Required |Description

|`platformName`
|String
|Yes
|The platform name (e.g., "Android", "iOS")

|`appium:automationName`
|String
|Yes
|The automation engine to use ("UIAutomator2" for Android, "XCUITest" for iOS)

|`kobiton:sessionName`
|String
|Yes
|A descriptive name for your automation session

|`kobiton:sessionDescription`
|String
|Yes
|A description of what the session will test

|`kobiton:deviceGroup`
|String
|Yes
|The device group to use (e.g., "KOBITON", "ORGANIZATION")

|`appium:udid`
|String
|Yes
|The unique device identifier

|`kobiton:groupId`
|String
|Yes
|The group ID for the device

|`appium:deviceName`
|String
|Yes
|The name of the device

|`appium:platformVersion`
|String
|Yes
|The platform version of the device

|`kobiton:retainDurationInSeconds`
|String
|No
|How long to retain the session (0 for immediate release)

|`browserName`
|String
|Conditional
|Required for web testing, omit for app testing

|`kobiton:runtime`
|String
|Yes
|Must be set to "appium" for basic Appium 2 sessions
|===

For detailed information about automation settings, see xref:devices:manage-devices.adoc#_automation_settings[Manage devices - Automation settings].

=== Example Capabilities

Here's an example of working capabilities for a basic Appium 2 session:

[source,json]
----
{
  "platformName": "Android",
  "appium:automationName": "UIAutomator2",
  "kobiton:sessionName": "Automation test session",
  "kobiton:sessionDescription": "Automation session",
  "kobiton:deviceGroup": "KOBITON",
  "appium:udid": "5561f118",
  "kobiton:groupId": "2576",
  "appium:deviceName": "Pixel 8 Pro",
  "appium:platformVersion": "15",
  "kobiton:retainDurationInSeconds": "0",
  "browserName": "chrome"
}
----

== Modify the capabilities in your Appium script

The following modifications must be made to the capabilities of your existing Xium script to run a basic Appium 2 session successfully:

=== Add _kobiton:runtime_

Add the `'kobiton:runtime'` capability to your script’s desired capabilities list. The value of this capability must be `'appium'` to launch a basic Appium 2 session.

=== Specify _automationName_

The `'appium:automationName'` capability is mandatory in Appium 2. This capability must have either of the below values:

* `'XCUITest'` for iOS devices.
* `'UIAutomator2'` for Android devices.

=== Add vendor prefixes

With https://appium.io/docs/en/2.1/guides/migrating-1-to-2/[Appium 2], vendor prefixes must be added to non-standard capabilities. The list of standard capabilities is given in the https://www.w3.org/TR/webdriver/#capabilities[WebDriver Protocol specifications] and includes a few commonly used capabilities such as `browserName` and `platformName`.

For non-standard capabilities, unless there are specific instructions from Kobiton to use the `kobiton:` vendor prefix, add `appium:` prefix to all of them.

[IMPORTANT]
For `'app'`, use `'kobiton:app'` instead of `'appium:app'`.

=== Example

Below is a sample list of capabilities that can be used on a Xium session:

[source,javascript]
----
const desiredCaps = {

      bundleId: 'com.example.ToDoApp',
      deviceOrientation: 'portrait',
      sessionName: 'Automation iOS Hybrid App',
      sessionDescription: 'Automation session',
      noReset: true,
      fullReset: false,
      captureScreenshots: true,
      networkActivity: false,
      app: 'kobiton-store:v657531',
      deviceGroup: 'ORGANIZATION',
      deviceName: '*',
      udid: 'aa2ace81ea5b7e6164965b97c5bf432432',
      platformName: 'iOS',

 }
----

After modification to run Appium 2, it should look like the below:

[source,javascript]
----
const desiredCaps = {

      'kobiton:runtime': 'appium',
      'appium:automationName': 'XCUITest',
      'appium:bundleId': 'com.example.ToDoApp',
      'appium:deviceOrientation': 'portrait',
      'kobiton:sessionName': 'Automation iOS Hybrid App',
      'kobiton:sessionDescription': 'Automation session',
      'appium:noReset': true,
      'appium:fullReset': false,
      'appium:captureScreenshots': true,
      'appium:networkActivity': false,
      'kobiton:app': 'kobiton-store:v657531',
      'kobiton:deviceGroup': 'ORGANIZATION',
      'appium:deviceName': '*',
      'appium:udid': 'aa2ace81ea5b7e6164965b97c5bf432432',
      'platformName': 'iOS'
 }
----

Once these changes are made, your script is ready to run basic Appium 2 sessions on Kobiton.

== Notes/Limitations

* Limited session exhaust is available, which means there are no device logs, device metrics, Appium inspector data, and network payload capture data at this time.

[NOTE]
====

Although there is a device logs file downloadable from the Overview page of a basic Appium session, the file only contains logs before the basic Appium script started.

====

include::automation-testing:partial$mixed-sessions-basic-appium-limitations.adoc[]

* AI features - including Scriptless, generate Appium script, validations, and flexCorrect - are not supported for basic Appium 2 sessions as they rely heavily on exhaust.

* Basic Appium 2 script does not support iOS 15 and later devices with passcode enabled.

== Additional notes

=== Check the current Appium Server version

A Kobiton admin who has access to the Mac mini host can use the following Terminal command to check the Appium Server version:

[source,bash]
----
/usr/local/deviceconnect/appium-server/index.js --version
----
