= List of cleanup configurations

Learn about the available cleanup configurations that are included in a cleanup policy.

== Android

=== Set chrome as debug application

This configuration is always active in user-created policies.

=== Remove device passcode

This configuration is always active in user-created policies when the organization is using passcode mode 1 or 2.

=== Unlock the screen

This configuration is always active in user-created polices when the organization is using passcode mode 1 or 2.

=== Remove http proxy on the devices

This configuration is always active in user-created polices when a NPC session ends.

=== Reset to the lowest screen brightness.

This configuration is always active in user-created polices.

Not working for some Chinese models.

=== Clear image injection.

This configuration is always active in user-created polices.

=== Set orientation device to portrait.

This configuration is always active in user-created polices.

=== Change the system language to English.

This configuration is always active in user-created polices.

=== Remove all non-system applications (except exempted apps)

Cleanup policy option: `All apps installed within a session will be removed`.

There is an option to exempt apps with certain bundle ID from being removed.

=== Clear data (cache) applications on devices (except system applications and appllications exempted from removal).

Cleanup policy option: `App’s data will be cleared`

This step is only executed when `All apps installed within a session will be removed` is turned off.

=== Turn on Wi-Fi.

Cleanup policy option: `Device settings will be reset`.

=== Turn off pocket mode on device.

Cleanup policy option: `Device settings will be reset`.

Only applies to some models that have this option.

=== Enable stay awake while plugging in device.

Cleanup policy option: `Device settings will be reset`.

Device will not go to sleep while being plugged in.

=== (?) Enable access to hidden APIs for testing or development purposes on Android.

=== Reset Time Zone.

Cleanup policy option: `Device settings will be reset`.

Reset the Time Zone to device’s current location.

=== Reset Geolocation.

Cleanup policy option: `Device settings will be reset`.

Reset Geolocation back to the current location of the device.

=== Reset all apps state to the default screen.

Cleanup policy option: `All apps in the Recent Apps list will return to their starting state`.

The opened apps are still going to be shown in the Recent Apps menu, only their states are reset.

The screenshot in the Recent Apps screen may not be reset. Launch the app to confirm that its state is reset.

The state reset depends on the behavior of the app itself.

Clear browsing history and data on supported browsers: Chrome and Chrome Beta.

Cleanup policy option: `Browser apps will be removed history and browsing data` - `Chrome`, `Chrome Beta`.

=== Remove all accounts from system

Cleanup policy option: `Signed in accounts will be removed`.

Remove user's online accounts which grant applications access to online resources with "one-click" approval first, then remove accounts by opening “Accounts” in setting and remove account one by one.

=== Set “Navigation bar” to buttons.

Cleanup policy option: `Turn on the navigation bar`.

Check if the device is using hardware or software navigation buttons. If software buttons are used:

* For Samsung devices, open Settings then navigate to Display → Navigation Bar, then set the navigation mode to Navigation buttons.

* For Google Pixel devices, open Settings then navigate to System → Gestures → System Navigation, then choose 3-button navigation.

NOTE: This does not work for some brands (Oppo, Xiaomi, etc.)

=== Set Chrome as default browser.

Cleanup policy option: `Set Chrome as the default browser`.

With Api >= 24, Open “Default app” by starting Intent. Then choose “Browser” and set “Chrome” as default browser. With Api < 24, Clear current default browser on device by go to detail page of current default browser and clear “Default browser”. Next open a website by starting web Intent. A dialog will show up tell to choose which browser to open. Choose Chrome and click “Always“ to set Chrome as default browser.

=== Turn off auto-update on Google Play Store.

This configuration is always active in user-created policies.

Perform the below steps in order:

* Open Google Play Store

* If there is no signed in account, select the 3-dot icon and choose Settings. If there is a signed-in account, open the drawer and select Settings.

* In Play Store Settings, select Network preferences → Auto-update apps, then choose Don’t auto-update apps and Done.

=== Clear the keyboard cache

Cleanup policy option: `Clear the keyboard cache`.

First will change to default (system) keyboard on the device. Then all keyboards cache on device (Only keyboards Kobiton supported e.g: GBoard, …). After changing to default keyboard, it'll clear keyboard’s clipboard (Expected result: Copy text from previous session does not paste after cleanup)

=== Set up Chrome browser of the device.

This configuration is always active in user-created policies.

First it opens chrome browser on the device then it’ll skip all the welcome screen of chrome (Because when clearing chrome, the first time we open chrome usually have some welcome screens and it will block the automation so we have to close it). After skipping all welcome screen, we will go to chrome’s setting then turn off auto save password by finding “password” cell and switch the “Save passwords” to off. Then we turn off auto translate language by going to “Languages“ cell and switch “Offer to translate pages in other languages.“ to off.

=== (?) Disable the toolbar on the Samsung keyboard, hiding shortcut icons for a cleaner interface

== iOS/iPadOS

(AC) Remove passcode

Condition: the organization is using passcode mode.

(AC) Reset http proxy

Condition: after an NPC session ends.

(A) Set orientation to portrait.

(A) Set screen brightness to lowest.

(A) Reset device language to English.

(S) Remove all non-system applications (except applications from mobile lab, applications’s bundleId contain apple prefix ("com.apple") and applications client chose to ignore remove). With 4.20, there is an option to exempt apps with certain bundle ID from being removed.

Cleanup policy option: All apps installed and associated data within a session will be removed

(S) Reset display zoom to Standard.

Cleanup policy option: Device settings will be reset.

Only triggers on devices that has Display Zoom available.

(S) Clean Safari history and data.

Cleanup policy option: Browser apps will be removed history and browsing data - Safari.

Open Settings → Apps → Safari (or Settings → Safari) → Clear History and Website Data, then select All History, turn on Close All Tabs, and select Clear History.

(S) Removed signed in mail accounts except iCloud.

Cleanup policy option: Signed in accounts will be removed.

Open Settings → Apps → Mail (or Settings → Mail) → Accounts, then remove all signed in accounts for Google, Outlook, Microsoft Exchange, Yahoo, Aol, Outlook.

Note: thi step will not removed signed in Apple IDs or iCloud accounts.

Known issue: for some iOS versions, Yahoo accounts are not removed.

(S) Turn on Wi-Fi

Cleanup policy option: Device settings will be reset.

(S) Turn on Bluetooth

Cleanup policy option: Device settings will be reset.

(S) Turn off airplane mode.

Cleanup policy option: Device settings will be reset.

(S) Turn on Web Inspector for Safari.

Cleanup policy option: Device settings will be reset.

Open Settings → Apps → Safari (Or Settings → Safari) → Advanced, then turn on Web Inspector.

Note: This cleanup policy does not turn on Remote Automation.

(S) Turn on UI Automation.

Cleanup policy option: Device settings will be reset.

Open Settings → Developer, then turn on Enable UI Automation.

(S) Turn off Low Power Mode and Auto-lock.

Cleanup policy option: Device settings will be reset.

Open Settings → Battery, then turn off Low Power Mode. Only triggers for iOS versions with this option.

Open Settings → Display & Brightness, then set the value of Auto-lock to Never. Note: this option is locked to 2 minutes if Low Power Mode is on.

(S) Turn on Location Services.

Cleanup policy option: Device settings will be reset.

(S) Turn off Assistive Touch.

Cleanup policy option: Device settings will be reset.

Open Settings → Accessibility → Touch → Assistive Touch, then turn off Assistive Touch.

(S) Turn off Ringer and Alert sound.

Cleanup policy option: Device settings will be reset.

Open Settings → Sound & Haptics (or Sound in iPad), then set Ringtone & Alerts volume to 0.

(S) Reset Time Zone.

Cleanup policy option: Device settings will be reset.

Open Settings → General → Date & Time, then turn off Set Automatically and set the time zone manually to the current location of the device.

Note: some time zone cannot be reset.

(S) Reset Geolocation.

Cleanup policy option: Device settings will be reset.

Reset Geolocation back to the current location of the device.

(S) Reset all apps state to the default screen.

Cleanup policy option: All apps in the Recent Apps list will return to their starting state

The opened apps are still going to be shown in the Recent Apps menu, only their states are reset.

The screenshot in the Recent Apps screen may not be reset. Launch the app to confirm that its state is reset.

The state reset depends on the behavior of the app itself. Example: in Safari, resetting the state does not close active browser tab, unless the cleanup steps for Safari are enabled.