= v3.8.2 | December 28, 2020
:navtitle: v3.8.2 | December 28, 2020

== Device Lab Management and Portal updates

=== New IDE plugin for IntelliJ and Android Studio

New IDE plugins are now available for both Android Studio and IntelliJ. These plugins are improvements upon the last plugins and will improve ADB debugging. With this update:

* Run your tests within your IDE’s without having to launch a separate manual session from the Kobiton portal.
* The IntelliJ plugin is in both the JetBrains marketplace and the Visual Studio Code Marketplace and is more accessible.
* There is no need to restart the IDE after establishing a session.

To learn more, you can read the https://support.kobiton.com/integration/adb-tunnel-plugin/1-intro[ADB tunnel plugin] documentation.

=== Manual canvas iFrame is now generally available

The manual canvas iFrame is now out of beta and generally available. With this iFrame, you can make Kobiton manual testing portable by embedding the Manual Canvas into anywhere that supports iFrame.

== Kobiton scriptless automation updates

=== Scriptless automation for Webview and hybrid applications on iOS

We have enhanced our AI’s ability to create and execute scriptless test automation for Webview and hybrid applications on iOS.

=== Teach your AI to scroll

On the blocker remediation page, you can now scroll in order to find the correct element when training our AI to best execute your scriptless tests.

== Enhancements

* An issue has been resolved that occasionally caused an inability to input text via physical keyboard when building tests for iOS devices.
* An issue has been resolved that occasionally caused the “Assigned Devices” tab to display improperly.
* An issue has been resolved that caused an inability to delete/sign out of a Jira integration.
* We have resolved an issue that caused the passcode-enabled devices to lock upon restarting the Kobiton Desktop app.
* We have resolved an issue that caused clean up policies to turn off the internet on devices running iOS 12 and older.
