= v3.0 | January 06, 2020
:navtitle: v3.0 | January 06, 2020

== New Product: Intelligent Test Automation (ITA)

We are excited to introduce the new product Intelligent Test Automation (ITA) to heal-up any pain points regarding the automation testing with artificial intelligence (AI). ITA lets you simply perform a manual test execution on one device and being automatically revisited on multiple other devices without any scripting skills required.

https://support.kobiton.com/hc/en-us/articles/360056068271[Explore ITA now]

== Kobiton

=== New Features

* *iOS Device Logs Enhancement*: Ease the process of debugging your application while using real-time logs from Logcat or Console, you could use the advanced filter log from app or system processes to investigate and fix bugs instantly.

* *Subscription Improvement*: We heard you! As requested by users, we have improved the UX in the Profile’s subscription, including the current billing and the next billing so that you can have an overview about your purchased plan regarding any update & modification.

=== Enhancements

* Support the manual & automation test up to iOS 13.3
* Support the automation test for Android on Chrome version 79
* We worked hard to fix the unsync device status on our Portal to ensure your testing
* Update Kobiton’s infrastructure like Xcode 11.3, Java 8, etc.
* Improve the quality of the system for a better testing experience (Unable to launch WebdriverAgent, iOS devices being restarted unexpectedly, etc.)
* If you have had a problem that your test execution could not be triggered due to the `[INSTALL_FAILED_INSUFFICIENT_STORAGE]` error, you should no longer encounter this problem
