= v3.7 | November 02, 2020
:navtitle: v3.7 | November 02, 2020

== New Device Lab Management features

* Efficiently share devices with soft booking: The new Soft booking API allows you to use an API to book devices so that your team can better share and manage device usage.
* Added visibility around device usage and time under test: To make device sharing and management easier, you will have extra visibility around who is using devices and how long they have been using certain devices.
* Added support around backwards compatibility with iOS 14: For local device users, devices running iOS 14 can be installed on the same desktop application as devices running previous iOS versions.
* Added support for the Google Flutter Driver: We now support the Google Flutter driver for supported Android and iOS devices on both Cloud and Private devices. For iOS, we support devices running iOS12+, excluding the iPad Air. For Android, we will support devices running Android 6+.
* We now support XCUITest! iOS teams rejoice! Kobiton now offers support for XCUITest alongside our already-existing support for both Appium and Espresso.
* Brand new ADB shell: Our new ADB shell allows you to easily interact with your real Android device using ADB commands directly within your Kobiton manual test session--no complex set-up required.

== New Intelligent Test Automation features

* Intelligent Test Automation now supports hybrid and mobile-web applications: You can now use ITA to create scriptless test automation across hybrid and mobile-web applications.
* New visual assertions for ITA: ITA can now catch visual differences between structural and layout changes on your real devices.
* ITA’s Data Driven Testing now supports date pickers and new assertions: We have made our DDT capabilities even better, with added support for date pickers as well as adding the ability for you to raise assertions for dynamic data.
* Added test actions for ITA’s Open-Appium Export: ITA’s Open-Appium Export script can now include the following test actions: Virtual Keyboard, Device Softkey, Rotate, Retry method, Check device availability.
