= Configure local server for debugging local devices
:navtitle: Configure local server

Learn how to configure your local Kobiton server so users in your organization can debug local devices hosted on your server.

[#_get_server_information_for_your_team]
== Get server information for your team

In order for users to xref:debugging:debug-local-devices/configure-personal-computer.adoc[set up their personal computer to debug local devices], they'll need the server's IP address and REST API port numbers. Here's a template:

[source,plaintext]
----
# Server information required for this set up: https://docs.kobiton.com/kobiton-docs/debugging/debug-local-devices/configure-personal-computer.html

<network-address> : VALUE
<api-port-baseurl> : VALUE
<api-port-grpc-baseurl> : VALUE
----

Save this information in a secure location your team can easily access.

=== Get network address

Users can use your private domain name _or_ the Kobiton server's IP address. If you prefer to use the Kobiton server's IP address, run the following command in the terminal and save the output to a secure location for your team:

[source,shell]
----
hostname -I
----

=== Get REST API port numbers

To get the Kobiton server's REST API port numbers, open `~/config/app.yaml` and check for the following port keys:

[source,plaintext]
----
rest_api_ingress_advertised_port: <port-number>
grpc_ingress_gateway_public_advertised_port: <port-number>
----

If the keys are present, save their values to a secure location. If they're not, save this information instead:

* Set the port number for `Kobiton.ApiBaseUrl` to `3000`.
* Set the port number for `Kobiton.ApiGrpcBaseUrl` to `3001`.

== Modify `dc.ini`

[NOTE]
The `dc.ini` file needs to be modified for *each Mac mini server*.

In the terminal, open the `deviceconnect` directory:

[source,shell]
----
cd ~/usr/local/deviceconnect
----

Open `dc.ini` and add the following environment variables:

[source,plaintext]
----
GatewayPublicAddress=<ip-address> # Set to your private or public IP address.
ExternalAirstreamTlsPort=<port-number> # Set to 10161 or public IP address.
----

For example:

[source,shell]
----
GatewayPublicAddress=192.168.36.36
ExternalAirstreamTlsPort=10161
----

Save your changes, then run the following command to restart the server:

[source,shell]
----
sudo sv restart dc-services dc-webviewer dc-watchdog
----

Now users in your organization can debug local devices hosted on your local Kobiton server.
