= App repository
:navtitle: App repository

Select *Apps* to open the app repository and manage your apps.

image:$NEW-IMAGE$[width=, alt=""]

[#_upload_an_app]
== Upload an app

Select the *+ icon* and upload a xref:supported-filetypes.adoc[supported filetype] from your computer.

image:$NEW-IMAGE$[width=, alt=""]

[NOTE]
You can also upload apps xref:upload-apps-using-rest-api.adoc[using our REST API].

[#_rename_an_app]
== Rename an app

Select *Rename Application* and enter a new name for your app.

image:$NEW-IMAGE$[width=, alt=""]

[#_remove_an_app]
== Remove an app

Choose an app and select *Remove App* to remove the entire app from your repository.

image:$NEW-IMAGE$[width=, alt=""]

To remove a specific version, select the app first and select a version to remove instead.

image:$NEW-IMAGE$[width=, alt=""]

== Download an app version

Select *Download* to download the the current app version to your computer.

image:$NEW-IMAGE$[width=, alt=""]

To download a specific version, select the app first and select a version to download instead.

image:$NEW-IMAGE$[width=, alt=""]

== Limit access

Limit who can access your app by selecting the *globe icon* and choosing either *Allow access to my team(s)* or *Allow only me to access*.

image:$NEW-IMAGE$[width=, alt=""]

[NOTE]
You can find which team(s) you're a part of on your xref:organization:manage-teams.adoc[organization's team page].
