= App metadata
:navtitle: App metadata

You can use the app library to display an app's metadata, like latest version, supported CPUs, last updated date, and more.

[#_metadata]
== Metadata

Display metadata by selecting the version dropdown beneath an app.

=== Name

The name of your app within Kobiton. This doesn't need to match the public name, so xref:manage-an-app.adoc#_rename_an_app[choose any name] that works for you and your team.

=== Version

There can be xref:manage-an-app.adoc#_upload_an_app_version[multiple versions] for each app. For example, `1.0.2` and `1.1.0`. Use this field to identify the app version.

=== Latest

There can be xref:manage-an-app.adoc#_upload_an_app_version[multiple versions] for each app. For example, `1.0.2` and `1.1.0`. Use this field to identify whether the version you're looking at is the latest version.

=== App ID

The unique identifier assigned to each app. For example, `com.kobiton.appname`.

=== Bundle version

Your app's bundle version. For example, `1.2.5`.

=== Bundle ID

The unique identifier Apple and Google use to identify your app. For example, `com.kobiton.appname`.

=== Minimum OS version

The earliest operating system (OS) version compatible with your app. For example, `iOS 11.0` or `Android 15`.

=== Supported CPU architectures

The different mobile CPUs compatible with your app. For example, `arm 64` or `x86`.

=== Updated

The date your app was last updated.For example, `May 15, 2023 10:55:35`.

[#_uploaded_by]
=== Uploaded by

The user who uploaded this version of the app.For example, `alex-lee`.
