= Manage your library
:navtitle: Manage your library

Learn how to manage your app library so you and your team can easily access the apps you use most. After an app is uploaded, you can rename it, upload new versions, limit access, and xref:manage-an-app.adoc[more].

== Options

[#_supported_filetypes]
=== Supported filetypes

include::ROOT:partial$supported-filetypes-for-app-uploads.adoc[]

[#_upload_an_app]
=== Upload an app

You can upload a new app by opening your app library, selecting the *+ icon*, choosing a xref:_supported_filetypes[supported file] to upload.

image:$NEEDSIMAGE$[width=, alt=""]

[NOTE]
You can also upload an app xref:upload-using-rest-api.adoc[using the Kobiton REST API].

When you're finished, you can start xref:manage-an-app.adoc[managing your app].

[#_remove_an_app]
=== Remove an app

First you'll search for your app using any related xref:app-metadata.adoc#_metadata[metadata].

image:$NEEDSIMAGE$[width=, alt=""]

When you're ready, select *Remove App* to remove the app (rather than xref:manage-an-app.adoc#_remove_an_app_version[remove a specific version]).

image:$NEEDSIMAGE$[width=, alt=""]

=== Download an app

include::apps:partial$download-an-app.adoc[]
