= Manage an app
:navtitle: Manage an app

Learn how to manage an app after you xref:manage-your-library.adoc#_upload_an_app[add it to your library]. You can rename apps, upload new versions, limit app access, and more.

== Options

[#_supported_filetypes]
=== Supported filetypes

include::ROOT:partial$supported-filetypes-for-app-uploads.adoc[]

[#_rename_an_app]
=== Rename an app

You can rename an app to change how it appears in search results. First, search for your app using its xref:app-metadata.adoc#_metadata[metadata].

When you're ready, select *Rename Application* and enter a new name to rename your app.

[#_upload_an_app_version]
=== Upload an app version

You can upload a new app by opening your app library and selecting the *+ icon*.Choose your xref:_supported_filetypes[app file] from your computer and select *Upload*.

We'll let you know when its finished uploading, so you can start xref:manage-an-app.adoc[managing your app].

[#_remove_an_app_version]
=== Remove an app version

First, search for your app using its xref:app-metadata.adoc#_metadata[metadata].

Confirm you want to remove this version rather than the xref:manage-your-library.adoc#_remove_an_app[full app].When you're ready, select *Remove App*.

=== Download an app

include::apps:partial$download-an-app.adoc[]

=== Limit access

You can limit who can access your app. First, search for your app using its xref:app-metadata.adoc#_metadata[metadata].

When you're ready, select the *globe icon* then choose *Allow access to my team(s)* or *Allow only me to access*.

[NOTE]
You can find which team(s) you're a part of on your xref:organization-and-profile:your-teams/manage-your-teams.adoc[organization's team page].
