= Manage your library
:navtitle: Manage your library

Learn how to manage your app library so you and your team can easily access the apps you use most. After an app is uploaded, you can rename it, upload new versions, limit access, and xref:manage-an-app.adoc[more].

== Options

[#_supported_filetypes]
=== Supported filetypes

include::ROOT:partial$supported-filetypes-for-app-uploads.adoc[]

[#_upload_an_app]
=== Upload an app

You can upload a new app by opening your app library and selecting the *+ icon*.Choose your xref:_supported_filetypes[app file] from your computer and select *Upload*.

We'll let you know when its finished uploading, so you can start xref:manage-an-app.adoc[managing your app].

[#_remove_an_app]
=== Remove an app

First, search for your app using its xref:app-metadata.adoc#_metadata[metadata].

Confirm you want to remove the full app rather than a xref:manage-an-app.adoc#_remove_an_app_version[specific version]. When you're ready, select *Remove App*.

=== Download an app

include::apps:partial$download-an-app.adoc[]
