= About biometrics authentication
:navtitle: About biometrics authentication

== What is biometric authentication?

Today, most mobile devices support biometric authentication which allows mobile owners to sign in to their mobile device using unique physical characteristics like their face or fingerprint.

== How others test biometric authentication

Yearly improvements to mobile app security make testing biometric authentication difficult. Many mobile testing companies try to get around this by decompiling your app during testing, which puts your app at risk. If you develop a banking, travel, work, gaming, or any kind of app that contains sensitive data, we know how important security is for you, so we do biometric authentication testing differently.

== How Kobiton does it differently

We created a biometric authentication SDK you can add to a test version of your mobile app:

* Biometric authentication SDK for iOS
* Biometric authentication SDK for Android

After you upload the altered app to xref:apps:index.adoc[your repository], you can testing biometric authentication in Kobiton without ever decompiling your app. This gives you control over your app and keeps your data safe.
