= Upload an app using the Kobiton API
:navtitle: Using the Kobiton API

Learn how to upload an app to the xref:manage-apps.adoc[app repository] using our link:https://api.kobiton.com/v2/docs/[REST API].

== Before you start

* Make sure your app package belongs to a xref:apps:supported-filetypes.adoc[supported filetype].
* xref:profile:manage-your-api-credentials.adoc[Get your API credentials].

[#_configure_your_authorization_header]
== Configure your authorization header

include::automation-testing:partial$configure-your-authorization-header.adoc[]

[#_generate_an_upload_url]
== Generate an upload URL

In a terminal of your choice, make a `POST` request to `/v2/apps/uploadUrl`, which will generate a unique upload URL that connects to our private S3 bucket on Amazon Web Services (AWS). The sample cURL command of the request is:

[source,shell]
----
curl -X POST https://api.kobiton.com/v2/apps/upload-url \
  -H 'Authorization: Basic ${yourBase64String}' \
  -H 'Content-Type: application/json' \
  -d '{ "file_name": "${app_file_name}" , "app_id": ${app_id} }'
----

The request contains 2 parameters:

* `+${app_id}+`: (optional) if another version of this app is already uploaded, provide the `app_id` of the existing app.Example: `100`.
* `+${app_file_name}+`: (required) provide the name of the app file to upload.Example: `MyApp.ipa`.

A successful response will return the following:

.Example
[source,shell]
----
{
    "app_path": "users/1/apps/MyApp‐237824a0‐302c‐9bfd‐ff417c89610a.ipa",
    "url": "https://kobiton-xx.s3.amazonaws.com/users/1/apps/MyApp‐12b27d40-1ff5-11ee-9992-8d505d811030.ipa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20230711%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230711T141313Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=84b350ede5c07b825cc4efa1ee82f09a81660da84f3283c1ee3abee7b93e2a13"
}
----

Save the above values for the next sections.

== Upload app file to S3 storage

Make a `PUT` request to the `url` you generated in the previous step.

[source,shell]
----
curl -X PUT "${url}" \
  -H "Content-Type: application/octet-stream" \
  -H "x-amz-tagging: unsaved=true" \
  -T ${file_path} \
----

This request must contains:

* `+${url}+`: the `url` obtained from the xref:_generate_an_upload_url[previous section]. Use the exact full URL.
* `+${file_path}+`: the path to the app package file you want to upload. Make sure it is of a xref:apps:supported-filetypes.adoc[supported filetype].

If the response is blank, then the file is uploaded successfully.

[#_create_app_or_app_version]
== Create the app or app version in the app repository

Make a `POST` request to create the entry for the app or app version in the app repository in Kobiton.

[source,shell]
----
curl -X POST https://api.kobiton.com/v2/apps \
    -H 'Authorization: Basic ${yourBase64String}' \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -d '{ "file_name": "${app_file_name}" , "app_path": "${app_path}" }'
----

This request contains 2 parameters:

* `+${app_path}+`: (required) use the value of `app_path` in the response of xref:_generate_an_upload_url[this step].
* `+${app_file_name}+`: (optional) specify the name of the app. If not declared, the name of the file from `+${app_path}+` is used.

If your request was successful, `POST` will return a `200` status with the following response:

[source,shell]
----
{
  "app_id": 100,
  "version_id": 101
}
----

In the response above, `app_id` is the ID of the new app, and `version_id` is the ID of the new application version. Both of them are used in other endpoints such as installing the app on a device, or get information about a specific app or app version. If the app file is too large, it may take a while to process the file and the value of `app_id` will be `N/A`. See the next section on how to obtain the `app_id`.

== Obtain the app ID

Make a `GET` request to obtain the parsing status and the `app_id` of your newly uploaded app.

[source,shell]
----

curl -X GET -H https://api.kobiton.com/v2/apps/parsing-status?appVersionId=${version_id} \
    -H 'Authorization: Basic ${yourBase64String}'

----

This request contains 1 parameter:

* `+${version_id}+`: (required) use the value of `version_id` in the response of xref:_create_app_or_app_version[this step].

If your request was successful, `GET` will return a `200` status with the following response:

[source,shell]
----

{
"app_id": 61999,
"app_state": "OK"
}

----

You can now use the `app_id` other in endpoints such as installing the app on a device, or get information about a specific app.