= Installing mid-session
:navtitle: Installing mid-session

You can install an app during your manual testing session by xref:_searching_app_repository[searching the app repository], xref:_uploading_a_file[uploading a file], or xref:_installing_from_url[installing from a URL].

.Prerequisites
* This
* This

[#_searching_app_repository]
== Searching app repository

1. This
- Search and install your apps which have been uploaded to the App Repository.

Note: When the app starts uploading and installing, the progress bar shows the progress status accordingly. After the installation has finished, you will receive a notification and the app will automatically launch. Kobiton automatically uninstalls all of your apps when the test session ends.

[#_uploading_a_file]
== Uploading a file

1. This
- Click on Upload File to browse the location of the file and supply it.

Note: When the app starts uploading and installing, the progress bar shows the progress status accordingly. After the installation has finished, you will receive a notification and the app will automatically launch. Kobiton automatically uninstalls all of your apps when the test session ends.

[#_installing_from_url]
== Installing from URL

1. This
- Click on Install from URL to install the app from a third-party URL.

Note: When the app starts uploading and installing, the progress bar shows the progress status accordingly. After the installation has finished, you will receive a notification and the app will automatically launch. Kobiton automatically uninstalls all of your apps when the test session ends.
