= About timeouts
:navtitle: About timeouts

Learn about default session timeouts, explicit timeouts, and HTTP timeouts for client libraries.

== Default session timeouts

After you link:https://api.kobiton.com/v2/docs#tag/NativeFrameworkAPI/operation/NativeFrameworkAPI_InitiateNativeSession[initiate a session], you'll have 10 minutes for xref:list-of-desired-capabilities.adoc#_web_testing[web apps] and 30 minutes for xref:list-of-desired-capabilities.adoc#_app_testing[native/hybrid apps] to send your first HTTP request. You'll then have 10 minutes for each following request, regardless of app type.

For example:

[source,java]
----
// Desired capabilities for a native/hybrid app
capabilities.setCapability("app", "kobiton-store:000111");
// Other capabilities...

// Initiate the session...

// Requests
driver.findElement(By.id("com.mycompany.app:id/open_button")).click(); // Since this is a native/hybrid app, this first request must be sent within 30 minutes.
driver.findElement(By.id("com.mycompany.app:id/login_button")).click(); // This request must be sent within 10 minutes of the previous request.
driver.findElement(By.id("com.mycompany.app:id/enter_button")).click(); // This request must be sent within 10 minutes of the previous request.
----

== Implicit and explicit waits

You can use implicit and explicit waits to override the default session timeout. Wait values less than 10 seconds or greater than 30 minutes, will be replaced with the closest value within that range instead.

For example:

[source,java]
----
// Desired capabilities for a web app
capabilities.setCapability("useConfiguration", "kobiton");
capabilities.setCapability("autoWebview", true);
capabilities.setCapability("browserName", "safari");
// Other capabilities...

// Initiate the session...

// Set explicit wait
WebDriverWait wait = new WebDriverWait(driver, 20 * 60); // Typicall web apps require the first HTTP request to be sent within 10 minutes, but WebDriverWait is explicitly set to 30 minuntes instead.

// Requests
driver.findElement(By.id("com.mycompany.app:id/open_button")).click(); // This request must be sent within 20 minutes of the previous request.
driver.manage().timeouts().implicitlyWait(45, TimeUnit.MINUTES); // Sets the implicit wait of the next request to 45 minutes, however Kobiton will use 30 minutes instead (the maximum allowed value).
driver.findElement(By.id("com.mycompany.app:id/open_button")).click(); // This request must be sent within 30 minutes of the previous request.
----

== Override default HTTP timeouts

xref:supported-client-libraries.adoc[Client libraries] typically rely on third-party HTTP libraries to send requests, and many of these libraries time out after 2 minutes of inactivity. If you plan on installing an app during your test session, consider modifying your client library's HTTP timeout, so your app can install before your session times out.

For example:

[source,java]
----
// Desired capabilities
String kobitonServerUrl = "https://<user-name>:<api-key>@api.kobiton.com/wd/hub";
// Other capabilites...

// Custom executor that sets Selenium's HTTP library, Apache HttpClient, to 15 a minute timeout.
HttpCommandExecutor executor = new HttpCommandExecutor(new URL(kobitonServerUrl));
executor.getClient().setReadTimeout(15, TimeUnit.MINUTES);
executor.getClient().setConnectTimeout(15, TimeUnit.MINUTES);

// Initiate the session using the custom executor.
WebDriver driver = new RemoteWebDriver(executor, capabilities);
----
