= Run visual validations
:navtitle: Run visual validations

Learn how to run visual validations

Visual Validations allows users to turn existing Appium scripts into functional and visual tests by

== Before you start

xref:export-appium-scripts.adoc[Export your Appium script], so you use it for running visual validations, rather than creating validation scripts from scratch.

== Change desired capabilities

First you'll open the config file in your `test` directory. The exact file name and location varies depending on xref:export-appium-scripts.adoc#_export_your_script[your testing framework]. Here's an example:

[source,]
----
manual
└── src
    └── test
        └── <configuration-file>
----

Next, change the following desired capabilities:

* Set `"kobiton:visualValidation"` to `true`.
* Set `"kobiton:visualValidation"` to `true`.
* Optionally, set `"kobiton:referenceSessionId"` to a xref:fetch-kobitonsessionid.adoc[different session ID].

Here's an example:

[source,java]
----
public static DesiredCapabilities getIPhone11ProIOS146DesiredCapabilities() {
        DesiredCapabilities capabilities = new DesiredCapabilities();

        // Change these capabilities:

        capabilities.setCapability("kobiton:visualValidation", true); // Set to true.
        capabilities.setCapability("kobiton:visualValidation", true);  // Set to true.
        capabilities.setCapability("kobiton:referenceSessionId", 0000011); // (Optional) Enter a different session ID.

    return capabilities;
}
----

When you're finished, save your changes.

Now you can run visual validations on a single test device. To run your script in parallel, you'll also need to xref:_modify_setup_function[modify your `setup()` function].

[#_modify_setup_function]
== Modify `setup()`

You can run visual validations in parallel by modifying the `setup()` function in your `test` directory. The exact location of the function depends on your xref:export-appium-scripts.adoc#_export_your_script[selected framework].

Here's where you may find the function:

[source,]
----
manual
└── src
    └── test
        └── TestApp.java // Java testing framework
        └── TestApp.java // Java testing framework
----

To run Visual Validations on parallel executions:

. On `config.java`, add and configure the desired configuration for the additional devices.
. Navigate to `manual > src > test > java > com.kobiton.scriptlessautomation > TestSuite`
. Change `testApp.setup(capabilities, {# of executions});` to reflect the number of parallel executions the test will run.

Example: to run two parallel executions:

[source,javascript]
----
@Test
public void [Your test function name]() throws Exception {
   DesiredCapabilities capabilities = Config.[Your defined desired capabilities];
   findOnlineDevice(capabilities);
   setup(capabilities, 2);
   runTest();
}
----
Run the project to test on the defined devices.
