= Supported client libraries
:navtitle: Supported client libraries

You can make calls to the link:https://api.kobiton.com/docs/#kobiton-api-v2[Kobiton API] using the following client libraries.

== C#

=== Appium

Version 4.3.1 and earlier of C#'s link:https://www.nuget.org/packages/Appium.WebDriver/[`Appium.WebDriver`] package is supported.

=== Selenium

Version 3.141.0 and earlier of C#'s link:https://www.nuget.org/packages/Selenium.WebDriver/[`Selenium.WebDriver`] package is supported.

== Java

=== Appium

Version 7.5.1 and earlier of Java's link:https://github.com/appium/java-client/[`java-client`] dependency is supported.

=== Selenium

Version 3.141.0 and earlier of Java's link:https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/[`selenium-java`] dependency is supported.

== NodeJS

=== Appium

Version 1.0.0 and later of link:https://www.npmjs.com/package/wd/[`wd`] is supported.

=== Selenium

Version 3.6.0 and earlier of link:https://www.npmjs.com/package/selenium-webdriver/[`selenium-webdriver`] is supported.

== PHP

=== Appium

Version 0.2.0 and later of PHP's link:https://github.com/appium/php-client/[`appium-php`] library is supported.

=== Selenium

Version 1.1.0 and later of PHP's link:https://github.com/php-webdriver/php-webdriver[`php-webdriver`] library is supported.

== Python

=== Selenium

Version 3.141.0 and earlier of Python's link:https://pypi.python.org/pypi/selenium/[`selenium`] package is supported.

== Ruby

=== Appium

Version 11.2.0 and earlier of Ruby's link:https://rubygems.org/gems/appium_lib/[`appium_lib`] library is supported.

=== Selenium

Version 3.14 and later of Ruby's link:https://rubygems.org/gems/selenium-webdriver/[`selenium-webdriver`] package is supported.
