= Test biometric authentication
:navtitle: Test biometric authentication

Learn how to test your app's biometric authentication using an automation script.

== Before you start

You’ll need to add our biometric authentication library to your iOS and Android apps:

* xref:integrations:biometric-authentication/add-our-library-to-your-android-app.adoc[Add our library to your Android app]
* xref:integrations:biometric-authentication/add-our-library-to-your-ios-app.adoc[Add our library to your iOS app]

[NOTE]
Learn about xref:integrations:biometric-authentication/about-our-library.adoc[the benefits] of our biometrics authentication library.

== Script parameters

After you send a biometric authentication request, end-users can choose to authenticate themselves (`pass`) or reject your request (`fail`). Use these scripts to test how your app responds to each choice:

[cols="3,2"]
|===
| `driver.execute('mobile:biometrics-authenticate', {result: 'passed'})`
| Simulate the end-user authenticating themselves.

| `driver.execute('mobile:biometrics-authenticate', {result: 'failed'})`
| Simulate the end-user rejecting your request.
|===

[NOTE]
Learn more about Appium’s link:https://appium.io/docs/en/2.0/guides/execute-methods/[`driver.execute()`] method.

== Example script

Here’s an example script testing a successful biometric authentication attempt:

[source,python]
----
def test_biometric_authentication():
    try:
        # Look for the XPath containing the words "Log In" and select the element.
        wait = WebDriverWait(driver, 10)
        log_in_element = wait.until(EC.presence_of_element_located((By.XPATH, '//XCUIElementTypeStaticText[@id="Log In"]')))
        log_in_element.click()

        # Wait for 20 seconds for the biometric authentication screen to load.
        driver.implicitly_wait(20)

        # Simulate the end-user authenticating themselves.
        driver.execute('mobile:biometrics-authenticate', {'result': 'passed'})

    # Catch any errors that occur.
    except Exception as e:

        # Log the error in the console.
        print(e)

        # Throw the error to stop the test.
        raise e
----
