= Session UI options
:navtitle: Session UI options

These are the customization options for your session UI. Select *Settings*, then *iFrame Configuration* to customize your session UI.

== View

Toggle between *Website* and *IDE* to...

== Visuals

* Header color
* Background color
* Brand color
* Logo URL

== Launch device screen

To customize the visual components of the device panel:

. Adjust the RGB color value for the frame's header, background color, or toolbar icons (brand color).
. Change the logo by entering your logo's URL to the Logo URL field.
. To apply changes, click Save Configuration.

Customizable functions

The functionality of the panel can be customized by adding and removing abilities.

To edit functionality, toolbar functionality, or device settings:

. Use the radio buttons to enable or disable the functionality.
. To apply changes, click Save Configuration.

Toolbar functionality

* screenshot
* device location
* timezone
* rotate screen
* power
* volume up
* volume down

Device settings

* device log
* log pause
* clean logs
* download log

Top menu

* session settings
* Install apps
