= Manage your profile
:navtitle: Manage your profile

Learn how to manage your profile by changing your name, password, default team, and more. Select your user profile to get started.

[NOTE]
Sign up for a link:https://info.kobiton.com/trial[free trial] today!

== Profile options

[#_change_your_name]
=== Change your name

This is the name displayed in your xref:session-analytics:search-options.adoc[sessions], xref:apps:app-metadata.adoc#_uploaded_by[apps], and xref:your-teams/manage-your-teams.adoc[teams]. Choose a name that's easy for others to identify.

[#_change_your_password]
=== Change your password

Passwords must be between 5 and 32 characters, contain at least one lowercase letter (a-z), one uppercase letter (A-Z), and one digit (0-9). After you create a strong password, be sure to store it somewhere secure, like a password manager.

[NOTE]
If you forget your password, choose *Forgot Password?* on the login page to reset it.

[#_change_your_default_team]
=== Choose a default team

You can choose one of your teams to be your xref:your-teams/manage-your-teams.adoc[default team]. Any xref:automation-testing:index.adoc[automation sessions] you run will be automatically added to this team.

[#_change_your_timezone]
=== Change your timezone

You can change your timezone so dates and times in Kobiton match your current location.

[#_change_your_session_timeout]
=== Change your session timeout

By default, sessions close after 10 minutes of inactivity. You can change this by choosing any length between 5 and 30 minutes.

Additionally, during xref:manual-testing:resume-a-session.adoc[unexpected interruptions], we'll keep your session active for up to 10 minutes. If you're using a public device, you'll be charged testing minutes during this time (since others may be waiting to use this device), so keep that in mind when change these settings.
