= Profile settings
:navtitle:Profile settings

Select *Profile* to change your profile settings.

image:$IMAGE$[width=, alt=""]

[#_change_your_name]
== Change your name

Enter a name that's easy for others to identify. This name will be displayed in your xref:session-analytics:search-options.adoc[sessions], xref:apps:list-of-app-metadata.adoc#_uploaded_by[apps], and xref:organization:manage-teams.adoc[teams].

image:$IMAGE$[width=, alt=""]

[#_change_your_password]
== Change your password

Enter a password between 5 and 32 characters that contains at least one lowercase letter (a-z), one uppercase letter (A-Z), and one digit (0-9).

image:$IMAGE$[width=, alt=""]

[NOTE]
If you forgot your password, select *Forgot Password?* on the login page to reset it.

[#_change_your_default_team]
== Choose a default team

Choose xref:organization:manage-teams.adoc[one of your teams] to be your default. Your xref:automation-testing:index.adoc[automation sessions] will be automatically added to this team.

image:$IMAGE$[width=, alt=""]

[#_change_your_timezone]
== Change your timezone

Choose a timezone so dates and times in Kobiton will match your current location.

[#_change_your_session_timeout]
== Change your session timeout

By default, sessions automatically close after 10 minutes of inactivity. Choose any time between 5 minutes and 30 minutes to change this.

image:$IMAGE$[width=, alt=""]

[NOTE]
If your manual session is xref:manual-testing:resume-a-session.adoc[unexpected interrupted], we'll keep your session active for the length of your session timeout. Keep in mind: you'll be charged testing minutes for public device sessions we keep active, since others may be waiting to use the device.
