= Supported OS versions
:page-aliases: supported-platforms:operating-systems.adoc

:navtitle: OS versions

The following mobile operating system (OS) versions are supported on Kobiton.

[#_operating_systems]
== Operating systems

[NOTE]
Before upgrading iOS/iPadOS devices to a new OS version, ensure that the hosting Mac mini is running a supported version of macOS and has a compatible version of Xcode installed. For details on which macOS and Xcode versions are required, see https://developer.apple.com/support/xcode/[Apple’s compatibility information,window=read-later].

[cols="1,1,1"]
|===
|Developer|Operating System|Supported version(s)

|Google
|Android
|link:https://developer.android.com/about/versions/oreo[Android 8,window=read-later] through link:https://developer.android.com/about/versions/16[Android 16,window=read-later] ^*1*^

|Apple
|iOS & iPadOS
|link:https://developer.apple.com/documentation/ios-ipados-release-notes/ios-12-release-notes[iOS 12,window=read-later] ^*2*^ through link:https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-26-release-notes[iOS & iPadOS 26,window=read-later]
|===

^*1*^ _Lower versions may still work, but are no longer tested._

^*2*^ _iOS 12 and 13 support was reintroduced in release 4.19 with some xref:release-notes:all-releases/4_19.adoc#_re_enabled_ios_12_and_13_support[known limitations,window=read-later]._