= Configure an Android device for network payload capture
:navtitle: Configure an Android device

Learn how to configure an Android device for network payload capture, so you can xref:devices:local-devices/network-payload-capture/create-a-configuration.adoc[create a configuration for network payload capture].

[NOTE]
You'll need to configure each Android device you want to use for network payload capture.

[#_before_you_start]
== Before you start

You'll need to:

* Confirm your system administrator already xref:devices:local-devices/network-payload-capture/configure-the-host-machine.adoc[configured your host machine].

== Download certificate
On your Android device, open any web browser, then download the xref:attachment$kobiton-network-payload-capture-certificate-1.3.crt[network payload capture certificate].

== Install certificate

=== Android 10 or 9

On the Android device, 

=== Android 11 or later

On the Android device, open *Settings*, *Biometrics and security*, then *Other security settings*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Install from the device storage*, then *CA certificate*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Choose *Install anyway*, then select the certificate.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

=== Other Android versions

On the Android device, open *Settings*, then *Explore*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select the certificate.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

If the device doesn't have a passcode already, you'll be asked to create one. Follow the on-screen instructions to create a passcode.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

== Remove device passcode

If your device has a passcode, open *Settings*, then *Security*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Screen lock*, enter your passcode, then select *screen lock: None*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Yes, remove to delete all passcode*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

== Create config file

include::partial$network-payload-capture/create-config-file.adoc[]
