= Configure an iOS device for network payload capture
:navtitle: Configure an iOS device

Learn how to configure an iOS device for network payload capture so you can xref:devices:local-devices/network-payload-capture/create-a-configuration.adoc[create a configuration for network payload capture].

[NOTE]
You'll need to configure each iOS device you want to use for network payload capture.

[#_before_you_start]
== Before you start

You'll need to:

* Confirm your system administrator xref:devices:local-devices/network-payload-capture/configure-the-host-machine.adoc[configured your local Kobiton server].
* Download the xref:attachment$kobiton-network-payload-capture-certificate-1.3.crt[network payload capture certificate] on your personal macOS computer.*

== Get device UDID

Connect your device to your macOS computer. Open Finder, then select the device.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Hover the mouse over the device information, then right-click and copy the device UDID to a secure location.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

== Add certificate to device

Turn on airdrop, confirm the location of the xref:_before_you_start[certificate you downloaded earlier], then share the certificate from your computer to the device.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

When you see the airdrop notification on the device, select *Accept*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

== Install certificate

On the device, open *Settings*, then *General*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Profiles*, then the certificate.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Install*, then *Done*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

== Enable full trust for certificate

On the device, open *Settings*, then *General*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *About*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Certificate Trust Settings*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Turn on *Kobiton Certification Authority*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]
