= Configure an Android device for network payload capture
:navtitle: Configure an Android device

Learn how to configure an Android device for network payload capture, so you can xref:devices:local-devices/network-payload-capture/create-a-configuration.adoc[create a configuration for network payload capture].

[NOTE]
You'll need to configure each Android device you want to use for network payload capture.

[#_before_you_start]
== Before you start

You'll need to:

* Confirm your system administrator already xref:devices:local-devices/network-payload-capture/configure-the-host-machine.adoc[configured your host machine].
* Open the network payload capture certificate xref:attachment$kobiton-network-payload-capture-certificate-1.3.crt[download link] from the Android device's browser and save it onto the device.

[NOTE]
====
You can also save the certificate to the Mac mini host machine, then use https://www.android.com/filetransfer/[Android File Transfer] to https://support.google.com/android/answer/9064445?hl=en#zippy=%2Cmac-computer[transfer files] from MacOS to Android devices. Devices need to be plugged directly into the Mac mini for Android File Transfer to recognize them. Ensure the USB settings are *not* set to _no file transfer_.
====

== Install certificate
Network traffic from the device is captured through a proxy server installed on the Mac mini host machine. For HTTPS connection, the device must be set up to trust a CA certificate issued by the proxy server.

=== Android 9 and 10

On the Android device, open a file explorer app, then navigate to the certificate file and open it.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

For organizations with device passcode enabled, input the device passcode, then enter a name for the certificate and select *OK*. The certificate is then installed.


For organizations without device passcode, enter a name for the certificate and select *OK*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

You'll be asked to create a passcode for the device. Follow the on-screen instructions to do so. The certificate is installed when the passcode setup completed
.
// TODO: image:$NEW-IMAGE$[width=, alt=""]

[IMPORTANT]
====
If your organization does not use any passcode mode, remove the passcode on the device.
====

=== Android 11 or later

On the Android device, open *Settings*, *Biometrics and security*, then *Other security settings*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Select *Install from the device storage*, then *CA certificate*.

// TODO: image:$NEW-IMAGE$[width=, alt=""]

Choose *Install anyway*, then select the certificate. Select *Done* to install.

// TODO: image:$NEW-IMAGE$[width=, alt=""]
