= Configure an iOS device for network payload capture
:navtitle: Configure an iOS device

Learn how to configure an iOS device for network payload capture so you and your team can use network payload capture during a xref:manual-testing:local-devices/use-network-payload-capture.adoc[manual session] or xref:automation-testing:local-devices/use-network-payload-capture.adoc[automation session].

[NOTE]
You'll need to configure each iOS device you want to use for network playload capture.

[#_before_you_start]
== Before you start

include::partial$network-payload-capture/before-you-start.adoc[]

== Choose MIME types

include::partial$network-payload-capture/choose-mime-types.adoc[]

== Get device UDID

Connect your device to your MacOS computer. Open Finder, then select the device.

image:$NEW-IMAGE$[width=, alt=""]

Hover the mouse over the device information, then right-click and copy the device UDID to a secure location.

image:$NEW-IMAGE$[width=, alt=""]

== Add certificate to device

Turn on airdrop, confirm the location of the xref:_before_you_start[certificate you downloaded earlier], then share the certificate from your computer to the device.

image:$NEW-IMAGE$[width=, alt=""]

When you see the airdrop notification on the device, select *Accept*.

image:$NEW-IMAGE$[width=, alt=""]

== Install certificate

On the device, open *Settings*, then *General*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Profiles*, then the certificate.

image:$NEW-IMAGE$[width=, alt=""]

Select *Install*, then *Done*.

image:$NEW-IMAGE$[width=, alt=""]

== Enable full trust for certificate

On the device, open *Settings*, then *General*.

image:$NEW-IMAGE$[width=, alt=""]

Select *About*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Certificate Trust Settings*.

image:$NEW-IMAGE$[width=, alt=""]

Turn on *Kobiton Certification Authority*.

image:$NEW-IMAGE$[width=, alt=""]

== Remove device passcode

On the device, open *Settings*, then do one of the following:

* On a device with Face ID: select *Face ID & Passcode*.
* On a device with a Home button: select *Touch ID & Passcode*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Turn Passcode Off*.

image:$NEW-IMAGE$[width=, alt=""]

== Create config file

include::partial$network-payload-capture/create-config-file.adoc[]
