= Configure an Android device for network payload capture
:navtitle: Configure an Android device

Learn how to configure an Android device for network payload capture so you can xref:devices:local-devices/network-payload-capture/create-a-configuration.adoc[create a configuration for network payload capture].

[NOTE]
You'll need to configure each Android device you want to use for network playload capture.

[#_before_you_start]
== Before you start

include::partial$network-payload-capture/before-you-start.adoc[]

[#_get_device_udid]
== Get device UDID

Connect the Android device to your personal computer, then enter the following command to get the device UDID:

[source,shell]
----
adb shell settings get secure android_id
----

You'll need this later. Copy it to a secure location.

== Add certificate to device

Confirm the location of the xref:_before_you_start[certificate you downloaded earlier], then enter the following command:

[source,shell]
----
adb push <path/to/certificate> sdcard
----

.MacOS
[source,shell]
----
adb push ~/Downloads/mitmproxy-cert.crt sdcard
----

.Windows
[source,shell]
----
adb push C:\Users\Alex\Downloads\mitmproxy-cert.crt sdcard
----

== Install certificate

=== Android 11 or later

On the Android device, open *Settings*, *Biometrics and security*, then *Other security settings*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Install from the device storage*, then *CA certificate*.

image:$NEW-IMAGE$[width=, alt=""]

Choose *Install anyway*, then select the certificate.

image:$NEW-IMAGE$[width=, alt=""]

=== Other Android versions

On the Android device, open *Settings*, then *Explore*.

image:$NEW-IMAGE$[width=, alt=""]

Select the certificate.

image:$NEW-IMAGE$[width=, alt=""]

If the device doesn't have a passcode already, you'll be asked to create one. Follow the on-screen instructions to create a passcode.

image:$NEW-IMAGE$[width=, alt=""]

== Remove device passcode

If your device has a passcode, open *Settings*, then *Security*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Screen lock*, enter your passcode, then select *screen lock: None*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Yes, remove to delete all passcode*.

image:$NEW-IMAGE$[width=, alt=""]

== Create config file

include::partial$network-payload-capture/create-config-file.adoc[]
