= Create a configuration for network payload capture
:navtitle: Create a configuration

Learn how to create a configuration so can enable network payload capture for your xref:manual-testing:local-devices/capture-network-payload-data.adoc[manual session] or xref:automation-testing:local-devices/capture-network-payload-data.adoc[automation session].

== Before you start

You'll need to:

* xref:devices:local-devices/network-payload-capture/configure-the-local-server.adoc[Configure your local Kobiton server].
* Configure an xref:devices:local-devices/network-payload-capture/configure-an-ios-device.adoc[iOS device] or xref:devices:local-devices/network-payload-capture/configure-an-android-device.adoc[Android device].

== Create a configuration

In Kobiton, select your profile, then choose *Settings*.

image:$NEW-IMAGE$[width=, alt=""]

Select *Network Capture*.

image:$NEW-IMAGE$[width=, alt=""]

Enter one or more domain names, then select *Advanced*.

image:$NEW-IMAGE$[width=, alt=""]

Choose one or more xref:devices:local-devices/network-payload-capture/supported-mime-types.adoc[MIME types] to capture.

image:$NEW-IMAGE$[width=, alt=""]

When you're finished, select *Apply*.

Now you can enable network payload capture for xref:manual-testing:local-devices/capture-network-payload-data.adoc[manual testing] or xref:automation-testing:local-devices/capture-network-payload-data.adoc[automation testing].
