= Kobiton 2.14 release notes (Legacy)
:navtitle: Kobiton 2.14 release notes

_November 25, 2019_

== New Features

* *Device Logs (Android only)*: Ease the process of debugging your application while using real-time logs from Logcat or Console, you could use the advanced filter log from app or system processes to investigate and fix bugs instantly.

[NOTE]
This will be rolled out to iOS soon!

* *Private Test Mode*: You can control your sensitive data (e.g. username, passcode,etc.) within the manual execution for security purpose. By enabling the Private Test Mode, all commands, videos, screenshots, videos and logs will not be captured.

[NOTE]
Only available for in-house devices. To enable this feature, mailto:support@kobiton.com[contact support].

* *Bypass the passcode on iOS devices*: Devices or applications that are encountered the passcode for security or any specific testing purpose, Kobiton will help you to automatically input the passcode and continue your test execution.

[NOTE]
The bypass feature supports both manual and automated tests on iOS devices (versions 10 to 13.2.3) that have passcodes enabled following Kobiton's guidelines.

== Enhancements

* Support the manual & automation test up to iOS 13.2.3
* Support the automation test for Android on Chrome version 78
* Enhance the clean-up policy progress (reset the iOS device back to English after ending a session)
* Improve the quality of the system for a better testing experience (fix problems with adb, issues with Chrome 77, etc.)
