= Kobiton 3.27 release notes (Legacy)
:navtitle: Kobiton 3.27 release notes

_March 4, 2023_

These release notes pertain to Legacy Kobiton 3.27. As a reminder, in our November release, we started using 4.0+ as the numbering for releases of the new Kobiton, while Legacy Kobiton will continue with numbering starting with 3.25 and above. If you are using the new Kobiton, see xref:all-releases/4_1.adoc[].

If you have any questions or would like to update your Kobiton system, mailto:support@kobiton.com[contact support].

== New iOS and Android support

Legacy Kobiton 3.27 supports the following except the ability to change timezone and cleanup timezones during a session:

* iOS/iPadOS 15.7.3
* iOS/iPadOS 16.3
* iOS/iPadOS 16.3.1

== Device Log: Show info logging for iOS devices

You can now view and filter device logs by *Info* level for iOS devices (Android devices already support this type of logging). More information is available xref:manual-testing:device-information/device-logs.adoc#_filters[here].

_Note:_

* _Info log is supported from iOS/iPadOS 14 onward._
* _An application must enable Info level logging to retrieve Info log._

== API v2

API v2 is now available with improved performance and new endpoints.

Check out the API v2 documentation site link:https://api.kobiton.com/v2/docs[here].

link:https://api.kobiton.com/docs/?http#kobiton-api-v1-0[Kobiton API v1] is still available until further notice. We encourage you to start using API v2 as you add new test scripts and processes.

For endpoints in API v1 not yet offered in v2, continue to use API v1. We'll continue to enhance API v2 in future releases.

_Note: Some API v2 endpoints do not apply to Legacy Kobiton, as the underlying features are not available for Legacy Kobiton._

== Additional enhancements and bug fixes

In addition to the above, this release includes a number of minor bug fixes and enhancements to improve your day-to-day testing.
