= Kobiton 4.14 release notes
:navtitle: Kobiton 4.14 release notes

_August 2, 2024_

== New OS support

Kobiton 4.14 adds support for the following:

* iOS/iPadOS 18 Beta 3
* Xcode 16 Beta

== Lightning mode support for iOS 17.4 devices and later without networking changes

When Apple introduced iOS 17, they rolled out new connectivity protocols that impacted how iOS 17 devices communicated with solutions like Kobiton. These protocols required special network configurations for Kobiton Lightning Mode deployments that were not always possible for customers to implement.

With iOS 17.4, Apple introduced a new communication protocol that significantly enhances connections between iOS devices and the Kobiton platform. We implemented this innovative protocol with this release. This protocol eliminates the need for the special Lightning Mode networking changes introduced with iOS 17 for iOS 17.4+ devices, simplifying your networking.

[IMPORTANT]
====

* iOS 17.0-17.3 devices continue to require special networking to support Lightning mode, so we recommend those devices are hosted on a separate Mac mini in Standard mode.

====

[NOTE]
====

* iOS 17.4 and later devices still need to be plugged into the Mac mini to establish trust before connecting to the GEM.
* Metrics is not available for iOS 17.0 to 17.3 devices.
* virtualUSB is not available for iOS 17 and later.

====

== SSO: allow non-SSO login for specific users in SSO-only organizations



== Minor improvements and bug fixes
This release includes several enhancements and bug fixes to improve your day-to-day testing.

* Addressed the following Script-based test automation and Device Inspector items:
** Fixed a bug that prevents image injection via app instrumentation in Appium.
** Implemented method `appium:optionalIntentArguments` .
** The `sendKeys` action now works in generated C# Appium script.
* Other items addressed:
** Image injection via app instrumentation is now working with iOS devices.
** Uploading app for installation in a manual session now works for Standalone Portal with SSL enabled.