= Kobiton 4.15 release notes
:navtitle: Kobiton 4.15 release notes

_September 14, 2024_

== New OS support

This release adds support for the following:

* iOS/iPadOS 18 beta 8

[NOTE]
For iOS/IPadOS 18 Beta 8, the cleanup policy does not clear signed-in accounts in the Mail app and Safari browser cache.

== Restart a device for users without ADMIN role

Before this release, only users with the `ADMIN` predefined role could restart a private/local device, and they could only do this from the Device Management page.

With this release, users with the appropriate permission can restart a device by selecting *Restart* via the *Device List* page.

[NOTE]
====

* Users without ADMIN role must be assigned a custom role with the permission `org_setting.reboot_private_device` to use this feature.

* Non-admin users with restart permission may only restart devices they can access via their assigned teams.

* Only devices with *Available* status or *Retained* by the current user can be restarted from the device details.

====

== Option to enable/disable unlimited retention for devices

This release introduces the option to enable/disable unlimited retention of devices for an org. In *Settings → Other Settings*, we added the checkbox: *Allow unlimited retention*. Check or uncheck this box, then choose *Save* to enable/disable unlimited retention of devices.

[NOTE]

====

* To access the *Other Settings* page, the user must be assigned a role with the permission `org_setting.modify`.

* The *Allow unlimited retention* checkbox applies to the whole org. By default, this checkbox is checked.

====

== Minor improvements and bug fixes

This release includes several enhancements and bug fixes to improve your day-to-day testing.

* Addressed the following Script-based test automation and Device Inspector items:

** Enable the ability to kick off sequential Xium sessions while in a mixed session.

** Fixed an issue with running Appium automation using the Appium Selenium WebDriver 5.0.0 or above.

** Added support for UIAutomator locator when using Appium Inspector.

** Added support for slider element in Appium Inspector.

* Addressed the following Scriptless enhancements and bug fixes:

** Adjust settings for the following flags in a session: `IgnoreUnimportantViews`, `IncludeSystemWindows`

*** Default setting for manual and Appium automation sessions is `false`.

*** If a user selects Capture mode in a Manual session, both flags are set to `true`.

** Some minor improvements and bug fixes.

* Other items addressed:

**  Added wildcard support to the deviceName query parameter for the get all devices API v2 endpoint. Example: Use `/v2/devices?deviceName=iPad*` to return devices whose name starts with *iPad*.

** Network Payload Capture: fixed an issue with converting payload files with `%%%` in the content.

** Improve stability of passcode-enabled devices.

** Improve stability of Lightning-mode devices.

** Fixed an issue with iOS/iPadOS 14 to 16 devices in virtualUSB for MacOS. *Note:* iOS/iPadOS 17 and above is not supported in virtualUSB.

** Improved device battery information reporting in the Device List: temperature, percent charged, battery health, and status.
