= Kobiton 4.18.3S Release Notes
:navtitle: Kobiton 4.18.3S release notes

_February 18, 2025_

This release brings improvements and fixes to deviceConnect while still ensuring the best compatibility with 4.18S portal.

[NOTE]
If the standalone environment is already running 4.18S, only the software on the Mac mini hosts needs updating.

== New OS Support

This release adds support for the following:

* iOS/iPadOS 18.3.1

[NOTE]
====

For iOS/iPadOS 18.3.1:

* Native XCUITest automation script is currently not supported.

* (Passcode-enabled organization only) If a manual session launches when the device is locked, the device is stuck on lock screen. As a workaround, press the power button twice, then swipe up on the lock screen to bypass it.

====

== General Improvements and Fixes

* Fixed an issue where the iOS/iPadOS Developer Disk Images (DDI) did not automatically remount after an update, resulting in the following error:
[source]
Can't find iOS device <UDID> with BoardID <number> and ChipID <number> in DDI BuildManifest.plist. Xcode may need to be updated.

* Improve the performance when there are more than four concurrent sessions with video capture enabled.

* Automatically disable Google Play Protect scanning as it can cause the manual session to become unresponsive for Android devices.
