= Kobiton 4.18.3S Release Notes
:navtitle: Kobiton 4.18.3S release notes

_February 18, 2025_

This release brings improvements and fixes to deviceConnect while still ensuring the best compatibility with 4.18S portal.

[NOTE]
If the standalone environment is already running 4.18S, only the software on the Mac mini hosts need updating.

== New OS Support

This release adds support for the following:

* iOS/iPadOS 18.3.1 [TBC]

[NOTE]
For iOS/iPadOS 18.3.1, [TODO]

== General Improvements and Fixes

* Fixed an issue with the iOS/iPadOS Developer Disk Images (DDI) not automatically remount when there is an update to the DDI, causing the below error:
[source]
Can't find iOS device <UDID> with BoardID <number> and ChipID <number> in DDI BuildManifest.plist. Xcode may need to be updated.

* Improve the latency when there are more than 4 concurrent sessions with video capture turned on.

* Automatically disable Google Play Protect scanning as it can cause the manual session to become unresponsive for Android devices.
