= Kobiton 4.19.6S Release Notes
:navtitle: Kobiton 4.19.6S release notes

_July 18, 2025_

[IMPORTANT]
This release does not include updates to the Portal software on the Standalone Dell server. Only `deviceConnect` and `deviceShare` on the Mac mini, and `adb` and `gigacap` on the Dell server should be upgraded.

== New OS support

* Xcode 26 Beta

* iOS/iPadOS 26 Beta

* iOS/iPadOS 18.4 official

* iOS/iPadOS 18.5 official

* Android 16 official

== Update adb version

This release upgraded adb to version `36.0.0` on the Mac mini and GEM.

For the Mac mini, the adb service is automatically updated when you upgrade to deviceConnect `4.19.6`

For our Standalone/On-Prem customers, please contact Kobiton Support to update the Kobiton software and `adb` on your GEM.

== Session Resilience and Performance Improvements

Improved system stability and performance in several areas, including device booking, Lightning Mode sessions, and deviceConnect services to enhance reliability and reduce errors.

