= Kobiton 4.19.6 Release Notes
:navtitle: Kobiton 4.19.6 release notes

_July TBD, 2025_

== New OS support

* Xcode 26 Beta

* iOS/iPadOS 26 Beta

* iOS/iPadOS 18.4 official

* iOS/iPadOS 18.5 official

* Android 16 official

== Changes to App Signing support for iOS Devices

=== The situation

* Apple no longer allows creating new App IDs with full wildcards like `\*` or `*.*`
* Existing profiles using legacy wildcards still work - for now.
* These profiles will eventually expire, and cannot be renewed or recreated.

=== Why this matters

If you haven’t already, you’ll need to transition to profiles using partial wildcards, e.g.: `com.\*`, `org.*`, `co.\*`, `uk.*`

Note that Kobiton requires at least one profile configured for and loaded into `deviceConnect` that has `com.*`

=== What you need to do

* Generate provisioning profiles that cover all the bundle ID formats you use.
* Import the profiles to `deviceConnect` and `deviceShare`, or contact *Kobiton Support* with the bundle ID of your apps to request profiles for Public devices.
* A step-by-step guide for creating the correct provisioning profiles for Hybrid customers will be available soon.

== Hybrid Lightning: update adb version

This release upgraded adb to version 36.0.0 on the Mac mini and GEM.

For the Mac mini, the adb service is automatically updated when you upgrade to deviceConnect 4.19.4.

For our Hybrid customers, please contact Kobiton Support to update the Kobiton software and adb on your GEM.

For our Standalone/On-Prem customers, please wait until the Standalone release announcements before upgrading adb.

== Session Resilience and Performance Improvements

* Enhanced the reliability of the device booking process to reduce the chances of encountering errors when launching or booking a device.

* Improve the performance of the `adb` server on the Lightning Mode GEM to better handle fetching multiple web contexts from Android devices.

* Reduced frame tearing in Manual sessions when there are many concurrent Lightning mode sessions.

* Improved the resilience of deviceConnect services to prevent hanging and crashing.


