= Kobiton 4.19.6S Release Notes
:navtitle: Kobiton 4.19.6S release notes

_July 18, 2025_

[IMPORTANT]
This release does not introduce changes to the Portal software on the Standalone Dell server. Only upgrade `deviceConnect`, `deviceShare` on the Mac mini and `adb`, `gigacap` on the Dell server.

== New OS support

* Xcode 26 Beta

* iOS/iPadOS 26 Beta

* iOS/iPadOS 18.4 official

* iOS/iPadOS 18.5 official

* Android 16 official

== Hybrid Lightning: update adb version

This release upgraded adb to version `36.0.0` on the Mac mini and GEM.

For the Mac mini, the adb service is automatically updated when you upgrade to deviceConnect `4.19.6`

For our Standalone/On-Prem customers, please contact Kobiton Support to update the Kobiton software and `adb` on your GEM.

== Session Resilience and Performance Improvements

* Enhanced the reliability of the device booking process to reduce the chances of encountering errors when launching or booking a device.

* Improve the performance of the `adb` server on the Lightning Mode GEM to better handle fetching multiple web contexts from Android devices.

* Reduced frame tearing in Manual sessions when there are many concurrent Lightning mode sessions.

* Improved the resilience of deviceConnect services to prevent hanging and crashing.


