= Kobiton 4.6.1 release notes
:navtitle: Kobiton 4.6.1 release notes

_August 31, 2023_

== iOS 17 beta support

Kobiton Cloud now supports iOS 17 beta 8.

We've added iOS 17 beta devices to our Public Cloud for those with Public Cloud subscriptions. We'll be adding more in the coming weeks.

Private and Local Cloud customers - please contact your Customer Success Managers or Account Executives to discuss next steps for iOS 17 beta support.

[NOTE]
====
_The following are limitations related to iOS 17 beta:_

* iOS 17 is supported in Standard Mode. Lightning Mode support is coming soon.
* Passcodes are not currently supported for deployments that include iOS 17 beta devices.
* virtualUSB does not support iOS 17 devices.
* XCUI automation is not currently supported for iOS 17 devices.
* Device metrics are not currently available for iOS 17 devices.

_The following are known issues:_

* The Cleanup Policy does not reset the device’s Display Zoom to the default if it is set to Zoomed during a prior session.
* The Cleanup Policy does not close system apps opened during a session.
====

We are actively working to support and resolve the above items, as well as supporting iOS 17 beta for our other deployment types: Cloud with Lightning Mode and Standalone. Stay tuned!