name: Release step

inputs:
  site:
    description: "The site to release"
    required: true

  cloudfront-id:
    description: "The Cloudfront ID to invalidate"
    required: true

  aws-account-id:
    description: "The AWS account ID to assume"
    required: true

  aws-region:
    description: "The AWS region to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials from PRODUCTION account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-action-role
        aws-region: ${{ inputs.aws-region }}

    - name: Release-docs 
      uses: dagger/dagger-for-github@v5
      with:
        version: "0.11.8"
        verb: call
        module: github.com/${{ github.repository }}@${{ github.ref }}
        args: |
          --ref ${{ github.ref }} \
          release \
          --site="${{ inputs.site }}" \
          --aws-region=${{ inputs.aws-region }} \
          --aws-access-key-id=env:AWS_ACCESS_KEY_ID \
          --aws-secret-access-key=env:AWS_SECRET_ACCESS_KEY \
          --aws-session-token=env:AWS_SESSION_TOKEN \
          --cloudfront-id=${{ inputs.cloudfront-id }} \
