name: Release step

inputs:
  site:
    description: "The site to release"
    required: true

  cloudfront-id:
    description: "The Cloudfront ID to invalidate"
    required: true

  aws-account-id:
    description: "The AWS account ID to assume"
    required: true

  aws-region:
    description: "The AWS region to use"
    required: true

  dagger-token:
    description: "The Dagger Cloud token"
    required: true

  ssh-key:
    description: "SSH private key to pull dagger module from private repo"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials from PRODUCTION account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-action-role
        aws-region: ${{ inputs.aws-region }}
    - name: ssh-agent setup
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}

    - name: Release-docs
      uses: dagger/dagger-for-github@847ae4458ef34fe9b5f566655957bde6d4891112 # v7.0.3
      with:
        version: "0.15.3"
        verb: call
        args: |
          release \
          --site="${{ inputs.site }}" \
          --aws-region=${{ inputs.aws-region }} \
          --aws-access-key-id=env:AWS_ACCESS_KEY_ID \
          --aws-secret-access-key=env:AWS_SECRET_ACCESS_KEY \
          --aws-session-token=env:AWS_SESSION_TOKEN \
          --cloudfront-id=${{ inputs.cloudfront-id }} \
        dagger-flags: "--silent"
        cloud-token: ${{ inputs.dagger-token }}
