= Viewing user's profile
:navtitle: Viewing user's profile

== How to view users’ profile
To see a user's profile:

1. Go to *Org Management*, click *Users* tab.

2. Click the user’s name (also hyperlinked in purple). You will be redirected to the User Details page.

On the *User Details*, you will see the user’s name, email, organization, and the option to enable SSO.

In the *User Roles* tab, you will see all roles assigned to the user. Click hyperlink *Derived Permissions* to check permissions associated with that role. You can also remove a role from the user on this page.

The *Teams* tab functions similarly to the User Roles tab. You can also remove the user from listed teams on this page.

== How to search for users
1. Go to the *Org Management*, click *Users* tab to view the list of users in your Kobiton organization.

2. Type the name or email in the *Search Users* search bar.

== How to remove users

The Remove function works the same way as Delete. To remove users from the organization:

1. Click *Users* tab on *Org Management*.

2. Click on the item in the list, not hyperlinks on users’ names or teams names or Roles. Otherwise, you will be redirected to another page.

3. A *Remove* tab appears, click *Remove*.

4. A pop up appears, click *Remove* if you still want to remove that user.

== How to disable users

The Disable function is the same as inactivating. To disable users from the organization:

1. Click *Users* tab on *Org Management*

2. Click on the item in the list, not hyperlinks on users’ names or teams names or Roles.

3. Click *Disable* when the tab appears.

4. A pop up appears, click *Disable* if you still want to disable that user.

NOTE: *Disable* and *Remove* buttons are only available for Active status users.

For users with a pending status, the Disable button is grayed out and there's a *Remove Invitation* button instead of *Remove*.

You can also *Disable/ Remove* users in the User Details page.

