= Create a baseline session for scriptless automation
:navtitle: Create a baseline session

Learn how to create a baseline session so you can run scriptless automation using the xref:scriptless-automation:run-scriptless-automation/using-the-kobiton-portal.adoc[Kobiton portal] or xref:scriptless-automation:run-scriptless-automation/using-the-kobiton-api.adoc[Kobiton API].

== Before you start

Review the supported xref:scriptless-automation:baseline-sessions/supported-apps.adoc[apps], xref:scriptless-automation:baseline-sessions/supported-actions.adoc[actions], and xref:scriptless-automation:baseline-sessions/supported-api-endpoints.adoc[API endpoints] you can use to create a baseline session.

include::manual-testing:partial$start-a-manual-session.adoc[]

If you want to test an app, first install a xref:scriptless-automation:baseline-sessions/supported-apps.adoc[supported app].

image:$NEW$[width="",alt=""]

Next, use xref:scriptless-automation:baseline-sessions/supported-actions.adoc[supported actions] during the session. To ensure these actions are correctly captured, xref:manual-testing:device-controls.adoc#_synchronous_inventory_capture[enable synchronous inventory capture].

image:$NEW$[width="",alt=""]

When you're finished testing, select the *X* icon.

image:$NEW$[width="",alt=""]

Select *Exit Session*.

image:$NEW$[width="",alt=""]

Now you can use this session to run scriptless automation using the xref:scriptless-automation:run-scriptless-automation/using-the-kobiton-portal.adoc[Kobiton portal] or xref:scriptless-automation:run-scriptless-automation/using-the-kobiton-api.adoc[Kobiton API].
