= Supported actions for scriptless automation
:navtitle: Supported manual actions

Learn about the requirements to convert a manual or automation session into Automated Test Case for Scriptless.

== Performance

The following actions may impact Scriptless Automation performance

* Clicking very quickly. For best results, please wait three seconds between two manual actions. This wait will ensure the screen has loaded completely when you make another “click” action.
* Swiping on map
* Clicking outside the pop-up to close it. Instead -  use "Back" button in the manual toolbar to close the pop-up
* Tapping on text prediction above the virtual keyboard
* Typing text into number input only
* Typing string that has length more than limit when editing text

== General Limitations

* Avoid interacting too fast during manual execution
** Since every action performed during manual execution will take a minor time for inventory capturing, especially when testing on Mobile Browser or Hybrid apps.
Tips: To ensure every action could be properly captured data, you could enable xref:manual-testing:device-controls.adoc#_synchronous_inventory_capture[Synchronous Inventory Capturing] during manual execution.

* Avoid tapping on the “blank” space, e.g. to close a pop-up, to un-focus on a text box, etc.
** This tap could cause “confusion” for AI when finding elements, which is more error-prone for revisit execution.

* Avoid tapping on text prediction above the device’s virtual keyboard
** Since the text prediction will be different on each device, so this tap will be encountered with an inconsistency.

== Device control in manual session

In the manual session, perform only the supported controls in the table below:

[options="header,footer"]
|===
|Controls                            |OS          |Status        |Comment
|Touch                               |Android/iOS |Supported     |
|Swipe                               |Android/iOS |Supported     |
|Device softkeys                     |Android     |Supported     |
|Virtual keyboard (ASCII characters) |Android/iOS |Supported*    |*Might not work properly on  the password field on Android 7 and below.

*Only English language is supported in iOS, excluding the emoji.
|Physical keyboard                   |Android/iOS |Supported     |
|Home (toolbar)                      |Android/iOS |Supported     |
|Power (toolbar)                     |Android/iOS |Supported     |
|Recent app (toolbar)                |Android     |Supported     |
|Back (toolbar)                      |Android     |Supported     |
|Long press                          |Android/iOS |Supported     |
|Double tap                          |Android/iOS |Not supported |
|Double press home                   |Android/iOS |Not supported |
|Pin to zoom                         |Android/iOS |Not supported |
|Take screenshot                     |Android/iOS |Not supported |
|Set timezone                        |Android/iOS |Not supported |
|Copy & paste (copy to clipboard)    |iOS         |Not supported |
|===
