= Android Debug Bridge (`adb`) commands
:navtitle: Android Debug Bridge (`adb`) commands

During a manual session, you can xref:device-controls.adoc#_adb_shell_android_only[run Android Debug Bridge (`adb`) commands] on your private and local devices, as well as your public ones.

== Private and local

You can run most `adb` commands on private and local devices--unless they could harm the device or alter device systems in real-time. Here's some examples of commands we *don't* allow:

* `kobiton/i`
* `logcat/i`
* `monkey/i`
* `top/i`
* `com.domobile.applock/i`
* `com.domobile.applockwatcher/i`
* `com.sp.protector.free/i`
* `com.manageengine.mdm.android/i`
* `com.manageengine.mdm.samsung.knox/i`
* `com.manageengine.mdm.samsung/i`
* `com.manageengine.admp/i`
* `com.android.systemui/i`
* `com.android.settings/i`
* `com.android.vending/i`
* `com.google.android.webview/i`
* `monkey -p com.myAppPackage -v 10000 -s 100`

== Public

Since public devices can be accessed by anyone using Kobiton, we limit the amount of `adb` commands you can run on public devices. For now, these are the only supported commands:

* `dumpsys display`
* `dumpsys battery`
* `pm list packages -3`
