= Custom gestures
:navtitle: Custom gestures

During a manual session, you create scripts to xref:device-controls.adoc#_draw_custom_gesture[draw custom gestures].

== Scripts

Scripts contain one or more xref:_functions[functions] space-separated in a single line. Each function could contain zero or more xref:_parameters[parameters], depending on the specific function. If a parameter is required for a specific function, it'll be marked `<>`, otherwise it'll be marked `[]`.

[source,javascript]
----
down(0%, 0%, 3) move(50%, 50%, 3) up(3) // Places the 4th finger on the screen at 0%, 0%, moves the finger to 50%, 50%, and then removes the finger.
----

[#_functions]
== Functions

[#_arc]
=== `arc(<x>, <y>, <angle>, [finger], [duration])`

Draws an elliptical shape starting from the current location of `finger` and finishing at the same location.

The xref:_x_and_y[`x`] and xref:_x_and_y[`y`] coordinates refer to the exact center of the shape--the arc's path never passes through `x` and `y`, rather it goes _around_ in a symmetrical path.Set the `angle` to determine how wide or narrow the shape should be.

By default, `finger` is set to `0` and `duration` is set to `2s`.

[source,javascript]
----
down(50%, 50%) arc(50%, 50%, 180) //
down(50%, 50%) arc(50%, 50%, 0) //
down(50%, 50%) arc(50%, 50%, 360) //
----

[#_down]
=== `down(<x>, <y>, [finger])`

Place a finger on the screen at the xref:_x_and_y[`x`] and xref:_x_and_y[`y`] coordinates. By default, xref:_finger[`finger`] will be set to `0`, unless you choose a different finger. The `finger` won't move unless called in another function.

[source,javascript]
----
down(1px, 400px) // Places a finger at 1px, 400px using the pixels of your computer monitor.
down(400dp, 1dp) // Places a finger at 400px, 1px using the pixels of the mobile device screen.
down(1%, 100%) // Places a finger at 1%, 100% by multiplying the length of the mobile device screen by its relavant axis.
----

[#_move]
=== `move(<x>, <y>, [finger], [duration])`

Swipe a finger from its current location to the location specified in `move()`. By default, xref:_finger[`finger`] will be set to `0` and xref:_duration[`duration`] will be set to `2s`.

[NOTE]
If there's no `finger` on the screen yet, xref:_down[`down()`] will be called instead.

[source,javascript]
----
down(50%, 50%) move() // This
down(50%, 50%) move() // This
down(50%, 50%) move() // This
----

[#_sync]
=== `sync([finger])`

Wait for all function calls to finish before calling more functions. If xref:_finger[`finger`] is assigned, `sync()` only applies to function calls using that `finger`.

[source,javascript]
----
down(0) sync() down(1) // Wait for all functions to finish before placing the 2nd finger down.
down(0) sync(1) down(1) // Wait for the 1st finger to finish before placing the 2nd finger down.
down(0) sync(0) down(1) // Place the 2nd finger down immediately, since sync() was only applied to the 1st finger.
----

[#_up]
=== `up([finger])`

Remove a finger from the screen. By default, xref:_finger[`finger`] will be set to `0`, unless you choose a different finger.

[source,javascript]
----
up() // Removes the 1st finger from the screen since a finger wasn't specified.
up(5) // Removes the 6th finger from the screen.
----

[#_wait]
=== `wait(<duration>)`

Wait for `duration` before calling more functions.

[source,javascript]
----
wait(20ms) // Waits for 20 milliseconds before calling another function.
wait(30s) // Waits for 30 seconds before calling another function.
----

[#_parameters]
== Parameters

=== `angle`

An integer ranging from `-360` to `360` that determines the angle of xref:_arc[`arc()`]. Positive integers are drawn clockwise, while negative integers are drawn in reverse.

[source,javascript]
----
down(50%, 50%) arc(50%, 50%, 180) //
down(50%, 50%) arc(50%, 50%, 0) //
down(50%, 50%) arc(50%, 50%, 360) //
----

[#_duration]
=== `duration`

A positive integer used to set the duration of a function. By default, `duration` is set to milliseconds, but you can append `ms` (milliseconds) or `s` (seconds) to manually change this.

[source,javascript]
----
wait(50) // Waits for 50 milliseconds.
wait(30ms) // Waits for 30 milliseconds.
wait(8s) // Waits for 8 seconds.
----

[#_finger]
=== `finger`

An integer ranging from `0` to `9` indicating _which_ finger to use in a gesture. By default, `finger` is set to `0`, but you can choose another integer up to `9`. Use different fingers with different functions to create multi-finger gestures, like a two-finger swipe or pinch.

[source,javascript]
----
down(50%, 50%, 0) // Places the first finger on the center of the screen.
move(1px, 400px, 8) // Swipes the ninth finger from pixel 1 to pixel 400 on the screen.
up(4) // Removes the fifth finger from the screen.
----

[#_x_and_y]
=== `x` and `y`

Two positive integers used to set a gesture's coordinates.By default, `x` and `y` refer to pixels, but you can append `px` (pixels), `dp` (device-independent pixels), or `%` (percent) override the coordinate type.

[source,javascript]
----
down(1px, 400px) // Places a finger at 1px, 400px using the pixels of your computer monitor.
down(400dp, 1dp) // Places a finger at 400px, 1px using the pixels of the mobile device screen.
down(1%, 100%) // Places a finger at 1%, 100% by multiplying the length of the mobile device screen by its relavant axis.
----
