= Device controls
:navtitle: Device controls
:numbered:

You can interact with the test device using these controls during a manual session.

image:$NEEDSIMAGE$[alt="A manual session with each device control numbered in red."]

== Touch

You can interact with your device by using *left-click* to tap and swipe the screen.

== Pinch/zoom

You can zoom or pinch the device screen by placing the center circle on your target location and dragging an outer circle closer or farther away.

image:$NEEDSIMAGE$[alt=""]

== Set device location

You can change the device location by either searching for a location or entering a longitude and latitude.

image:$NEEDSIMAGE$[alt=""]

== Set device timezone

You can change the device timezone by selecting a new timezone from the dropdown.

image:$NEEDSIMAGE$[alt=""]

== Rotate screen

You can rotate the device screen between portrait and landscape.

image:$NEEDSIMAGE$[alt=""]

== Volume

You can change the device volume by selecting *Volume Up* or *Volume Down*.

[NOTE]
This won't change the volume coming from your computer, only...

[#_adb_shell]
== `adb` shell

You can enter Android Debug Bridge (`adb`) commands to install or debug apps on your Android test device.

[NOTE]
We only allow xref:adb-commands.adoc[specific `adb` commands] so we can continue keeping test devices in excellent condition.

== Preform VoiceOver

After you set up xref:devices:enable-voiceover-for-ios.adoc[VoiceOver for iOS], you can test screen reader compatibility.

== Biometric authentication

After you add our xref:integrations:biometric-authentication/about-our-library.adoc[biometrics authentication library] to your app, you can select *Pass* or *Fail* to test biometric authentication requests.

[#_draw_custom_gesture]
== Draw custom gesture

You can draw custom gestures like three-finger swipes or two-finger taps by choosing a sample gesture or xref:custom-gestures.adoc[creating your own].

image:$NEEDSIMAGE$[alt=""]

After you create a gesture, you can save it for future sessions.

== Input sensitive data

You can input sensitive data (like usernames and passwords) without recording it in the xref:session-analytics:session-overview.adoc#_session_video[session video]. Enter your sensitive data, tap the related field on your device, then select *Save* to send it securely.

image:$NEEDSIMAGE$[alt=""]

== Image injection

You can xref:test-in-app-camera.adoc[test your in-app camera] by adding an image to the injection library and selecting *Set Image*.

image:$NEEDSIMAGE$[alt=""]

== Power

You can restart your device by selecting the *Power* button. (Don't worry--this won't end your session).

image:$NEEDSIMAGE$[alt=""]

== Home button

You can single-click or double-click the *Home Button* to replicate the link:https://support.apple.com/en-us/HT208204[iOS] or link:https://support.google.com/android/answer/9079644[Android] home button.

== Recent apps

While using an Android device, select *Recent Apps* to link:https://support.google.com/android/answer/9079646[display your recent apps].

image:$NEEDSIMAGE$[alt=""]

== Back

While using an Android device, select *Back* to xref:https://support.google.com/android/answer/9079644[return to the previous page].

image:$NEEDSIMAGE$[alt=""]

== Synchronous inventory capture

If any device interactions are missing from your xref:session-analytics:index.adoc[session analytics], enable *Synchronous Inventory Capture* to prevent interactions from moving faster than the inventory capture.

image:$NEEDSIMAGE$[alt=""]

Now you'll have to wait for each interaction to be captured before attempting a new one.

image:$NEEDSIMAGE$[alt=""]

== Speedometer

You can increase the test device screen to 30 frames per second (FPS) by enabling *Lightning Mode*. You can also check your session runtime, latency, and resolution.

image:$NEEDSIMAGE$[alt=""]

[NOTE]
Lightning mode is only available on link:https://kobiton.com/pricing/[certain plans].

== Screenshots

You can select *Take Screenshot* to take a screenshot and select *Screenshots* to download them. Your total number of screenshots will be displayed on the *Screenshots* icon.

image:$NEEDSIMAGE$[alt=""]
