= Enable network payload capture
:navtitle: Enable network payload capture

The Network Payload Capture enables users to intercept the network traffic and inspect data for every HTTP requests and responses in and out of devices in test sessions.

== Before you start

You'll need to complete the following:

* xref:devices:local-devices/network-payload-capture/configure-ios-device.adoc[Configure iOS device]
* xref:devices:local-devices/network-payload-capture/configure-android-device.adoc[Configure Android device]
* Download link:https://apps.apple.com/app/id1037126344[Apple Configurator] and link:https://support.apple.com/guide/apple-configurator-mac/use-the-command-line-tool-cad856a8ea58/mac[install automation tools].

== Use the Network Payload capture testing on the device

. Make sure that the mobile device and the computer where it is plugged connect to the same Wifi/Ethernet address.
. With the mobile device plugged in, launch the Kobiton Desktop application.
. Make sure that the Apple configurator tool is started and running during the test for Android devices.
. Start your test session including Manual (or Appium automation) that accesses the domain which is set up to capture payload.
. You can view the payload in the tab Observe Request / Response Payloads in Session Detail page on the Kobiton portal.
