= In-session device information
:navtitle: In-session device information

During a manual session you can read, filter, and analyze information about your device in realtime.

[#_device_log]
== Device log

=== Clear logs

Erase the current stream of logs.

=== Pause/Play

Pause or play the current stream of logs.

=== Download logs

Download the current stream of logs as a `.log` file.

=== Dropdown

Only display logs with a *Notice*, *Warning*, or *Error* message.

=== Search bar

Only display logs matching your search.

[#_inspector]
== Inspector

=== Refresh inventory

After navigating to a new page in your app or web browser, select *Refresh inventory* to display that page's *Hierarchy*. *Refresh inventory* also resets your current filters and searchers.

=== Inspect elements

Hover over an element on the device screen and highlight its XML data.

=== Download inventory

Download the current inventory as an `.xml` file.

=== Dropdown

Choose a specific WebView to display. The default WebView is `NATIVE_APP`.

=== Search bar

Only display elements in the *Hierarchy* that match your search.

=== Attributes

Select an element and display a list of related attributes, like `type`, `name`, `xpath`, and more.

[#_metrics]
== Metrics

=== Memory

==== Used

The amount of memory the device is using.

=== CPU

==== Load

The amount of work the device's CPU is performing.

=== Network

==== Bytes in

The amount of bytes the device is receiving over the network.

==== Bytes out

The amount of bytes the device is sending over the network.

==== Bytes in per second

The amount of bytes the device is receiving over the network per second.

==== Bytes out per second

The amount of bytes the device is sending over the network per second.

=== Battery drain

==== Used

The speed at which the device's battery is draining.
