= Manual testing
:navtitle: Manual testing

Welcome to the help section on manual testing! In this section you will learn everything you need to know on Kobiton's manual testing. From the high-level, like how to find the test device, to the detailed, like how to spoof the device's location during the manual test.

[NOTE]
Kobiton offers https://training.kobiton.com/unit/view/id:2196[a free, video-led training course] where you can become a certified Manual Testing Specialist.

== Manual testing workflow

Manual Testing is one of three types of testing you can perform on Kobiton. To explore the other types of testing on Kobiton, hop over to the sections on xref:automation-testing:index.adoc[Automation Testing] and Scriptless Testing.

image::manual-testing-flow.svg[Diagram visually depicting the manual testing workflow]

1. xref:launching-your-device/index.adoc[]
2. xref:installing-apps/index.adoc[]
3. xref:performing-manual-tests/index.adoc[]
4. xref:analyzing-results/index.adoc[]
5. xref:next-steps/index.adoc[]
