= Install an app
:navtitle: Install an app

Learn how to install an app during a test session.

[#_install_an_app]
== Install an app

. xref:start-a-session.adoc[Launch a device].
. Select *Install Apps*.
[IMPORTANT]
You'll need to enable xref:test-an-app/image-injection.adoc[image injection] and xref:integrations:biometrics-library.adoc[biometrics] to use these features during your test session.
. Choose *Upload File*, *Install From URL*, or *Search App*:

* *Upload File:* Upload an `.apk`, `.ipa`, `.zip`, or `.aab` file from your local device.
* *Install From URL:* Enter a URL and download from the Apple or Google Play app stores.
* *Search App:* Use the search bar to locate and install an app from the app repository.
[NOTE]
You can xref:app-management:app-repository.adoc[add more apps] to the app repository at any time.

. You'll receive a notification when your installation is complete.
. Depending on your xref:device-lab-management:device-cleanup.adoc[cleanup policy], the app will be automatically uninstalled after your session.
