= iOS VoiceOver commands
:navtitle: iOS VoiceOver commands

After you xref:devices:local-devices/enable-ios-voiceover.adoc[enable iOS VoiceOver] you can xref:device-controls.adoc#_adb_shell[run iOS VoiceOVer commands] during a manual session to test your app's screen reader compatibility.

image:$NEW-IMAGE$[width, alt=""]

== Tap

=== Double-tap

To double-tap, select *Activate selected item*.

=== Triple-tap

To triple-tap, select *Double-tap selected item*.

=== Two-finger tap

To two-finger tap, select *Pause/resume speech*.

=== Two-finger double tap

To two-finger double tap, select *Special action*.

=== Two-finger triple tap

To two-finger triple tap, select *Open item chooser*.

=== Three-finger tap

To three-finger tap, select *Speak current page number and position*.

=== Three-finger double-tap

To three-finger double-tap, select *Toggle speech on/off*.

=== Three-finger triple-tap

To three-finger triple-tap, select *Toggle screen curtain on/off*.

== Swipe

=== Swipe right

To swipe right, select *Select next item*.

=== Swipe left

To swipe left, select *Select previous item*.

=== Swipe up or down

To swipe up or down, select *Perform or move to the next selected option*.

=== Two-finger swipe up

To two-finger swipe up, select *Read all content from the first object in selected area*.

=== Two-finger swipe down

To two-finger swipe down, select *Read all content from selected item*.

=== Two-finger swipe back-and-forth

To two-finger swipe back-and-forth, select *Go back, cancel, close pop-up*.

=== Three-finger swipe left

To three-finger swipe left, select *Move to next horizontal screen page*.

=== Three-finger swipe right

To three-finger swipe right, select *Move to previous horizontal screen page*.

=== Three-finger swipe up

To three-finger swipe up, select *Move/scroll down a page*.

=== Three-finger swipe down

To three-finger swipe down, select *Move/scroll up a page*.

=== Four-finger swipe left/right

To four-finger swipe left/right, select *Switch to next/previous app*.

=== Four-finger swipe up/down

To four-finger swipe up/down, select *Open or close multitask pane*.

== Pinch

=== Two-finger pinch out/in

To two-finger pinch out/in, select *Select / deselect*.

=== Four-finger pinch in

To four-finger pinch in, select *Go to home screen*.
