= Session settings
:navtitle: Session settings

You can change your session's name, description, idle settings, and cleanup policy while your in a test session. Select the *settings icon*, make your changes, and select *Apply*.

== Settings

=== Name

You can enter a new name for the current manual session. This name will appear in search results when you xref:session-analytics:search-for-a-session.adoc[search for your session] later. If you can't think of one right now, you can also add one xref:session-analytics:session-overview.adoc[after the session].

=== Description

You can enter a description for the current manual session. You'll see this description in the xref:session-analytics:session-overview.adoc[session overview]. If you need to make any changes, you can edit it there too.

=== Quit session after staying idle for 10 minutes

By default, manual sessions will end after being idle for 10 minutes. Uncheck this box to disable this setting. If you'd like to disable this for all future sessions, xref:organization-and-profile:your-profile/manage-your-profile.adoc#_change_your_session_timeout[update your preferences].

=== Automatically clean-up after session end

Check or uncheck this setting to automatically xref:organization-and-profile:your-organization/create-a-device-cleanup-policy.adoc[clean up your device] after the session.
