= Test your in-app camera
:navtitle: Test your in-app camera

Learn how to test your in-app camera during a manual session using image injection.

== Before you start

To test your in-app camera, you'll need to enable *Instrument application for camera injection* before you xref:install-an-app-during-a-session.adoc[install your app].

== Add an image

First you'll add one or more images to your injection library. From your xref:device-controls.adoc[device controls], select *Image Injection*.

Then select *Set Simulated Image* and upload one or more `.jpg`, `.jpeg`, or `.png` files from your computer.

== Inject an image

Now that you've added some images to your library, launch your app and select your in-app camera. Choose an image from the library and select *Inject* to test your in-app camera.

When you're finished, select *reset camera* to stop injection.

== Remove an image

At any time, you can remove an image from your injection library. From your xref:device-controls.adoc[device controls], select *Image Injection*, then choose an image and select *Clear Image* to remove it from your library.
