= Device summary report
:navtitle: Device summary report

The device summary report is a predefined report containing up-to-date data for all devices.

image:<NEW-IMAGE>[width=, alt=""]

== Time

Update the report with the most recent device data.

image:<NEW-IMAGE>[width=, alt=""]

== Operating system (OS)

Only display entries with this device operating system (OS).

image:<NEW-IMAGE>[width=, alt=""]

== Team

Only display devices xref:organization:manage-teams.adoc[owned by this team].

image:<NEW-IMAGE>[width=, alt=""]

== Search

Filter the report by a specific device tag.

image:<NEW-IMAGE>[width=, alt=""]

== Adjust service level ability (SLA)

Change the minimum number of available devices and the maximum number of offline devices to adjust your service level ability (SLA).

image:<NEW-IMAGE>[width=, alt=""]

If the SLA is breached, the related column will be highlighted in red.

image:<NEW-IMAGE>[width=, alt=""]

== Columns

Each column contains details about your devices.

image:<NEW-IMAGE>[width=, alt=""]

=== OS version

The device operating system version (OS version).

=== Available Devices

The total number of available devices, which includes devices with a status of online and utilizing.

=== Online Devices

The total number of online devices.

=== Utilizing

The total number of utilized devices.

=== Offline Devices

The total number of offline devices.

== Edit the "Minimum Available Devices" and "Maximum Available Devices"

There is a pencil icon next to each row. Noting that if the actual number of Available devices are less than "Minimum Available Devices" --> the number will be in Red color.

If the actual number of Offline devices are greater than "Maximum Offline Devices" --> the number will be in Red color.

The calculation of "Minimum Available Devices", "Maximum Offline Devices" will be stopped when users filter the report.

NOTE: there is only Organization Admin who can edit Minimum Available Devices and Maximum Available Devices.
