= Reporting controls
:navtitle:

$DESCRIPTION$

== Device Summary

Device Summary report gives you quick visibility of your devices pool: counts of Online vs. Offline, Utilized vs. Available devices. This feature is essential when customers scale up and manage a large number of devices.

=== Navigate to the report

On the left-side navigation, select Predefined Reports. This report will access all Kobiton devices, including Kobiton Public devices or your Private & Local devices.

Users can filter the reports by:
* OS version.
* Team.
* Device Tag.

Users can view and sort the following metrics based on OS versions:
* Available Devices: the total number of Online and Utilizing devices.
* Online Devices: Devices that are online.
* Utilizing: Devices that are being utilized.
* Offline Devices: Devices that are offline.

=== Edit the "Minimum Available Devices" and "Maximum Available Devices"

There is a pencil icon next to each row. Noting that if the actual number of Available devices are less than "Minimum Available Devices" --> the number will be in Red color.

If the actual number of Offline devices are greater than "Maximum Offline Devices" --> the number will be in Red color.

The calculation of "Minimum Available Devices", "Maximum Offline Devices" will be stopped when users filter the report.

NOTE: there is only Organization Admin who can edit Minimum Available Devices and Maximum Available Devices.

=== Explanation of each column in the Device Summary report

* OS Version: Android or iOS

Special cases:
- Android 5.x or below (count all devices that are having android version equal or below 5.x).
- iOS 13.6.x or below (iOS 13.6.x + iOS 12 + iOS 11 + iOS 10,...)
- iOS 13.7 or above (count all devices that are having iOS version equals 13.7 to 13.x (exclude 13.6 and below).

Normal cases:
- Android: "6.x", "7.x",...,"12.x" (group and count all devices that are having the same parent version, e.g., android 6.1, 6.2,...,6.5 -> will be counted as 6.x).

Available Devices: a total of Online AND Utilizing devices.
Online Devices: Devices that are online.
Utilizing Devices: Devices that are being utilized.
Offline Devices: Devices that are offline.

== Usage Report

Usage Report provides users with statistics about usage on Kobiton platform.

The Usage Report counts the number of sessions and aggregate minutes on session types:
* Manual
* Automation
* Mixed sessions
* Scriptless on Manual (scriptless sessions triggered on Manual session baseline)
* Scriptless on Automation (scriptless sessions triggered on Automation session baseline)
* Test Case

The report also provides the total count and minutes aggregation on sessions with Scriptless session Validation types:
* Text Validation
* Color Validation
* Visual Validation
* flexCorrect
* Accessibility Validation
* Font Size (WBI)

System Latency Report

System Latency Report displays a summary of the org's connection timing as well as response time of steps from sessions. The goal is to assist Kobiton Organizations to notice latency and determine where the latency is occurring. The feature aims to provide transparency, insights, and to troubleshoot the root cause of a performance issue that could occur in Kobiton Lightning Mode.

NOTE:

Only Manual and Mixed session types are measured in this report, not Automation session.
This report only includes sessions on devices on the Latest Kobiton platform.
Manual commands that we measure include:
- Type
- Touch
- Swipe
- Drag
- Zoom
- Press button: Home, Power, Volume Up, Volume Down, Delete, Enter, App Switch (Android), Back (Android).

However, those commands are not visible on the report.
We only measure the timing from the Device to the Browser for those devices hosted with GEM (sessions that have Lighting Mode enabled).
If data of a session = N/A, it means that a user doesn't perform any supported manual commands (listed above) in their sessions.

== How to use System Latency Report

To view this report, go to Predefined Reports, click System Latency Report to view details.

Below is the demonstration of Summary report by Connection type: Browsers to devices, Browser to Server, Server to deviceShare, deviceShare to Device, Device to Browser. The default time frame is 7 days. However, users can modify the time frame. Noting the maximum time users can view the report is 1 month.

On this Summary table - we calculate the Average, Minimum, Maximum, and Median latency of all manual sessions' commands (manual commands in mixed sessions are also included).

Click Details to view the details of each Connection type.

Click on the arrow to expand the data to a lower level (view all deviceShare of 1 location or view all sessions per deviceShare).

By default, we will display 10 sessions per deviceShare - you can click on "See more" to view more data.

Kobiton supports searching data on System Latency Report. Select Details of a Connection type to access the search bar. You can search by Location, deviceShare, Session ID, User, or Device UDID. Use the format: <Search category>: <keyword>. We support searching with multiple categories. For example:
- "location:Atlanta user:johndoe" will search any session with Location matched "atlanta" and was run by user "johndoe".

The search result table will return all records matched with your criteria. If your keyword has space in between, you need to put it in a double quote. For example: "location:"atlanta - US"".

== Device Availability report

Device Availability provides users with a detailed history of Private and Local device states. Some insights that you can collect from the report are: Count of current devices that are online or offline, devices that temporarily have no network (no internet access).

== How to navigate to Device Availability report

In the Predefined Reports, select Device Availability report. There are three sections in the report:

=== Overview

Users can filter the report by date range (within 90 days).
To apply the date filter: select Refresh.

=== Hosted by Kobiton - Private Devices

Device Availability report on Private devices which are hosted and maintained by Kobiton.

=== Hosted by [Organization's name] - Local Devices

Device Availability report on users' Local devices which are hosted and maintained by the user.

== Field explanation in the Device Availability report

Overall, the report will cover 3 main events of devices: Offline, Offline (Unplugged), No Network (no internet access).
If one of those events happens, Kobiton will track and display the history in the Device Availability report.

* Total Registered Devices

Date range: to indicate the start and end date.
Number: the number of total devices that were hosted online during this Date range.

* Avg. Device Availability

The average number of device availability in percentage (100% indicates all registered devices are online).
This record will have 2 parts:
- Days: total days that the devices were online.
- Avg. device availability: the percentage of online devices.

* List view

UDID: UDID of the devices. You can select or deselect devices for reporting by using the filter icon.
Device Type:
- For the parent row: Name of the devices.
- For the child rows: The status of devices (Offline, Offline (Unplugged), No Network).
OS version: OS versions of the devices.

In-Service Dates:
- Start date: the day that the device was registered for the first time.
- End date: the day the device was unregistered.

Days Online: Actual online days within the selected date range.
Minutes Offline:
- Total minutes offline for each event - Offline, Offline (Unplugged), or No Network.
