= v1.2 | July 17, 2017
:navtitle: v1.2 | July 17, 2017

== Subscription Updates

Based on feedback from our customers, we have changed our subscription model to be more flexible and affordable. There are 3 subscription plans.

=== Trial plan

* 15-day trial with no credit card requirement
* Access to 30 real devices
* All features are included

=== Indie plan

* Buy minutes as you go and minutes never expire

=== Business plan

* Choose your own minutes and device slots
* Unused minutes will roll over to the next billing cycle
* Add more minutes and device slots any time

== Improvements

=== REST API

You can now use our API to seamlessly integrate Kobiton into your CI/CD workflow or development process. Check out the API documentation for more details.

=== Simulate device location (manual testing)

You can now change device location in Android devices. iOS support will be implemented in a future release.

=== Video recording (manual testing)

Kobiton automatically records your manual test session and the video can later be accessed in the Session Details page.

=== Others

* Reset orientation and remove Google account on Android upon session end
* Better handling of swiping gesture
* Many bug fixes and UI updates

== Customers update

*Upgrade notes for customers plugging in their own devices*

1. Android devices need extra setup so that they can be cleaned up properly upon session end, please follow the step of Change the Settings View Type into List View Type

2. Due to an upgrade on Auto Update feature, you need to install the latest version of Kobiton Desktop manually
** Quit the Kobiton Desktop App (if actively running)
** Login to https://portal.kobiton.com/login[Kobiton]
** Click Download to download the Kobiton Desktop App
** Install and launch it
