= v3.10.1 | March 29, 2021
:navtitle: v3.10.1 | March 29, 2021

== Updates to the Kobiton platform

=== Rerun Kobiton Scriptless automation on different device bundles via APIs

Device Bundles can now be set and run via APIs, giving users the ability to run revisit sessions on different devices without having to go into the Kobiton user interface.

=== Visual Assertions in Appium - Beta Version

You can now inject the same Visual Assertions from Kobiton scriptless automation into your existing Appium scripts. These scripts can then be executed on Kobiton real devices and can be run in parallel. This allows you to turn your Appium Functional Tests into a Functional and Visual Test. The Beta version supports content layout and content structure assertions and remediation.

Injecting these assertions is as easy as configuring your Desired capabilities, eliminating the need to script custom assertions, alter your source code, or leverage complex API calls in order to add Visual Testing to your mobile testing strategy.

You can learn more about Visual Assertions https://support.kobiton.com/hc/en-us/articles/360059106831[here].

== Bug Fixes and Enhancements

=== Open Appium export

* We've resolved some limitations preventing Export Appium scripts from properly running on Android devices.
