= v3.18 | January 15, 2022
:navtitle: v3.18 | January 15, 2022

== Device Support

We now support Android 12L!

== Portal Enhancements

On the Session Explorer, the metrics graphs may have displayed a blank space if a user was running a test, but no action was taken. To more accurately display the information on the graph, metrics will always display data, but the ranges will not be highlighted on the time graph. Instead, any highlights will be directly associated with an action.

== iOS Accessibility - voiceOver

voiceOver is a screen reader allowing users to know what is happening on their screen by giving an audible description of what's visually happening.

== Android Image Injection

Android apps that need to test images or QR codes, which now can be tested on Kobiton's Android devices. The added functionality will make it possible and easy to get your features tested without having to write scripts to accomplish it.

== Portal Updates

** Need the IP address or host name of your machine? That info will now be available right on the portal by clicking on More Info alongside the device UDID, IMEI, and serial number.
** Added Used by filter to the device list page which (when enabled) will display the username of the user who is using the device.
** If you have two tabs open on the same browser, closing one will no longer automatically log you out of the second page.
