= v3.22 | July 16, 2022
:navtitle: v3.22 | July 16, 2022

Earlier this year, we introduced you to a smarter, faster Kobiton with the easy-to-remember name: Kobiton

As we roll out this new Kobiton to existing customers, we will continue to offer some updates to our original Kobiton product—which we refer to as Legacy Kobiton. But the majority of our new features and updates will be found in the new Kobiton. So, when you review the release notes below, please keep in mind that some changes are only in Kobiton and some are in both Kobiton and Legacy Kobiton.

As always, we are here to help! If you have any questions, would like to update your Kobiton system, or get an understanding of what this all means for your Kobiton system, please contact your salesperson or send us an email at support@kobiton.com.

== What's new in both Kobiton and Legacy Kobiton

=== New iOS and Android support

The following OS versions are now supported:

** Android 13 beta 3.3

** iOS 15.6 beta 2

Note: We plan to support iOS 16 beta soon!

== What's new in Kobiton

=== Support for Espresso automation

You can now run Espresso automation on the latest version of Kobiton!

=== Introducing the System Latency report

With this release, we have introduced a new report that displays both a summary of an org's connection timing as well as details about user sessions. The goal is to assist orgs that notice latency in determining where the latency is occurring.

The System Latency report allows you to extract insights like the following: rendering time average, whether the slowness comes from a particular device-hosting machine/geographical region, in which session slowness occurs, and more.

Admins can find this report in the left hand navigation for reports.

=== Enable validations on scroll action

To date, Kobiton has performed validations such as Text, Text-color, and Visual only on captured screenshots from the Touch action. This enhancement adds the ability to analyze captured screenshots from the scroll action - we will compare the screen before and after the scroll to perform validations. More about validations can be found https://support.kobiton.com/hc/en-us/articles/360056070291-Validation-Remediation-[here].
