= v3.25 | November 19, 2022 (Legacy)
:navtitle: v3.25 | November 19, 2022 (Legacy)

Earlier this year, we introduced you to a smarter, faster Kobiton with the easy-to-remember name: Kobiton.

To further differentiate the new Kobiton from Legacy Kobiton, we are changing the release numbering. With this release, we have started using 4.0+ as the numbering for releases of the new Kobiton going forward, while Legacy Kobiton will continue with numbering starting with 3.25 and above.

The majority of our new features and updates will be found in the Kobiton 4.0+.

As always, we are here to help! If you have any questions or would like to update your Kobiton system, please send us an email at support@kobiton.com or contact your Account Executive.

== New iOS and macOS support

Legacy Kobiton 3.25 supports the following:

* iOS 16.1
* iPadOS 16.1
* macOS 13 Ventura for running Kobiton

For customers hosting Kobiton, please note that from iOS 16, all iOS 16 and higher devices must enable Developer Mode manually on physical devices. Previously, it was auto-enabled by plugging into Xcode.

Furthermore, please note that Xcode 14, released last month and necessary to support iOS 16 and above, no longer supports building apps for iOS 9 and iOS 10. With this change, Kobiton supports apps iOS 11 and higher.

== Additional enhancements and bug fixes

In addition to the above, this release includes some minor bug fixes, including a fix to the cleanup policy for iOS 15.6.1 and above when a user changes the device language to non-English during a manual session.
