= Kobiton 3.28 release notes (Legacy)
:navtitle: Kobiton 3.28 release notes

_April 1, 2023_

These release notes pertain to Legacy Kobiton 3.28. If you are using the new Kobiton, see the v4.3 release notes.

If you have any questions or would like to update your Kobiton system, please send us an email at link:mailto:support@kobiton.com[support@kobiton.com] or contact your Account Executive.

== API v2: new endpoints and enhancements

We have a number of additions and changes to API v2 as follows.

We added the following endpoints:

* Change uploaded application's default access level
* Get parsing state of an application version id
* Get devices with all specific tags
* Install an application on a device
* Uninstall an application on an API session

We made the following changes:

* Standardized the response format of APIs that update multiple objects to give meaningful error messages to each failed case
* Added two memory metrics: _memory free_ and _memory used_ to _Get device metrics for a session_ endpoint
* Included a running session’s log in the response of _Get a session_ endpoint
* Added the ability to access both API v1 and API v2 from within the Kobiton Cloud Portal

Check out the API v2 documentation site link:https://api.kobiton.com/v2/docs[here]. A quick introduction on how to navigate and try real API requests in this site, as well as the current API v2 limitations, can be found link:https://support.kobiton.com/hc/en-us/articles/6782179234445-API-v2[here].

link:https://api.kobiton.com/docs/?http#kobiton-api-v1-0[Kobiton API v1] is still available until further notice. We encourage you to start using API v2 as you add new test scripts and processes.

For endpoints in API v1 not yet offered in v2, continue to use API v1.

NOTE: Some API v2 endpoints are not applicable for Legacy devices as the endpoint's associated feature is only available for Kobiton 4+.

== Additional enhancements and bug fixes

In addition to the above, this release includes a number of minor bug fixes and enhancements to improve your day-to-day testing.
