= Text validation
:navtitle: Text validation

$DESCRIPTION$


== Text Validation

Scriptless Automation will point out exactly the difference in character changes between the baseline and screenshot as you can see this one. In the below example, there are some spacing errors caused by different screen resolution on two device types.

image:./guide-media/01GWDZ1TA9HZPD14VF4ZNHW19B[width=, alt="text-assertion.png"]

We provide you an ability to remediation submission so that you won't encounter this validation again.

|===
|Action|Description

|Adjust Comparison
|Currently, you can choose three comparison level that be suitable
to your expectation:
* Exact: Two texts (string) must be exactly the same.
* Beginning Text: Focus only the content on the first text, but still
raise the issue regarding the text-wrapping.
* Relaxed Placement: A part of Beginning Text and also ignore the
text wrapping

|Skip
|This action indicates that we will skip scanning the selected element.
|===

*Note*: The “Recommended” label will appear on the action that
is recommended by our system but of course you can select any options that you
want.
