= Contact support
:navtitle: Contact support

If you run into any issues, please reach out to our Support team by opening a support ticket from the portal or link:https://support.kobiton.com[support.kobiton.com].

However, we do encourage you to check out our documentation or look through our link:https://support.kobiton.com/hc/categories/360005234072-FAQs[FAQs] - you may just find the answers you need.

== Submit a ticket from the Kobiton portal

To open a support ticket from the Kobiton portal:

. Click on the Support icon, located at the top right of the portal, which will redirect you to support. kobiton. com
+
image:./guide-media/01GWE6J5MJ8Y3MZRDWP6JNHA3Z[alt="support-icon-on-kobi-portal.png"]

. Click on *Submit a request*
+
image:./guide-media/01GWEQS55XKCFNRER1Y7TRVB90[alt="submit-support-ticket.png"]

. Fill out the fields on the Submit a request form
.. *Your email address:* email address to contact you
.. *Subject:* detailed subject line
.. *Ticket Type:* select from the dropdown menu options
.. *Description:* a detailed description of the issue
.. *Attachments:* Images, videos and/or logs that will help explain the issue you're experiencing

. Click *Submit*
