= How to Open and Submit a Support Ticket
:navtitle: = How to Open and Submit a Support Ticket

If you run into any issues, please reach out to our Support team by opening a support ticket from the portal or link:https://support.kobiton.com[https://support.kobiton.com].

However, we do encourage you to check out our documentation or look through our link:https://support.kobiton.com/hc/en-us/categories/360005234072-FAQs[FAQs] - you may just find the answers you need.

=== Submit a ticket from the Kobiton portal

To open a support ticket from the Kobiton portal:

1. Click on the Support icon, located at the top right of the portal, which will redirect you to link:https://support.kobiton.com[https://support.kobiton.com]
+
image::/guide-media/01GWE6J5MJ8Y3MZRDWP6JNHA3Z[support-icon-on-kobi-portal.png]
+
2. Click on *Submit a request*
+
image::/guide-media/01GWEQS55XKCFNRER1Y7TRVB90[submit-support-ticket.png]
+
3. Fill out the fields on the Submit a request form

. *Your email address:* email address to contact you
. *Subject:* detailed subject line
. *Ticket Type:* select from the dropdown menu options
. *Description:* a detailed description of the issue
. *Attachments:* Images, videos, and/or logs that will help explain the issue you're experiencing

4. Click *Submit*