= Supported Versions
:navtitle: Supported Versions

The following information applies to the latest Kobiton Cloud.


|===
|*Name* |*Supported Versions for Kobiton*

|Android
|7 - 13

|iOS/iPadOS
|12.0 - 16.3.1

|Xcode
|10.0 - 14.2

|macOS
|Big Sur, Monterey, Ventura

|Appium
|Appium v1 and v2

|Chrome
|Supported

|JDK
|Oracle JDK 1.8

|SDK
|Min. Java version: '1.8.x', Min. Adb version: '1.0.41'
|===

Kobiton officially supports Google Chrome and recommends Chrome for the best Kobiton Portal experience. Lightning mode can be enabled on some other browsers: Safari, Opera, Microsoft Edge, and the latest version of Brave.

[.fabric-text-color-mark]
.For customers hosting Kobiton, please note that from iOS 16, all iOS 16 and higher devices must enable Developer Mode manually on physical devices. Previously, it was auto-enabled by plugging into Xcode.

[.fabric-text-color-mark]
Furthermore, please note that Xcode 14, which is necessary to support iOS 16, no longer supports building apps for iOS 9 and iOS 10. With this change, Kobiton currently supports apps iOS 11 and higher.

For those hosting devices, please be sure to review Apple's minimum Xcode versions required for iOS versions: link:https://developer.apple.com/support/xcode/[https://developer.apple.com/support/xcode/]
