= How to get the logs of the Standalone environment for troubleshooting

== Gather logs on the Dell server

[NOTE]
====
These instructions apply to v4.11.2S and later.
====

Remote access to the Mac Mini inside the Kobiton cart.

Launch the Terminal app, access the Dell server by running the below command (replace `<Dell’s IP>` with the private IP of the Dell server):

[source,shell]
----
ssh kobitonSupport@<Dell's IP>
----

Please contact Kobiton to get the password of `kobitonSupport` to access the machine.

Switch to the `root` user:

[source,shell]
----
sudo su -
----

The shell becomes the remote shell on the Dell server, then run the below command to collect all necessary Dell server logs:

[source,shell]
----
bash /ml/var/kobiton-op/k3s/scripts/utils/collect-logs.sh
----

[IMPORTANT]
====
Note: the above will collect logs in 3 days by default. You specify how long you would like to collect using the below (for 7 days):

[source,shell]
----
bash /ml/var/kobiton-op/k3s/scripts/utils/collect-logs.sh 7
----
====

Wait a while for the script to run. When it is finished, the exact path of the logs file will be printed out like below:

[NOTE]
====
✅ Logs collection completed. You can find the logs file at `/var/log/kobiton/k4s-20240410-034416.tgz`
====

In the above example, the path of the log file is `/var/log/kobiton/k4s-20240410-034416.tgz`. Note down this path.

Go back to the Terminal app (in the Mac Mini), open a new Terminal window.

Run the below command to copy the file from the Dell server to `/Users/deviceconnect/Downloads/` in the Mac Mini (replace `<Dell’s IP>` with the private IP of the Dell server).

Type the password if the server requires it.

[NOTE]
====
Replace `/path/to/log/k4s-log.tgz` with the exact path to the actual log file. Example:

[source,shell]
----
scp kobitonSupport@192.168.35.75:/var/log/kobiton/k4s-20240410-034416.tgz /Users/deviceconnect/Downloads
----
====

Copy the log file in the Mac Mini to your computer and send the log file to Kobiton support.

== Working with large log files

[NOTE]
====
After collecting Dell logs, some customers may restrict file transfers if the file size exceeds 1GB. To work around this, we ask customers to split large files into smaller chunks, send them separately, and then reassemble them on the Kobiton side.

Typically, Mac Mini logs do not exceed 1GB, so this section is generally not applicable. However, it can be used if needed.
====

=== Split a large Dell log file into smaller files

Assume that you have transferred the Dell log file to the Mac Mini at `/Users/deviceconnect/Downloads/k4s-20240410-034416.tgz`. In the below commands (in Terminal in Mac Mini), please replace `k4s-20240410-034416.tgz` with the correct filename.

Split the logs file into smaller chunks:

[source,shell]
----
split -b 900M k4s-20250205-024634.tgz k4s-20250205-024634-
----

* `-b 900M`: Specifies the size of each split file (900 Megabytes in this case). *Adjust this to stay within the required file size limit.*
* `k4s-20240410-034416.tgz`: The large log file we want to split. *Replace this with the correct filename.*
* `k4s-20240410-034416-`: The prefix for the names of the smaller files. You can name it whatever you want.

This command will create files named `k4s-20250205-024634-aa`, `k4s-20250205-024634-ab`, `k4s-20250205-024634-ac`, etc. Send all those chunks to Kobiton support.

=== Concatenate the files

To concatenate the smaller files back into one large file, use:

[source,shell]
----
cat k4s-20250205-024634-* > k4s-20250205-024634.tgz
----

* `k4s-20250205-024634-*`: matches all files that start with the prefix `k4s-20250205-024634-` (*the prefix you used when splitting the file*).
* `k4s-20250205-024634.tgz`: the filename for concatenated output. *Note that the extension needs to be the same as the original file, i.e. `.tgz`.*

=== (Optional) Verify the concatenation

To ensure the concatenation was successful, you can compare the checksum of the original and concatenated files. The output of both commands below needs to be the same:

[source,shell]
----
md5 -q original_log_file.tgz
md5 -q concatenated_log_file.tgz
----

== Gather logs on the Mac Mini server

1. Use the Portal or deviceConnect Viewer: link: https://docs.kobiton.com[Retrieve deviceConnect logs :: Kobiton Docs]
2. Alternatively, use the command line interface on the Mac Mini host:

Launch the Terminal app on the Mac Mini. Create a log package directory by using the below command:

[source,shell]
----
rm -rf ~/log; mkdir ~/log
----

Copy deviceConnect and deviceShare configuration to the log package directory:

[source,shell]
----
cp /usr/local/deviceconnect/dc.ini \
/usr/local/deviceconnect/register-consul.sh \
/usr/local/kobiton/deviceshare/deviceshare_signing*.log \
/usr/local/kobiton/deviceshare/deviceshare_config.toml ~/log
----

Copy the deviceConnect logs to the log package directory:

[source,shell]
----
cp -r /usr/local/deviceconnect/Logs ~/log/dC-Logs
----

Compress the log package directory:

[source,shell]
----
tar zcf /Users/deviceconnect/Downloads/mac-server.tgz -C ~/log .
----

Send `/Users/deviceconnect/Downloads/mac-server.tgz` to receiver.
