= Prepare an iOS/iPadOS device for hosting
:navtitle: Prepare an iOS/iPadOS device for hosting

Learn how to prepare iOS/iPadOS devices to be utilized with Kobiton 4.0 and later.

Different models of devices and versions of iOS/iPadOS may have different layout for settings and options. Refer to Apple's official manual if you cannot find the options mentioned in this document.

== Before you start

You'll need the following:

* An iOS/iPadOS device
* For iOS/iPadOS 16 and later devices, a Mac machine with Xcode installed.

== Turn off auto update

Open the Settings app.

Tap *General* -> *Software Update* -> *Automatic Updates*.

Turn off *Install iOS Updates*.

Go back to the Settings screen and tap *App Store*.

Under *Automatic Downloads*, turn off *App Updates*.

== Turn off passcode, if one is set

In the *Settings* app, select *Face ID & Passcode* or *Touch ID & Passcode*.

Enter the current passcode.

Tap *Turn Passcode Off*.

Enter the current passcode again to turn off passcode.

== Turn on developer mode and UI automation]



