= User roles
:navtitle: User roles

This section walks users through the introduction of Team Role, how to assign users and modify permissions.

The Team Role determines the access rights and privileges that members of the team have when interacting with Kobiton's system. There are three levels of Team Role:

* Team Owner: the one who created a team or assigned by the Org Owner as the Team Owner.
* Team Admin.
* Team Member.

[NOTE]
====
* Available accounts belong to at least a Team and a role.
* When a new user is added to a Team, they are automatically assigned as a Team Member.
* Team Admin can only access the Team they are assigned to, while The RBAC Admin [a][b] can access all teams in the organization.
====

== Team Permissions

Below is the mechanism of editing/accessing to Teams and its related functions:

* Team Owner:
- Can access Org Management and see the list of the Teams that this user is a Team Owner of that Team. Unless they have the RBAC Admin role, they cannot access other Teams and use Roles, Users, and Devices features of the Org Management..
- Can edit all of the info (Details, Settings, Users, Permissions, Devices) in the team.

* Team Admin: Only assign users with the role: Team Member
- Can access Org Management AND see the list of the Teams that this user is a Team Admin of that Team.
- Can edit all of the info (Details, Settings, Users, Permissions, Devices) in the Team BUT can't assign users with roles: Team Owner Or Team Admin (only Team Owner can do this) → Team Admin can assign Team Member to the Team only

* Team Member:
- Can access Org Management AND see the list of the Teams that this user is having the permission: "settings.modify" in that Team.
- Can edit only 2 tabs: Details, Settings if this user is having the team role permission: "settings.modify" in that Team

The permissions of each Team Role can be described as follows:

[cols="5", options="header"]
|===
|Permission codes |Descriptions |Team Owner |Team Admin |Team Member
|settings.modify |Can edit the info in the details tab (Name, Description, Assertion value). Can edit the settings (private test mode, cleanup policy) in settings tab. |Always ON |ON |OFF
|members.modify |Assign/ Unassign members to the team. Be able to grant the permission (enable/disable permission) for "Team members" in the team. |Always ON |ON |Always OFF
|devices.modify |Can Assign/ Unassign devices to the team. |Always ON |ON |Always OFF
|member.make_admin |Can choose the role of the user will be "Team Admin" or not. Only Team Owner (s) have this permission |Always ON |Always OFF |Always OFF
|member.make_owner |Can choose the role of the user will be "Team Owner" or not. Only Team Owner (s) have this permission |Always ON |Always OFF |Always OFF
|apps.unassigned |Can Unassign an app from a team. Only Team Owner (s) have and grant this permission for Team Admin |Always ON |OFF |Always OFF
|===

== Modify permissions

To modify Team Role permissions, go to Org Management, select Teams tab.

1. Click the Team's name to direct to the Team Details page, then click the Permissions tab.
2. Turn on/ off the toggle to enable/ disable permissions for Team Owner, Team Admin, and Team Member.
3. Click Save.

NOTE:

* Team Owner: has all permission by default.
* Team Admin: editable only: "settings


* All users can access device bundles but only users with the org_management.modify permission can add, edit and delete device bundles.
