= Transfer an organization
:navtitle: Transfer an organization

Learn how to transfer an organization to an admin in your organization. You can either transfer the organization and reassign yourself as an admin, or transfer the organization and remove yourself completely.

[NOTE]
Only the current owner can transfer an organization. If the current owner no longer works at your company, reach out to support@kobiton.com.

== Transfer organization and reassign your account

In *Org Management*, select *Users*.

image:<NEW-IMAGE>[width=, alt=""]

Search for the user you want to transfer the organization to, then select their username.

image:<NEW-IMAGE>[width=, alt=""]

Select *Make Organization Owner*.

image:<NEW-IMAGE>[width=, alt=""]

Confirm ownership transfer. The current owner will become an admin.

image:<NEW-IMAGE>[width=, alt=""]

== Transfer organization and disable your account

In *Org Management*, select *Users*.

image:<NEW-IMAGE>[width=, alt=""]

Search for your account, then select your username.

image:<NEW-IMAGE>[width=, alt=""]

Select *Transfer and Disable*.

image:<NEW-IMAGE>[width=, alt=""]

Confirm ownership transfer and disable your account:

image:<NEW-IMAGE>[width=, alt=""]
