= Transfer organization
:navtitle: Transfer organization

$DESCRIPTION$

== Transfer Organizational Owner role to another user

Every organization has an Org Owner, who is considered as the master of Admin. This role is associated with all admin permissions and the abilities to view, edit detailed subscription information. The Transferring Owner role will be executed from the Users tab of the Org Management.

=== Transferring Owner role without disabling/ removing current Org Owner

1. Go to Org Management, select Users tab.
2. Search for the user you want to make as a new Org Owner.
3. Click on the username.
4. Click the Make Organization Owner button. A dialog displays to confirm your action. Click Transfer to proceed.

Once the Org Owner is transferred, the old owner becomes a normal admin and the selected user will change to the Owner role with associated permissions.

[NOTE]
====
Only admin users can be selected as the new Org Owner.
====

=== Transferring Owner role after disabling/removing the Org Owner

1. Go to Org Management, select Users tab.
2. Click on Org Owner's username.
3. In the User Details page, click Disable.
4. A dialog is prompted to ask who would be selected as the new Org Owner. Choose an option in the drop-down list. Click Transfer and Disable/ Transfer and Remove to proceed.

Once disabled, the user will immediately be logged out.

[NOTE]
====
Only Org Owner can disable herself/himself and transfer the owner role. Normal users will encounter the below message when trying to disable an Org Owner.
====
