= Upload a project to your cloud VCS
:navtitle: Upload a project to your cloud VCS

Learn how to upload a project to your cloud version control system (VCS), like link:https://github.com/about[GitHub] or link:https://about.gitlab.com/[GitLab], so you can integrate the following tools with Kobiton:

* xref:integrations:azure-devops/index.adoc[]
* xref:integrations:bitrise/index.adoc[]
* xref:integrations:buildkite/index.adoc[]
* xref:integrations:jenkins/index.adoc[]
* xref:integrations:testrail/index.adoc[]

== Before you start

You'll need to complete the following:

* Create xref:automation-testing:scripting/auto-generate-an-appium-script.adoc[or generate] a test script with xref:automation-testing:capabilities/auto-generate-capabilities.adoc[Kobiton capabilities].
* Verify SSH has been enabled for your cloud repository account.

== Open the project

Open the terminal and navigate to your project's root directory.

.Example
[source,shell]
----
cd ~/my-app/
----

If your project is already initialized as a git repository, you can xref:_upload_the_project[upload your project files].

== Optional: initialize as a git repository

If your project hasn't been initialized as a git repository yet, run the following commands to create your first commit.

[source,shell]
----
git init -b main
git add --all
git commit -m "First commit"
----

[#_upload_the_project]
== Upload the project

[tabs]
======
GitHub::
+
--
link:https://github.com/cli/cli#installation[Install `gh`], GitHub's command-line tool, using your operating system's package manager.

.Example
[source,shell]
----
brew install gh
----

Enter the following command and follow the prompts in your terminal.

[source,shell]
----
gh repo create
----

link:https://github.com/login[Open GitHub] and confirm your source files have been successfully uploaded.

image:$OLD$[width="",alt=""]
--

GitLab::
+
--
Use the `--set-upstream` flag to push the commit to GitLab. Set `<namespace>` to a link:https://docs.gitlab.com/ee/user/namespace/[personal or group namespace] and `<myproject>` to a short, descriptive project name.

.Example
[source,shell]
----
git push --set-upstream git@gitlab.example.com:<namespace>/<myproject>.git main
----

link:https://gitlab.com/users/sign_in[Open GitLab] and confirm your source files have been successfully uploaded.

image:$OLD$[width="",alt=""]
--
======
