= Intelligent Quality Suite
:navtitle: Home
mermaid-background: transparent

Kobiton's [.product-name]#Intelligent Quality Suite# contains a suite of artificial intelligence-backed capabilities to help the Manual Tester and Automation Engineer improve productivity. It is comprised of four main capabilities:

. [.product-name]#Appium Export#: Export an Appium Script from a manual or automation session;
. [.product-name]#Validations#: Perform inferred validations to complement your explicit assertions;
. [.product-name]#Scriptless#: Rerun a manual or automation session without a script; and
. [.product-name]#flexCorrect#: Preven Appium-based scripts from failing with self-healing.

== Nova

[.product-name]#Nova# is Kobiton's artificial intelligence engine and is used to power [.product-name]#Intelligent Quality Suite#. You won't explicitly see [.product-name]#Nova# in the Kobiton user interface; [.product-name]#Nova# is behind the scenes working its magic to increase your mobile app quality and improve your productivity.

This video describes how artificial intelligence is used in testing or you can take the full Artificial Intelligence in Testing course.

[mermaid,export_flow,format=svg]
----
include::partial$diagrams/export_flow.mmd[]
----
