= Ignore remediation
:navtitle: Ignore remediation

When you encounter a non-annotated remediation and sure that this is an issue from the application and it is required to fix for the next release, then you use the ignore to exclude an execution out from the Scriptless Automation process. Therefore, you will not encounter the remediation again.

image:./guide-media/01GWEFXHEQ3Q59HAMA1EYDH1XA[width=, alt="ignore-remediation.png"]

[width="60%",frame="all",options="header"]
|===
| Values | Description

| Once
| This option is to reproduce this issue, after submitted, an execution will be re-run and still raise the remediation if the issue still happens.

| For 15 days
| An execution will be excluded from the Scriptless Automation process for 15 days.

| Indefinitely
| An execution will be excluded from the Scriptless Automation process forever.
|===

Moreover, you can access back any ignored remediation to modify the selected ignored value.

image:./guide-media/01GWE6JYR36D4D6PWBXMZCR2GN[width=, alt="ui-remediation2.png"]
