= Automation test script setup
:navtitle: Automation test script setup

Introduction.

== Setup

To be able to execute automation test scripts using the Azure DevOps Kobiton Extension, your Git repo needs to contain automation test scripts, with environmental variables to allow the extension to access test scripts.

. *Kobiton API credentials* +
For automation test script, please set your Kobiton *Username* and *API Key* in your automation test setting code like below: +
In your automation test settings, set your Kobiton Username and API Key:
+
[source,java]
----
String kobitonServerUrl = "https://" + System.getenv("KOBITON_USERNAME") + ":" + System.getenv("KOBITON_API_KEY") + "@api.kobiton.com/wd/hub";
----

. *Kobiton Devices*
* When using Kobiton cloud devices, set the deviceGroup field in your desiredCaps to: KOBITON.
* To use Kobiton Cloud devices, set device values in desiredCaps as:
+
[source,java]
----
capabilities.setCapability("deviceGroup", "KOBITON");
capabilities.setCapability("deviceName", System.getenv("KOBITON_DEVICE_NAME"));
capabilities.setCapability("platformName", System.getenv("KOBITON_DEVICE_PLATFORM_NAME"));
----

. *Applications* +
Set the *app* field in your *desiredCaps* with the following environment variables:
+
[source,java]
----
capabilities.setCapability("app", System.getenv("KOBITON_SESSION_APPLICATION"));
----

== Additional options

Default values can be hard-coded for the following parameters to avoid failing test cases.

* *KOBITON_USERNAME:* Kobiton Username set in the Azure Service connection
* *KOBITON_API_KEY:* Kobiton API Key set in the Azure Service connection
* *KOBITON_DEVICE_NAME:* Value of the device name in the Kobiton Extension Task
* *KOBITON_SESSION_PLATFORM_VERSION:* Value of the device platform in the Kobiton Extension Task
* *KOBITON_DEVICE_PLATFORM_NAME:* Value of the device platform, Android / iOS, in the Kobiton Extension Task
* *KOBITON_SESSION_APPLICATION:* App value in the Kobiton Extension Task

To view a sample project, click link:https://github.com/kobiton/samples/blob/master/java/java_testng_junit/src/main/java/kobiton/com/testng/azureTestNG.java[here].

Once you have your Git repository configured, let's move to the next step.
