= Create a profile
:navtitle: Create a profile

This section guides users to create a new account and manage account profile on Kobiton portal.

== Register a trial account
1. On kobiton.com, click *Get Started/ Try Kobiton*.

2. Click *Get Started* under *Request a Free Trial*.

3. Fill in the required fields:
* First name & Last name

* Email

* Primary area of interest to discuss with Kobiton

* Message

4. Click *Submit*.

NOTE: Kobiton’s team will contact users for a free trial for 14 days.

Once users are set up a free trial, on portal.kobiton.com, fill in below information:

1. First name

2. Last name

3. Username (username must be between 5 and 32 characters).

3. Email

4. Password/Confirm password (The password must contain at least 1 lowercase letter (a-z); 1 uppercase letter (A-Z); and 1 digit (0-9)).

5. Phone number

6. Check reCapTcha and agree to the License Agreement.

7. Click *Register*.

== Manage user profiles

=== Change password

1. Click the account icon, go to *Profile*.
+
2. Scroll down to *Change password*.
+
3. Type current and new passwords.
+
NOTE: Passwords must be between 5 and 32 characters and contain at least 1 lowercase letter: a-z; 1 uppercase letter: A-Z; and 1 digit (0-9)
+
4. Retype new password.
+
5. Click *Update password*.

=== Change display name

1. Click the account icon, go to *Profile*.

2. Type a new First name & Last name.

3. Click *Update Profile*.

=== Set Default Team
The Default Team is a team new users automatically assigned to. In addition, the Default Team is also where automation sessions will be stored.

To set or change the Default Team:

1. In the *Default Team* section on *Profile*, select a team from a drop down list.

2. Click *Update Team*.

Learn more about Teams on Kobiton _here_.

=== Set time zone

1. In the *Time Zone* section on *Profile*, select a time zone from the dropdown list.

2. Click *Update Settings*.

=== Set session timeout

Session timeout is the set time (in minutes) users can remain idle. Users can configure session timeout by:

1. In the *Session Timeout* section on *Profile*, select an idle timeout (in minutes) from the drop down list.

2. Click *Update Timeout*.
\

NOTE: Users can tick/ untick the box “Automatically quit a manual session after exceeding the idle”.
