= Get started
:navtitle: Get started

Welcome to Kobiton.
Give a little pitch of all the things that are possible.
Give an overview of what will be accomplished in the get started doc.

== Before you start:

If I’m the org owner, I should probably invite some folks first.

If I’m not the org owner, I should make sure I’ve been invited.

== Find a device:

Guide them to a public device assigned to their team.

This will not show all the different ways you can find a device but that page will be linked in a note.

== Launch a manual session:

Open the device overview, look at a couple settings, select launch device.

== Install an app:

(Do all instances of Cloud Kobiton come preinstalled with some kind of test app they can mess around with? If not, can we embed .ipa or .apk for the customer to download and install during session).

Guide them to install app.

== Interact with the device:

Swipe, touch, etc. Keep it simple.

== Close the session:

Guide them to close session.

== Find your session:

Guide them to find session and open session overview.

== Review your session:

Highlight a couple session analytics.

Make a note to “Session Explorer” to show value.

== Next steps

Review what was accomplished.

Give some links for next steps.
