= Get started
:navtitle: Get started

Welcome to Kobiton.

== Before you start

* If I’m the org owner, I should probably invite some folks first.
* If I’m not the org owner, I should make sure I’ve been invited.
* Download test app. https://developer.apple.com/tutorials/sample-apps/dateplanner

== Find a device

Guide them to a device assigned to their team.

[NOTE]
This will not show all the different ways you can find a device but that page will be linked in a note.

== Launch a session

Open the device overview, look at a couple settings, select launch device.

== Install an app

Guide them to install app.

== Test the app

Swipe, touch, etc. Keep it simple.

== Exit the session

Close session.

== Review the session

Find session and open session overview.

[NOTE]
This will not show all the different ways you can find a session but that page will be linked in a note.

Highlight a couple session analytics.

[NOTE]
Session Explorer.

== Next steps

Review what was accomplished.

* xref:automation-testing:index.adoc[Automation testing]
* xref:scriptless-automation:index.adoc[Scriptless automation]
* xref:debugging:index.adoc[virtualUSB]
* xref:session-explorer:index.adoc[Session Explorer]
