= Setting up profiles
:navtitle: Setting up profiles

== Changing password

1. Click the account icon, go to *Profile*.

2. Scroll down to *Change password*.

3. Type current and new passwords.
+
_Note: Password must be between 5 and 32 characters and contain at least 1 lowercase letter: a-z; 1 uppercase letter: A-Z; and 1 digit (0-9)._

4. Retype new password.

5. Click *Update password*.

== Changing display name

1. Click the account icon, go to *Profile*.

2. Type your new First Name and Last Name.

3. Click *Update Profile*.

== Setting Default Team

1. In the *Default Team* section on *Profile*, select a team from a drop down list.

2. Click *Update Team*.

== Setting time zone

1. In the *Time Zone* section on *Profile*, select a time zone from the dropdown list.

2. Click *Update Settings*.

== Setting session timeout

1. In the *Session Timeout* section on *Profile*, select an idle timeout (in minutes) from the drop down list.

2. Click *Update Timeout*.
+
_Note: Tick on the box "Automatically quit a manual session after exceeding the idle timeout" if needed._

