= v3.9 | January 25, 2021
:navtitle: v3.9 | January 25, 2021

== Major updates to the Kobiton platform

=== Kobiton Administration and org management updates

* *Kobiton org management via your IdP*: Admins using SSO to manage their users can now manage their Kobiton org and users via their IdP instead of the Kobiton Org Management within the Kobiton UI.

* *Support for Jira Custom Fields*: Kobiton now supports Jira Custom Fields. Please see the below chart for information around any limitations:

[cols="1,1,1,4"]
|===
| Supported Fields | Login Jira with Username, API token | Login Jira with Oauth2 | Limitations

|Description
|Yes
|Yes
|No

|Labels
|Yes
|No
|Support this field if user login by Basic Authentication

|Sprint
|Yes
|No
|- Support this field if user login by Basic Authentication +
- Not support this field for Scrum project type +
- Permission required

|Story Point Estimate
|Yes
|Yes
|No

|Reporter
|Yes
|Yes
|No

|Attachments
|Yes
|Yes
|No

|Linked Issue
|Yes
|Yes
|No

|Flagged
|Yes
|Yes
|No


|Environment
|Yes
|Yes
|No

|Components
|Yes
|Yes
|No

|Fix Version
|Yes
|Yes
|No

|Priority
|Yes
|Yes
|No

|Severity
|Yes
|Yes
|No

|Defect Escape
|Yes
|Yes
|No

|QA Incharge
|Yes
|No
|Support this field if user login by Basic Authentication

|Due Date
|Yes
|Yes
|No

|Start Date
|Yes
|Yes
|No
|===

=== Major Device Lab Management and Portal updates

* *Payload capture for iOS and older Android devices*: Kobiton now supports Payload capture for iOS devices (iOS 9-12) and older Android devices (Android 7 & 8)
* *New UI for the Kobiton Manual Session*: We have changed the UI for the manual session. All actions and gestures will now be on the left side of the session.

=== Major Kobiton Intelligent Quality Suite Updates

* *Scriptless automation for Webview and hybrid applications on iOS*: We have enhanced our AI’s ability to create and execute scriptless test automation for Webview and hybrid applications on iOS.
* *Teach your AI to scroll*: On the blocker remediation page, you can now scroll in order to find the correct element when training our AI to best execute your scriptless tests.
* *Use API to create a new dataset for the Data-Driven Testing*: You can now create or edit a dataset by using an API, either by commandID or an element property. Click https://api.kobiton.com/docs/#data-driven-testing/[here] for more information.
* *Provide instructions for backup devices for scriptless automation executions*: You can now use an API to direct Kobiton scriptless automation to execute on "backup" devices if your originally chosen device is not available. That way, if a given device is not available, our scriptless automation can still run on these backup devices. Click https://api.kobiton.com/docs/#kobiton-scriptless-automation/[here] for more information.
* *Provide instructions for Dynamic Content (Beta)*: You can now provide instructions to our AI to find the next best matching element when executing scriptless automation on apps with dynamic content. This will help ensure that your test automation runs, even if dynamic content presents a situation where exact elements are difficult and/or impossible to find. This is the beta version of this new feature, and we will release the full version in a future release.

[NOTE]
To enable this feature, you need to access the IQS Plan, open the Settings tab & update the configuration.

=== Bug fixes/enhancements

* *Session Explorer slider*: When zooming into the Session Explorer timeline:
** The slider now stands still
** The vertical scroller stays still

* *Enhanced Device Log search on the manual session*: Prior to this release, using the device log “search” capability would highlight the device logs that contain the elements that you were searching for while still returning device logs that might not contain the searched-for element. With this release, if you search for a certain element, the search will return only the logs that contain that element.
* *Device Health Check for network*: Testers who are looking to run test automation can now run a Device Health check prior to executing automation to confirm that their device is connected to the internet prior to test execution.
* *Wifi shut-off issue for iOS 12.2 and below*: We have fixed an issue that caused wifi to be automatically turned off after sessions were exited for devices running iOS 12.2 and below.
* *We have improved the app repo loading performance*.
* *Element validation highlighting for Data-driven testing*: Now, when validating the existence of an element via Kobiton Data-driven testing, that element will be highlighted within the DDT UI.

=== Added support

* *Support for MacOS Big Sur*: The Kobiton desktop app will be able to run properly on the latest MacOS BigSur.
* *Support for Chrome 87*: Kobiton now supports Chrome 87.
