= v3.9.1 | Feb 08, 2021
:navtitle: v3.9.1 | Feb 08, 2021

== Major Updates to the Kobiton Platform

=== Kobiton Intelligent Quality Suite and Scriptless Automation

* Appium Export on your manual session: You can now generate and export Appium scripts from a completed manual session, making test automation authoring and execution easier, faster, and more efficient.

== Bug fixes/enhancements

=== Kobiton Intelligent Quality Suite and Scriptless Automation

* *11962*: The issue causing export Appiums scripts to sometimes run the incorrect coordinates on Android devices has been resolved.
* *11565*: The issue preventing vertical swipe on the horizontal swipe part of the mobile browser has been resolved.
* *11401*: We fixed an issue with scriptless automation that caused a revisit session to perform the incorrect action due to the keyboard being hidden.

=== Kobiton Device Lab Management and Portal

* *11955*: We fixed the issue causing application updates to fail because apps exceeded the character limit.
* *11954*: To prevent high CPU usage, the “remove-org-member” function has been removed.
* *11868*: During the session initialization phase, logs have been added to the runner when a session attempt fails.
* *11844*: The issue causing devices to not return online after a Hub restart has been resolved.
* *11842*: The checkbox custom field is now posting data when integrated through Jira.
* *11828*, *11910*, *11941*, *11849*: On the Kobiton UI, the banner warning of exceeding public usage minutes will no longer display for private device users.
* *11808*: The issue preventing non-synched devices from matching desired capability values has been resolved.
