= v3.10 | March 8, 2021
:navtitle: v3.10 | March 8th, 2021

== Kobiton Device Lab Management

=== Kobiton Intelligent Quality Suite and Scriptless Automation

* *Added iOS support:* Kobiton now supports iOS 14.4 devices in addition to iOS beta 14.5 Beta 1 using XCode 12.5 Beta 1.

=== New Front-end Performance Testing Features

* *Response time chart in the Session Explorer’s Insights Panel:* We continue to introduce new front-end Performance Testing features. With this release, we now capture and visualize response time in the Session Explorer’s Insights Panel.

* *Payload Capture for iOS devices:* We now support Payload capture for iOS native applications in addition to the pre-existing support for Android native and web apps and iOS web apps. For information around how to enable Payload Capture on your Kobiton devices, please reach out to the Kobiton Support team.

=== New Scriptless Automation features

* *New API capabilities:* with this March release, users can use API’s to:

** Trigger scriptless tests using a device’s deviceBundleID. This additional parameter will give users the ability to specify the devices to run revisit executions on.
** Notify users of any crashes that occurred during a Kobiton scriptless automation execution that are caught by our basked-in Crash assertions. This new feature will detect crashes and send a notification back towards their CI/CD pipelines with a deep link to the exact moment of failure.

== Bug Fixes and Enhancements

=== Kobiton Intelligent Quality Suite and Scriptless Automation

* Once a Scriptless test has been triggered, users will be able to see Execution List updates in real-time, eliminating the need to check for email updates or constantly reloading the Execution List page.
* Metrics on the Session Explorer have been converted from tabs across the screen to a dropdown menu, giving users a much more organized UI experience.
* Users can now search for an already uploaded app with userName on apps that have been uploaded by another user.

* On the Export Appium Script manual testing feature:
** element selectors will properly interact with those elements
** ensure correct navigation within a script

=== Device Lab Management

* The issue preventing devices from launching a manual session after a hub restart has been corrected.
