= v3.13 | July 12, 2021
:navtitle: v3.13 | July 12, 2021

== Updates to the Kobiton Platform

=== Org. Management

In our May 31st release, Kobiton introduced new feature Role-based Access Control (RBAC): a highly customizable, role-based system giving org. owners and admins a variety of permissions to be added to new and existing roles that can further be assigned to users. Kobiton has aimed to continue delivering additional enhancements to RBAC to supplement our users' needs to meet more granular control of org. management. In this release, we will be bringing two existing org. management features, Private Testing Mode and Cleanup Policy, to the team (group) level.

* *Private Testing Mode:* Previously, private testing mode was offered at the organization level, as well as at the individual level. Now, private testing more is offered at the team level of an organization. Users with admin. permissions may enable or disable private testing mode for team(s).
** Enabled: Users of that team will experience private testing mode when testing on private devices during a manual session and may not disable the feature.
** Disabled: Users of that team will not experience private testing mode when testing, however, they may enable/disable private testing mode on an individual basis when testing on private devices during a manual session.
* *Cleanup Policy:* Previously, cleanup policy was offered at the organization level. Now, cleanup policy will be offered at the team level. Users with admin permissions may configure cleanup policy for team(s) and customize each cleanup policy as they see fit.

* *Additional updates to RBAC include:*
** Improved performance and enhanced UI/UX to benefit user experience
** Add a deleted account back to an organization via email invite: Admins of an organization will now have the ability to invite users of deleted accounts back to their original organization or to other organizations by sending an email invitation.

== Added Security Measures

Kobiton takes security seriously and continues to work diligently in delivering features to keep sensitive data safe and secure amongst other users of the same team or organization when testing. In this release, two new features have been delivered to help protect sensitive data in manual and scriptless automation:

* *Set and encrypt full text in manual session:* In a manual session, Kobiton will now have an option button to indicate to users to input sensitive data they wish to encrypt when testing ie passwords. Uses can input the data that they want to hide in the Manual session outside the device screen and the full text will be encrypted within session details of the manual session.

* *Obfuscate sensitive data in data-driven testing (DDT) tab and session details of Revisit sessions:* During a manual session, users now have the option to mark set_text commands of data that are sensitive, such as passwords. Thereafter, Kobiton will display these values as asterisks characters in the data-driven testing tab and in session details of revisit sessions. Other users within the same team/ organization will not be exposed to set sensitive data when accessing session details/DDT tab, thus ensuring sensitive data does not get leaked.

== Kobiton Intelligent Quality Suite and Scriptless Automation

* *Enhanced Session Snapshots:* In Kobiton's May 31st release, we delivered Session Snapshots that helps provide transparency into the test case creation after a manual session by rendering screenshots per test step along with highlighting elements on the page that were interacted with. Now, Session Snapshots will also render the same functionality for revisited sessions, giving users even more transparency in their testing efforts. Even further, in cases where the revisit status is blocked or has failed the next test step, Session Snapshots will display the error message and when clicked upon will navigate users to the resolution page to resolve the blocker.

* *Enhanced Session List:* Last release, Kobiton was elated to deliver our new session list with its amazing search capability. With this release, we optimized session list response time to be even faster in search returns, and Kobiton also delivered the ability to use copy/paste commands in the search bar.

* *Bypass one-time password (SMS & Email):* One-time password security measures can cause disruption in testing. Kobiton now handles both SMS and email one-time password events to help facilitate our user's testing and minimize test blockers.
** SMS one-time password: When a user runs an exported appium script that includes bypassing SMS one-time password, Kobiton will call a 3rd party, Plivo, to receive the passcode and bypass the login step.
** Email one-time password: When running scriptless automation that requires email input that kicks off one-time password event, Kobiton will input an autogenerated email to receive the one-time password and will automatically provide the one-time password when executing the session.

* *Text Assertions in Appium Export:* Kobiton provides text assertions when running a manual session. Users may use the created session as scriptless or export an appium script to be used as script-based automation. Kobiton will now offer new desired capability to implement text assertions within the exported appium script, so that users may benefit from text assertion feature within their script-based automation.

== Device Lab Management

* *Added Version Support:* Kobiton now supports iOS 14.7 beta with Xcode 12.5; iOS 15 beta with Xcode 13 beta; and Android 12 beta.

* *Filtering of Device Page:*
** Sorting Devices on Device List Page: Users may now sort devices, within the device list page, by device type (android or iOS icons), OS version, Device Name, and Friendly Name. Devices will display in ascending order from latest OS version to oldest OS version with subversions included.
** Hide Unplugged Devices: When a user filters offline devices, there is now a new option 'Hide Unplugged Devices' that will hide devices that are not plugged in and will display devices that are offline, but still plugged in.

* *Softbooking - History API:* To give more visibility into which users made softbooking reservations for a private device, Kobiton has implemented an API endpoint to call that will return device reservation history from all users within a specific period of time.

* *Notifications:* Kobiton is working hard to bring notifications regarding public devices faster to our users. In regard to public devices that do not have an internet connection, Kobiton has created a new method to send notifications to Kobiton Slack channels to let Kobiton users be aware of issue(s).

== Bug Fixes

* Kobiton has fixed the issue where crash log lines stack when viewing crash logs in session details.
* Additionally, the purple line of capture network has been removed when viewing crash logs.
* Additional errors, when downloading the Kobiton Desktop Platform, have been resolved so that users may not have to click 'retry' or re-open desktop application when downloading.
