= v3.23 | August 27, 2022
:navtitle: v.3.23 | August 27, 2022

Earlier this year, we introduced you to a smarter, faster Kobiton with the easy-to-remember name: Kobiton

As we roll out this new Kobiton to existing customers, we will continue to offer some updates to our original Kobiton product - which we refer to as Legacy Kobiton. But, the majority of our new features and updates will be found in the new Kobiton. So, when you review the release notes below, please keep in mind that some changes are only in Kobiton and some are in both Kobiton and Legacy Kobiton. We'll note which items apply to Legacy Kobiton.

As always, we are here to help! If you have any questions or would like to update your Kobiton system, please send us an email at support@kobiton.com or contact your salesperson.

== New iOS and Android versions support

The following OS versions are now supported on both Kobiton and Legacy Kobiton:

** Android 13 beta 4
** iOS 16 beta 3
** iOS 16 beta 4
** iOS 15.6 General Availability

The following OS versions are also supported on Kobiton:

** Android 13
** iOS 15.6.1

== App Repo: Increase max app upload size to 4GB

We've increased the max size per app upload to our App Repository from 1GB to 4GB. This change is for both Kobiton and Legacy Kobiton users.

== Biometrics authentication for iOS manual sessions

Many apps support the use of biometrics - fingerprint or FaceID - to login to the app. Our new feature allows users to bypass biometrics with a pass/fail during a manual iOS test session.

When your app requests biometric authentication, you'll be prompted with a dialog box to choose pass/fail.

In order to use this feature, the app to be tested must incorporate a Kobiton-provided customer library. (We'll publish instructions shortly!)

In future releases, we will update this feature to include iOS automation and Android test sessions.

== Network Payload Capture: New API to download HAR file

After having network payload captured during a session, users now can download all captured requests in a HAR file to review.

The new API can be found, https://api-staging.kobiton.com/docs/#get-captured-network-payload-reports[here].

== System Latency Report update

You can now view a summary report and then select the details button on a summary line item. From there, you will be taken to the bottom of the page where you can see additional details and drill-down by choosing the arrows next to each of the following: Location > deviceShare Server > Session > to view connection times. You are also able to click on the Session ID to dive deeper into the investigation.

== Ability to download server logs

This feature is available to customers who host Kobiton on-prem. It allows you to download server logs for troubleshooting and makes it easier for Kobiton Support to provide assistance for issues. Logs can be downloaded for the previous 3 or 7 days.

== Scriptless Testing: Enhancements to Data-Driven Testing

We made several enhancements to make data-driven testing functionality easier to use, such as:

** Automatically assign a device from the Device Bundle to a new dataset. The tester can change the device if needed, but should save time for the tester
** Messaging to ensure users make changes to new datasets
** Configuration for phone number / OTP to support signup flows that require 2FA

== Additional Intelligent Quality Suite Enhancements

** Enhancements to the generate and export Appium script functionality to improve speed of reruns using the generated scripts
** Improved execution time for scriptless sessions where there is a lot of scrolling
** Updates to the user flow to make it easier to work with device bundles
