= v3.19.0 March 12, 2022
:navtitle: v3.19.0 | March 12, 2022

As always, we are excited to share the additions and enhancements introduced in Kobiton 3.19.0!

With this release, we’d like to formally introduce you to a smarter, faster Kobiton with the easy-to-remember name: Kobiton.

We are working on rolling out this new Kobiton to existing customers over the coming months. During the transition, we will continue to offer some updates to our original Kobiton product - which we will now refer to as Legacy Kobiton. But, going forward, the majority of our new features and updates will be found in the new Kobiton.

So, when you review the release notes below, please keep in mind that some changes are only in Kobiton and some are in both Kobiton and Legacy Kobiton.

As always, we are here to help! If you have any questions, would like to update your Kobiton system, or get an understanding of what this all means for your Kobiton system, please contact your salesperson or send us an email at support@kobiton.com.

== What's New in Kobiton

[NOTE]
If you skipped the intro section - please scroll up and give it a read before continuing! And, if the below new features are not enabled for you, please contact us to discuss how to upgrade to the new Kobiton.

=== Test Case Management

We love our Session List and the ability to search for a session. But, we also understand that a long list of sessions can be cumbersome to navigate and see test coverage. So, we are thrilled to introduce Test Case Management, which can be found in the left-side navigation.

After completing a manual session, users can convert the session into a test case. To do so, in Session Explorer, choose Automated Test Case and under the camera roll, select Create Test Case.

In Test Case Management, a test case shows test steps in an easy-to-follow camera roll and provides direct access to run scriptless automation or download the corresponding Appium script. Plus, the test cases are also grouped by application and version to keep your tests organized.

=== iOS hidden password and location modal prompt

Starting with iOS 13, Apple introduced a security feature preventing the streaming of the password field. And, with iOS 15, Apple hid the "Allow [app name] to use your location" prompt when streaming. The result is that users either cannot view their input for password fields within Kobiton or cannot answer the location prompt question causing errors or confusion. To facilitate testing, we've added a visible modal prompt in Kobiton that allows you to see what you are typing for passwords and allows you to answer the location prompt.

=== Device Inspector will automatically update the page inventory

As elements on the inspected page are clicked on the Device Inspector, attributes will automatically update giving you real data as you select elements.

=== Lightning Mode tooltip

During a manual session, there are various reasons why Lightning Mode may not be enabled. We've added a tooltip that provides information about why you are unable to toggle it on.

=== flexCorrect

Every tester has run into the very frustrating "element not found" error- which basically stops a test and requires mediation to keep going. Frustrating- we know! Which is why we are so excited to introduce flexCorrect.

By providing a new desiredCap called “kobiton:flexCorrect”, automation testers have a fall back solution when their script encounters the “Element Not Found” error due to the changes in Element Selectors.

=== Trigger Scriptless from completed Appium automation session

In our last release, we provided the ability to call an API to trigger a scriptless session using an Appium automation script. In this release, we provide the ability for users to trigger Scriptless via the portal using a completed Appium automation session as follows:

1. From Session List: find the session, select View Test Execution Plan. Then select Device Bundle and Run Scriptless
2. From Session Explorer: select the Automated Test Case tab, Run Scriptless button, select Device Bundle, and Run Scriptless

=== Additional updates and bug fixes for Kobiton:


** For our NOVA users enabling the power of the Kobiton smart engine to automate tests, we've eliminated screen size inconsistency and increased the consistency of our AI engine.
** Resolved Scriptless Data-Driven Testing (DDT) issues regarding duplicate data and getting an error message when deleting a step

== What's New on both Kobiton and Legacy Kobiton

=== New iOS Support

We now support devices on iOS 15.2.1 and 15.3. For users that conduct tests on local devices, please note that Xcode 13.2.1 is required to support iOS 15.3.

=== Device Summary report

Quickly get a glance at the state of your devices right from the portal. You can find this new report by selecting the Predefined Reports icon in the left-side navigation panel. Broken up by OS, you'll be able to view how many devices are available, online, utilized, and offline for each of your Teams.

=== Ability to bookmark reports

As we continue to add additional reports to the portal, bookmarks will allow you to quickly access the reports that are most important to your organization. To create a bookmark, simply click the bookmark icon on the report and a new menu item will appear in the left-side navigation panel.

=== Remember your workspace

Do you prefer list view or card view? Do you primarily test in a particular team? The Kobiton portal will save you time by remembering how you work. User portal settings, such as list or card view, selected team, device type, and the last page you were on, are now retained after you log out, so that you can start working quickly when you log back in.

=== Additional updates for both Kobiton and Kobiton Legacy

** The maximum app package size has been increased to 1GB, instead of the conventional 500MB limit when uploading apps to the App Repository.
** Tags that are not supported and recognized on the security banner (e.g. `<h1>`, `<i>`) will automatically display as a `<p>` (paragraph tag). This will avoid breakage in your messaging and ensure messages are displayed for your organization.
** On the device details pop-up and device management page, text will now wrap and adjust to the size of the window to avoid information appearing outside the display.
** You'll receive a detailed message on the portal when your organization has run out of minutes.
