= v3.21 | June 4, 2022
:navtitle: v3.21 | June 4, 2022

In March, we introduced you to a smarter, faster Kobiton with the easy-to-remember name: Kobiton and sometimes referred to as the latest version of Kobiton.

As we roll out this new Kobiton to existing customers, we will continue to offer some updates to our original Kobiton product - which we now refer to as Legacy Kobiton. But the majority of our new features and updates will be found in the new Kobiton. So, when you review the release notes below, please keep in mind that some changes are only in Kobiton and some are in both Kobiton and Legacy Kobiton.

As always, we are here to help! If you have any questions, would like to update your Kobiton system, or get an understanding of what this all means for your Kobiton system, please contact your salesperson or send us an email at support@kobiton.com.

== What's New in both Kobiton and Legacy Kobiton

=== New OS Support

The following OS versions are now supported:

** iOS 15.5 beta 4
** iOS 15.5 RC
** iOS 15.5 official
** iOS 15.6 beta 2
** Android 13 beta 2 (Manual Only)

=== Introducing Kobiton API v2

We are revamping our API Documentation to allow you to interact with it and run APIs directly from the page. This initial release of our API v2 will include some APIs from the following services: User, Devices, Session, and App Repository. We'll roll out additional services in upcoming releases. And, we'll continue to support the original API Documentation for several releases.

Check out the new https://api.kobiton.com/v2/docs[API Documentation page].

=== Device status updated more quickly on Device List

Sometimes, a device may display "Online", but has actually just been put in use by another user. In that case, the tester that selects the device, sees an error, and cannot launch that device. So, we changed how we update device status, so it's now updated more quickly - almost real-time - when a device status changes to "Utilizing", "Offline" or "Online" to provide more accurate device availability.

=== Manual Testing: Enhance the left-hand side toolbar menu

We have added a number of actions in the left-hand navigation while in a manual test session, so that a user needed to scroll to see them all and might not see an action. So, we updated the icons and spacing, so that the icons will fit without scrolling on most screensizes.

=== Predefined Reports: Usage Report Enhancements

We updated the Usage Report to show the following components:

** Text Validation

** Text-color Validation

** Visual Validation

** Accessibility Validation

== What's New in Kobiton

=== Test Case Management: Delete Test Steps Enhancement

In May, we introduced the ability to delete a single test step in a test case. Now, users will be able to select multiple test steps at a time to delete. And, future re-runs will be based on the modified test case.

=== Test Case Management: Modify text value on text setting steps

In addition to deleting test steps, users now can alter the text value for a particular “Set Text” step for later rerun or script exports by clicking the “Settings” icon and making the text modifications. This is very handy if you mistype during a test session and don't want to start over when you create a test case!

=== Introducing the Rerun Configuration Modal for Scriptless

Our new Rerun Configuration Modal acts like a one-stop shop for launching Scriptless reruns, making it easier to work with our Scriptless functionality. And, we've updated buttons to say "Rerun" to make it easy to find.

=== Enhancements that improve the quality of Scriptless and Validations

We've made a number of changes that improve the quality of our Scriptless and Validation functionality. Many of the changes are under-the-covers. The good news is that you will see improvements in:

** Text validations - reducing the "noise" that might report false validations
** Ability to handle floating elements on pages that scroll
** Support for record and playback with the "set location" action
** Performance improvements when accessing the Execution Plan page
** If you try to kick off scriptless with an automation script that does not qualify for scriptless, we'll provide a meaningful message

=== Show Validation results for Failed/Blocked/Ignored reruns

Previously, only validations of a Passed revisit scriptless tests could be reviewed. Now, all scanned validations - even those tests that are Failed/Blocked/Ignored/Terminated up to the step that caused the non-Passed status - will be visible to users and allow users to submit remediation.

=== Scriptless: Introducing Synchronous Inventory Capturing Mode

Previously, we were using asynchronous inventory capturing. While this method is fast, we found it can cause a syncing issue between the screenshot and XML on a test action and thus impact the quality of Scriptless functionality. So, we are introducing a Synchronous Inventory Capturing Mode that users can turn on/off during a manual session. When it is on, note that you will see "Capturing" messages and the test execution will be slowed down. So, it's best to use it when you are planning to turn a manual session into a test case.

=== XCUITest: Support for videos and test reports

Users testing with XCUITest will now be able to see the videos and test reports of their Kobiton XCUITest sessions.

=== Support of passcodes on iOS devices

Some tests require that a passcode be set on a device. The latest version of Kobiton supported passcodes on Local and Private Android devices in a previous release. With this release, we added support for device passcodes on Local and Private iOS devices.

=== Display tooltip when a user’s browser doesn't support Lightning mode

If a user is using an older browser, our lightning mode functionality may not function properly. With this release, we will detect the issue and provide a tooltip for the user with a suggestion to use another browser.

=== Introducing virtualUSB (beta)

Developers often connect devices to their development workstations to use their IDE to troubleshoot and debug mobile apps. Sometimes, they don't have physical access to specific devices or OS versions. Testers also may need direct access to devices from an IDE. So, we're introducing virtualUSB, which provides the means to use XCode, Instruments, or iTunes to remotely connect to a real Private or Local device from the Kobiton Portal as if the device were directly connected to the user’s machine. With virtualUSB installed, the user can login with their Kobiton credentials, then connect to device(s) and use them as they were plugged to their machine. Learn more https://support.kobiton.com/hc/en-us/articles/6306031444109-virtualUSB-Beta-version-Install-and-config-guide-on-MacOS[here].
