= v2.13 | October 14, 2019
:navtitle: v2.13 | October 14, 2019

== New Features

=== Remove specific members from an organization

You can transfer members to another organization and these members can immediately use devices, sessions, etc. with the following organization.

[NOTE]
The feature is only available for organization owner - Transfer request will be sent to new org owner’s email for approval - All related data (sessions, screenshots, logs, etc.) will be transferred along with selected member to a new organization

=== Bypass passcode for Android

Devices or applications that are encountered the passcode for security or any specific testing purpose, Kobiton will help you to automatically input the passcode and continue your test execution.

[NOTE]
Worked for both manual & automation - Supported from Android version 4.4.2 to 9.x - Required to strictly follow the guidelines for the setup

=== Volume controls

Now you can adjust the real device’s volume for any testing that is required the volume up/down function.

[NOTE]
Supported manual (In-house only) & automation for both iOS & Android devices

.Example
[source, terminal]
----
(AndroidDriver) driver).pressKeyCode(AndroidKeyCode.KEYCODE_VOLUME_UP);
    (AndroidDriver) driver).pressKeyCode(AndroidKeyCode.KEYCODE_VOLUME_DOWN);
----

=== Set device location

Now you can set any real device to an exact location, using geographic coordinates.

[NOTE]
Supported automation for both iOS & Android devices. Example: `driver.setLocation(new Location(0, 0, 0));`

==== Export the users’ report

Export the see the report of your members’ consumption on the amount of minutes & sessions from the session list.

== Enhancements

* Support manual test for iOS and iPad OS version 13, 13.1 and 13.1.2
* Support manual and automation for Android 10.
* Support the automation test for Android on Chrome version 77
* Enhance the clean-up policy progress (turn off the AssistiveTouch and mute device’s volume)
* New UI design for a manual test (enhance UI/UX for the install app model, animation for the toolbar, etc.)
* Provide an option to use the same Chrome version with Kobiton
* Some minor bug fixes
