= Resume a session
:navtitle: Resume a session

Learn how to resume a test session after experiencing an unexpected disruption, like:

* Your browser crashing
* Your network disconnecting
* Your computer powering down

For more information, check out our xref:_frequently_asked_questions[frequently asked questions].

== Resume a test session

[IMPORTANT]
You can only resume a test session *within 10 minutes* of an unexpected disruption.

. Open the https://portal.kobiton.com/login[Kobiton portal].
. Select *Devices*.
. Next to the device you were previously using, select *Connect*.
. Resume your test session.

[#_frequently_asked_questions]
== Frequently Asked Questions (FAQ)

=== Will I be charged minutes during the 10-minute window?

Yes. You'll be charged minutes during the 10-minute window. To avoid unexpected charges, be sure to choose *Exit session*, instead of force-quitting your browser.

=== Will I be charged minutes for public devices as well as private & local devices?

Yes. You'll be charged for xref:start-a-session.adoc#_device_types[public devices] and xref:start-a-session.adoc#_device_types[private & local] devices.

=== Can I change the length of the 10-minute window?

Yes. You can change this setting in your xref:account-setup-and-admin:user-profile.adoc[user profile].

=== Can I resume a session using Legacy Kobiton?

No. Currently, this feature is not available for Legacy Kobiton.
