= Use Azure AD for SSO authentication
:navtitle: Use Azure AD

Learn how to use link:https://azure.microsoft.com/solutions/active-directory-sso/[Azure Active Directory (Azure AD)] for Single Sign-On (SSO) authentication so members of your organization can sign in to Kobiton using their Microsoft credentials.

[#_get_kobiton_parameters]
== Get Kobiton parameters

include::partial$get-kobiton-parameters.adoc[]

== Create IdP application

In Azure DP, open your default directory, select *Enterprise Application*, then *New Application*.

image:$OLD-IMAGE$[width=,alt=""]

From *Add your own app*, choose *Non-gallery application*, then enter a name for your application in the search bar and select *Add*.

image:$OLD-IMAGE$[width=,alt=""]

Select *Assign users and groups* and add test user for your application.

image:$OLD-IMAGE$[width=,alt=""]

You'll *set up single sign on* in the next section.

== Map parameters

Now that your IdP application is initially created, you'll need to create Azure AD parameters mapped to Kobiton and download your Base64 certificate. Select *Set up single sign on* to get started.

image:$OLD-IMAGE$[width=,alt=""]

In step 1, *Basic SAML Configuration*, use your xref:_get_kobiton_parameters[Kobiton SSO parameters from earlier] to fill out the following fields:

* *Identifier (Entity ID)*
* *Reply URL (Assertion Consumer Service URL)*
* *Relay State*

image:$OLD-IMAGE$[width=,alt=""]

In step 2, *User Attributes & Claims*, create the following parameters:

Parameter 1::
* *Name:* `email`
* *Namespace:* _Leave blank_
* *Name format:* Basic
* *Value:* `user.email`
Parameter 2::
* *Name:* `firstName`
* *Namespace:* _Leave blank_
* *Name format:* Basic
* *Value:* `user.givenname`
Parameter 3::
* *Name:* `lastName`
* *Namespace:* _Leave blank_
* *Name format:* Basic
* *Value:* `user.surname`
Parameter 4::
* *Name:* `phone`
* *Namespace:* _Leave blank_
* *Name format:* Basic
* *Value:* `user.telephonenumber`
Parameter 5::
* *Name:* Unique User Identifier
* *Namespace:* _Leave blank_
* *Name format:* Basic
* *Value:* `user.userprincipalname`

image:$OLD-IMAGE$[width=,alt=""]

== Download certificate and get IdP parameters

In step 3, *SAML Signing Certificate*, download *Certificate (Base64)*.

image:$OLD-IMAGE$[width=,alt=""]

In step 4, *Set up Kobiton Azure Local*, copy the following values and save them to a note:

* *Login URL*
* *Azure AD Identifier*
* *Logout URL*

image:$OLD-IMAGE$[width=,alt=""]

== Add IdP parameters and certificate to Kobiton

include::partial$add-idp-parameters-and-certificate-to-kobiton.adoc[]

== Verify and save configuration

include::partial$verify-and-save-configuration.adoc[]
