= Use Google Workspace for SSO authentication
:navtitle: Use Google Workspace

Learn how to use link:https://support.google.com/a/answer/60224?hl=en[Google Workspace] for Single Sign-On (SSO) authentication so members of your organization can sign in to Kobiton using their Google credentials.

[#_get_kobiton_parameters]
== Get Kobiton parameters

include::partial$get-kobiton-parameters.adoc[]

== Create IdP application

In the Google Admin console, and select *Apps*.

image:$OLD-IMAGE$[width=,alt=""]

In Apps, choose *SAML apps*.

image:$OLD-IMAGE$[width=,alt=""]

Select the *Add App* dropdown, then select *Add custom SAML app*.

image:$OLD-IMAGE$[width=,alt=""]

In step 1, *App details*, enter a name for your application.

image:$OLD-IMAGE$[width=,alt=""]

== Get IdP parameters and download certificate

In step 2, *Google Identity Provider Details*, copy the following values and save them to a note:

* *SSO URL*
* *Entity ID*
* *Certificate*
* *SHA-256 fingerprint*

image:$OLD-IMAGE$[width=,alt=""]

== Map parameters

In step 3, *Service Provider Details*, use your xref:_get_kobiton_parameters[Kobiton SSO parameters from earlier] to fill out the following fields:

* *ACS URL*
* *Entity ID*
* *Domain Key*

image:$OLD-IMAGE$[width=,alt=""]

Then in step 4, *Add custom SAML app*, create the following parameters:

Parameter 1::
* *Google Directory attributes:* Primary email
* *App attributes:* `email`
Parameter 2::
* *Google Directory attributes:* First name
* *App attributes:* `firstName`
Parameter 3::
* *Google Directory attributes:* Last name
* *App attributes:* `lastName`
Parameter 4::
* *Google Directory attributes:* Phone number
* *App attributes:* `phone`

image:$OLD-IMAGE$[width=,alt=""]

== Add IdP parameters and certificate to Kobiton

include::partial$add-idp-parameters-and-certificate-to-kobiton.adoc[]

== Verify and save configuration

include::partial$verify-and-save-configuration.adoc[]
