= Android frequently asked questions
:navtitle: Android frequently asked questions

Find answers to frequently asked questions related to Android devices.

== How can I bypass the black screen when logging into Google Play Store (device with passcode)?

On passcode-enabled devices with Android 12 and later, during a manual session, the screen turns black when logging into Google Play.

The black screen is actually the passcode input screen. This screen has been protected from screen sharing to prevent recording of passcode input.

To bypass this screen in a manual session:

* Copy the passcode in the top session bar.

* Open *adb shell* terminal in the device action.

* Type `input text <passcode>` (replace `<passcode>` with the copied passcode) and hit *Enter* on the keyboard.

* Type `input keyevent 66` and hit *Enter* on the keyboard.

* You can then move on to the next screen, which is no longer protected from screen sharing.

== How do I resolve the black screen issue when testing a secure app that blocks screen capture (FLAG_SECURE)?

