= Device metadata
:navtitle: Device metadata

In *Devices*, view device metadata in the xref:manage-devices.adoc[device settings] or use device metadata to create xref:search-for-a-device.adoc#_custom_columns[custom columns].

image:<NEW-IMAGE>[width=, alt=""]

== Device Name (default)

The official name of the device, like Galaxy S10, iPhone 11 Pro, or iPhone XS.

== Operating System (default)

The operating system, like Android or iOS.

== OS Version (default)

The operating system version, like Android 10, Android 8.0.0, or iOS 15.5.

== UDID (default)

The unique device identifier (UDID) used to identify iOS devices.

== Manufacturer

The manufacturer, like Apple, Google, or Samsung.

== Resolution

The screen resolution, like 1080x2220 or 1125x2436.

== Tag

Select a custom device tag to narrow your search.

== Browser

The installed web browser, like Chrome 95, Safari, or Firefox.

== Serial Number

The unique serial number assigned to the device, like 9876EFGH5432 or XYZ7890IJKL.

== CPU Platform

The CPU platform, like 32 or 64 bit.

== Total Memory

The memory volume, like 1380.47 GB or 1974.86 GB.

== Phone IMEI

The International Mobile Equipment Identity (IMEI) number used to identify devices on a cellular network, like 356412089347896.

== Phone ICCID

The Integrated Circuit Card ID (ICCID) number used to identify a SIM card, like 8944500016116273525.

== Phone IMSI

The International Mobile Subscriber Identity (IMSI) number used to identify the device user, like 310150123456789.

== Security Patch

The current security patch installed on the device, like

== Carrier

The mobile carrier, like Verizon or AT&T.

== Network Type

The type of network being used, like 4G or Wi-Fi.

== Battery Temp

The temperature of the device's battery, like 35°C or 95°F.

== Battery Health

The overall health of the device's battery, like Good or Needs Service.

== Mobile Number

The mobile phone number assigned to the device, like (718) 555-5678 or (213) 555-1234.

== Used By

The tester currently using the device.

== Usage Duration

The length of time the device has been in use, like 3 hours and 45 minutes or 1 day and 12 hours.

== Device Health

The overall health of the device, like Good or Needs Service.

== Network Status

The current status of the device's network connection, like Connected or Disconnected.

== Device Model

The device model, like D10Ap, Lenovo TB-8705F, or SM-G970U.

== Location

The location where the device is physically located.
