= Device Passcodes
:navtitle: Device Passcodes

== What are MDMs?

Mobile Device Management systems, or MDMs, act as digital gatekeepers. Their primary function is to control, secure, and enforce policies on mobile devices within an organization. A common practice is for MDMs to necessitate device passcodes, providing a potent safeguard against unauthorized access.

== Their role in mobile testing

While MDMs are beneficial, they also complicate the mobile testing pipeline, introducing additional layers of security to account for in each test script. Worse, if your mobile devices don't have passcode support, MDMs make mobile testing impossible.

== Our Solution

We provide device passcodes for private and local devices so you can write and run tests while meeting MDM requirements. When you xref:manual-testing:start-a-manual-session.adoc[start a manual session] or xref:manual-testing:device-controls.adoc#_power[restart your device] during a session, the passcodes are automatically inputted for you.

image:$NEW-IMAGE$[width="",alt=""]

To gain access to passcode support, reach out to support@kobiton.com.
