= Find a device
:navtitle: Find a device

Learn how to find a device by filtering your search results with views, statuses, custom columns, and more. Once you've found one, you can start xref:manage-a-device.adoc[managing the device].

== Filter your search results

First, you'll want to filter your search results.Open your device list, select a xref:#_views[view], then choose a xref:#_device_categories[device category].

Select *List View*, *Edit Column*, and choose xref:#_custom_columns[up to nine columns].

Once you've found a device, select the *vertical ellipses* to start xref:manage-a-device.adoc[managing your device].

[#_search_filters]
== Search filters

[#_views]
=== Views

==== Card view (default)

Displays essential information about your devices.Sort by xref:_device_statuses[device status], device health, device name, friendly name, or OS version.

==== List view

Displays detailed information about your devices. Select *Edit Column* to customize the view and add up to nine xref:_custom_columns[custom columns].


[#_device_categories]
=== Device category

[#_favorite]
==== Favorite
A list of your favorite devices.To favorite a device, select the *vertical ellipses* next to the device, then click the *star icon*.

==== Public devices
Devices shared between all Kobiton customers.Perfect for edge case testing and broad market coverage testing.

==== Private & local devices
Devices reserved for your team. Perfect for those leveraging xref:scriptless-automation:index.adoc[scriptless automation].

[#_device_statuses]
=== Device status

==== Online

The device is available for a testing session.

==== Busy: Utilized

Currently in a test session.

==== Busy: Retained

Reserved by a user, but may or may not be in a test session.

[NOTE]
Only available for private and local devices.

==== Offline: Connected

Offline, but physically connected to the hardware.

==== Offline: Unplugged

Offline and physically disconnected from the hardware.

[#_custom_columns]
=== Column options

Customize your view further by selecting *List View*, then *Edit Column*, and choosing up to nine of the following columns:

==== Device Name (default)
The official name of the device, like Galaxy S10, iPhone 11 Pro, or iPhone XS.

==== Operating System (default)
The operating system, like Android or iOS.

==== OS Version (default)
The operating system version, like Android 10, Android 8.0.0, or iOS 15.5.

==== UDID (default)
The unique device identifier (UDID) used to identify iOS devices.

==== Manufacturer
The manufacturer, like Apple, Google, or Samsung.

==== Resolution
The screen resolution, like 1080x2220 or 1125x2436.

[#_tag]
==== Tag
Select a custom device tag to narrow your search.

==== Browser
The installed web browser, like Chrome 95, Safari, or Firefox.

==== Serial Number
This

==== CPU Platform
The CPU platform, like 32 or 64 bit.

==== Total Memory
The memory volume, like 1380.47 GB or 1974.86 GB.

==== Phone IMEI
The International Mobile Equipment Identity (IMEI) number used to identify devices on a cellular network, like 356412089347896.

==== Phone ICCID
The Integrated Circuit Card ID (ICCID) number used to identify a SIM card, like 8944500016116273525.

==== Phone IMSI
The International Mobile Subscriber Identity (IMSI) number used to identify the device user, like 310150123456789.

==== Security Patch
The current security patch installed on the device, like

==== Carrier
The mobile carrier, like Verizon or AT&T.

==== Network Type
The type of network being used, like 4G or Wi-Fi.

==== Battery Temp
The temperature of the device's battery, like 35°C or 95°F.

==== Battery Health
The overall health of the device's battery, like Good or Needs Service.

==== Mobile Number
The mobile phone number assigned to the device, like (718) 555-5678 or (213) 555-1234.

==== Used By
The tester currently using the device.

==== Usage Duration
The length of time the device has been in use, like 3 hours and 45 minutes or 1 day and 12 hours.

==== Device Health
The overall health of the device, like Good or Needs Service.

==== Network Status
The current status of the device's network connection, like Connected or Disconnected.

==== Device Model
The device model, like D10Ap, Lenovo TB-8705F, or SM-G970U.

==== Location
The location where the device is physically located.
