= Hide the Public Devices tab
:navtitle: Hide Public Devices tab

Learn how to hide the Public Device tab, which is only accessible to Cloud and Hybrid customers and does not have a use in OnPrem deployments.

== Enable the Kobiton debug option in Settings

The option to hide the Public Device tab is hidden unless the debug mode is enabled. To enable debug mode, log into the Kobiton Portal as an admin in Chrome.

Click the profile picture, then select *Settings*.

Select *Other Settings*.

In the Chrome *address bar*, add this to the end of the current address: `?kobitonDebugEnabled=true`.

A new option *(Debug mode) Internal settings* appears at the end of the page with a checkbox to hide or show the Public Devices tab.

== Hide or show the Public Devices tab

Make sure the *(Debug mode) Internal settings* option is enabled.

Uncheck the *Show Public Device Tab* option and choose *Update*.

The Public Device tab is now hidden from the Devices page.

To show the Public Device tab again, repeat the steps from the beginning of this article, then check the *Show Public Device Tab* option and choose *Update*.