= Manage devices
:navtitle: Manage devices

Select *Devices*, then select the *vertical ellipses* next to a device to manage a device.

image:$NEW-IMAGE$[width=, alt=""]

== Rename the device

Enter a new device name and select *Save*. You can also check the box to apply this name to all similar devices.

image:$NEW-IMAGE$[width=, alt=""]

== Favorite the device

Select the *star icon* to add the device to your list of favorites. Select it again to remove it.

image:$NEW-IMAGE$[width=, alt=""]

== Add or remove tags

Create a new tag or choose an existing one to add a device tag. To remove a tag, select the *x* icon.

image:$NEW-IMAGE$[width=, alt=""]

== Enable network payload capture

Once xref:organization:network-payload-capture/about-network-payload-capture.adoc[network payload capture] is enabled, select *Use Configuration* and choose a configuration.

image:$NEW-IMAGE$[width=, alt=""]

== Retain the device

Select *Retain* to reserve the device and preventing other testers from using it.

image:$NEW-IMAGE$[width=, alt=""]

== Require a passcode

Once xref:organization:require-device-passcodes.adoc[device passcodes] are enable, select *Passcode Feature Enforced* to require a passcode for this device before it can be used in a test session.

image:$NEW-IMAGE$[width=, alt=""]

== Automation settings

You can select *Automation settings* to xref:automation-testing:auto-generate-desired-capabilities.adoc[auto-generate desired capabilities] you can add to your test suite.

image:$NEW-IMAGE$[width=, alt=""]
