= Customize your device
:navtitle: Customize your device

Learn how to customize a device by changing its name, installing apps, selecting configurations, and more.

[NOTE]
Only available for private and local devices.

== Open the device overview

After you xref:find-a-device.adoc[find a device], select the *vertical ellipses* to open the device overview. Here, you'll manage the device.

== Make changes

=== Rename the device

Rename your device to change how it appears in xref:find-a-device.adoc#_search_filters[search results]. Select the device name, then enter a new name for the device. If you want to apply this name to all similar devices, select the checkbox.

When you're finished, save your changes.

=== Favorite the device

You can add this device to your list of favorites by selecting the *star icon*. This will make it easy to xref:find-a-device.adoc#_favorite[find your device] later.

If you want to remove the device from your favorites, select the *star icon* again.

=== Add or remove tags

Add or remove tags to change how this device appears in xref:find-a-device.adoc#_tag[search results]. Select the search bar and choose a pre-existing tag, or enter your own.

Your new tag will save automatically.

=== Enable network payload capture

After you xref:organizations:your-organization/about-network-payload-capture.adoc[set up network payload capture], enable this feature by selecting *Use Configuration* and choosing the configuration you created.

=== Retain the device

Retaining a device allows you to reserve a device and prevent other testers from using it.

Select *Retain* to reserve this device and prevent another tester from using it.

=== Require a passcode

If your organization xref:organizations:your-organization/set-up-device-passcodes.adoc[set up device passcodes], select *Passcode Feature Enforced* to require a passcode for this device. Now a passcode will be required to use this device in a test session.
