= Run Buildkite scripts
:navtitle: Run Buildkite scripts

== About Buildkite

https://buildkite.com/[Buildkite] is a platform for running fast, secure, and scalable continuous integration pipelines
on your own infrastructure.

== Kobiton Plugins

Kobiton Plugins can be found here: https://buildkite.com/plugins?filter=kobiton[Buildkite Plugins].

You can add Kobiton plugin(s) to your YAML pipeline in order to:

* upload your app to Kobiton app repo
* execute test on Kobiton device

== How to use

Precondition: You should already have your Buildkite pipeline set up. Please
also refer to https://buildkite.com/docs/pipelines/defining-steps[Defining Your Pipeline Steps].

== Kobiton App Upload

To upload your application to Kobiton App Repo, add the following to your `pipeline.yml`:

[source]
----
steps:
- label: "Kobiton App Upload"
plugins:
- kobiton/kobiton-app-upload#v1.0.0:
    app-name: '<app-name>'
    app-path: '<path-to-your-app>'
    app-type: '<apk or ipa>'
    kobiton-app-id: 'your-kobiton-app-id'
    kobiton-app-access: 'private'
    kobiton-username: '<your-kobiton-username>'
    kobiton-api-key: '<your-kobiton-api-key>'
----
|===
|Configuration | Description

|app-name (required)
|Title of the app being built, for example `test-app`.

|app-path (required)
|Path to the app .apk or .ipa file, for example `./test.apk`.

|app-type
|`ipa` for iOS app or `apk` for Android app.

|kobiton-app-id
|App ID in Kobiton, use this in case you want to upload a new version of an existing app in Kobiton, for example `204234`.

Leave blank if you're uploading a new app.

|kobiton-app-access
|Use `private` if you want to make this app private, or `public` to make it available for everyone in the organization.

|kobiton-username
|Kobiton Username to upload to Kobiton, for example `kobitonadmin`.

|kobiton-api-key
|API key to access Kobiton API, for example `2c8n41e4-b30d-4f19-ba63-6596016c9e58`.

To get your Kobiton API Key, please follow instructions at "IV. Configure Test Script for Kobiton" section on https://kobiton.com/blog/tutorial/parallel-testing-selenium-webdriver/[our blog].

|===

For example: This will upload a new app version to app ID = 294808, and this app is private.

image:$NEEDSIMAGE$[width=,alt="https://support.kobiton.com/hc/article_attachments/6930761283085/image-20220509-140155.png"]

Once you're done adding the plugin to your pipeline, click on "Save and Build", then click "Create Build" to proceed.

image:$NEEDSIMAGE$[width=,alt="https://support.kobiton.com/hc/article_attachments/6931440421773/image-20220509-092420.png"]

image:$NEEDSIMAGE$[width=,alt="https://support.kobiton.com/hc/article_attachments/6931453510285/image-20220509-092527.png"]

(Optional) Once the pipeline completes running, you can go to Kobiton App Repo to double-check your new application/new application version.

== Kobiton Execute Test
To execute your test with Kobiton Executor, add the following to your pipeline.yml:

[source]
----
steps:
- label: "Kobiton Execute Test"
plugins:
- kobiton/kobiton-execute-test#v1.0.0:
   kobi-username: 'your kobiton username'
   kobi-api-key: "your kobiton api key"
   executor-url: 'https://executor-demo.kobiton.com'
   executor-username: 'your kobiton executor server username'
   executor-password: "your kobiton executor server password"
   git-repo-url: 'https://github.com/Nhattd97/azure-devops-sample-java-prod.git'
   git-repo-branch: 'master'
   git-repo-ssh-key: ''
   app-id: 'kobiton-store:91041'
   root-directory: "/"
   command: 'mvn test'
   device-name: 'Galaxy S10'
   device-platform-version: '10'
   use-custom-device: 'false'
   device-platform: 'android'
   wait-for-execution: 'true'
   log-type: 'combined'
----
|===
|Configuration | Description

|kobi-username (required)

kobi-api-key (required)
|To get your Kobiton Username and API Key, please follow instructions at _IV. Configure Test Script for Kobiton_ section on https://kobiton.com/blog/tutorial/parallel-testing-selenium-webdriver/[our blog]

|executor-url (required)

executor-username (required)

executor-password (required)
|We will provide you credentials to access our TestNG Execution Server. This will be used to execute your automation test script.

|git-repo-url (required)

git-repo-branch (required)

git-repo-ssh-key
a|You need to prepare your automation test project in a Git-based repository.

For your security, we highly recommend setting your Git repository to Private and prepare an SSH key for it.

If you do not know how to authenticate the key with Git, please follow the guide from https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/[Github create SSH key instruction] and https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/[Github adding the key to account instruction].

* git-repo-url: This is the URL to your Git repository that contains your TestNG test script.

* git-repo-branch: The branch of the repository to execute automation test script.

* git-repo-ssh-key: The SSH Key of the above repository

|app-id
|You can retrieve app-id from App Repo on Portal. Reference: https://support.kobiton.com/hc/en-us/articles/360056028911-Managing-Applications-#app-tiles-0-0[Managing Applications]

|root-directory (required)

command (required)
|Input the root directory of your Git repo and the command lines to install dependencies and execute your automation test script. These commands will run from the root directory of your Git repository.

|use-custom-device
|If you haven’t set the device information in your script, set this to “true” to choose a device to execute your test scrip

|device-name

device-platform-version

device-platform

|if above config is true, provide the info of the device you want to use to run the test

|wait-for-execution
|Set to “true” if your want the release pipeline to wait until your automation testing is completed or failed, then print out the console log and test result.

If it’s set to “false”, the release pipeline will continue to the next step. The execution job ID of this task will be printed, but not the console logs or TestNG report URL.

|log-type
|Your desired log type to be showed. Choose `"combined"` to show logs in chronological order, or specify a specific type of log (`"output"` or `"error"`)

|===

Example:

image:$NEEDSIMAGE$[width=,alt="https://support.kobiton.com/hc/article_attachments/6931694970125/image-20220509-140135.png"]

Once you’re done adding the plugin to your pipeline, select “Save and Build”, then click “Create Build” to proceed.


