= Upload an app using BuildKite
:navtitle: Upload an app

Learn how to upload an app to your app repository using BuildKite.

== Before you start

You'll need to link:https://buildkite.com/docs/pipelines/create-your-own[create a BuildKite pipeline], since the link:https://buildkite.com/plugins?filter=Kobiton+App+Upload[Kobiton App Upload] plugin will be added to your `pipeline.yml` file.

== Upload an app

Open link:https://buildkite.com/login[BuildKite] and select your pipeline.

image:$NEW-IMAGE$[width="",alt=""]

Select *Settings*.

image:$NEW-IMAGE$[width="",alt=""]

Select *Steps*.

image:$NEW-IMAGE$[width="",alt=""]

Add the following steps to your `pipeline.yml` file:

[source,yaml]
----
steps:
  - label: "Kobiton App Upload"
    plugins:
      - kobiton/kobiton-app-upload#v1.0.0:
          app-name: '<app-name>'                      // Required: the name of your app.
          app-path: '<path-to-your-app>'              // Required: the relative path to your app.
          app-type: '<apk-or-ipa>'                    // The app file type, 'apk' for Android and 'ipa' for iOS.
          kobiton-app-id: 'kobiton-app-id'       // When uploading a new app version, assign the app's existing Kobiton ID.
          kobiton-app-access: 'private'               // Always set to 'private'.
          kobiton-username: '<your-username>' // Your Kobiton username.
          kobiton-api-key: '<your-api-key>'   // Your Kobiton API key.
----

[NOTE]
You can get API key values from your list of xref:profile:manage-your-api-keys.adoc[Kobiton API keys].

When you're finished, select *Save and Build*.

image:$NEW-IMAGE$[width="",alt=""]

Choose to add a commit message or leave it blank, then select *Create Build*.

image:$NEW-IMAGE$[width="",alt=""]

When your build is complete, BuildKite will let you know if it passed.

image:$NEW-IMAGE$[width="",alt=""]
