= Session metadata
:navtitle: Session metadata

$DESCRIPTION$

== Session info

=== Session name

Select *Edit* to change the session name. You can also change this name in xref:manual-testing:session-settings.adoc[during a test session].

=== Description

Select *Edit* to change the session description. You can also change the description xref:manual-testing:session-settings.adoc[during a test session].

=== Testing type

Indicates whether the test session was manual or automated.

=== User

The name of the user that performed the test session.

=== Duration

The length of the test session.

=== Status

Indicates whether the test session was completed.

=== Start/End time

The date and time the test session started and ended.

== Apps installed

=== App name

The official name of the app, like Instagram or Gmail.

=== Size

The size of the app in MBs or GBs.

=== Version

The app version, like 268179862 or 1.0.0.

=== Package

The bundle identifier, like `com.burbn.instagram`.

=== Instrumentation

Instrumentation is required for xref:manual-testing:test-your-in-app-camera.adoc[image injection]. Indicates whether this feature was turned on during the test session.

=== Instrumentation status

Instrumentation is required for xref:manual-testing:test-your-in-app-camera.adoc[image injection]. Indicates whether instrumentation was successful during the test session.

=== Installation status

Indicates whether the app successfully installed during the test session.

== Device info

=== Manufacturer

The manufacturer, like Apple, Google, or Samsung.

=== Operating system

The operating system, like Android or iOS.

=== Device name

The official name of the device, like Galaxy S10, iPhone 11 Pro, or iPhone XS.

=== Resolution

The screen resolution, like 1080x2220 or 1125x2436.

=== Model name

The device model, like D10Ap, Lenovo TB-8705F, or SM-G970U.

=== UDID

The unique device identifier (UDID) used to identify iOS devices.

== Logs

=== Download

Select *Download* to save a copy of the device and crash logs.

=== Device

Select *Device* to open a preview of the device logs, then select *Download* to save a copy.

=== Crash

Select *Crash* to open a preview of the crash logs, then select *Download* to save a copy.
