= Assign users/ devices to Teams
:navtitle: Assign users/ devices to Teams

== Assign/ Remove users from Teams
=== Assign users
1. On *Org Management*, select the *Teams* tab.

2. Navigate to the Teams Details site by clicking on the Team name.

3. Click the *Users* tab.

4. Click *Add new user*.

5. Toggle one role amongst *Team Owner*, *Team Admin* Or *Team Member* to select the role you want to assign the user to.

6. Select users from the Unassigned Users drop-down list to add them to the Team.

7. Click *Update* to close the modal.

8. Click *Save*.

=== Remove users

1. On the Team Details site, click the *Users* tab.

2. Click the (-) icon to remove users from the team.

3. Click *Save*.

== Assign/ Remove devices from Teams

1. On the Team Details site, click the *Devices* tab.

2. To filter online/ offline devices, tick the *Online/ Offline* button. You can also filter *Public/ Private & Local/ All devices* by selecting one option from the drop-down list.

3. In the list of *Unassigned Devices*, click (+) icon to add a device. To remove a device, click (-) from the *Assigned Devices* list.

4. Click the *Assign All* button to assign all devices in the current *Unassigned Devices* list. Click the *Unassign All* button to remove all devices from the *Assigned Devices* list.

5. Click *Save*.

NOTE: As a device can be assigned to multiple teams, it may cause conflicts regarding Cleanup Policies amongst Teams. For example, a Team may set a No Cleanup policy while another Team set a Thorough policy to the same device.




