= Customize your organization
:navtitle: Customize your organization

This section guides users to customize Login Message and configure iFrame on the Kobiton portal.

== Customize the Login Message (Security Banner)
The Login Message (Security Banner) is a separate window that appears when a user logs into a system. The message includes information such as Terms of Service, organization notes for new users, or disclaimers.

By default, the system administrator defines the content of this window. However, the message and button text can be changed by users with the permission of org_setting.modify_security_banner.

To modify the Login Message, users follow below guidance:

1. Click your account drop-down arrow, go to *Settings*. Then, select *Security Banner*.

2. Enable *Only show on first login* toggle if you want the banner to only show on the first login. If this toggle is disabled, the banner shows every time the user logs in.

3. Edit the *Button Text* (if any). Button Text is the text on the button displayed underneath the security banner. Normally, users click the Button to close the login message and navigate to the Kobiton portal.

4. In the *Banner Text* box, modify your login message as you wish to appear to your organization. Banner Text could be Text or HTML. Kobiton generates the text or translates the HTML.
+
Note:

* The message must not exceed 4000 characters.

* Users can use bold, italic, underline, strike, hyperlink.
+
5. Click *Preview* (if any) to see how the security banner appears to actual users.

6. Click *Publish* once you finish editing.

== Configuring iFrame on the Kobiton portal

The Kobiton device panel's UI and functionality can be customized to tailor to your needs by following the below instruction:

1. Click on the user dropdown menu and select *Settings*.

2. On the top navigation menu, click *iFrame Configuration*.

3. Make changes on UI visuals and functions, then click *Save Configuration*.

NOTE: The iFrame configuration is for changing the look and feel of the Portal when embedded into another website, not for customizing the UI elements of the main Portal site.

For more details about the iFrame customization options, follow this link.

