= Set up an organization
:navtitle: Set up an organization

An organization comprises collective teams and is automatically created once the first user registers an account with Kobiton. Users can join the organization via request for a trial account from Kobiton team or invitation of the Org Owner/ Team Admin. With the Org Management feature, users can  modify their access to devices, sessions.

NOTE: Each user belongs to only one organization. Users cannot create a new organization.

== Org-level permissions
* The first user to join an organization is also the Org Owner. Later, the Org Owner can transfer this role to another admin user.

* The Org Management feature is enabled for the Org Owner, RBAC Admins, Team Owner/ Admin and is not visible in Member accounts.

* Org Owner/ RBAC Admins can access all Teams and edit organization’s information.

* Team Owner/ Admin *without Org Owner/ RBAC Admin roles* can only access and edit the Team they are assigned to.

== Edit an Organization

Users can change the Organization name and description by doing the following:

1. Click the pencil icon.

2. In the *Edit Organization* modal, type the new name and description.
+
NOTE: The name must be between 5 and 80 characters & can contain alphabet, alphanumeric, space,.+-_.
+
3. Click *Update*.

== Invite Members to an Organization

To add a member to the organization:

1. On the *Org Management* page, select the *Users* tab.

2. Click the *+Invite* button.

3. Enter the person’s email address.

4. Select a role in the dropdown list: Member (Predefined) or Admin (Predefined). Those with the Member role can only access devices, Teams they are assigned to, while the Admin role can access to all devices, Teams, sessions and have the managerial abilities.

5. The new user is assigned to the Default Team. Optional: select a Team in the dropdown list to add more teams.

6. Click *Send Invitation*. Members will be notified about the invitation via their emails.

NOTE: Invited members must be new and not belong to other existing organizations.



