= Test sessions
:navtitle: Test sessions

Now that you've xref:select-a-device.adoc[launched your device] and xref:install-an-app.adoc[installed an app], you're ready to start manual testing!

You can add manual test session details to help you organize your testing. While all settings are optional and Kobiton will automatically name your session, you may want to adjust it to your preferences.

. During a Manual Test session, click on Session Settings.
. Name your manual test session so it's easier to find in the list of test sessions.
. Describe the test objective in the test session description.
. By default, the option to automatically quit an idling session after 15 minutes is enabled.
. Set the Video Quality (Low, Medium, High) per your network speed.

[#_next_steps]
== Next steps

Learn more about performing manual tests:

* xref:test-sessions/session-controls.adoc[]
* xref:test-sessions/take-a-screenshot.adoc[]
* xref:test-sessions/run-adb-shell-commands.adoc[]
* xref:test-sessions/create-custom-gestures.adoc[]
