= Taking screenshots
:navtitle: Taking screenshots

Learn how to take screenshots during a test session.

Kobiton Portal equips you with the ability to capture screenshots during your Manual Test sessions. Screenshots can be viewed while the session is still end progress and will be stored as session details after the session has ended for easy review.

== Take a screenshot

. Open the https://portal.kobiton.com/login[Kobiton portal].
. xref:select-a-device.adoc[Launch a device].
. Select *Take screenshot* on the session page.
. You can view your screenshot xref:_during_a_session[during] or xref:_after_a_session[after] your session.

== View a screenshot

[#_during_a_session]
=== During a session

. During your session, the amount of screenshots you've taken will be displayed on the *Screenshots* icon.
. Select *Screenshots* to open a gallery of your current screenshots.
. Hover your mouse over a specific screenshot and select *Download* to save a copy locally.

[#_after_a_session]
=== After a session

After a Manual Test session has ended, you can still view the screenshots taken in that session.

. In the Sessions tab of Kobiton Portal, select a session to see its details.
. Because Take screenshot counts as an action, click on Actions Performed tab.
. Select the timestamp of the Take screenshot action to view the captured screenshot.
. You can download a screenshot by hovering on it and click on Download screenshot.
