= Set up Kobiton Command Line Interface
:navtitle: Set up Kobiton CLI

Learn how to set up Kobiton Command Line Interface (CLI) to control and operate your private device lab.

== Before you start

* Obtain the xref:profile:manage-your-profile.adoc#_manage_your_profile[username,window=read-later] and xref:profile:manage-your-api-credentials.adoc#_get_an_api_key[API key,window=read-later] from a Kobiton Enterprise account.

* Ensure private devices are available in the Kobiton Portal. Public devices are not supported.

* Contact Kobiton Support for the link to download the CLI package. The package is available for the below platforms:

** macOS - ARM64 (for Macs with Apple silicon)
** Linux - x64
** Windows - x64

== Setup and authentication

[tabs]

====

macOS or Linux::
+
--

Open a terminal window on the machine.

Navigate to the directory of the downloaded CLI package.

Extract the downloaded package to create the `kobiton` executable file.

[source,bash]
tar -zxvf kobiton-cli.<platform>.<version>.tgz

Export the following environment variables for authentication using the command `export <VARIABLE_NAME>=<VALUE>`

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.kobiton.com`. *Example*: `\https://api-acme-prodv2.kobiton.com`
** Standalone: use `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[source,bash]
.Examples
# Use one of the below based on the deployment type
export KOBITON_PORTAL=https://api.kobiton.com # Cloud/Hybrid
export KOBITON_PORTAL=https://api-acme-prodv2.kobiton.com # Cloud/Hybrid with custom domain
export KOBITON_PORTAL=https://acme.kobiton.local:3000 # Standalone
# Obtain the below from the Profile and Settings page of the Kobiton Portal
export KOBITON_USER=johndoe
export KOBITON_API_KEY=be99***0-c*df-4224-aed6-907****92d0

[TIP]
=====
Put the export commands for the above variables in a `.env` file, then run `source <env-filename>` to export all variables.

[source,bash]
.Example
# The below assumes that all required export variables command are in the file variables.env
source variables.env
=====
--

Windows::
+
--

Open the location of the downloaded CLI package in File Explorer.

Right-click the `kobiton-cli.win-x64.<version>.zip` package and select *Extract All...*, then choose *Extract*. This results in a folder with the file `kobiton.exe`.

Open *Powershell*, then navigate to the location of the `kobiton.exe` file.

Export the following environment variables for authentication using the command `$env:<VARIABLE_NAME>="<VALUE>"` in Powershell.

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.kobiton.com`. *Example*: `\https://api-acme-prodv2.kobiton.com`
** Standalone: use `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[source,bash]
.Cloud/Hybrid
# Use one of the below based on the deployment type
$env:KOBITON_PORTAL = "https://api.kobiton.com" # Cloud/Hybrid
$env:KOBITON_PORTAL = "https://api-acme-prodv2.kobiton.com" # Cloud/Hybrid with custom domain
$env:KOBITON_PORTAL = "https://acme.kobiton.local:3000" # Standalone
# Obtain the below from the Profile and Settings page of the Kobiton Portal
$env:KOBITON_USER = "johndoe"
$env:KOBITON_API_KEY = "be99***0-c*df-4224-aed6-907****92d0"

[NOTE]
=====
For *Command Prompt* (cmd.exe), use the below command instead to set environment variables:
[source,bash]
set KOBITON_PORTAL=https://api.kobiton.com
set KOBITON_USER=johndoe
set KOBITON_API_KEY=be99***0-c*df-4224-aed6-907****92d0
=====

--
====

After the CLI has been set up for the appropriate platform, run the below command from the same location as the `kobiton` file to check if the variables are valid and the CLI is working:

[tabs]

====

macOS, Linux, Windows - Powershell::
+
--

[source]
----
./kobiton device list --private
----

--

Windows - Command Prompt::
+
--
[source]
kobiton device list --private
--
====

If the device list is returned without any error, then the CLI is set up and ready for use.

If there is any error, follow the xref:use-the-cli.adoc#_troubleshooting[troubleshooting guide,window=read-later] to resolve the issue.

== Add environment variables to shell initialization script (optional)

[tabs]
====

macOS or Linux::

+

--

These commands can be added to the shell initialization script to set the variables each time a new shell instance is run.

The location of the shell initialization script depends on the shell being used:

* For Gnu Bash, the location can be `~/.bash_profile`.
* For Zsh, the location can be `~/.zprofile` or `~/.zshrc`.
* For TCSH, the location can be `~/.cshrc`.

Check the documentation for the shell in use to be sure.

It is possible to also update the `PATH` environment variable to include the `kobiton` location.

[source,bash]
# Export authentication variables
export KOBITON_PORTAL=<PORTAL_URL>
export KOBITON_USER=<USERNAME>
export KOBITON_API_KEY=<API_KEY>
# Add kobiton executable path to PATH
export PATH=$PATH:<PATH_TO_KOBITON>

Exit the current shell instance, and launch a new one to apply the changes.

--

Windows - Command Prompt::

+
--

Run these commands to set the permanent environment variables for shell instances. It is possible to also update the `PATH` environment variable to include the tool locations.

[source,bash]
# Run the below to export authentication variables
setx KOBITON_PORTAL=<PORTAL_URL>
setx KOBITON_USER=<USERNAME>
setx KOBITON_API_KEY=<API_KEY>
# Run the below to add kobiton executable path to PATH
setx PATH "%PATH%;<PATH_TO_KOBITON>"

Exit the current shell instance, and launch a new one to apply the changes.

--

Windows - PowerShell::

+

--
Run these commands to set the permanent environment variables for shell instances. It is possible to also update the `PATH` environment variable to include the tool locations.

[source]
# Run the below to export authentication variables
[System.Environment]::SetEnvironmentVariable("KOBITON_PORTAL","<PORTAL_URL>","User")
[System.Environment]::SetEnvironmentVariable("KOBITON_USER","<USERNAME>","User")
[System.Environment]::SetEnvironmentVariable("KOBITON_API_KEY","<API_KEY>","User")
# Run the below to add kobiton executable path to PATH
[System.Environment]::SetEnvironmentVariable("PATH",$env:PATH + ";<PATH_TO_KOBITON>","User")

Exit the current shell instance, and launch a new one to apply the changes.

--

====

== Next steps

xref:use-the-cli.adoc[Start using] Kobiton CLI.