= Start using Kobiton Command Line Interface
:navtitle: Start using Kobiton CLI

Learn how to use Kobiton Command Line Interface to control and operate your private device lab.

== Before you start

* xref:set-up-cli.adoc[Set up] Kobiton CLI.

* Ensure private devices are available in the Kobiton Portal. Public devices are not supported.

== Create a CLI session

Open a terminal program on the computer.

Find a private device that is available (not in use or retained by other users):

[source]
kobiton device list --booked false --reserved false --private

Note down the UDID of the device to use.

Create a session on the device:

[source]
.Example
kobiton session create -u <UDID>

[source]
.Output
Session <SESSION_ID> created for device <UDID>.
Session token <SESSION_TOKEN>

Note down the `<SESSION_ID>` for later use.

Export the `<SESSION_TOKEN>` to the `KOBITON_SESSION_TOKEN` environment variable for later use

[tabs]
====

macOS and Linux::
+
--

[source]
export KOBITON_SESSION_TOKEN=<SESSION_TOKEN>

--

Windows - Powershell::
+
--
[source]
$env:KOBITON_SESSION_TOKEN="<SESSION_TOKEN>"
--

Windows - Command Prompt::
+
--
[source]
set KOBITON_SESSION_TOKEN=<SESSION_TOKEN>
--
====

Most CLI commands require either `SESSION_ID` or `KOBITON_SESSION_TOKEN`. See the next section for the list of commands and their basic usage.

[NOTE]
====

* For CLI sessions:

** No Session Explorer available.

** Session video and logs are not available in Session Overview.

** Mixed sessions between manual and CLI are not supported.

** CLI sessions time out after 10 minutes by default and can be configured for up to 2 hours. You can reset the timeout using the `kobiton session ping` command.

====

== List of commands

[NOTE]
====

Required parameters are marked *bold* in syntax. In the example below, `<KEYWORD>` is required, but `[OPTIONS]` is optional:

`kobiton app find [OPTIONS] *<KEYWORD>*`

====

=== `app run`

Run app on device.

.Syntax
----
kobiton app run [OPTIONS] <APP_IDENTIFIER> [ARGS]...
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable
====

.Example
[source,shell]
----
kobiton app run com.example.app
----

.Output
----
PID 32124
----

=== `app kill`

Kill app on device.

.Syntax
----
kobiton app kill [OPTIONS] <IDENTITY>
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable
====

.Example
[source,shell]
----
kobiton app kill com.example.app
----

=== `app install`

Install app on device.

.Syntax
----
kobiton app install [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-s <SESSION_ID>`
====

.Example
[source,shell]
----
kobiton app install -s 123 -n 651911
----

.Output
----
Install app successfully
----

=== `app uninstall`

Uninstall app on device.

.Syntax
----
kobiton app uninstall [OPTIONS] <APP_IDENTIFIER>
----

[NOTE]
====
`[OPTIONS]`: requires `-u <UDID>`
====

.Example
[source,shell]
----
kobiton app uninstall -u 3e4e7fe7 com.example.app
----

.Output
----
The application is uninstalled successfully
----

=== `app upload`

Upload an app to the Kobiton App Repo.

.Syntax
----
kobiton app upload [OPTIONS] <PATH> [APP_ID]
----

.Example
[source,shell]
----
kobiton app upload ./sample.apk
----

.Output
----
Application uploaded.  Parsing status OK.
App ID: 651911
Version ID: 739431
----

=== `app find`

Find an app on the Kobiton App Repo using keyword.

.Syntax
----
kobiton app find [OPTIONS] <KEYWORD>
----

[NOTE]
====
Put `<KEYWORD>` between double quotes for space or special character.
====

.Example
[source,shell]
----
kobiton app find "example app"
----

.Output
----
Name: Example App
Version: 4.1.1
App ID: 651911
Version ID: 739431
----

=== `file list`

List files on the specified path of the device.

.Syntax
----
kobiton file list [OPTIONS] [PATH]
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable.
If `[PATH]` is empty, the home location is used.
====

.Example (Android)
[source,shell]
----
kobiton file list /data/local/tmp
----

.Example (iOS)
[source,shell]
----
kobiton file list @com.sample.app:./Documents/
----

.Output
----
sampleFolder
sampleFile1.tmp
----

=== `file push`

Push a file to the specified path on the device.

.Syntax
----
kobiton file push [OPTIONS] <LOCAL_PATH> <REMOTE_PATH>
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable.
If `<REMOTE_PATH>` is empty, the home location is used.
====

.Example (Android)
[source,shell]
----
kobiton file push foo.dat /data/local/tmp/foo.dat
----

.Example (iOS)
[source,shell]
----
kobiton file push foo.dat @com.sample.app:./Documents/foo.dat
----

.Output
----
Pushed 505031 bytes to /data/local/tmp/foo.dat
----

=== `file pull`

Pull a file from the specified path on the device.

.Syntax
----
kobiton file pull [OPTIONS] <REMOTE_PATH> [LOCAL_PATH]
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable.
If `[LOCAL_PATH]` is empty, the current location is used.
====

.Example (Android)
[source,shell]
----
kobiton file pull /data/local/tmp/foo.dat foo.dat
----

.Example (iOS)
[source,shell]
----
kobiton file pull @com.example.app:./Documents/foo.dat foo.dat
----

.Output
----
Pulled 505031 bytes to foo.dat
----

=== `device list`

List devices.

.Syntax
----
kobiton device list [OPTIONS]
----

[NOTE]
====
Highly recommended to use:

* `--private`: filter only private devices.
* `--booked false`: filter only devices not in use.
* `--reserved false`: filter only devices not retained.
====

.Example
[source,shell]
----
kobiton device list --private --booked false --reserved false
----

.Output
----
Display Name, UDID, Platform, List, Status, Host
iPhone 12, 79de3c497b9f1****19040aeb44, iOS 18.1, Private, ACTIVATED, 192.168.50.86
----

=== `device adb-shell`

Run ADB shell command on Android device.

.Syntax
----
kobiton device adb-shell [OPTIONS] [ARGS]...
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable.
If `[ARGS]...` is not provided, launch an interactive adb shell.
====

.Example
[source,shell]
----
kobiton device adb-shell "dumpsys window displays | grep -E 'mCurrentFocus|mFocusedApp'"
----

.Output
----
mCurrentFocus=Window{272f9b1 u0 com.example.app/MainActivity}
mFocusedApp=ActivityRecord{3d12396 u0 com.example.app/.MainActivity t2823}
----

=== `device forward`

Forward a port on the device to a port on the local machine.

.Syntax
----
kobiton device forward [OPTIONS] <LOCAL_ADDRESS> <REMOTE_ADDRESS>
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable.
`<LOCAL_ADDRESS>` and `<REMOTE_ADDRESS>` must follow `tcp:<port>` format.
====

.Example
[source,shell]
----
kobiton device forward tcp:8080 tcp:80
----

.Output
----
Listening on 127.0.0.1:8080.
----

=== `device ps`

View running processes on the device.

.Syntax
----
kobiton device ps [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable.
====

.Example
[source,shell]
----
kobiton device ps
----

.Output
----
PID NAME
 1 init
 2 [kthreadd]
 3 [rcu_gp]
 5 [kworker/0:0H]
----

=== `session create`

Create a CLI session.

.Syntax
----
kobiton session create [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-u <UDID>`.
Use `-t` to set session timeout in minutes. Default/minimum is `10` and maximum is `120`.
====

.Example
[source,shell]
----
kobiton session create -u 3e4e7fe7
----

.Output
----
Session 8155111 created for device 3e4e7fe7.
Session token eyJhbGciOiJ...
----

=== `session end`

End an active session (all types).

.Syntax
----
kobiton session end [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-s <SESSION_ID>`
====

.Example
[source,shell]
----
kobiton session end -s 8155111
----

.Output
----
Session 8155111 ended.
----

=== `session terminate`

Terminate a non-responsive session (all types).

.Syntax
----
kobiton session terminate [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-s <SESSION_ID>`
====

.Example
[source,shell]
----
kobiton session terminate -s 8155111
----

.Output
----
Session 8155111 terminated.
----

=== `session delete`

Delete and remove a completed CLI session from the Session list.

.Syntax
----
kobiton session delete [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-s <SESSION_ID>`
====

.Example
[source,shell]
----
kobiton session delete -s 8155111
----

.Output
----
OK
----

=== `session ping`

Ping an active CLI session to reset the timeout counter.

.Syntax
----
kobiton session ping [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires *both* `-s <SESSION_ID>` and `KOBITON_SESSION_TOKEN` environment variable (or `-a <SESSION_TOKEN>`).
====

.Example
[source,shell]
----
export KOBITON_SESSION_TOKEN=<SESSION_TOKEN> # Skip if already imported
kobiton session ping -s 8155111
----

.Output
----
Session 8155111 pinged.
----

=== `session list-active`

List active sessions (all types).

.Syntax
----
kobiton session list-active [OPTIONS]
----

.Example
[source,shell]
----
kobiton session list-active
----

.Output
----
Session 8155111, device 3e4e7fe7, status RUNNING, created 2025-10-09T03:38:03Z, ended active
----

=== `session show`

Show details of a session (all types).

.Syntax
----
kobiton session show [OPTIONS]
----

[NOTE]
====
`[OPTIONS]`: requires `-s <SESSION_ID>`
====

.Example
[source,shell]
----
kobiton session show -s 8155111
----

.Output
----
Session 8155111: Session created at 10/09/2025 04:13 AM
Created: 2025-10-09T03:13:55.698Z
Ended: 2025-10-09T03:31:26.973Z
Device 3e4e7fe7: Android 11
Status: COMPLETE
----

=== `test run`

Run a native framework automation session (XCUITest, UIAutomator, or Espresso). GameDriver is not supported.

.Syntax
----
kobiton test run [OPTIONS] --app <APP> --runner <TEST_RUNNER> <FRAMEWORK>
----

[NOTE]
====
`[OPTIONS]`: different requirements based on framework:

* Either `-u <UDID>` or `-d <DEVICE_NAME>` is required for any framework.
* Either `-t <TESTS>` or `--plan <TEST_PLAN>` is required for XCUITest.
** `<TEST_PLAN>` must be a direct URL. Local path is not supported.

`<APP>` and `<TEST_RUNNER>` must be either Kobiton App Repo ID (`kobiton-store:<APP_ID>` or `kobiton-store:v<APP_VERSION_ID>`) or direct URL. Local path is not supported.
====

.Example (UIAutomator)
[source,shell]
----
kobiton test run --app kobiton-store:662537 --runner kobiton-store:v762538 -u 3e4e7fe7 uiautomator
----

.Example (Espresso)
[source,shell]
----
kobiton test run --app https://example.com/apps-test/espresso-app.apk --runner kobiton-store:v762559 -u 3e4e7fe7 uiautomator
----

.Example (XCUITest)
[source,shell]
----
kobiton test run --app kobiton-store:662538 --runner kobiton-store:v762548 --plan https://example.com/test-plans/sample.xctestplan -u 00008120-000E44D***28C01E xcuitest
----

.Output
----
#UIAutomator/Espresso
UIAUTOMATOR Session 8155157 started.
#XCUITest
XCUITEST Session 8155161 started.
#XCUITest with --follow
Session 8155172: XCUITEST test session
Created: 2025-10-09T04:25:41.896Z
Device 00008120-000E44D***28C01E: iOS 16.1
Status: START
Session 8155172: XCUITEST test session
Created: 2025-10-09T04:25:43.769Z
Ended: 2025-10-09T04:26:26.261Z
Device 00008120-000E44D***28C01E: iOS 16.1
Status: COMPLETE
Test Suite:
Tests: 2
Failures: 0
Errors: 0
Skipped: 0
Duration: 1.000
Start Time: 2025-10-09T11:24:58
End Time: 2025-10-09T11:24:59
XCUITestSampleUITests#testABC [0.402] PASSED
out: Start Test at 2025-10-09 11:24:58.275
out: Set Up
out: Tear Down
XCUITestSampleUITests#testXYZ [0.324] PASSED
out: Start Test at 2025-10-09 11:24:58.684
out: Set Up
out: Tear Down
----

[#_troubleshooting]
== Troubleshooting

If you run into an error while running the CLI commands, try the below steps:

* Double-check the command syntax and usage. It is possible to bring up the manual for each command by adding `-h` or `--help`. Examples:

** `kobiton --help` or `kobiton -h`
** `kobiton device --help` or `kobiton session -h`
** `kobiton device list -h` or `kobiton session create -h`

* If the error is not resolved, look up the error messages and their resolutions in the below table:

+

|===
|Message |Solution

|`environment variable not found`
|Export the environment variables for authentication.

|`The credential you entered was not authorized. Please double-check and try again.`
|Double-check the Kobiton account's username and API Key.

|`error sending request for url (/https://api.kobiton.com/v2/sessions): client error (Connect): dns error: failed to lookup address information: nodename nor servname provided, or not known`

`504 Gateway Time-out`
|Ensure the local machine can access the Cloud or Standalone Kobiton Portal

|`This command requires a session ID (-s).`
|Create a CLI session to get a `<SESSION_ID>`, then add `-s <SESSION_ID>` to the command.

|`This command requires a --session-token or KOBITON_SESSION_TOKEN env.  See session create.`
|Create a CLI session to get a `<SESSION_TOKEN>`, then add `-a <SESSION_TOKEN>` to the command or export the `KOBITON_SESSION_TOKEN` environment variable.

|`Session not found or already ended`
|The CLI session is not found or already completed. Create a new CLI session before running the command.

|`Device --udid is required.`
|Provide the UDID of the device using `-u <UDID>`


|===


