= Configure your personal computer for debugging
:navtitle: Configure personal computer
:tabs-sync-option:

Learn how to configure your personal computer, so you can debug local or private devices using virtualUSB.

[#_before_you_start]
== Before you start

You'll need to complete the following:

* xref:debugging:set-up-virtualusb.adoc[Set up virtualUSB] on your personal computer.

== Trust self-signed SSL certificate (Standalone/On-Prem only)

[NOTE]
The below steps are only needed if the Standalone/On=Prem portal is using a self-signed SSL certificate.

Request the IT administrator of your organization for the root CA certificate from which the SSL cert of the OP server is issued. It should be a file named `root.crt` or `ca.crt`. Then proceed to import the certificates.

[tabs]
====

MacOS::
+
--

Request the IT administrator of your organization for the end-entity certificate from which the SSL cert of the OP server is issued. It should be a file named `ssl.crt`. Tranfer the certificate file to the MacOS machine.

Open the Keychain Access application.

image:

Open Finder, go to the location of the `ssl.crt` file, then drag and drop the file into the Keychain Access application.

Double-click on the newly added certificate file. In the dialog, choose the Always Trust option from the dropdown list for the two fields:

* Secure Sockets Layer (SSL)

* X.509 Basic Policy

image:

Close the dialog and enter the admin password of the user workstation to save the changes.

--

Windows::
+
--

Request the IT administrator of your organization for the root CA certificate from which the SSL cert of the OP server is issued. It should be a file named `root.crt` or `ca.crt`. Tranfer the certificate file to the Windows machine.

On the Windows machine, double-click the file, then select Install Certificate on the Certificate window.

image:

On the next screen, choose Local Machine. This requires administrators privileges.

image:

On the next screen, choose Place all certificates in the following store, then select Browse.

image:

Choose Trusted Root Certification Authorities, then select OK.

image:

Select Next, then Finish. The root CA certificate is now imported to the end-user workstation trust store.

image:

--

====
