= Configure personal computer to use local devices
:navtitle: Configure personal computer

Learn how to configure your personal computer so you can debug local devices using virtualUSB.

[#_before_you_start]
== Before you start

You'll need to complete the following:

* xref:set-up-virtualusb.adoc[Set up virtualUSB] on your personal computer.
* To debug on a local Kobiton server, get xref:debugging:local-devices/configure-local-server.adoc#_get_server_information_for_your_team[server information] from your system administrator.

== Modify `config.ini`

In the terminal, open your `virtualUSB` directory:

.MacOS
[source,shell]
----
cd ~/Library/"Application Support"/virtualUSB
----

.Windows
[source,powershell]
----
cd C:\Users\<your-user-name>\AppData\Roaming\virtualUSB
----

Open the `config.ini` file in a text editor and modify the following lines:

[source,asciidoc]
----
Kobiton.ApiBaseUrl: https://<network-address>:<api-port-baseurl>
Kobiton.ApiGrpcBaseUrl: https://<network-address>:<api-port-grpc-baseurl>
----

Debugging a local device on _Kobiton Cloud_ versus _a local Kobiton server_ requires different values for `Kobiton.ApiBaseUrl` and `Kobiton.ApiGrpcBaseUrl`. Reference the following table to ensure you set the right values:

[cols="1,1,1,1"]
|===
|Placeholder|Description|Kobiton Cloud|Local Kobiton server

|`<network-address>`
|The server's network address.
|Set to `kobiton` or your organization's private domain name.
|Set to the value listed in your xref:_before_you_start[server information].

|`<api-port-baseurl>`
|The server's API port number for `Kobiton.ApiBaseUrl`.
|Remove `<api-port-baseurl>` from the string.
|Set to the value listed in your xref:_before_you_start[server information].

|`<api-port-grpc-baseurl>`
|The server's API Port number for `Kobiton.ApiGrpcBaseUrl`.
|Remove `<api-port-grpc-baseurl>` from the string.
|Set to the value listed in your xref:_before_you_start[server information].
|===

For example:

.Kobiton Cloud
[source,asciidoc]
----
Kobiton.ApiBaseUrl: https://api.mycompany.com
Kobiton.ApiGrpcBaseUrl: https://proxy-api-public-grpc-server.mycompany.com
----

.Local Kobiton server
[source,asciidoc]
----
Kobiton.ApiBaseUrl: https://192.168.36.24:3000
Kobiton.ApiGrpcBaseUrl: https://192.168.36.24:3001
----

When you're finished, save the file, then restart your virtualUSB application to apply the changes. Now you can debug local devices using virtualUSB.
