= Configure your personal computer for local devices
:navtitle: Configure personal computer

Learn how to configure your personal computer so you can debug local devices using virtualUSB.

[#_before_you_start]
== Before you start

You'll need to complete the following:

* xref:debugging:set-up-virtualusb.adoc[Set up virtualUSB] on your personal computer.
* To debug on Kobiton Standalone, get xref:debugging:local-devices/configure-kobiton-standalone-server.adoc#_get_server_details_for_your_team[server details] from your system administrator.

== Modify `config.ini`

In the terminal, open the `virtualUSB` directory:

.MacOS
[source,shell]
----
cd ~/Library/"Application Support"/virtualUSB
----

.Windows
[source,powershell]
----
cd C:\Users\<your-user-name>\AppData\Roaming\virtualUSB
----

Open `config.ini` in a text editor and look for the following lines:

[source,plaintext]
----
Kobiton.ApiBaseUrl: https://<network-address>:<api-port-baseurl>
Kobiton.ApiGrpcBaseUrl: https://<network-address>:<api-port-grpc-baseurl>
----

Debugging a local device on *Kobiton Cloud* versus a *Kobiton Standalone* requires different values for `Kobiton.ApiBaseUrl` and `Kobiton.ApiGrpcBaseUrl`. Use the following to assign the correct values:

[cols="1,2,2,2"]
|===
|Placeholder|Description|Kobiton Cloud|Kobiton Standalone

|`<network-address>`
|The server's network address.
|Set to `kobiton`, or your organization's private domain name.
|Set to the value listed in your xref:_before_you_start[server information].

|`<api-port-baseurl>`
|The server's API port number for `Kobiton.ApiBaseUrl`.
|Only needed for Kobiton Standalone. Remove `<api-port-baseurl>` from the string.
|Set to the value listed in your xref:_before_you_start[server information].

|`<api-port-grpc-baseurl>`
|The server's API Port number for `Kobiton.ApiGrpcBaseUrl`.
|Only needed for Kobiton Standalone. Remove `<api-port-grpc-baseurl>` from the string.
|Set to the value listed in your xref:_before_you_start[server information].
|===

.Kobiton Cloud
[source,plaintext]
----
Kobiton.ApiBaseUrl: https://api.mycompany.com
Kobiton.ApiGrpcBaseUrl: https://proxy-api-public-grpc-server.mycompany.com
----

.Kobiton Standalone
[source,plaintext]
----
Kobiton.ApiBaseUrl: https://192.168.36.24:3000
Kobiton.ApiGrpcBaseUrl: https://192.168.36.24:3001
----

When you're finished, save the file, then restart your virtualUSB application to apply the changes. Now you can debug local devices using virtualUSB.
