= Configure Mac mini hosts for Hybrid or Standalone
:navtitle: Configure Mac mini hosts for Hybrid or Standalone

Learn how to configure the Mac mini hosts so Hybrid and Standalone/On-Prem users can debug with your organization's devices using virtualUSB.

== Before you start

You'll need to verify your system administrator privileges for your Kobiton Mac mini hosts.


== Modify `dc.ini` on the Mac mini host

[NOTE]
The `dc.ini` file needs to be modified for _each Mac mini host_ before virtualUSB can be used.

On the Mac mini host, edit the `dc.ini` file located under `/usr/local/deviceconnect` and add the following environment variables:

[source,plaintext]
----
GatewayPublicAddress=<ip-address> # Set to the Mac mini host's private or public IP address.
ExternalAirstreamTlsPort=<port-number> # Set to 10161 or public port.
----

.Example
[source,shell]
----
GatewayPublicAddress=192.168.36.36
ExternalAirstreamTlsPort=10161
----

Save the file, then xref:device-lab-management:deviceConnect/restart-deviceconnect-services.adoc[restart deviceConnect services,window=read-later] to apply the changes.

Now users in your organization can use virtualUSB for private or local devices hosted on the Hybrid or Standalone/On-Prem Mac mini hosts.
