== Kobiton Portal and the SSO settings page

. Navigate to your Kobiton portal and log in. In the upper-right corner beside the user module icon, click the dropdown arrow to expand the account dropdown menu. Click “Settings”.
+
image:./guide-media/01GWDZ164XDBP6R0V9GN15XRQ6[width=, alt="SSO_K1o5.png"]

. Click on the “SSO Settings” tab in the banner across the top of the screen. Your screen will now display the first section of the SSO settings configuration screen. (See image below step 3.)
. In the “Step 1: Basic configuration” box, Kobiton has already provided the Audience URL and Reply URL; you will need to copy these links and paste them in the appropriate fields in your preferred IdP’s configuration process. Input y
+
image:./guide-media/01GWEBXMR3RZF9DPB33SH3X3V2[width=, alt="SSO_K2o5.png"]

. In the “Step 2: User attributes (or parameters)” box, you can fill in attributes for mapping that you can then copy and paste into the corresponding fields with your IdP.
+
image:./guide-media/01GWEJY4RHQ9WKJ0TD3TH8Q0EY[width=, alt="SSO_K3o5.png"]

.In the "Step 3: Set up at Kobiton side" box, you will need to copy the corresponding information _from_ _your IdP's configuration page_ to these fields. You can find specific details in the guides below.
+
image:./guide-media/01GWE5594HQ74V7H648FV6W3RH[width=, alt="SSO_K4o5.png"]

.In the "Step 4: Verify Configuration" box, you can click the "Verify" button to have Kobiton test your SSO configuration. There is also an optional toggle that will allow you to enforce an SSO login to Kobiton for all your users, should you wish to make SSO mandatory across your organization.
+
image:./guide-media/01GWE6JBRQV5CJ67HQ5DT9T272[width=, alt="mceclip0.png"]

.If you do choose to utilize the login toggle in the previous step, a fifth box will appear on your SSO settings page, labeled "Step 5: Specify Organization Access Restrictions". In this box you can define the assertion specifying an admin role; you can then test to make sure this admin role can successfully log in using your SSO/SAML configuration. There is also an optional toggle that allows you to pass your role/team assignments between your IdP and Kobiton to sync them. There is no continual or scheduled synchronization of data, but if this toggle is enabled, synchronization will occur at the time of user login.
+
image:./guide-media/01GWE775THSDC1Z3A1433WATPD[width=, alt="SSO_K6o6.png"]

.Once all your configuration changes are made, be sure to click the "Save" button at the bottom of the page to confirm and apply your changes.

IMPORTANT NOTE: If you choose to enforce SSO and you wish to reverse that setting for some or all of your users, please have the affected users go to the Kobiton log in page and click "Forgot Password" to have a new password set for their account.

Below are step-by-step guides for some of the more common IdPs you may use with Kobiton.
