= Use the Command Line Interface
:navtitle: Use the CLI

Learn how to use the Command Line Interface (CLI) to control and operate your private device lab.

== Before you start

* Obtain the username and API key from a Kobiton Enteprise account.
* Have private devices available in the Kobiton Portal.
* Contact Kobiton support for the link to download the CLI package. The package is available for the below platforms:
** macOS - ARM64 (for Macs with Apple silicon)
** Linux - x64
** Windows - x64

== Setup and authentication

[tabs]

====

macOS or Linux::
+
--

Open the terminal on the machine.

Navigate to the path of the downloaded CLI package.

Extract the download package into the `kobiton` executable file.

[source,bash]
tar -zxvf kobiton-cli.<platform>.<version>.tgz

Export the following environment variables for authentication using the command `export <VARIABLE_NAME>=<VALUE>`

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.com`. *Example*: `\https://api-acme-prodv2.com`
** Standalone: user `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[source,bash]
.Examples
# Use one of the below based on the deployment type
export KOBITON_PORTAL=https://api.kobiton.com # Cloud/Hybrid
export KOBITON_PORTAL=https://api-acme-prodv2.kobiton.com # Cloud/Hybrid with custom domain
export KOBITON_PORTAL=https://acme.kobiton.local:3000 # Standalone
# Obtain the below from the Profile and Settings page of the Kobiton Portal
export KOBITON_USER=johndoe
export KOBITON_API_KEY=be99***0-c*df-4224-aed6-907****92d0

[TIP]
=====
Put the export commands for the above variables in a `.env` file, then run `source <env-filename>` to export all variables.

[source,bash]
.Example
# The below assumes that all required export variables command are in the file variables.env
source variables.env
=====
--

Windows::
+
--

Open the location of the downloaded CLI package in File Explorer.

Right-click the `kobiton-cli.win-x64.<version>.zip` package and select *Extract All...*, then choose *Extract*. This results in a folder with the file `kobiton.exe`.

Open *Powershell*, then navigate to the location of the `kobiton.exe` file.

Export the following environment variables for authentication using the command `$env:<VARIABLE_NAME>="<VALUE>"` in Powershell.

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.com`. *Example*: `\https://api-acme-prodv2.com`
** Standalone: user `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[source,bash]
.Cloud/Hybrid
# Use one of the below based on the deployment type
$env:KOBITON_PORTAL = "https://api.kobiton.com" # Cloud/Hybrid
$env:KOBITON_PORTAL = "https://api-acme-prodv2.kobiton.com" # Cloud/Hybrid with custom domain
$env:KOBITON_PORTAL = "https://acme.kobiton.local:3000" # Standalone
# Obtain the below from the Profile and Settings page of the Kobiton Portal
$env:KOBITON_USER = "johndoe"
$env:KOBITON_API_KEY = "be99***0-c*df-4224-aed6-907****92d0"

[NOTE]
=====
For *Command Prompt* (cmd.exe), use the below command instead to set environment variables:
[source,bash]
set KOBITON_PORTAL=https://api.kobiton.com
set KOBITON_USER=johndoe
set KOBITON_API_KEY=be99***0-c*df-4224-aed6-907****92d0
=====

--
====

After the CLI has been set up for the appropriate platform, run the below command from the same location as the `kobiton` file to check if the variables are valid and the CLI is working:

[tabs]

====

macOS, Linux, Windows - Powershell::
+
--

[source]
----
./kobiton device list --private
----

--

Windows - Command Prompt::
+
--
[source]
kobiton device list --private
--
====

If the device list is returned without any error, then the CLI is set up and ready for use.

If there is any error, follow the troubleshooting section to resolve the issue.

== (Optional) Add environment variables to shell initialization script

[tabs]
====

macOS or Linux::

+

--

These commands can be added to the shell initialization script to set the variables each time a new shell instance is run.

The location of the shell initialization script depends on the shell being used:

* For Gnu Bash, the location can be `~/.bash_profile`.
* For Zsh, the location can be `~/.zprofile` or `~/.zshrc`.
* For TCSH, the location can be `~/.cshrc`.

Check the documentation for the shell that you're using to be sure.

You can also update the `PATH` environment variable to include the `kobiton` location.

[source,bash]
# Export authentication variables
export KOBITON_PORTAL=<PORTAL_URL>
export KOBITON_USER=<USERNAME>
export KOBITON_API_KEY=<API_KEY>
# Add kobiton executable path to PATH
export PATH=$PATH:<PATH_TO_KOBITON>

Exit the current shell instance, and launch a new one to apply the changes.

--

Windows - Command Prompt::

+
--

Run these commands to set the permanent environment variables for shell instances. You can also update the `PATH` environment variable to include the tool locations.

[source,bash]
# Run the below to export authentication variables
setx KOBITON_PORTAL=<PORTAL_URL>
setx KOBITON_USER=<USERNAME>
setx KOBITON_API_KEY=<API_KEY>
# Run the below to add kobiton executable path to PATH
setx PATH "%PATH%;<PATH_TO_KOBITON>"

Exit the current shell instance, and launch a new one to apply the changes.

--

Windows - PowerShell::

+

--
Run these commands to set the permanent environment variables for shell instances. You can also update the `PATH` environment variable to include the tool locations.

[source]
# Run the below to export authentication variables
[System.Environment]::SetEnvironmentVariable("KOBITON_PORTAL","<PORTAL_URL>","User")
[System.Environment]::SetEnvironmentVariable("KOBITON_USER","<USERNAME>","User")
[System.Environment]::SetEnvironmentVariable("KOBITON_API_KEY","<API_KEY>","User")
# Run the below to add kobiton executable path to PATH
[System.Environment]::SetEnvironmentVariable("PATH",$env:PATH + ";<PATH_TO_KOBITON>","User")

Exit the current shell instance, and launch a new one to apply the changes.

--

====

== Using the CLI

[NOTE]
====

All commands in this section assumes that:

* The location of the `kobiton` executable has been added to `PATH`.

* The environment variables for authentication have been set.

====

=== Create a session

Most of the functionalities of the CLI requires a CLI session. To create a session:

Find a private device that is available (not in use or retained by other users):

[source]
kobiton device list --booked false --reserved false --private

Note down the UDID of the device to use.

Create a session on the device:

[source]
.Example
kobiton session create -u <UDID>

[source]
.Output
Session <SESSION_ID> created for device <UDID>.
Session token <TOKEN>

Note down the `SESSION_ID` for later user.

Export the `TOKEN` to the `KOBITON_SESSION_TOKEN` environment variable for later use

[tabs]
====

macOS and Linux::
+
--

[source]
export KOBITON_SESSION_TOKEN=<TOKEN>

--

Windows - Powershell::
+
--
[source]
$env:KOBITON_SESSION_TOKEN="<TOKEN>"
--

Windows - Command Prompt::
+
--
[source]
set KOBITON_SESSION_TOKEN=<TOKEN>
--
====

For commands that need to be run within a CLI session, either `SESSION_ID` or `KOBITON_SESSION_TOKEN` is required. See the next section for the list of commands and their basic usage.

=== List of commands

[NOTE]
====

Required parameters are marked *bold* in syntax. In the example below, `<KEYWORD>` is required, but `[OPTIONS]` is optional:

`kobiton app find [OPTIONS] *<KEYWORD>*`

====
[cols="1,1,3,4,4"]
|===
|Category|Operation|Description|Syntax|Example

.6+|App

|Run
|Run app on device
a|`kobiton app run *[OPTIONS]* *<APP_IDENTIFIER>* [ARGS]...`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable
a|
[source]
kobiton app run 

|Kill
|Kill app on device
a|`kobiton app kill *[OPTIONS]* *<IDENTITY>*`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable
|

|Install
|Install app on device
a|`kobiton app install *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Uninstall
|Uninstall app on device
a|`kobiton app uninstall *[OPTIONS]* *<APP_IDENTIFIER>*`

`[OPTIONS]`: requires `-u <UDID>`

This operation does not need a CLI session.
|

|Upload
|Upload an app to the Kobiton App Repo
a|`kobiton app upload [OPTIONS] *<PATH>* [APP_ID]`
|

|Find
|Find an app on the Kobiton App Repo using keyword
a|`kobiton app find [OPTIONS] *<KEYWORD>*`

Put <KEYWORD> between double quotes for space or special character.
|

.3+|File

|List
|List file on the specified path of the device
a|`kobiton file list *[OPTIONS]* [PATH]`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable

If `[PATH]` is empty, the home location is used.
|

|Push
|Push a file to the specified path on the device
a|`kobiton file push *[OPTIONS]* *<LOCAL_PATH>* <REMOTE_PATH>`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable

If `[REMOTE_PATH]` is empty, the home location is used.
|

|Pull
|Pull a file from the specified path on the device
a|`kobiton file pull *[OPTIONS]* *<REMOTE_PATH>* [LOCAL_PATH]`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable

If `[LOCAL_PATH]` is empty, the current location is used.
|

.4+|Device

|List
|List devices
a|`kobiton device list [OPTIONS]`

Highly recommended to use:

* `--private`: filter only private devices.

* `--booked false`: filter only devices not in use.

* `--reserved false`: filter only devices not retained.
|

|ADB shell
|Run ADB shell command on Android device
a|`kobiton device adb-shell *[OPTIONS]* [ARGS]...`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable

If `[ARGS]...` is not provided, launch an interactive adb shell.

|

|Forward
|Forward a port on the device to a port on the local machine
a|`kobiton device forward *[OPTIONS]* *<LOCAL_ADDRESS>* *<REMOTE_ADDRESS>*`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable

`<LOCAL_ADDRESS>` and `REMOTE_ADDRESS` must follows `tcp:<port>` format
|

|PS
|View running processes on the device
a|`kobiton device ps *[OPTIONS]*`

`[OPTIONS]`: requires `-a <SESSION_TOKEN>` or `KOBITON_SESSION_TOKEN` environment variable
|

.7+| Session

|Create
|Create a CLI session
a|`kobiton session create *[OPTIONS]*`

`[OPTIONS]`: requires `-u <UDID>`

Use `-t` to set session timeout in minutes. Default/minimum is `10` and maximum is `120`.
|

|End
|End an active session (all types)
a|`kobiton session end *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Terminate
|Terminate a non-responsive session (all types)
a|`kobiton session terminate *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Delete
|Delete and remove a completed CLI session from the Session list
a|`kobiton session delete *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Ping
|Ping an active CLI session to reset the timeout counter
a|`kobiton session ping *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|List active
|List active sessions (all types)
a|`kobiton session list-active [OPTIONS]`
|

|Show
|Show details of a session (all types)
a|`kobiton session show *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Test

|Run
a|Run a native framework automation session (XCUITest, UIAutomator, Espresso). GameDriver is not supported.
a|`kobiton test run *[OPTIONS]* --app *<APP>* --runner *<TEST_RUNNER>* *<FRAMEWORK>*`

`[OPTIONS]`: different requirements based on framework:

* Either `-u <UDID>` or `-d <DEVICE_NAME>` is required for any framework

* Either `-t <TESTS>` or `--plan <TEST_PLAN>` is required for XCUITest
|

|===