= Use Command Line Interface
:navtitle: Use the CLI

Learn how to use the Command Line Interface (CLI) to control and operate your private device lab.

== Before you start

* Obtain the username and API key from a Kobiton Enteprise account.
* Have private devices available in the Kobiton Portal.
* Contact Kobiton support for the link to download the CLI package. The package is available for the below platforms:
** macOS - ARM64 (for Macs with Apple silicon)
** Linux - x64
** Windows - x64

== Set up the CLI

[tabs]

====

macOS or Linux::
+
--

Open the terminal on the machine.

Navigate to the path of the downloaded CLI package.

Extract the download package into the `kobiton` executable file.

[source,bash]
tar -zxvf kobiton-cli.<platform>.<version>.tgz

Export the following environment variables using the syntax `export <VARIABLE_NAME>`

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.com`. *Example*: `\https://api-acme-prodv2.com`
** Standalone: user `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[TIP]
Put the export commands for the above variables in a `.env` file, then run `source <env-filename>` to export all variables.

From the same location as the `kobiton` file, run the below command to check if the variables are valid and the CLI is working:

[source,bash]
----
./kobiton device list --online true --private
----

If the device list is returned without any error, then the CLI is set up and ready for use.

If there is any error, follow the troubleshooting section to resolve the issue.

--

Windows::
+
--



--
====