= Use the Command Line Interface
:navtitle: Use the CLI

Learn how to use the Command Line Interface (CLI) to control and operate your private device lab.

== Before you start

* Obtain the username and API key from a Kobiton Enteprise account.
* Have private devices available in the Kobiton Portal.
* Contact Kobiton support for the link to download the CLI package. The package is available for the below platforms:
** macOS - ARM64 (for Macs with Apple silicon)
** Linux - x64
** Windows - x64

== Set up the CLI

[tabs]

====

macOS or Linux::
+
--

Open the terminal on the machine.

Navigate to the path of the downloaded CLI package.

Extract the download package into the `kobiton` executable file.

[source,bash]
tar -zxvf kobiton-cli.<platform>.<version>.tgz

Export the following environment variables using the command `export <VARIABLE_NAME>=<VALUE>`

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.com`. *Example*: `\https://api-acme-prodv2.com`
** Standalone: user `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[source,bash]
.Examples
# Use one of the below based on the deployment type
export KOBITON_PORTAL=https://api.kobiton.com # Cloud/Hybrid
export KOBITON_PORTAL=https://api-acme-prodv2.kobiton.com # Cloud/Hybrid with custom domain
export KOBITON_PORTAL=https://acme.kobiton.local:3000 # Standalone
# Obtain the below from the Profile and Settings page of the Kobiton Portal
export KOBITON_USER=johndoe
export KOBITON_API_KEY=be99***0-c*df-4224-aed6-907****92d0

[TIP]
=====
Put the export commands for the above variables in a `.env` file, then run `source <env-filename>` to export all variables.

[source,bash]
.Example
# The below assumes that all required export variables command are in the file variables.env
source variables.env
=====
--

Windows::
+
--

Open the location of the downloaded CLI package in File Explorer.

Right-click the `kobiton-cli.win-x64.<version>.zip` package and select *Extract All...*, then choose *Extract*. This results in a folder with the file `kobiton.exe`.

Open *Powershell*, then navigate to the location of the `kobiton.exe` file.

Export the following environment variables using the command `$env:<VARIABLE_NAME>="<VALUE>"` in Powershell.

* `KOBITON_PORTAL`: the API URL of the Kobiton Portal.
** Cloud/Hybrid: use `\https://api.kobiton.com`
** Cloud/Hybrid with custom domain: use `\https://api-<custom-domain>.com`. *Example*: `\https://api-acme-prodv2.com`
** Standalone: user `https://<Dell-IP-or-domain>:3000`, where <Dell-IP-or-domain> is the IP address or domain of the Dell server where the Portal is accessible.
* `KOBITON_USER`: the Kobiton username.
* `KOBITON_API_KEY`: the Kobiton API Key.

[source,bash]
.Cloud/Hybrid
# Use one of the below based on the deployment type
$env:KOBITON_PORTAL = "https://api.kobiton.com" # Cloud/Hybrid
$env:KOBITON_PORTAL = "https://api-acme-prodv2.kobiton.com" # Cloud/Hybrid with custom domain
$env:KOBITON_PORTAL = "https://acme.kobiton.local:3000" # Standalone
# Obtain the below from the Profile and Settings page of the Kobiton Portal
$env:KOBITON_USER = "johndoe"
$env:KOBITON_API_KEY = "be99***0-c*df-4224-aed6-907****92d0"

[NOTE]
=====
For *Command Prompt* (cmd.exe), use the below command instead to set environment variables:
[source,bash]
set KOBITON_PORTAL=https://api.kobiton.com
set KOBITON_USER=johndoe
set KOBITON_API_KEY=be99***0-c*df-4224-aed6-907****92d0
=====

--
====

After the CLI has been set up for the appropriate platform, run the below command from the same location as the `kobiton` file to check if the variables are valid and the CLI is working:

[tabs]

====

macOS, Linux, Windows - Powershell::
+
--

[source]
----
./kobiton device list --private
----

--

Windows - Command Prompt::
+
--
[source]
kobiton device list --private
--
====

If the device list is returned without any error, then the CLI is set up and ready for use.

If there is any error, follow the troubleshooting section to resolve the issue.

== (Optional) Add CLI to PATH and set permanent environment variables



== Using the CLI

[NOTE]
All commands in this section assumes that location of the `kobiton` executable has been added to `PATH`.

=== Create a session

Most of the functionalities of the CLI requires a CLI session. To create a session:

Find a private device that is available (not in use or retained by other users):

[source]
kobiton device list --booked false --reserved false --private

Note down the UDID of the device to use.

Create a session on the device:

[source]
.Example
kobiton session create -u <UDID>

[source]
.Output
Session <SESSION_ID> created for device <UDID>.
Session token <TOKEN>

Note down the `SESSION_ID` for later user.

Export the `TOKEN` to the `KOBITON_SESSION_TOKEN` environment variable for later use

[tabs]
====

macOS and Linux::
+
--

[source]
export KOBITON_SESSION_TOKEN=<TOKEN>

--

Windows - Powershell::
+
--
[source]
$env:KOBITON_SESSION_TOKEN="<TOKEN>"
--

Windows - Command Prompt::
+
--
[source]
set KOBITON_SESSION_TOKEN=<TOKEN>
--
====

Depending on the command, either `SESSION_ID` or `KOBITON_SESSION_TOKEN` is required. Some commands do not require either of them. See the next section for the list of commands and their basic usage.

=== List of commands

[NOTE]
====

Required parameters are marked *bold* in syntax. In the example below, `<KEYWORD>` is required, but `[OPTIONS]` is optional:

`kobiton app find [OPTIONS] *<KEYWORD>*`

====
[cols="1,1,3,4,4"]
|===
|Category|Operation|Description|Syntax|Example

.6+|App

|Run
|Run app on device
a|`kobiton app run *[OPTIONS]* *<APP_IDENTIFIER>* [ARGS]...`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`

|

|Kill
|Kill app on device
a|`kobiton app kill *[OPTIONS]* *<IDENTITY>*`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`
|

|Install
|Install app on device
a|`kobiton app install *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Uninstall
|Uninstall app on device
a|`kobiton app uninstall *[OPTIONS]* *<APP_IDENTIFIER>*`

`[OPTIONS]`: requires `-u <UDID>`

This operation does not need a CLI session.
|

|Upload
|Upload an app to the Kobiton App Repo
a|`kobiton app upload [OPTIONS] *<PATH>* [APP_ID]`
|

|Find
|Find an app on the Kobiton App Repo using keyword
a|`kobiton app find [OPTIONS] *<KEYWORD>*`

Put <KEYWORD> between double quotes for space or special character.
|

.3+|File

|List
|List file on the specified path of the device
a|`kobiton file list *[OPTIONS]* [PATH]`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`

If `[PATH]` is empty, the home location is used.
|

|Push
|Push a file to the specified path on the device
a|`kobiton file push *[OPTIONS]* *<LOCAL_PATH>* <REMOTE_PATH>`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`

If `[REMOTE_PATH]` is empty, the home location is used.
|

|Pull
|Pull a file from the specified path on the device
a|`kobiton file pull *[OPTIONS]* *<REMOTE_PATH>* [LOCAL_PATH]`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`

If `[LOCAL_PATH]` is empty, the current location is used.
|

.4+|Device

|List
|List devices
a|`kobiton device list [OPTIONS]`

Highly recommended to use:

* `--private`: filter only private devices.

* `--booked false`: filter only devices not in use.

* `--reserved false`: filter only devices not retained.
|

|ADB shell
|Run ADB shell command on Android device
a|`kobiton device adb-shell *[OPTIONS]* [ARGS]...`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`

If `[ARGS]...` is not provided, launch an interactive adb shell.

|

|Forward
|Forward a port on the device to a port on the local machine
a|`kobiton device forward *[OPTIONS]* *<LOCAL_ADDRESS>* *<REMOTE_ADDRESS>*`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`

`<LOCAL_ADDRESS>` and `REMOTE_ADDRESS` must follows `tcp:<port>` format
|

|PS
|View running processes on the device
a|`kobiton device ps *[OPTIONS]*`

`[OPTIONS]`: requires `-a <KOBITON_SESSION_TOKEN>`
|

.7+| Session

|Create
|Create a CLI session
a|`kobiton session create *[OPTIONS]*`

`[OPTIONS]`: requires `-u <UDID>`

Use `-t` to set session timeout in minutes. Default/minimum is `10` and maximum is `120`.
|

|End
|End an active session (all types)
a|`kobiton session end *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Terminate
|Terminate a non-responsive session (all types)
a|`kobiton session terminate *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Delete
|Delete and remove a completed CLI session from the Session list
a|`kobiton session delete *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Ping
|Ping an active CLI session to reset the timeout counter
a|`kobiton session ping *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|List active
|List active sessions (all types)
a|`kobiton session list-active [OPTIONS]`
|

|Show
|Show details of a session (all types)
a|`kobiton session show *[OPTIONS]*`

`[OPTIONS]`: requires `-s <SESSION_ID>`
|

|Test

|Run
|
|
|

|===