= Manual Testing Overview

Welcome to the help section on manual testing! In this section you will learn everything you need to know on Kobiton's manual testing. From the high-level, like how to find the test device, to the detailed, like how to spoof the device's location during the manual test.

== The Flow

Manual Testing is one of three types of testing you can perform on Kobiton. To explore the other types of testing on Kobiton, hop over to the sections on xref:automation-testing:ROOT:automation_testing_overview.adoc[Automation Testing] and Scriptless Testing.

image::manual_testing_flow.svg[title="Manual Testing Flow"]

[NOTE]
Kobiton offers https://training.kobiton.com/unit/view/id:2196[a free, video-led training course] where you can become a certified Manual Testing Specialist.

. xref:select_and_launch_device.adoc[Select and Launch Device]
. xref:install_app.adoc[Install App]
. xref:perform_manual_test.adoc[Perform Manual Test]
. xref:analyze_results.adoc[Analyze Results]
. xref:extended_workflows.adoc[Extended Workflows]

