= Manage roles
:navtitle: Manage roles

Learn how to manage roles for your organization, so you can leverage xref:about-role-based-access-control.adoc[Role-Based Access Control (RBAC)]. In *Org Management*, select *Roles*, then choose a role to get started.

image:<NEW-IMAGE>[width=,alt=""]

== Change a role name

In *Details*, enter a new name.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Change a role description

In *Details*, enter a new description.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Clone a role

In *Details*, select *Clone* to create a copy of the role.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Disable a role

In *Details*, select *Disable* to deactivate the role but keep it in your system.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Delete a role

In *Details*, select *Delete* to completely remove a role from your system.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Assign a role to a user

In *Members*, select *Add Members*, then search for the user you want to assign the role to.

image:<NEW-IMAGE>[width=,alt=""]

Select the *plus icon* next to the user.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove a role from a user

In *Members*, search for the user you want to remove the role from.

image:<NEW-IMAGE>[width=,alt=""]

Select the *minus icon* next to the user.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

[#_set_permissions]
== Set permissions

In *Permissions*, add or remove permissions from the role.

[NOTE]
xref:roles/user-roles-and-permissions.adoc[See full list of user roles and permissions].

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]
