= Role permissions
:navtitle: Role permissions

$DESCRIPTION$

Every user is assigned a role to determine what actions they can take in the Kobiton portal. These roles can be customized so that different users have unique sets of permissions (for example, a role called "App Manager" that has all app repo permissions assigned and none of the others, or a "Universal" role with all of the permissions assigned.) The actions contained in each permissions are described below:

== Predefined roles

=== Admin

THIS

=== Member

THIS

== Permissions

=== App Repo

==== `app_repo.delete_other_application`

Delete other users' public apps (this also includes private apps if the view_all permissions below is enabled)

==== `app_repo.view_all_application`

View all public/locked apps

==== `app_repo.upload_application`

Upload app; can also rename an app uploaded by the user previously

=== Device

==== `device.custom_device_name`

User can create custom device name

==== `device.tag_devices`

User can create tags for devices

=== Org Management

==== `org_management.modify`

User has access to all abilities in org management tab (create, edit, invite user, etc… for Groups/Roles/Users/Devices Bundle

=== Settings

==== `org_setting.modify`

View and edit cleanup policy (org level) + iFrame + Integration (disable/enable) + Other Settings

==== `org_setting.modify_sso_setting`

View and edit SSO settings/configuration

[#_org_setting_modify_security_banner]
=== `org_setting.modify_security_banner`

THIS

=== Session

==== `session.view_all_session`

View all sessions in the org

==== `session.terminate_other_session`

Terminate others (all) session

==== `session.modify_other_session`

Modify information of session (e.g, session name, etc.); also allows user to delete sessions

=== Softbook

==== `soft_book.terminate_other_soft_book`

Delete other users' softbook

