= User roles and permissions
:navtitle: Roles and permissions

These are the predefined roles and the permissions for your organization. You can also use these permissions when you xref:organization:roles/create-a-role.adoc[create a new role] or xref:organization:roles/manage-roles.adoc#_set_permissions[change a role's permissions].

== Predefined roles

By default, the following roles are predefined and cannot be changed:

=== Organization Owner

The owner of the Kobiton account is given xref:_permissions[all user permissions]. This role can only be transferred to another user xref:organization:transfer-your-organization.adoc[by the current Organization Owner].

=== ADMIN

The ADMIN role must be assigned by the Organization Owner or another ADMIN. ADMINs are given xref:_permissions[all user permissions] and permissions to manage all devices in the organization in the settings.

=== MEMBER

Every user xref:organization:users/invite-a-user.adoc[invited to your organization] is assigned the MEMBER role and given the following permissions:

* xref:_system_login[]
* xref:_system_logout[]
* xref:_app_repo_view_all_application[]

[#_permissions]
== Permissions

[#_system_login]
=== `system.login`

Allows a user to log in to Kobiton. _Always required._

[#_system_logout]
=== `system.logout`

Allows a user to log out of Kobiton. _Always required._

=== `app_repo.delete_other_application`

Allows a user to delete public apps in the app repository. If xref:_app_repo_view_all_application[] is assigned, the user can also delete private apps.

[#_app_repo_view_all_application]
=== `app_repo.view_all_application`

Allows a user to view all apps in the app repository, including private and locked apps.

=== `app_repo.upload_application`

Allows a user to upload and rename any apps they previously uploaded.

=== `device.custom_device_name`

Allows a user to create custom device names.

=== `device.tag_devices`

Allows a user to create device tags.

=== `org_management.modify`

Allows a user to manage all teams, roles, users, and device bundles.

=== `org_setting.modify`

Allows a user to manage all organization settings, including cleanup policies, integrations, configurations, and more.

=== `org_setting.modify_sso_setting`

Allows a user to manage all Single-Sign On (SSO) authentication settings.

[#_org_setting_modify_security_banner]
=== `org_setting.modify_security_banner`

Allows a user to change the portal login message.

=== `session.view_all_session`

Allows a user to view all test sessions.

=== `session.terminate_other_session`

Allows a user to end another user's test session.

=== `session.modify_other_session`

Allows a user to change session details and delete sessions.

=== `soft_book.terminate_other_soft_book`

Allows a user to remove the retention of any device by any user.

[#_org_setting_reboot_private_device]
=== `org_setting.reboot_private_device`

Allows a user without the `ADMIN` predefined role to restart assigned devices from the xref:devices:manage-devices.adoc#_restart_private_device[manage device,window=read-later] page.
