= Create a team
:navtitle: Create a team

Learn how to create a team in your organization so you can set user roles, assign devices, and more.

== Create a team

In *Org Management*, select *Teams*, then *Create*.

image:<NEW-IMAGE>[width=, alt=""]

In *Details*, enter a team name and description, then select *Settings*.

[NOTE]
You can select *Mark as Default* to make this xref:profile:your-teams.adoc[your default team].

image:<NEW-IMAGE>[width=, alt=""]

In *Settings*, choose to enable xref:teams/manage-teams.adoc#_private_test_mode[Private Test Mode] and a xref:teams/manage-teams.adoc#_cleanup_policy[Cleanup Policy], then select *Users*.

image:<NEW-IMAGE>[width=, alt=""]

In *Users*, use the search bar to assign users to the team, then select *Permissions*.

image:<NEW-IMAGE>[width=, alt=""]

In *Permissions*, choose permissions for each xref:teams/team-roles.adoc[team role], then select *Devices*.

image:<NEW-IMAGE>[width=, alt=""]

In *Devices*, choose to xref:teams/manage-team-devices.adoc[assign devices to the team].

image:<NEW-IMAGE>[width=, alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=, alt=""]


