= Manage teams
:navtitle: Manage teams

Learn how to manage your team, so you can clone your team, add team members, set member permissions, and more. In *Org Management*, select *Teams*, then choose a team to get started.

image:<NEW-IMAGE>[width=,alt=""]

== Clone a team

In *Details*, select *Clone* to create a copy of the team including all settings, users, permissions, and devices.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Disable a team

In *Details*, select *Disable* to disable the team.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Choose a default team

In *Details*, choose the team to be your xref:profile:your-teams.adoc[default team].

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Delete a team

In *Details*, select *Delete* to delete the team.

[NOTE]
Deleting a team cannot be undone.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

[#_private_test_mode]
== Enable private test mode

In *Settings*, select *Enable Private Test Mode* to turn off session recordings for all private devices, which includes any commands, screenshots, or videos typically recorded in a session.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

[#_cleanup_policy]
== Set a cleanup policy

In *Settings*, select the dropdown and choose a default cleanup policy, or xref:teams/create-a-device-cleanup-policy.adoc[create a new one] for the team.Team devices will be cleaned up after every session, so they're ready to use in the next one.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

[#_add_a_new_user]
== Add a new user

In *Users*, select *Add new user*, then choose a role: *Team Owner*, *Team Admin*, or *Team Member*.

image:<NEW-IMAGE>[width=,alt=""]

After you choose a role, search for a user.

[NOTE]
A user must be xref:users/invite-a-user.adoc[invited to your organization] before you can add them to a team.

image:<NEW-IMAGE>[width=,alt=""]

Choose the user, then select *Update*.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove a user

In *Users*, search for a user, then select the *minus icon*.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

[#_set_team_permissions]
== Set team permissions

In *Permissions*, choose permissions for each xref:teams/team-roles.adoc[team role].

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Manage devices

In *Device*, you can xref:teams/manage-team-devices.adoc[manage your team's devices].

image:<NEW-IMAGE>[width=,alt=""]
