= Manage team devices
:navtitle: Manage team devices

Learn how to manage your team devices, so your team can easily access the devices they need for testing. In *Org Management*, select *Teams*, choose a team, then select *Devices* to get started.

image:<NEW-IMAGE>[width=,alt=""]

== Assign a device

In *Unassiged Devices*, search for a device using filters, statuses, or the search bar.

image:<NEW-IMAGE>[width=,alt=""]

Select the *plus icon* to assign the device to your team.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Assign all devices

In *Unassiged Devices*, select *Assign All* to assign all devices in your organization to the team.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Automatically assign new public devices

In *Unassiged Devices*, enable *Automatically assign new public device(s) to this team*.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove a device

In *Assigned Devices*, search for a device using filters, statuses, or the search bar.

image:<NEW-IMAGE>[width=,alt=""]

Select the *minus icon* to remove the device from your team.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]

== Remove all devices

In *Assigned Devices*, select *Unassign All* to remove all devices currently assigned to your team.

image:<NEW-IMAGE>[width=,alt=""]

When you're finished, select *Save*.

image:<NEW-IMAGE>[width=,alt=""]
