= Set a cleanup policy for a team
:navtitle: Set a team cleanup policy

Assign a cleanup policy to a team so the team's Private & Local Devices are cleaned up at the end of each session. A team-level policy overrides the xref:devices:local-devices/cleanup-policy/manage-device-cleanup-policies.adoc#_assign_as_organization_default[organization default].

NOTE: If a device is assigned to multiple teams with different cleanup policies, the policies may conflict. A confirmation popup warns you of this when saving.

== Open team settings

. In the left navigation bar, select the *Org Management* icon, then select *Teams*.
. Search for your team, then select the team name.
. Select *Settings*.

== Assign an existing policy

. From the cleanup policy dropdown, select a policy.
. Select *Save*.

== Create and assign a new policy

. Next to the cleanup policy dropdown, select *New*.
. Enter a name and an optional description.
. Select the *Android* tab and check the configurations to apply. Then select the *iOS*
tab and do the same.
+
For details on each option, see
xref:devices:local-devices/cleanup-policy/cleanup-configurations.adoc[Cleanup configurations].
. Select *Save*.
. In the *Create Cleanup policy* popup, select *Create*.
. On the team settings page, select *Save* to apply the assignment.

To manage all cleanup policies including editing, removing, or assigning as the
organization default, see xref:devices:local-devices/cleanup-policy/manage-device-cleanup-policies.adoc[Manage device cleanup policies].