= Team roles and permissions
:navtitle: Roles and permissions

These are the roles and permissions available when xref:teams/manage-teams.adoc#_set_team_permissions[setting team permissions] or xref:teams/change-a-users-team-role.adoc[changing a user's team role].

== Roles

=== Team owner

The user(s) with the highest team permissions. Team owners *always* have the following permissions, and they cannot be changed:

* xref:_settings_modify[]
* xref:_members_modify[]
* xref:_devices_modify[]
* xref:_apps_unassign[]
* xref:_member_make_admin[]
* xref:_member_make_owner[]

=== Team admin

The user(s) with the second-highest team permissions. By default, *Team Admins* are assigned the following permissions:

* xref:_settings_modify[]
* xref:_members_modify[]
* xref:_devices_modify[]
* xref:_apps_unassign[]

*Team Owners* can add or remove these permissions, but they cannot add any other permissions.

=== Team member

The user(s) with the lowest team permissions. By default, *Team Members* have *no team permissions*. *Team Owners* Allows a user to choose to add xref:_settings_modify[] to *Team Members*, but they Allows a user tonot add any other permissions.

== Permissions

[#_settings_modify]
=== `settings.modify`

Allows a user to edit team details (name, description, assertion value) and team settings (private test mode, cleanup policy).

* *Team owner:* Always
* *Team admin:* By default, On
* *Team member:* By default, Off

[#_members_modify]
=== `members.modify`

Allows a user to add and remove members, and change member permissions.

* *Team owner:* Always
* *Team admin:* By default, On
* *Team member:* Never

[#_devices_modify]
=== `devices.modify`

Allows a user to add and remove devices assigned to the team.

* *Team owner:* Always
* *Team admin:* By default, On
* *Team member:* Never

[#_member_make_admin]
=== `member.make_admin`

Allows a user to make a team member a team admin.

* *Team owner:* Always
* *Team admin:* Never
* *Team member:* Never

[#_member_make_owner]
=== `member.make_owner`

Allows a user to make a team member the team owner.

* *Team owner:* Always
* *Team admin:* Never
* *Team member:* Never

[#_apps_unassign]
=== `apps.unassign`

Allows a user to remove an app assigned to the team.

* *Team owner:* Always
* *Team admin:* Never
* *Team member:* Never
