= Kobiton 3.29 release notes (Legacy)
:navtitle: Kobiton 3.29 release notes

_May 13, 2023_

These release notes pertain to Legacy Kobiton 3.29.

As a reminder, in our November release, we started using 4.0+ as the numbering for releases of the new Kobiton, while Legacy Kobiton will continue with numbering starting with 3.25 and above. If you are using the new Kobiton, see the xref:previous/4.4.adoc[].

If you have any questions or would like to update your Kobiton system, please send us an email at link:mailto:support@kobiton.com[support@kobiton.com] or contact your Account Executive.

== New iOS and device support

Kobiton 4.4 supports the following:

* iOS/iPadOS 16.4 (Note: cannot view Session detail for XCUI automation session)
* iOS/iPadOS 16.4.1 (Note: cannot view Session detail for XCUI automation session)
* iOS/iPadOS Security Response 16.4.1 (a)
* iOS/iPadOS 15.7.5
* Zebra Technologies TC21 (Note: cannot turn on navigation bar during Cleanup)

== UI/UX improvements

We introduced several enhancements to the UI/UX below:

* For Cloud customers, we included the link to API v2 in the API v1 documentation site to allow better navigation between them.
* Hover the mouse on the partial UDID in the *Device Details* modal to show and copy the full UDID.

== Additional enhancements and bug fixes

In addition to the above, this release includes a number of minor bug fixes and enhancements to improve your day-to-day testing.
