= Kobiton 4.3 release notes
:navtitle: Kobiton 4.3 release notes

_April 1, 2023_

These release notes pertain to Kobiton 4.3. For Legacy Kobiton, see xref:previous/3_28.adoc[].

== virtualUSB for macOS (GA)
virtualUSB for macOS is now General Availability (GA)! Learn more about virtualUSB link:/hc/en-us/articles/11016368492301[here].

NOTE: virtualUSB for Windows remains in beta.

== Kobiton Inspector: ability to inspect Shadow DOM data

For hybrid apps built on frameworks such as the Ionic Framework, Shadow DOM is often utilized to provide encapsulation. It allows a component to have its own Shadow DOM tree that is not accessible from the main document so it can have local style rules.

The Kobiton Inspector can now show Shadow DOM data in the Manual Session and in Session Explorer. With this feature, testers can retrieve information about an element’s style previously hidden by Shadow DOM.

== API v2: new endpoints and enhancements

We have a number of additions and changes to API v2 as follows.

We added the following endpoints:

* Change uploaded application's default access level
* Get parsing state of an application version id
* Get devices with all specific tags
* Install an application on a device
* Uninstall an application on an API session

We made the following changes:

* Standardized the response format of APIs that update multiple objects to give meaningful error messages to each failed case
* Added two memory metrics: memory free and memory used to Get device metrics for a session endpoint
* Included a running session’s log in the response of Get a session endpoint
* Added the ability to access both API v1 and API v2 from within the Kobiton Cloud Portal

Check out the API v2 documentation site link:https://api.kobiton.com/v2/docs[here].
A quick introduction on how to navigate and try real API requests in this site, as well as the current API v2 limitations, can be found link:https://support.kobiton.com/hc/en-us/articles/6782179234445-API-v2[here].

link:https://api.kobiton.com/docs/?http#kobiton-api-v1-0[Kobiton API v1] is still available until further notice. We encourage you to start using API v2 as you add new test scripts and processes.

For endpoints in API v1 not yet offered in v2, continue to use API v1.

== Android Audio device-to-browser with Orion (beta)

For enterprise customers who need to test audio output from apps and mobile browsers, we have released support streaming audio from device to user browser on Private Kobiton-hosted Android devices in beta. Contact your account executive to learn how to try this feature.

[NOTE]
====
* Requires addition hardware setup: Orion Board 32+ Gen 3 audio interface.
* Requires Android 10 or later devices that have a headphone jack.
====

== Additional enhancements and bug fixes

In addition to the above, this release includes a number of minor bug fixes and enhancements to improve your day-to-day testing.
