= Prepare a manual session for scriptless
:navtitle: Prepare a manual session for scriptless

Learn how to convert a manual session to an Automated Test Case for Scriptless Automation.

== Launch a manual session as a baseline

Start a manual session.

Install one or multiple apps that satisfy these conditions.

Perform the supported actions in the session.

For best results, follow the Scriptless best practices guidelines.

End the session.

== Convert a manual session into an Automated Test Case

After the session ends, you are automatically redirected to the Session Overview page. You can also navigate to this page by searching and selecting a manual session from the session list.

In Session Overview, select Automated Test Case.

If the session does not satisfy all Scriptless requirements, the screen appears as below. Launch a new manual session and make sure that all requirements are met.

If all requirements are satisfied, the screen displays the test steps recorded from the baseline session.

From here, you can perform several actions:

* Annotate test steps.

* Rerun the recorded test case on device bundles.

* Generate Appium script.

* Convert to Automated Test Case.


