= Prepare a manual session for scriptless
:navtitle: Prepare a manual session for scriptless

Learn how to convert a manual session to an Automated Test Case for Scriptless Automation.

== Launch a manual session as a baseline

Start a xref:manual-testing:start-a-manual-session.adoc[manual session].

xref:manual-testing:install-an-app.adoc[Install] one or multiple apps that satisfy xref:prepare-baseline-session/supported-apps.adoc[these conditions].

Perform the xref:prepare-baseline-session/supported-actions.adoc[supported actions] in the session.

For best results, follow the xref:prepare-baseline-session/scriptless-best-practices.adoc[Scriptless best practices] guidelines.

End the session.

== Convert a manual session into an Automated Test Case

After the session ends, you are automatically redirected to the Session Overview page. You can also navigate to this page by searching and selecting a manual session from the session list.

In Session Overview, select Automated Test Case.

If the session does not satisfy all scriptless requirements, the screen appears as below. Launch a new manual session and make sure that all requirements are met.

If all requirements are satisfied, the screen displays the test steps recorded from the baseline session.

If the recorded test steps do not contain any overlapping element, the green message displays as below. You can then select Convert to Test Case to convert and start xref:manage-test-case.adoc[managing the test case].

If any of the test steps contains overlapping element, the red message displays as below. You can xref:remediations/annotate-test-step.adoc[annotate the steps] before converting to test case.


