= Create a project
:navtitle: Create a project

Learn how to ...

== Before you start

You'll need to create xref:automation-testing:scripting/auto-generate-an-appium-script.adoc[or generate] an Appium script with xref:automation-testing:capabilities/auto-generate-capabilities.adoc[Kobiton capabilities], as well as access to the following:

* A personal computer with your Integrated Development Environment (IDE) set up.
* A cloud-based repository (like link:https://github.com/about[GitHub], link:https://about.gitlab.com/[GitLab], etc.) with merge permissions.
* A Jenkins account with at least link:https://www.jenkins.io/doc/book/security/access-control/permissions/#access-granted-with-overallmanage[Overall/Manage] permissions.

== Create a project

. Within the Jenkins Dashboard, select New Item. +
image:/guide-media/01GWEGMNT65G21F0DM1YGXJ458[alt="mceclip5.png"]
. Select the Maven Project to take advantage of the POM file that is included with the exported Appium File from Kobiton. +
image:/guide-media/01GWEMKZV318SBWC42F4WRHMRX[alt="mceclip6.png"] The Configuration Screen will appear next.

=== General tab

. Enter a Description, if so desired.
. Select "Discard Old Builds". Determine your Log Rotation Strategy and fill in "Days to keep builds" and "Max # of builds to keep" fields. An example is shown below:
+
image:/guide-media/01GWE55K478THXB4SACF5MZM7C[alt="mceclip7.png"]

=== Source Code Management tab

. Select Git and provide the Repository URL (as mentioned previously) and your corresponding credentials.

image:/guide-media/01GWEFX4DGZ37Y7HDMEEGNKXPA[alt="mceclip8.png"]

=== Build Triggers tab

. Select the appropriate build triggers depending on your requirement(s). In this example, the Build whenever a SNAPSHOT dependency is built as well as a Build Periodically – hourly triggers are selected.
+
image:/guide-media/01GWEYQBP9PAPQAZE290G8VEDZ[alt="mceclip9.png"]

=== Build Environment tab

. Select the "Delete Workspace before build starts" option to enable Jenkins to request a code refresh from the Github repository.
. Select "Abort the build if it’s stuck".
. Select "Add timestamps to Console Output" if you would like timestamps to be included in every line of the output log of your test.
+
image:/guide-media/01GWEJYJ7EMT8X58EYERYYF2K0[alt="mceclip10.png"]

=== Steps and settings

image:/guide-media/01GWESQSWAQHDMFCKVNG8AJMWC[alt="mceclip11.png"]

Select Save or Apply to save your changes.

image:/guide-media/01GWE55MJZBEVTPWMAWXFXK7H6[alt="mceclip12.png"]

=== Optional configurations

. Optionally, if you wish to pass String Parameters to the Appium Code to use at run time as Environmental Variables, in the General Configuration, check “This Project is parameterized”.
+
image:/guide-media/01GWEGMPMDYWVFMTM8K8J6SK8F[alt="mceclip13.png"]
. Select "String Parameters" from the dropdown list.
+
image:/guide-media/01GWEYQCDY5W9BPTB7N7F01MA6[alt="mceclip14.png"]
. Enter your Username Parameters (example below):
+
image:/guide-media/01GWEBXX7E51V7N8NAJXHB5RX5[alt="mceclip15.png"]
. Ensure the changes are reflected in the Config.java within the Github Repository.
+
image:/guide-media/01GWESQTRSGV6ZWM7HGWSEMJS2[alt="mceclip16.png"]
