= Create a Jenkins job
:navtitle: Create a Jenkins job

Learn how to create a Jenkins job so you can, so you can automatically run Jenkins jobs when a commit is pushed to your project.

== Before you start

You'll need to complete the following:

* xref:integrations:jenkins/upload-your-project-to-a-cloud-repository.adoc[Upload your project to a cloud repository].
* Verify your Jenkins account is assigned link:https://www.jenkins.io/doc/book/security/access-control/permissions/#access-granted-with-overallmanage[Overall/Manage] permissions or higher.

== Create a project

. Within the Jenkins Dashboard, select New Item.
. Select the Maven Project to take advantage of the POM file that is included with the exported Appium File from Kobiton.

=== General tab

. Enter a Description, if so desired.
. Select "Discard Old Builds". Determine your Log Rotation Strategy and fill in "Days to keep builds" and "Max # of builds to keep" fields. An example is shown below:

=== Source Code Management tab

. Select Git and provide the Repository URL (as mentioned previously) and your corresponding credentials.

=== Build Triggers tab

. Select the appropriate build triggers depending on your requirement(s). In this example, the Build whenever a SNAPSHOT dependency is built as well as a Build Periodically – hourly triggers are selected.

=== Build Environment tab

. Select the "Delete Workspace before build starts" option to enable Jenkins to request a code refresh from the Github repository.
. Select "Abort the build if it’s stuck".
. Select "Add timestamps to Console Output" if you would like timestamps to be included in every line of the output log of your test.

=== Steps and settings

Select Save or Apply to save your changes.

=== Optional configurations

. Optionally, if you wish to pass String Parameters to the Appium Code to use at run time as Environmental Variables, in the General Configuration, check “This Project is parameterized”.

. Select "String Parameters" from the dropdown list.

. Enter your Username Parameters (example below):

. Ensure the changes are reflected in the Config.java within the Github Repository.
