= Jenkins integration
:navtitle: Jenkins

The Jenkins integration let's your team...

CI/CD pipelines, while often appearing as that singular term, are actually composed of two workflows. The first, Continuous Integration, is the process of integrating code into a mainline code base. Continuous Delivery is a bit more complicated; CD is a catchall for the many processes that deliver app changes to an app's user base after the code is integrated. Those processes involving testing, staging and deploying code.

Jenkins is a CI server that can assist your organization with its CI/CD pipeline goals. If your organization is using Jenkins as part of its DevOps testing workflow, you can easily incorporate it with your Kobiton experience. Kobiton is platform-agnostic and can be used with any CI/CD system, such as Jenkins, Testrail, and other similar systems that permit scripting - this document will cover how you can configure your Jenkins Automation Suite and Kobiton's Mobile Device Lab to give you a prime testing environment.

image:/guide-media/01GWEGMMZMQ7H9APN7S6911Z1J[alt="mceclip0.png"]

== In this section

* xref:integrations:jenkins/upload-a-project.adoc[]
* xref:integrations:jenkins/create-a-project.adoc[]
* xref:integrations:jenkins/test-cicd-workflow.adoc[]
