= Test CI/CD workflow
:navtitle: Test CI/CD workflow

Learn how to ...

== Test CI/CD workflow

. Return to the Dashboard and select the new Project we’ve just created.
+
image:/guide-media/01GWEYQAW0B8A072GNE2V7KYPM[alt="mceclip17.png"]
. Select “Build with Parameter”.
+
image:/guide-media/01GWE6JMT5EYFA9XCAF3EXXG88[alt="mceclip18.png"]
. Verify that the String Parameters are correct and click to Build. Validate the build is running by observing the Build History.
+
image:/guide-media/01GWE55KTEXS13JE3G33311FSD[alt="mceclip19.png"]
. To observe the Console Output, click on the Build # (2) and a drop down box will appear.
+
image:/guide-media/01GWDZ1KM2AGKFAP57483QKMHB[alt="mceclip20.png"]
. Observe and validate that the Build has been started and the test is running.
+
image:/guide-media/01GWE6JNNWAMY4HWZ34AAQ0VQR[alt="mceclip21.png"]

You can also view the test running in Kobiton's platform concurrently with the feedback you receive from Jenkins by viewing the associated session in Kobiton:

image:/guide-media/01GWDZDR93A007JSCQKH8X4M66[alt="mceclip1.png"]

image:/guide-media/01GWECYPB75DH3WZB6C3AVXWP5[alt="mceclip0.png"]
