= Adding users in teams
:navtitle: Adding users in teams

== Inviting new users

1. On *Org Management*, select *Users* tab.

2. Click *Invite*.

3. Type a user’s email address. Many email addresses are separated by semicolon (;).

4. Click the drop-down list to browse roles on *Assign to Roles*. Click + to assign users to that role.
+
Learn more about Role-Based Access Control _here_.

5. Click the drop-down list to browse teams on *Assign to Teams*. Click + to assign users to that team.

6. Click *Send Invitation*. (New users will receive the email and join Kobiton via invitation).

NOTE: Admins can only invite unexisting users to your organization. Users already existed and belonged to another organization cannot be added.

== Adding users in teams

1. On *Org Management*, select *Teams* tab.

2. On *Teams* tab, open Teams settings by clicking on the team name.

3. Click *Users* tab.

4. Click *Add new user*.

5. Toggle one role amongst *Team Owner*, *Team Admin* Or *Member*.

6. Select users from the *Unassigned Users* drop-down list.

7. Click *Update* to close the modal.

8. Click *Save*.

== Removing users from teams

1. On *Teams* tab, select the team by clicking on the team name.

2. Click *Users* tab.

3. Click the (-) icon to remove users from the team.

4. Click *Save*.