= Annotate test step
:navtitle: Annotate test step

After the baseline session has been completed, Kobiton NOVA AI Engine analyzes the actions performed and determine which visual elements are acted upon automatically. However, there are cases where multiple visual elements overlap each other and the AI Engine returns low confidence in selecting the correct element. In this case, you can annotate the correct element by doing the following:

In the Automated Test Case or the Test Case Management page, select Annotate on a test steps with low confidence.

In the next page, a list of possible visual elements appear, along with its tags. Select an element and hit Submit to confirm.

Repeat the above for all test steps that need annotation. When all test steps have been annotated, a green message appears like the below:

At this point, your test case is good to be used for Scriptless Automation.

Note: Annotation is not required for Scriptless Automation. It only helps increasing the Scriptless Automation success rate.

