= Taking screenshots
:navtitle: Taking screenshots

Kobiton Portal equips you with the ability to capture screenshots during your Manual Test sessions. Screenshots can be viewed while the session is still end progress and will be stored as session details after the session has ended for easy review.

== Taking screenshots

- During a Manual Test session, you can click on Take screenshot on the toolbar to take a real-time screenshot of the testing device.

== Viewing screenshots

=== During a Manual Test session

. In an ongoing Manual Test session, you can see the number of captured screenshots indicated on Screenshots button.

. Click on Screenshots to open a pop-up containing all of the screenshots that you have captured up to this point of the current session. You can also download a screenshot by hovering on it and click on Download.

=== After a Manual Test session has ended

After a Manual Test session has ended, you can still view the screenshots taken in that session.

. In the Sessions tab of Kobiton Portal, select a session to see its details.
. Because Take screenshot counts as an action, click on Actions Performed tab.
. Select the timestamp of the Take screenshot action to view the captured screenshot.
. You can download a screenshot by hovering on it and click on Download screenshot.
