= Content style guide [WIP]

== General guidelines

Aside from a few <<_kobiton_specific_guidelines,Kobiton-specific guidelines>>, our documentation's spelling, grammar, and formatting adheres to the standards found within https://www.ahdictionary.com/[The American Heritage Dictionary] and the https://learn.microsoft.com/en-us/style-guide/welcome/[Microsoft Style Guide].

If you're unsure about a particular spelling, grammar, or formatting rule, check out the xref:_faq[frequently asked questions] below.

[#_kobiton_specific_guidelines]
== Kobiton-specific guidelines

=== CSS styles

The xref:../ui-bundle/css/site.css[`site.css`] file formats the overall site and structure. Only admins and repository owners should be updating this file.

=== File names

Ensure your filenames follow these formatting rules:

[cols="1,1"]
|===
|Formatting Rule|Example

|All lowercase letters
|Change this: +
`This Is My TITLE` +
_To this:_ +
`this is my title`

|Replace unique special characters
|Change this: +
`i love c++ & c#` +
To this: +
`i love cpp and csharp`

|Remove non-unique special characters
|Change this: +
`this: is my title!` +
To this: +
`this is my title`

|Replace spaces with dashes
|Change this: +
`this is my title` +
To this: +
`this-is-my-title`
|===

=== Content reuse

Sometimes a section of documentation, or an entire document itself, belongs to multiple sections within the documentation site.

At Kobiton, there are three primary products, (also called components): *Device Lab Management*, *Intelligent Quality Suite*, and *Kobiton Desktop*. Each component contains a variety of modules, and each module contains a variety of features.

In the case that a feature belongs to _several_ modules (and, likewise several components), documentation related to that feature should be included in each related module's documentation.

This requires content reuse, which you can learn more about xref:reusing-content.adoc[here].

=== Embedded media [WIP]

Our documentation hosts a variety of embedded media, including <<_screenshots, screenshots>>, <<_diagrams, diagrams>>, and <<_video, video>> content.

==== Figma

The following section outlines the style and naming guidelines for Figma files. If, instead, you'd like to learn _how_ to create screenshots using Figma, check out xref:creating-screenshots.adoc[this tutorial].

[cols="1,1"]
|===
|Formatting rule |Example

|Figma file names should mirror the full directory path.
|`manual-testing/modules/ROOT/images/manual-testing-flow`

|Figma files should be exported as an `.svg`.
|`manual-testing-flow.svg`
|===

[#_screenshots]
==== Screenshots [WIP]

Screenshots are ...

[cols="1,1"]
|===
|Formatting rule |Example

|App screenshots should horizontally cover the content area of the screen.
|This

|Text should not wrap around screenshots.
|This

|The width-to-height ratio should be between 1.74 and 1.80.
|This
|===

[#_diagrams]
==== Diagrams [WIP]

The following section outlines the style guidelines for diagrams. If, instead, you'd like to learn _how_ to create diagrams using Mermaid, check out xref:creating-diagrams.adoc[our tutorial].

[cols="1,1"]
|===
|Formatting rule |Example

|Use the font Roboto at 32pt font size.
|This

|Use the color `Primary/Default` for fonts, lines, and arrows (located in the Figma file: *Kobiton Style Guide*).
|This

|Use the background color `Primary/Light` color (located in the Figma file: *Kobiton Style Guide*).
|This

|Use a *soft drop shadow* on shapes.
|This
|===

[#_video]
==== Video [WIP]

Videos are ...

[cols="1,1"]
|===
|Formatting rule |Example

|This
|This

|This
|This
|===

[#_faq]
== Frequently asked questions (FAQ)

=== This?

This.

=== This?

This.

=== This?

This.

=== This?

This.

=== This?

This.

=== This?

This.