= [WIP] Content style guide

== General guidelines

Aside from a few <<_kobiton_specific_guidelines,Kobiton-specific guidelines>>, our documentation's spelling, grammar, and formatting adheres to the standards found within https://www.ahdictionary.com/[The American Heritage Dictionary] and https://learn.microsoft.com/en-us/style-guide/welcome/[Microsoft Style Guide].

=== Table of contents

* xref:_css_styles[CSS styles]
* xref:_product_names[Product names]
* xref:_file_names[File names]
* xref:_file_structure[File structure]
* xref:_content_reuse[Content reuse]
* xref:_embedded_media_wip[Embedded media]

[#_kobiton_specific_guidelines]
== Kobiton-specific guidelines

[#_css_styles]
=== CSS styles

The xref:../ui-bundle/css/site.css[`site.css`] file formats the overall site and structure. Changes to this file require a review from our repository admins.

[#_product_names]
=== Product names [WIP]
// Update link to public-facing documentation site once the site is live.

Check out our xref:../docs/modules/glossary/index.adoc[product glossary].

[#_file_names]
=== File names

Ensure your filenames follow these formatting rules:

[cols="1,1"]
|===
|Formatting Rule|Example

|All lowercase letters
|Change this: +
`This Is My TITLE` +
_To this:_ +
`this is my title`

|Replace unique special characters
|Change this: +
`i love c++ & c#` +
To this: +
`i love cpp and csharp`

|Remove non-unique special characters
|Change this: +
`this: is my title!` +
To this: +
`this is my title`

|Replace spaces with dashes
|Change this: +
`this is my title` +
To this: +
`this-is-my-title`
|===


[#_file_structure]
=== File structure

Our docs repository hosts a single `modules` folder containing an `antora.yml` file and several components, where each component represents a particular topic, e.g. manual testing, release notes, APIs, etc. This means each Kobiton product shares the same `antora.yml` file for versioning and nav bar configuration.

Here's an example file structure:

[listing]
----
📒 repository
  📂 docs
    📂 modules
        📂 .partials
        📂 component-a
            📂 images
            📂 pages
            📄 nav.adoc
        📂 component-b
            📂 images
            📂 pages
            📄 nav.adoc
        📂 component-c
            📂 images
            📂 pages
            📄 nav.adoc
----

To configure the navigation for a particular section, you'll edit the section's corresponding `nav.adoc` file, then add its relative path to the `antora.yml` file, like so:

[listing]
.antora.yml
----
nav:
  - modules/ROOT/nav.adoc
  - modules/release-notes/nav.adoc
  - modules/supported-platforms/nav.adoc
----

If a piece of documentation needs to be added to several components, check out our guidelines for xref:_content_reuse[content reuse].

[#_content_reuse]
=== Content reuse

If a piece of documentation needs to be added to several components, you'll need to reuse content using https://docs.antora.org/antora/latest/page/partials/[partials]. The `.partials` folder found within `modules` contains a variety of partials including, product descriptions, callouts, role requirements, and more. If a there's already a partial for a commonly used piece of writing, use its corresponding partial.

If you want to learn how to reuse content, checkout our guide for xref:reusing-content.adoc[reusing content].

[#_embedded_media_wip]
=== Embedded media [WIP]
// Migrate from google doc: https://docs.google.com/document/d/1TJuRQO4uof6NW94AIP0MVWtjYr9vEykgO1yddv6WDoY/edit#heading=h.e4wvl4myvq6w

Our documentation hosts a variety of embedded media, including <<_screenshots, screenshots>>, <<_diagrams, diagrams>>, and <<_videos, video>> content.

==== Figma

The following section outlines the naming guidelines for Figma files. If you'd like to learn _how_ to create screenshots using Figma instead, check out xref:creating-screenshots.adoc[this tutorial].

[cols="1,4"]
|===
|Key |Value

|File names
a|
Figma file names should mirror the full directory path. +
*Example:* `manual-testing/modules/ROOT/images/manual-testing-flow`

|File extensions
a|
Figma files should be exported as an `.svg`. +
*Example:* `manual-testing-flow.svg`
|===

[#_screenshots]
==== Screenshots [WIP]

The following section outlines the style guidelines for screenshots. If you'd like to learn _how_ to create screenshots using Figma instead, check out xref:creating-screenshots.adoc[this tutorial].

[cols="1,2"]
|===
|Key |Value

|This
|This

|This
|This
|===

[#_diagrams]
==== Diagrams [WIP]

The following section outlines the style guidelines for diagrams. If you'd like to learn _how_ to create diagrams using Mermaid instead, check out xref:creating-diagrams.adoc[this tutorial].

[cols="1,2"]
|===
|Key |Value

|This
|This

|This
|This
|===

[#_videos]
==== Videos [WIP]

The following section outlines the style guidelines for videos. If you'd like to learn _how_ to create videos instead, check out xref:creating-videos.adoc[this tutorial].

[cols="1,2"]
|===
|Key |Value

|This
|This

|This
|This
|===
