= [WIP] Content style guide

== General guidelines

Aside from a few <<_kobiton_specific_guidelines,Kobiton-specific guidelines>>, our documentation's spelling, grammar, and formatting adheres to the standards found within https://www.ahdictionary.com/[The American Heritage Dictionary] and https://learn.microsoft.com/en-us/style-guide/welcome/[Microsoft Style Guide].

=== Table of contents

* xref:_css_styles[CSS styles]
* xref:_product_names[Product names]
* xref:_file_names[File names]
* xref:_file_structure[File structure]
* xref:_content_reuse[Content reuse]
* xref:_embedded_media_wip[Embedded media]

[#_kobiton_specific_guidelines]
== Kobiton-specific guidelines

[#_css_styles]
=== CSS styles

The xref:../ui-bundle/css/site.css[`site.css`] file formats the overall site and structure. Changes to this file require a review from our repository admins.

[#_product_names]
=== Product names
// Update link to public-facing documentation site once the site is live.

Use our xref:../docs/modules/resources/glossary.adoc[product glossary] for up-to-date spelling, abbreviations, and styling.

[#_file_names]
=== File names

Ensure your filenames follow these formatting rules:

[cols="1,1"]
|===
|Formatting Rule|Example

|All lowercase letters
|Change this: +
`This Is My TITLE` +
_To this:_ +
`this is my title`

|Replace unique special characters
|Change this: +
`i love c++ & c#` +
To this: +
`i love cpp and csharp`

|Remove non-unique special characters
|Change this: +
`this: is my title!` +
To this: +
`this is my title`

|Replace spaces with dashes
|Change this: +
`this is my title` +
To this: +
`this-is-my-title`
|===


[#_file_structure]
=== File structure

Our docs repository uses a single `modules` folder containing an `antora.yml` file and several components, where each component represents a particular topic, e.g. manual testing, release notes, APIs, etc. This means each Kobiton product shares the same `antora.yml` file for versioning and nav bar configuration.

Here's an example file structure:

[listing]
----
📒 repository
  📂 docs
    📂 modules
        📂 component-a
            📂 images
            📂 pages
                📄 index.adoc
            📂 partials
            📄 nav.adoc
        📂 component-b
            📂 images
            📂 pages
                📄 index.adoc
                📄 other-page.adoc
            📂 partials
            📄 nav.adoc
        📂 ROOT
            📂 images
            📂 pages
                📄 index.adoc
            📂 partials
            📄 nav.adoc
----

[NOTE]
Antora requires a `ROOT` folder. For our purposes, this folder will only contain the site's landing page and site-wide xref:_content_reuse[partials].

To configure the navigation for a particular section, you'll edit the section's corresponding `nav.adoc` file, then add its relative path to the global `antora.yml` file, like so:

[listing]
.*Example*
----
nav:
  - modules/ROOT/nav.adoc
  - modules/release-notes/nav.adoc
  - modules/supported-platforms/nav.adoc
----

If a piece of documentation needs to be added to several components, check out our guidelines for xref:_content_reuse[content reuse].

[#_content_reuse]
=== Content reuse

If a piece of documentation needs to be added to several components, you can reuse content using https://docs.antora.org/antora/latest/page/partials/[partials].

The `partials` folder found within `ROOT` contains a variety of global partials (like product descriptions, role requirements, etc.), while component-specific partials are located within their own `partials` folder.

Use the following syntax to add a global or component-specific partials:

* *Global:* `include::ROOT:partial$<FOLDERNAME>/<FILENAME>`
* *Component-specific:* `include::<COMPONENTNAME>:partial$<FOLDERNAME>/<FILENAME>`

If you'd like a more in-depth tutorial for content reuse, checkout our xref:reusing-content.adoc[reusing content] guide.

[#_embedded_media_wip]
=== Embedded media [WIP]
// Migrate from google doc: https://docs.google.com/document/d/1TJuRQO4uof6NW94AIP0MVWtjYr9vEykgO1yddv6WDoY/edit#heading=h.e4wvl4myvq6w

Our documentation hosts a variety of embedded media, including <<_screenshots, screenshots>>, <<_diagrams, diagrams>>, and <<_videos, video>> content.

[#_screenshots]
==== Screenshots [WIP]

The following section outlines the style guidelines for screenshots. If you'd like to learn _how_ to create screenshots using Figma instead, check out xref:creating-screenshots.adoc[this tutorial].

[cols="1,2"]
|===
|Key |Value

|This
|This

|This
|This
|===

[#_diagrams]
==== Diagrams [WIP]

The following section outlines the style guidelines for diagrams. If you'd like to learn _how_ to create diagrams using Mermaid instead, check out xref:creating-diagrams.adoc[this tutorial].

[cols="1,2"]
|===
|Key |Value

|This
|This

|This
|This
|===

[#_videos]
==== Videos [WIP]

The following section outlines the style guidelines for videos. If you'd like to learn _how_ to create videos instead, check out xref:creating-videos.adoc[this tutorial].

[cols="1,2"]
|===
|Key |Value

|This
|This

|This
|This
|===
