= Creating screenshots [WIP]

Learn how to create screenshots using Figma.

== Prerequisites

* https://help.figma.com/hc/en-us/articles/360039811114-Create-a-Figma-account[A Figma account]
* The https://www.figma.com/downloads/[Figma desktop app] _(optional)_
* Access to Kobiton's Figma team and *Documentation* file

== Creating simple screenshots

A simple screenshot is ...

. This
. This
. This

== Creating highlighted screenshots

A highlighted screenshot is ...

. Take screenshot using shortcut.

. Resize width to 1662.

. Crop web browser info.

. Frame the screenshots.

. Duplicate screenshot. We'll need the duplicate for later.

. Create rectangle (press *R*) and resize to perfectly fit screenshot.

. Change fill to 00000 (all black) and opacity to 20% (located on right hand side). Change background blur to 8.

. Create second rectangle (press *R*) and place it over the section you'd like to highlight.

. Hold *CTRL* and select both rectangle layers. At the top of the screen, select *Subtract selection*.

. Select the subtracted section and press *Shift + 2* to zoom into the section.

. Resize the subtracted section to perfectly fit the element you'd like to highlight.
+
[NOTE]
If the element is rounded, select *Corner Radius* under *Design* and adjust the radius until it fits the rounded element you'd like to highlight.

. Now that you've highlighted your element, you're ready to create a zoomed-in version using the duplicate screenshot we created in step 5.
+
Select *Crop* and place the crop tool around the duplicate version of the element. Then press *Shift + 2* to zoom into the section.

. Resize the crop tool to perfectly fit around the element you'd like to zoom in on.
+
[NOTE]
If the element is rounded, select *Corner Radius* under *Design* and adjust the radius until it fits the rounded element you'd like to highlight.

. Once the crop tool is properly fit around the element, press *Enter*.

. Move the element over your original screenshot and drag a corner of the crop tool to resize it. Typically, zoomed-in elements should be X%RATIO, but feel free to do what's best to increase readability.

. Center the element over the original screenshot.

. Select *Drop shadow*, and set it's values to the following:
* *X:* 0
* *Y:* 150
* *Spread:* 0
* *Blur:* 250
* *Color:* 000000
* *Opacity:* 15%

. Click the current name and change it to a short, descriptive title.

. Select *Export* on the right side, confirm the file extension is set to *.png*, and click *Save*.

. You've successfully created a highlighted screenshot!
