= [WIP] Creating screenshots

Learn how to create xref:_establishing_screenshots[establishing], xref:_creating_map_screenshots[map], and xref:_simple_screenshots[simple] screenshots using Figma. If you don't have access to Figma, you can use Photoshop, Gimp, or any other image editor instead.

[#_establishing_screenshots]
== Establishing screenshots

*Establishing screenshots* offer visual context to the end-user. You can think of these like the https://wikipedia.org/wiki/Establishing_shot[establishing shot] at the beginning of a movie. Once you've established the context, feel free to use xref:_simple_screenshots[simple screenshots] instead.

. Open Figma.

. Select *File*, then *Place image* to import your screenshot.

. Resize the width to 1662.

. Crop the window title bar, web browser toolbar, and any other non-essential information by selecting *Crop*, dragging a corner of the crop tool, and pressing *Enter*.
+
[TIP]
Press *Shift + 2* to zoom in on the section you're cropping to make sure the crop is pixel perfect.

. Select your screenshot and frame it by pressing *F*.

. Later we'll need a duplicate, so *Right-Click* and select *Copy* and *Paste* to create one.

. Next we'll create a blur effect. Press *R* to create a square and use it to cover the screenshot.

. Modify the square to match the following settings:
* *Fill:* 00000
* *Opacity:* 20%
* *Blur:* 8

. Create second rectangle by pressing *R* and place it over the section you'd like to highlight.

. Hold *CTRL* and select both rectangle layers. Then select *Subtract selection*.

. Select your newly subtracted section and press *Shift + 2* to zoom in.

. Resize the subtracted section to fit the element you'd like to highlight.
+
[NOTE]
If the element is rounded, select *Corner Radius* under *Design* and adjust the radius until it fits the element.

. Now that you've highlighted your element, you're ready to create a zoomed-in version using the duplicate screenshot we created in step 6.
+
Select *Crop* and place the crop tool around the duplicate element. Then press *Shift + 2* to zoom in.

. Resize the tool to crop the element you'd like to zoom in on.
+
[NOTE]
If the element is rounded, select *Corner Radius* under *Design* and adjust the radius until it fits the rounded element you'd like to highlight.

. Once the crop tool is fit to the element, press *Enter*.

. Move your new zoomed-in element over your original screenshot and resize it. Typically, zoomed-in elements should be X%RATIO, but feel free to do what looks best.

. Center the element over the original screenshot.

. Select *Drop shadow* and set its values to the following:
* *X:* 0
* *Y:* 150
* *Spread:* 0
* *Blur:* 250
* *Color:* 000000
* *Opacity:* 15%

. Click the default frame name and change it to a short, descriptive one.

. Select *Export*, confirm the file extension is set to *.png*, then click *Save*.

. You've successfully created an establishing screenshot!

[#_creating_map_screenshots]
== Creating map screenshots

. This

. This

. This

[#_simple_screenshots]
== Creating simple screenshots

Simple screenshots are a cropped portion of the screen, rather than the full screen. Use simple screenshots after using an xref:_establishing_screenshots[establishing] one.

. Open Figma.

. Select *File*, then *Place image* to import your screenshot.

. Resize the width to 1662.

. Crop the window title bar, web browser toolbar, and any other non-essential information by selecting *Crop*, dragging a corner of the crop tool, and pressing *Enter*.
+
[TIP]
Press *Shift + 2* to zoom in on the section you're cropping to make sure the crop is pixel perfect.

. Select your screenshot and frame it by pressing *F*.

. Click the default frame name and change it to a short, descriptive one.

. Select *Export*, confirm the file extension is set to *.png*, then click *Save*.

. You've successfully created a simple screenshot!
