// tag::introduction[]

= Process to make a GEM-bootable USB stick
:navtitle: Process to make a GEM-bootable USB stick

This document describes step-by-step instruction to create a bootable USB stick having the GEM firmware which will be used to install the GEM into the Dell server.

// end::introduction[]

// tag::prerequisites[]

== Prerequisites
* USB stick with a minimum 4GB size.

* A Mac computer.

* A USB adapter to plug the USB stick to the Mac.

// end::prerequisites[]

== Getting started

1. Download the GEM base image at https://kobiton-operation.s3.ap-southeast-1.amazonaws.com/operation-software/gem-installer-4.0.b9e78fe.img on your local machine.
+
NOTE: this URL is downloadable only in TV, Norcross, and Databank locations. Let’s say the downloaded file is at ~/Downloads/gem-installer.img

+
2. Make sure the USB stick is unplugged, run the below command line (with sample output), and note down the list of /dev/disk*
+
[source,ruby]
----
% diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.3 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         494.4 GB   disk0s2
   3:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +494.4 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            8.9 GB     disk3s1
   2:              APFS Snapshot com.apple.os.update-... 8.9 GB     disk3s1s1
   3:                APFS Volume Preboot                 4.7 GB     disk3s2
   4:                APFS Volume Recovery                763.5 MB   disk3s3
   5:                APFS Volume Data                    334.9 GB   dis
----
3. Plug the USB stick, and re-run the above command, you will see one extra disk item which is the USB stick, use that device name from now (for example: /dev/disk4) as below example.
+
[source,ruby]
----
% diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.3 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         494.4 GB   disk0s2
   3:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +494.4 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            8.9 GB     disk3s1
   2:              APFS Snapshot com.apple.os.update-... 8.9 GB     disk3s1s1
   3:                APFS Volume Preboot                 4.7 GB     disk3s2
   4:                APFS Volume Recovery                763.5 MB   disk3s3
   5:                APFS Volume Data                    334.9 GB   disk3s5
   6:                APFS Volume VM                      6.4 GB     disk3s6

/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *15.5 GB    disk4
   1:                        EFI EFI                     209.7 MB   disk4s1
   2:                  Apple_HFS Install macOS Big Sur   15.1 GB    disk4s2
----
+
4. Unmount the partitions in the USB stick, do many times until we only have /dev/disk4 mounted.

    diskutil unmount /dev/disk4s2
+
5. Write the GEM base image into the USB stick, enter the password of your macOS user.

    sudo dd if=$HOME/Downloads/gem-installer.img of=/dev/rdisk4 bs=8m

6. Once the above command completes, run

    sync

7. If the writing image is correct, the output is as below.
+
[source,ruby]
----
% diskutil list
....

/dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *61.5 GB    disk6
   1:                        EFI GIGACAP                 1.1 GB     disk6s1

----

8. Finally, run the below command and unplug the USB stick. It’s ready to be used on the Dell server.

    diskutil eject /dev/disk4