= Bypass One Time Password
:navtitle: Bypass One Time Password

== How to bypass OTP

*Step 1:* During a Manual Test session with Kobiton, after installing an iOS or Android app that requires One Time Password (OTP) authentication, you can input your phone number and your received passcode as common flow.

*Step 2:* When exiting the session, you may encounter Scriptless Automation popup and jump to Text Execution Plan for setting up some pre-condition before triggering Scriptless Automation.

*Step 3:* Finally, click on the run Scriptless Sessions button to trigger automation test sessions on multiple device types. Let us bypass OTP authentication in the automation sessions under our background.

NOTE: In the Text Execution Plan, please focus on the Dynamic Data section, you can override your dataset related to phone number and OTP instead of using our bypassing OTP in the background. For your reference on how to set dynamic data, please access the guideline below.

== Constraint

Currently, our solution to bypassing OTP works effectively with any apps requiring the phone number of a user to registration and login in just one step. If you make some debug on your failed automation sessions by OTP authentication, please consider that your test case may belong to one of below scenarios that we haven’t supported yet:

* Your app requires a user phone number and OTP but does not use for authentication.
* Users need to register their phone number before login to an application and receive OTP via registered phone number.
* If your test case is out of our mentioned scenarios, please contact our customer support.

We know these will make you feel inconvenient and not have a good usage experience, but our team is working hard to free-up these limitations ASAP for providing a better feature for you.
