= Input sensitive data
:navtitle: Input sensitive data

$DESCRIPTION$

== What Is Text Encryption/ISD Tool?

Kobiton has introduced a new feature for the Kobiton platform to increase security and put your mind at ease during your testing process. There are times when sensitive information needs to be input to an application or element during a test, such as passcodes, that you do not want to be visible during the session or in recording views or revisited sessions/Scriptless tests afterward. Instead of entering that sensitive text directly into the device during your test session, Kobiton has provided a method for encrypting your text so that it reaches the device without compromising or exposing your information.

== How It Works

Text Encryption is a tool you can use during your manual session testing within the Kobiton platform. The obfuscation of data will carry over to your Scriptless tests as well. This section will go over how to use the ISD Tool in your manual session. The next section will discuss reviewing and manipulating the results of the ISD Tool in your Test Execution Plan for automated tests.

=== Manual Session

. Launch a manual session on the device of your choice. In the tools sidebar to the left of the screen, you will see an icon that looks like a padlock. This is the Text Encryption/Input Data tool. Click the icon.
+
image:./guide-media/01GWE77AYC0TGW8WP2THE661XH[ISD_1.png]

. The Input Data box will appear as a pop-out from the sidebar. If you use any passcode management plug-ins with your browser, they will be accessible from here. The eye icon to the right of the text field will toggle your text data to appear in the field as asciidoc or encrypted text. The text field is where you can enter the data you wish to not be visible during the manual session. Since the pop-out is a part of the Kobiton software platform and is therefore not a part of the session itself or directly connected to the device your session is using, your data is protected.
+
image:./guide-media/01GWDZDHYB9Y92KWBMMEE01QD7[ISD_2.png]

. Within the device, navigate to the page and field where you wish to input data. In the Input Data tool’s text field, enter the desired text in the text field and click “Save”. Kobiton will save the data as you entered it and transfer it, encrypted and in real time, to the text field you selected on the device.
+
image:./guide-media/01GWESQEK8VNPFEDYCGPZ2VT1A[ISD_3.png]

=== Scriptless/automated Session

Please note that if you do not use the ISD Tool as described above, data cannot
be obfuscated after the test is completed. In order for text to be encrypted
in a Scriptless session, it must first be encrypted during the primary manual
session.

. Once your manual test has been completed and you have chosen to create a NOVA
Scriptless test from your manual session, you will be taken to the Test Execution
Plan page. Navigate to the Data-Driven Testing tab.
+
image:./guide-media/01GWEYQ2B9NT6NT83T3XVYTTMA[ISD_4.png]

. In the Data-Driven Testing tab, the steps taken in the manual session that
will be translated to your automated test are listed in the panel to the left.
Any text typed into the ISD Tool will appear as encrypted text and will not be
visible to the viewer, as you can see in the step highlighted in the example
test below.
+
image:./guide-media/01GWE1CRPX9M650EXW63TP3RP4[ISD_5.png]

As in the ISD Tool itself, you can click the eye icon to reveal the encrypted
text as asciidoc. However, the eye icon and the option to view the sensitive
text is _only available to the original creator of the session. _ Please
note that this is not a permission that can be granted to roles or teams, including
administrators.

image:./guide-media/01GWESQFBYZXSKZMYBPSE8SEZB[ISD_6.png]

If you have any questions or issues regarding the use of the Encrypted Text tool, please submit a support ticket at support. kobiton. com.
