= Run scriptless with the Kobiton portal
:navtitle: Run scriptless with the Kobiton portal

Learn how to run scriptless automation using the Kobiton portal.

== Before you start

You'll need to complete the following:

* xref:create-a-baseline-session.adoc[Create a baseline session].
* xref:test-management:create-a-test-case.adoc[] using your baseline session.

== Open scriptless automation

In *Sessions*, search for your baseline session, then select the session.

image:$NEW$[width="",alt=""]

[NOTE]
For more information, see xref:session-explorer:session-metadata.adoc[].

Select *Automation Test Case*.

image:$NEW$[width="",alt=""]

Select *Rerun*.

image:$NEW$[width="",alt=""]

== Configure your scriptless session

=== Device Bundles

In the *Rerun Configurations* window, select *Device Bundles*.

image:$NEW$[width="",alt=""]

Select the dropdown and choose a bundle.

image:$NEW$[width="",alt=""]

If you'd like to remove any devices for this session, select the checkbox next to each device.

image:$NEW$[width="",alt=""]

[NOTE]
If you'd like to make more changes to this bundle, select *Configure Bundle*. For more information, see xref:organization:device-bundles/manage-device-bundles.adoc[].

=== Data driven testing

Data-driven testing allows you to define custom data sets and replace values from your baseline session. In the *Rerun Configurations* window, select *Data Driven Testing*.

image:$NEW$[width="",alt=""]

To replace a value used for a specific test step, select the test step, then enter a new value.

image:$NEW$[width="",alt=""]

Once a value has been modified, it will be marked as *Edited*.

image:$NEW$[width="",alt=""]

=== Settings

In the *Rerun Configurations* window, select *Settings*.

image:$NEW$[width="",alt=""]

In the *Settings* pane, select the dropdown, then decide how you'd like the AI to handle matching elements missing on the device screen.

image:$NEW$[width="",alt=""]

== Run scriptless automation

When you're finished configuring your scriptless session, select *Rerun*.

image:$NEW$[width="",alt=""]

You'll be redirected to your test run where you can view live updates for your run.

image:$NEW$[width="",alt=""]
