= Add `flexCorrect`
:navtitle: Add `flexCorrect`

Learn how add `flexCorrect` to your capabilities, so your automation script will automatically select the right element--even across different devices. Using `flexCorrect` will decrease the amount of `Element not found` errors you may get during testing.

== Locate config file

First, open your test suite and locate your config file. The exact name and location may vary, but you'll find it in a similar location:

[source,plaintext]
----
root
└── src
    └── test
        └── Config # Java TestNG
        └── Config.java # Java JUnit
        └── config.js # NodeJS Mocha
----

== Add capability

In the config file, locate `DesiredCapabilities`, and add the following lines:

[cols="2,3", options="header"]
|===
| Capability
| Value

| `kobiton:flexCorrect`
| `true`

| `kobiton:baselineSessionId`
| (Optional) Choose a different baseline session by assigning its xref:automation-testing:get-a-session-id.adoc[session ID].
|===

Here's an example:

[source,java]
----
// Located in test/scriptlessautomation/Config in the Java's TestNG framework.

public static DesiredCapabilities getIPhone11ProIOS146DesiredCapabilities() {
        DesiredCapabilities capabilities = new DesiredCapabilities();

        // Change these desired capabilities:

        capabilities.setCapability("kobiton:flexCorrect", true);  // Enable flexCorrect by setting capability to true.
        capabilities.setCapability("kobiton:baselineSessionId", 0000011); // (Optional) Choose a different baseline session by assigning its kobitonSessionId.

    return capabilities;
}
----

When you're finished, save your changes. Now `flexCorrect` will automatically select the correct elements, even when you run your script on different devices.

[NOTE]
After a session, you can see xref:session-analytics:session-overview.adoc#_number_of_corrections[how many elements were corrected].
