name: Build and Push Image to ECR 🚀
on:
  # Enable manual trigger for easy debugging
  workflow_dispatch:
  push:
    branches:
      - main
      - '**-rc'
      - production
      - 'production-hotfix'


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials from PRODUCTION account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-role
          aws-region: ${{ secrets.AWS_REGION }}
      - name: ssh-agent setup
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Build 
        uses: dagger/dagger-for-github@31393402b06d9d3524e2bc67a14f63d1462821ab # v7.0.5
        with:
          version: "0.15.3"
          verb: call
          args: |
            publish \
            --sites="docs,widget" \
            --image-tag=$IMAGE_TAG \
            --aws-region=$AWS_REGION \
            --aws-account-id=$AWS_ACCOUNT_ID \
            --aws-access-key-id=env:AWS_ACCESS_KEY_ID \
            --aws-secret-access-key=env:AWS_SECRET_ACCESS_KEY \
            --aws-session-token=env:AWS_SESSION_TOKEN \
          dagger-flags: "--silent"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

