name: Build and Push image to ECR
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches:
      - '**-rc'


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  setenv:
    name: Set Environment to passthrough reuses workflows
    runs-on:
      group: ubuntu-runners
    outputs:
      repo-name: ${{ steps.setenv.outputs.repo-name }}
    steps:
      - name: Set up environment
        id: setenv
        run: |
          echo "repo-name=documentation" >> $GITHUB_OUTPUT

  build:
    needs: [setenv]
    name: Build
    uses: kobiton/deployment/.github/workflows/ci.yaml@master
    with:
      git-ref: ${{ github.event.inputs.git-ref }}
      repo-name: ${{ needs.setenv.outputs.repo-name }}
    secrets: inherit
  
  