name: Build and Push Image to ECR
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches:
      - master
      - main
      - '**-rc'
      - production
      - 'production-hotfix'


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-docs:
    name: Build
    uses: kobiton/deployment/.github/workflows/ci.yaml@update-workflow-portal-help
    with:
      git-ref: ${{ github.event.inputs.git-ref }}
      repo-name: 'documentation'
      dockerfile-path: 'docker/docs/Dockerfile'
    secrets: inherit

  build-wiget:
    name: Build
    uses: kobiton/deployment/.github/workflows/ci.yaml@update-workflow-portal-help
    with:
      git-ref: ${{ github.event.inputs.git-ref }}
      repo-name: 'portal-help'
      dockerfile-path: 'docker/widget/Dockerfile'
    secrets: inherit
