name: Test Build

on:
  push:
    branches:
      - 'main'
      - 'add-ci'
  pull_request:
    branches:
      - '*'
  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  pull-requests: write

jobs:
  build-and-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID || '681314228305' }}
      AWS_REGION: ${{ vars.AWS_REGION || 'ap-southeast-1' }}
      DOCS_S3_HOSTING_BUCKET: ${{ vars.DOCS_S3_HOSTING_BUCKET || 'docs-test.kobiton.com' }}
      DOCS_CLOUDFRONT_ID: ${{ vars.DOCS_CLOUDFRONT_ID || 'E1EVWSBO6PATYU' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
        
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y curl python3 python3-pip python-is-python3 python3-venv
          npm install -g yarn
      
      # - name: ssh-agent setup
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh: |
      #       default=${{ env.SSH_AUTH_SOCK }}

      - name: Yarn test/build
        run: |
          yarn install
          yarn build
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to TEST environment
        run: |
          aws s3 ls
          cp ./ci/index.html ./build/docs
          aws s3 sync ./build/docs s3://${{ env.DOCS_S3_HOSTING_BUCKET }}
          aws cloudfront create-invalidation --distribution-id ${{ env.DOCS_CLOUDFRONT_ID }} --paths "/*"