name: Deploy to Production 🚀

on:
  push:
    branches:
      - 'main'
  # Enable manual trigger for easier debugging
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Docs publish"
        uses: ./.github/actions/call
        with:
          site: "docs"
          cloudfront-id: ${{ secrets.DOCS_CLOUDFRONT_ID }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: ${{ secrets.AWS_PROD_REGION }}

  widget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Widget publish"
        uses: ./.github/actions/call
        with:
          site: "widget"
          cloudfront-id: ${{ secrets.WIDGET_CLOUDFRONT_ID }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: ${{ secrets.AWS_PROD_REGION }}
