name: Test Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  pull-requests: write

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
        
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y curl python3 python3-pip python-is-python3 python3-venv
          npm install -g yarn

      - name: Yarn install/build
        run: |
          yarn install
          yarn build
          
