name: Test Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # Enable manual trigger for easier debugging
  workflow_dispatch:
  
permissions:
  contents: read    # This is required for actions/checkout
  pull-requests: write

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Build 
        uses: dagger/dagger-for-github@e49f5bfe7f9a3593f38b9d7391f110d6dff48f94 # v6.8.0
        with:
          version: "0.13.0"
          module: github.com/${{ github.repository }}@${{ github.ref }}
          verb: call
          args: --ref ${{ github.ref }} build
