name: lint
on:
  push:
    paths:
      - '**.adoc'
  pull_request:
    paths:
      - '**.adoc'

jobs:
  vale:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vale
        uses: errata-ai/vale-action@v1.3.0
        with:
          config: .vale.ini
          styles: styles
