= Accessibility validation
:navtitle: Accessibility validation

Session Explorer automatically flags xref:_issue_types[accessibility issues] for each test session. Learn more about a specific issue by checking the xref:session-explorer/accessability-validation.adoc[issue details].

image:<NEW-IMAGE>[width=, alt=""]

[#_issue_types]
== Accessibility issues

=== Touch target size

The size of an element on the screen your user can interact with.If an element is too small, some users may struggle to interact with elements on your app or website.

image:<NEW-IMAGE>[width=,alt=""]

=== Color Contrast

The difference in light between a foreground element and its background.If the color contrast is insufficient, some users may struggle to see elements on your app or website.

image:<NEW-IMAGE>[width=, alt=""]

=== Content labeling

Each UI element on the screen should be properly labeled in your codebase. If a UI element is missing or using an incorrect label, users may be unable to use a screen reader with your app or website.

image:<NEW-IMAGE>[width=, alt=""]

== Issue details

=== Issue markers

Issues are marked with a yellow dot both on the timeline and the device.

image:<NEW-IMAGE>[width=, alt=""]

=== Next and previous screen

Move through each device screen with an issue. Each screen can contain multiple issues.

image:<NEW-IMAGE>[width=, alt=""]

=== Next and previous issue

Move through each issue on the current device screen. Each screen can contain multiple issues.

image:<NEW-IMAGE>[width=, alt=""]

=== Issue description

The issue description along with a link to the related guideline in link:https://developer.apple.com/design/human-interface-guidelines/accessibility[Apple's] or link:https://www.google.com/accessibility/for-developers/[Google's] accessibility guidelines.

=== Visible

The visibility of the selected element marked `true` or `false`.

image:<NEW-IMAGE>[width=, alt=""]

=== Xpath

The Xpath of the selected element. Hover over the Xpath value to copy it to your clipboard.

image:<NEW-IMAGE>[width=, alt=""]

=== Text

The text output of the selected element.

image:<NEW-IMAGE>[width=, alt=""]

=== Width

The width of the selected element.

image:<NEW-IMAGE>[width=, alt=""]

=== Height

The height of the selected element.

image:<NEW-IMAGE>[width=, alt=""]

=== X

The X-coordinate on the screen of the selected element.

image:<NEW-IMAGE>[width=, alt=""]

=== Y

The Y-coordinate on the screen of the selected element.

image:<NEW-IMAGE>[width=, alt=""]
