= Timeline
:navtitle: Timeline

The timeline in the Session Explorer lets you play back sessions, share test steps, view accessibility issues, and more.

image:<NEW-IMAGE>[width=, alt=""]

== Play or pause

Play or pause the session recording.

image:<NEW-IMAGE>[width=, alt=""]

== Test steps

Display the selected test step on the device screen.

image:<NEW-IMAGE>[width=, alt=""]

The related action is marked in red.

image:<NEW-IMAGE>[width=, alt=""]

== Previous or next

Skip to the previous or next test step.

image:<NEW-IMAGE>[width=, alt=""]

== Zoom

Zoom in or out of the session timeline.

image:<NEW-IMAGE>[width=, alt=""]

== Copy link

Copy a link to the current test step and share it with others easily.

image:<NEW-IMAGE>[width=, alt=""]

== Copy command id

Copy the unique id assigned to the current test step.

image:<NEW-IMAGE>[width=, alt=""]

== Accessibility issue marker

Session Explorer automatically flags accessibility issues during the session. Select *View Details* to open xref:session-explorer/accessability-validation.adoc[accessibility validation] and view all issues in one place.

image:<NEW-IMAGE>[width=, alt=""]

== Download

Download a screenshot of the selected test step.

image:<NEW-IMAGE>[width=, alt=""]
