== Open the project

Open the terminal and navigate to your project's root directory.

.Example
[source,shell]
----
cd ~/my-app/
----

If your project is already initialized as a git repository, you can xref:_upload_the_project[upload your project files].

== Optional: initialize as a git repository

If your project hasn't been initialized as a git repository yet, run the following commands to create your first commit.

[source,shell]
----
git init -b main
git add --all
git commit -m "First commit"
----

[#_upload_the_project]
== Upload the project

[tabs]
======
GitHub::
+
--
link:https://github.com/cli/cli#installation[Install `gh`], GitHub's command-line tool, using your operating system's package manager.

.Example
[source,shell]
----
brew install gh
----

Enter the following command and follow the prompts in your terminal.

[source,shell]
----
gh repo create
----

link:https://github.com/login[Open GitHub] and confirm your source files have been successfully uploaded.

image:$OLD-IMAGE$[width="",alt=""]
--

GitLab::
+
--
Use the `--set-upstream` flag to push the commit to GitLab. Set `<namespace>` to a link:https://docs.gitlab.com/ee/user/namespace/[personal or group namespace] and `<myproject>` to a short, descriptive project name.

.Example
[source,shell]
----
git push --set-upstream git@gitlab.example.com:<namespace>/<myproject>.git main
----

link:https://gitlab.com/users/sign_in[Open GitLab] and confirm your source files have been successfully uploaded.

image:$OLD-IMAGE$[width="",alt=""]
--
======
