= Run Appium script on Kobiton devices
:navtitle: Run Appium script

Learn how to utilize Kobiton automation testing with Appium script and GitHub Action.

NOTE: For more information, see link:https://github.com/marketplace/actions/kobiton-execute-appium-test[Official GitHub Marketplace Kobiton Action for Appium].

== Before you start

You'll need the following:

* A Kobiton account. To create a Kobiton account visit link:https://portal.kobiton.com/register[Kobiton].
* Kobiton Username and API key. To get your Kobiton Username and API Key, follow instructions at `IV. Configure Test Script` section on link:https://kobiton.com/blog/parallel-testing-with-selenium-webdriver/[Kobiton blog].
* `EXECUTOR_USERNAME` and `EXECUTOR_PASSWORD`. To get your executor username and password, contact Kobiton support.

== Run the Appium script

To run Appium script on Kobiton devices using GitHub Actions, follow the instruction on our link:https://github.com/marketplace/actions/kobiton-execute-appium-test[official GutHub Marketplace Action for Appium script] page.